### PR TITLE
Added Vishay IRF7606PBF N Channel Mosfet

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Based on the BUZ11 component

screenshot from 2017-12-19 19-35-54

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
Aaaragh I just put the wrong subject on this pull request. Added the IRF740BPBF NOT the 7606!

**Comment by johnfwhitmore** [comment]
This addition has produced errors in the Integration tests. I'll have to go over this again.

**Comment by johnfwhitmore** [comment]
Going through the CI issues. The symbol is not centered, which is fair enough, but if I did center the symbol the pins would not be on the 100 mill points. I've moved the component so that pins are on the zero line.

**Comment by SchrodingersGat** [comment]
Hi @johnfwhitmore we have started to transition to the new v5 libraries while leaving these legacy libraries in place. The `Transistor` libs have already been transferred to https://github.com/kicad/kicad-symbols

Please resubmit this PR at the new repo, in the `Transistor_FET` library. Thanks :)

**Comment by poeschlr** [comment]
About your comment: Centering the symbol has a lower priority then the 100mil requirement.

**Pull request closed without merging**
