### PR TITLE
Add LT1492 dual-opamp symbol 

### PR DESCRIPTION
**Pull request by jkriege2**
Add LT1492 dual-opamp symbol

http://cds.linear.com/docs/en/datasheet/14923f.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Okay @jkriege2 we shall start with this one :) A long road ahead, so many PRs!!

## KLC Convention
Firstly, are you aware of the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) (KiCad Library Convention)? This is a set of rules / suggestions that we like all symbols and footprints to conform to. Some of the KLC rules are for professionalism, some for aesthetics, and all are generally helpful for consistency across the library (particularly important as there are many people contributing). 

There is also the [KiCad Library Utilities](https://github.com/KiCad/kicad-library-utils), a collection of helpful Python scripts which help to speed up this PR process . Some of the KLC rules have been scripted such that a new symbol (or footprint) can be checked without the input of a librarian. 

Running these scripts against some of your current PRs, it appears that there are some KLC violations that could be easily located and fixed using these scripts :)

For this part (LT1492), the checklib.py script reveals the following:
```
python checklib.py linear.lib --enable-extra -vv -c LT1492

checking component: LT1492
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: -INA (2), posx -250, posy -100
    pin: +INA (3), posx -250, posy 100
    pin: +INA (5), posx -250, posy 100
    pin: -INA (6), posx -250, posy -100
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: U at posx 100 posy 150 size 60
    field: LT1492 at posx 200 posy -175 size 60
    field: UNKNOWN at posx 0 posy 0 size 60
    field: UNKNOWN at posx 0 posy 0 size 60
```

As a first step, making sure that your symbols and footprints conform to KLC will be of great help!

## Aesthetic Style
Aside from fixing the KLC issues as above, my only other suggestion at this stage is that the symbol be updated to match the aesthetic style of other library symbols.

Specifically:
* Increase line thickness of the triangle shape to 0.01"
* Set the triangle shape to background (yellow) fill

Thanks for your contributions, I hope this is not too much to throw at you straight out of the gate :)

**Comment by jkriege2** [comment]
Hi!

OK, for this PR I copied the symbol from another opamp already in the lib, so the style should conform + I added the quad-OPAMP LT1493 which corresponds to the LT1492.

Hope this is OK now. I'll have a look at the other PRs ... but that may take some time ;-) I'll also have a look at the python scripts ... (the two OpAmps already conform !

Best,
JAN

PS: Are there any specifics in the library where you would need some help? Otherwise I'll contribute, what I need and find useful for others!

**Comment by SchrodingersGat** [comment]
Great, thanks :)

A couple of other suggestions for this one :)

1. Please do not duplicate the part name in the part description. 
2. Description keywords do not need to repeat all words used in the description.

e.g. for the LT1492 I would suggest
```
Description: LT1492 5MHz, 3V/µs, Low Power Single Supply, Dual Precision OpAmps
Keywords: AmpliOp Low Power Single Supply Dual Precision OpAmps
```
becomes
```
Description: Dual Low-Power Single-Supply Op-Amp, 5MHz, 3V/µs
Keywords:  operational amplifier opamp 
```

The *Description* field should have comma-separated features of the part, with the most "important" (yes, this can be subjective) first.
The *Keywords* field should contain extra keywords (normally not present in the description field) and are essentially just there to assist part searching.

**Comment by SchrodingersGat** [comment]
Nice work, thanks :)

**Pull request merged**
