### PR TITLE
added LMC7660

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
image

**Comment by poeschlr** [comment]
The C pins should be named Cap to match the datasheet.
pin 6 should be an input. (I'm not sure about the naming. In the block diagram it is called Reg, in the pin configuration it is called LV.)

Pin order (my suggestion. open for discussion)
top left, V+
top right Vout
bottom GND
OSC and LV(Reg) on the left side
Cap+/- on the right

**Comment by Misca1234** [comment]
Is it possible for me to pull down his push?
It is 2.5 month ago and he have not responded.

I can fix those issues and re push it.

**Comment by jkriege2** [comment]
just go ahead I think ... ;-)

**Comment by Misca1234** [comment]
How do I download his branch, either I get RSA warnings or permission denies
(I used  git pull git@github.com:ilya-epifanov/KiCad/kicad-library.git LMC7660)

Or should I create my own branch from scratch and push it ?

**Comment by Misca1234** [comment]
This branch is obsolete and can be closed
replacement push is here 
https://github.com/KiCad/kicad-library/pull/1589

**Pull request closed without merging**
