### PR TITLE
Added full description for MCP9700/MCP9700A temperature sensors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Ref
http://ww1.microchip.com/downloads/en/DeviceDoc/21942e.pdf

### CODE REVIEW

**Comment by diggit** [comment]
Please fix this:
- add FP filters
- switch NC pins to invisible

Symbol tweaks:
- make both symbols look same, [look here for explanation](https://github.com/KiCad/kicad-library/pull/455#issuecomment-207978528) the only difference here are NC pins, so no big deal. GND and VDD oriented vertically.

**Comment by SchrodingersGat** [comment]
Done, done and done

**Comment by diggit** [comment]
Good, nice art :)
Add \* to footprint filters. There could be SOT-23-3_Handsoldering (**all** FP filters should have \* at the end)

**Comment by SchrodingersGat** [comment]
done

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
