### PR TITLE
Added the 3D model for AG12864E

### PR DESCRIPTION
**Pull request by Misca1234**
This is the 3D model for AG12864E
https://github.com/KiCad/Displays.pretty/pull/10
Not so funny 3D model but I can not find any images of it, only the data sheet with measurements

bild

### CODE REVIEW

**Comment by Shackmeister** [comment]
Has this been exported with material properties? :)

**Comment by Misca1234** [comment]
If you mean the colours ?

Green is 87,174,114
Black 14,14,14
"White" 229,228,208

According to the "kicad colour pdf guidelines"

Then this button was used in the "kicad" macro
bild

**Comment by poeschlr** [comment]
The colors in your screenshot look a bit flat. 
This might be either because you have a old kicad version, the wrl file does not include all material properties or because it is a very large component with large areas in the same color. 
(I guess it is the later.)

Just in case there is something wrong:
After you press the export button there should be pop up windows for each color. What did you select in the drop down menu? You should select black body, white body and green body. Do not select "as is" because then some material properties are not exported for the wrl model.

**Comment by Misca1234** [comment]
Hi

I use kicad 4.0.5 release build
Freecad 0.17 (on request from kicad team)

The colours I got from the "offical kicad colour pdf" 
(btw, where do I find it, the rbg values I use is somethign I wrote down)

> After you press the export button there should be pop up windows for each color. What did you select > in the drop down menu? You should select black body, white body and green body. 
> Do not select "as > is" because then some material properties are not exported for the wrl model.

I selected "as is", I will do a re export

**Comment by Shackmeister** [comment]
When selecting "as is" you only assign colors to the vrml file, when selecting you add material properties. This also includes info on on how it should react with different lighting and stuff, makes for really nice renderings :)

**Comment by Misca1234** [comment]
What about this, i pimped it up a little with round corners, replaced black with grey and cut out the LED area a little

bild

**Comment by Misca1234** [comment]
https://github.com/KiCad/packages3D/pull/71 have not been updated yet, waiting for this approval

**Comment by poeschlr** [comment]
Please move this model to Displays.3dshapes

**Comment by Misca1234** [comment]
Hold on to check this, i will pimp up a little like 
bild

and add them to the packages3D-source

**Comment by Misca1234** [comment]
Pimped up the 3D model a bit

bild

**Comment by poeschlr** [comment]
Very nice model.
I think you can remove the model from the Display.3dshapes directory.

**Comment by Misca1234** [comment]
Sure, np, hold on a second

**Comment by Misca1234** [comment]
They are removed from Display.3dshapes

**Comment by poeschlr** [comment]
Thanks again for your contributions

**Comment by Misca1234** [comment]
No problem, it is fun

**Pull request merged**
