### PR TITLE
Fixes to the OpAmp schematic

### PR DESCRIPTION
**Pull request by Fat-Zer**
This is proposed changes against issue #200.

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Nice!

**Comment by Fat-Zer** [comment]
>can you please check the conflicts?

Done.

**Comment by diggit** [comment]
Symbols look really nice. Can you fix documentation of their aliases? It should be peace of cake for you...

```
checking alias: LM101H
      missing datasheet, please provide a datasheet link if it isn't a generic component
checking alias: NE5532
      missing whole documentation (description, keywords, datasheet)
checking alias: 4558
      missing whole documentation (description, keywords, datasheet)
checking alias: ADA4075
      missing keywords
checking component: LM733CH
      missing datasheet, please provide a datasheet link if it isn't a generic component
```
*(unneeded info removed from script output)*
*alias documentation checking was added to kicad-library-utils lately, pull changes from its repo unless you have already done*

**Comment by diggit** [comment]
Somehow, alias LM101H got back. As it is not valid alias to CA3130, please remove it. Issue #406

**Comment by Fat-Zer** [comment]
> Symbols look really nice. Can you fix documentation of their aliases?

Done.
Note about LM733CH: it haven't found a datasheet link to some official manufacturer's site, so the link leads to some hobbiest's database.

> Somehow, alias LM101H got back. As it is not valid alias to CA3130, please remove it. Issue #406

I haven't delete it before due to I considered that I may be wrong about that...
And after quite a while it is now obvious that nobody knows about that and it's very likely it's just wrong...

**Comment by diggit** [comment]
I can't even find datasheet for "LM101H". It is ok to delete it.
In closer look eg. AD813 has really close + and V+, same for negative. It is really uncomfortable to read. Any ideas how to solve it?
Maybe put pin names outside and place text fields with +/- inside for inputs?

**Comment by Fat-Zer** [comment]
>In closer look eg. AD813 has really close + and V+, same for negative. It is really uncomfortable to read. Any ideas how to solve it?

It's the same for nearly all OpAmps... The only thing can be done is to reduce the field offset to 10 or even 5 mils, but I'd rather done it in a separate pull request, because this one is hanging around for quite a while already...

>Maybe put pin names outside and place text fields with +/- inside for inputs?

Hmm... I don't really like that... IMHO the pin names is an information that doesn't want to be loosed, especially +/- v+/v- pins due to that may be helpful for the upcoming migration to new schematic format (at least I'm one of guys who still hope it is still upcoming...)

**Comment by timofonic** [comment]
Will it happen for 5.0? Is going to have the symbols embedded in the file too? What about including the PCB? Can it be done in a way friendly with version control like Git? 
It's nice to have hope abs there are reasons for it. Other projects are in a much worse situation, with lots of forks and not the great improvements KiCad is having these days. 

On March 22, 2016 9:30:01 PM CET, Golubev Alexander <notifications@github.com> wrote:
>>In closer look eg. AD813 has really close + and V+, same for negative.
>It is really uncomfortable to read. Any ideas how to solve it?
>
>It's the same for nearly all OpAmps... The only thing can be done is to
>reduce the field offset to 10 or even 5 mils, but I'd rather done it in
>a separate pull request, because this one is hanging around for quite a
>while already...
>
>>Maybe put pin names outside and place text fields with +/- inside for
>inputs?
>
>Hmm... I don't really like that... IMHO the pin names is an information
>that doesn't want to be loosed, especially +/- v+/v- pins due to that
>may be helpful for the upcoming migration to new schematic format (at
>least I'm one of guys who still hope it is still upcoming...)
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/KiCad/kicad-library/pull/405#issuecomment-200007313

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor disculpa mi brevedad.

**Comment by Fat-Zer** [comment]
> Will it happen for 5.0? Is going to have the symbols embedded in the file too? What about including the PCB? Can it be done in a way friendly with version control like Git?

I don't know a lot as well, just some fragmentary (and may be particularly outdated) info from the maillist... The new format is on the road map for v5, so I hope it will be finished till it. But as I can see there haven't been done a lot since some drafts of the format was published... The format itself is S-Expression like the one used for pcbs, so pros and cons are mostly the same...

**Comment by diggit** [comment]
Ok then.
Please solve conflicts, I'll merge your changes.
Sorry for late reply, PR got lost on queue.

**Comment by Fat-Zer** [comment]
rebased on current master...

**Pull request merged**
