### PR TITLE
Add Microchip MCP23018

### PR DESCRIPTION
**Pull request by mattbooks**
Copied from MCP23017. QFN pinout not included.

Datasheet here: http://ww1.microchip.com/downloads/en/DeviceDoc/22103a.pdf

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work and thanks for the contribution. There are a few things to be changed, before we can merge this PR:
1. please add all the NC pins (2,14,17,28) of the PDIP/SOIC package as invisible pins of type not-connected
2. please set/modify the FPFilters: SSOP: `SSOP*5.3x10.2mm*Pitch0.65mm*` and PDIP/SOIC: `DIP*W7.62mm*` and `SOIC*7.5x17.9mm*Pitch1.27mm*`

Best,
JAN

**Comment by mattbooks** [comment]
Thanks, done

**Comment by jkriege2** [comment]
Hi!

please move the NC--pins onto the 100mil grid (see output of Travis check scripts:
2017-03-08 22_03_01-created footprint library housings_lcc by yo3iti pull request 1 kicad_housi

Best,
JAN

**Comment by mattbooks** [comment]
(updated)

**Comment by poeschlr** [comment]
The symbol has the wrong datasheet linked.
This part naming does not conform with the current KLC but we are still discussing how it should be in the future. (I asked in the issue https://github.com/KiCad/kicad-library/issues/1398 how currently open pull requests should be handled.)

**Pull request closed without merging**
