### PR TITLE
Renamed the whole LDK130 Family

### PR DESCRIPTION
**Pull request by suzizecat**
Fixing #1386

### CODE REVIEW

**Comment by bobc** [comment]
typo: "quienscent" should be "quiescent"

**Comment by suzizecat** [comment]
fixed

**Comment by SchrodingersGat** [comment]
Hi @suzizecat seems that there have been some conflicts here - can you fix this?

**Comment by suzizecat** [comment]
Done ! :wink:

**Comment by suzizecat** [comment]
The check is OK for my component, i hope that i didn't broke the lib...

**Comment by SchrodingersGat** [comment]
It seems like more files have changed than just the regul.lib file. I'm not sure what you've done!

Please either fix this PR so it only touches the files you want to change, or open a new PR if that proves too difficult...

**Comment by suzizecat** [comment]
Meh... I'll look into it

**Comment by SchrodingersGat** [comment]
@suzizecat are you going to address this one or should we close it? :)

**Comment by suzizecat** [comment]
I'll check into it... School took me quite the time :sweat_smile:

**Comment by SchrodingersGat** [comment]
Looks like there have been some merge issues with this PR. We are moving the symbols to kicad-symbols for the new software release. Please resubmit a PR to https://github.com/kicad/kicad-symbols

Thanks

**Pull request closed without merging**
