### PR TITLE
Tsc2046

### PR DESCRIPTION
**Pull request by Misca1234**
This is push for TSC2046

Datasheet
http://www.ti.com/lit/ds/symlink/tsc2046.pdf

Main: TSC2046IPW
Alias TSC2046IPWG4, TSC2046IPWR, TSC2046IPWRG4

Main TSC2046IRGVR
Alias TSC2046IRGVRRG4, TSC2046IRGVT

Main TSC2046IZQCR

kicad-library branch
https://github.com/KiCad/kicad-library/pull/1491

Housings_BGA.pretty branch
https://github.com/KiCad/Housings_BGA.pretty/pull/18

packages3D branch
https://github.com/KiCad/packages3D/pull/107

bild

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis script errors complain off the VBAT pin, travis thinks it is a power signal but it is not

**Comment by Misca1234** [comment]
Modified foot print, see https://github.com/KiCad/Housings_BGA.pretty/pull/18

**Comment by Misca1234** [comment]
The travis error says that pin VBAT, is a power pin pin, which is not the case.
The travis error should be ignored

**Comment by SchrodingersGat** [comment]
As we are now close to moving all the symbols to the new kicad-symbols repository, this PR will have to be reissued at https://github.com/kicad/kicad-symbols

Thanks for your contributions, and sorry for the inconvenience

**Pull request closed without merging**
