### PR TITLE
adding BC817DS & CSD17579Q3A

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
please fix conflicts!

**Comment by jkriege2** [comment]
Hi!

please fix:
- where does the `BC818-40` come from (in the DCM)? There is no symbol for that ...
- transistors.dcm causes errors when loading in current nightlies!
- since we discussed a bit about hidden pins: You could use a standard MOSFET-symbol from device.lib for CSD17579Q3A and stack 2 hidden S-pins over the one visible one.

Best,
JAN

**Comment by jeromebeguin** [comment]
I don't know what is BC818-40, I don't have it in my library. 
I thought device.lib was abandoned ?

**Comment by jkriege2** [comment]
yes, but it's there in your PR ... maybe a remenant from a merge-gone-wrong? Please remove it, see whether there are any errors with current versions and correct this PR.

**Comment by jeromebeguin** [comment]
Sorry I'don't have this in my lib. And I'm in this current branch. Don't know what happening. I cannot erase something I don't have. 
 image

**Comment by jkriege2** [comment]
simply erase it in the DCM file ... it's a text-file that can be edited with any editor!

**Comment by jeromebeguin** [comment]
Ok, I can do that.

**Comment by jeromebeguin** [comment]
Here we are, could you merge ?

**Comment by jkriege2** [comment]
Hi!

OK, so now for a review of the symbols
1. Please change the symbol for `BC817DS` to be like the other dual transistors that we have in this lib (e.g. `BC846BS`), i.e. make two subsymbols in the symbol!
2. Please fix the errors reported by Travis
3. For the `CSD17579Q3A` you might also consider having a symbol where the doubled/tripled pins are stacked (just a proposal)
4. What about having the ESD diode from the datasheet in the symbol for `RV3C002UN`? Althought that might make the symbol significantly larger ... (just a proposal)
5. The `XR20M1172` comes a bit as a surprise ... next time, please split the PRs by lib, which makes it easier to review the stuff! ... Now about the symbol: Please rename to `XR20M1172IL` as this postfix denominates the QFN32 package ... otherwise looks good to me.

best,
JAN

**Comment by evanshultz** [comment]
A couple follow on questions/concerns:
3. See clause 4.3 of KLC for more details on pin stacking.
5. The "IL" suffix captures both temp range and package. KLC (clause 3.6) states that when packages for a different symbol, append the symbol with the simplified package name. In this case, it would be `XR20M1172_DFN`.

KLC can be found at: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

@jeromebeguin Thanks for the contribution!!

**Comment by jeromebeguin** [comment]
I'm sorry but I don't have the time to make changes all the time. Why don't you asked me to transform directly the BC817DS and the CSD17579Q3A right at the beginning ? It's really hard to add new component to library. I'm taking the time to share because Kicad is free and I'm using it at work. But I could not spend half of my design time to build and correct several time the same component. So please accept the minimum to be useful and if somebody have the time to make it nice and pretty he can modify it as well later on. I'm happy to collaborate at this project, I think it worth. but the way to share is really long and not convenient for a work environment. Please take this in account. Travis helps a lot, this is a big improvement, but I'm sure you can simplify and accelerate the process. 

Best

Jérôme

**Comment by jkriege2** [comment]
Hi!

if I remember correctly, there were already conflicts right when I had a look at it the first time and then I was unable to load your transistors.dcm due to the error I mentioned above ... So all the review process was a bit delayed UNTIL I could have a look at the symbols. Please consider two things for this lib:
1. We try to move towards a common style on most components, so we try to NOT acept stuff that does not fit so nicely ... If we would accept every symbol, we will end up having to find someone that makes everything nice, which will probably never happen ... so: Yes this is a bit of a burdon on the commiter, but will help the overall lib quality.
2. Please also consider: We are also only a small team of maintainers that have jobs of their own on the side therefore we also only contribute a bit of time ... and sometimes things do not go as smoothely as with someone ONLY committed to building this lib!

One way you can easily improve the review process is by providing some info when pushing your PR. usually what is helpful is:
- explain what you did (a bit more elaborated than in the title ;-), e.g. name the components you added/changed
- add screenshots of modified/new components
- give datasheet links

Here's an example of how this could look (and yes that PR of mine was WAYYYY too big ;-)
https://github.com/KiCad/kicad-library/pull/737

Best,
JAN

PS: I will have a look at the changes this evening ...

**Comment by jeromebeguin** [comment]
Thank you for that feed back. I'll try to give you more info to make the review easier.

**Pull request closed without merging**
