### PR TITLE
add DS1267 dual digital potentiometer to maxim

### PR DESCRIPTION
**Pull request by penoud**
I plan to do the SOIC and the TSSOP when this one will be accepted.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

if you want you can also add the other packages to this PR and I review them all at once?

Aboute the ``:
- FPFilter should be `DIP*W7.62mm*`
- several pins seem to be defined multiple time:
```
 Violating EC05 - Extra Checking
   Pin numbers should not be duplicated, and all pins should be present
   Pin 11 is duplicated
   11 - H0 @ 400,300
   11 - H0 @ 600,350
   Pin 5 is duplicated
   5 - ~Reset @ -400,200
   5 - Reset @ -600,-100
   Pin 12 is duplicated
   12 - W0 @ 400,200
   12 - W0 @ 600,250
   Pin 9 is duplicated
   9 - COUT @ -400,-200
   9 - COUT @ 600,-500
   Pin 14 is duplicated
   14 - VCC @ 0,500
   14 - VCC @ 0,700
   Pin 7 is duplicated
   7 - GND @ 0,-500
   7 - GND @ 0,-750
   Pin 8 is duplicated
   8 - DQ @ -400,300
   8 - DQ @ -600,-300
   Pin 10 is duplicated
   10 - L0 @ 400,100
   10 - L0 @ 600,150
   Pin 1 is duplicated
   1 - VB @ 100,-500
   1 - VB @ -600,300
   Pin 13 is duplicated
   13 - SOUT @ -400,-100
   13 - SOUT @ 600,-400
   Pin 3 is duplicated
   3 - L1 @ 400,-200
   3 - L1 @ 600,-250
   Pin 2 is duplicated
   2 - H1 @ 400,0
   2 - H1 @ 600,-50
   Pin 6 is duplicated
   6 - CLK @ -400,100
   6 - CLK @ -600,-200
   Pin 4 is duplicated
   4 - W1 @ 400,-100
   4 - W1 @ 600,-150
```

Best,
JAN

**Comment by penoud** [comment]
I corrected the pin double, the footprint ref and add the SOIC and TSSOP version.

**Comment by jkriege2** [comment]
Hi!

ran the script again:
```
Component: DS1267_DIP
  No violations found
checking component: DS1267_SOIC
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 10 is duplicated
    10 - COUT @ -400,-200
    10 - L0 @ 400,100
    Pin 5 is missing
    Pin 13 is missing
    Pin 15 is missing
checking component: DS1267_TSSOP
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 2 is missing
    Pin 8 is missing
    Pin 9 is missing
    Pin 12 is missing
    Pin 18 is missing
    Pin 19 is missing
```

1. ... please add the NC-pins as such
2. remove the `-`from the `TSSOP`/`SOIC`/`DIP`-FPFilters
3. maybe use the IEC-resistor symbol (box) instead of the wavy-line ... to match the symbols in `device.lib`

Best,
JAN

**Comment by penoud** [comment]
Hi, sorry for mistakes. I hanged them. And correct the aspect of the Pot symbol. I tried to keep the TSSOP smal even with a lot of NC pins. But I you prefer I can extend the component box for the TSSOP.

**Comment by jkriege2** [comment]
nice work1

JAN

**Pull request merged**
