### PR TITLE
NXP: Add PCA9536 and PCA9544

### PR DESCRIPTION
**Pull request by myfreescalewebpage**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Just some minor changes here

* Add package info into the description field so parts can be differentiated in the component selection window (e.g. "4-bi5 I2C-bus and SMBus IO port, **SOIC package**")
* Change line-thickness for the shape to 0.01"

**Comment by myfreescalewebpage** [comment]
Forgotten fo change the shape to 0.01". Finally done.

**Comment by jkriege2** [comment]
Please fix FPFilters. they should be:
- `SOIC*3.9x4.9mm*Pitch1.27mm*`
- `TSSOP*3x3mm*Pitch0.65mm*`
- `SOIC*7.5x12.8mm*Pitch1.27mm*`
- `TSSOP*4.4x6.5mm*Pitch0.65mm*`

Best,
JAN

**Comment by myfreescalewebpage** [comment]
Done.

**Comment by jkriege2** [comment]
@SchrodingersGat do you go on with the review here?
JAN

**Comment by SchrodingersGat** [comment]
Sorry, didn't mean to close this - checking over it now

**Comment by SchrodingersGat** [comment]
Great, these look good :)

**Pull request merged**
