### PR TITLE
KLC compliance for linear.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
I have fixed a lot of KLC errors and added some new part aliases to linear.lib

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@ricardocrudo in addition to fixing most parts against some of the KLC rules, I have added some new op-amps and aliases (which now have documentation, too).

**Comment by SchrodingersGat** [comment]
Can I get some feedback on whether ADC1118 (16-bit quad-input ADC) should go here or in interface.lib. If you want me to move it before merging this please let me know. Thanks.

**Comment by CarlPoirier** [comment]
Hi Oliver,

Here are my comments:

1. Can you make the 1408 smaller and use 100mils pins as per rule 1.1 for black-box symbols?
2. AD620, AD813, CA3130, and all the others, can you try to shorten the pins such as with ADA4075 or LM2902N?
3. As for the ADS1118, I suggest putting it in the adc-dac library.

Besides that, it looks good!

Thanks,

Carl

**Comment by SchrodingersGat** [comment]
Done (I think!) I've adjusted a lot of schematic symbols therein.

**Comment by CarlPoirier** [comment]
test this please

**Comment by CarlPoirier** [comment]
Thanks Oliver for your hard work!

**Pull request merged**
