### PR TITLE
Pic16 l f18346

### PR DESCRIPTION
**Pull request by Misca1234**
PIC16F18346
all four formfactors
PIC16F18346-P
PIC16F18346-GZ	is an PIC16F18346-P alias
PIC16F18346-SO	is an PIC16F18346-P alias
PIC16F18346-SS	is an PIC16F18346-P alias
http://ww1.microchip.com/downloads/en/DeviceDoc/40001839B.pdf

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Should I remove all variants, that is PIC16F18346-P, PIC16F18346-GZ, PIC16F18346-SO and PIC16F18346-SS 
and only have one variant, PIC16F18346, because the footprint  filter is in PIC16F18346-P anyway ?

**Comment by poeschlr** [comment]
The aliases are ok. 
But i would shorten the pin names. (Remove the functional descriptions and use the main name only. Example RA5, RA4, ...)
Have a look at pull request https://github.com/KiCad/kicad-library/pull/1311 to see what i mean.

**Comment by Misca1234** [comment]
Nice, I wanted to do that (otherwise they become so large) but when I looked at the already approved ones they had the full pin descriptions so I did the same.

**Comment by Misca1234** [comment]
Now it looks like this 

bild

**Comment by poeschlr** [comment]
The footprint filters should not include pin numbers.
It should match dimensional information though.

Also the uqfn version has different pin numbers compared to the other versions. (you need a separate symbol for this version.)
Maybe make the symbol atomic. (add the 4 symbols you where previously aliases and set the footprint field to the appropriate value.)

The Rxy pins should be bidirectional. (i assume these are gpio pins)
Why is RC6 a power input pin?

**Comment by Misca1234** [comment]
Ohhh, you got an falk eye, what a practical move of Microchip to change the pin numbering for one of the capsules.

The schematic have been separated into four schematic
PIC16F18346-P  PDIP 
PIC16F18346-SS SSOP
PIC16F18346-SO SOIC
PIC16F18346-GZ which is the UQFN
In order to be able to specify a specific footprint for each of them

If I remove the pin number form the foot print filter it will look like this for the PDIP 
DIP*7.62mm*
and don't specify a specific footprint it means it will match almost ALL PDIP footprints


All Rxx pins are now bidirectional (including RC6) 

bild

bild

bild

bild

PS
If this is ok I will do the same for PIC16F18344
https://github.com/KiCad/kicad-library/pull/1343
DS

**Comment by poeschlr** [comment]
The pin count is matched by a separate kicad filter. (In cvpcb the one with the # sign i think.)

**Comment by Misca1234** [comment]
Hmm, I have been searching through a couple .lib files and did not find the # sign for the footprint filter.

I notice there are a lot of work to do among the existing schematics, for example PIC16(L)F1459-I/P will match all DIP foot prints.

Perhaps we should keep these four (PIC16F18346) as they are now?

**Comment by poeschlr** [comment]
Sorry to confuse you. This button is what i meant:
screenshot from 2017-06-24 15-01-25
It toggles the option to use the number of pins in the symbol to filter which footprints will be listed.

**Comment by poeschlr** [comment]
I checked the symbol and it looks good now.
Thanks for this contribution.

**Comment by Misca1234** [comment]
Aha, ok, nice to know.

Thx, I will fix the PIC16F18344 in same way

**Pull request merged**
