### PR TITLE
Ea e diptft70 xxx

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIPTFT70-A (and it's alias EA eDIPTFT70-ATP and EA eDIPTFT70-ATC)

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/ediptft70-ae.pdf

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1500

pretty push branch is 
https://github.com/KiCad/Displays.pretty/pull/36

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/128

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/52

The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

**Comment by jkriege2** [comment]
Great work!

only two minor things:
1. see my comment there: https://github.com/KiCad/Displays.pretty/pull/28 ...
2. as discussed elsewhere, how do we handle color/colour? (just trying to keep the lib consistent ... no offense implied!)

Best,
JAN

**Comment by Misca1234** [comment]
There is also another isssue, see 
https://github.com/KiCad/kicad-library/pull/1494

I "did the RS-232" just to make it easy for me but depending on how the discussion goes in
https://github.com/KiCad/kicad-library/pull/1494
I might have to create more symbols

**Comment by jkriege2** [comment]
OK, I merged the package/footprint, could someone ( @poeschlr ???) please merge this, when the issue above has been resolved ... I will be away for a few days now!

Thanks,
JAN

**Comment by Misca1234** [comment]
Let us wait with this one until 
https://github.com/KiCad/kicad-library/pull/1495
is merged.
https://github.com/KiCad/kicad-library/pull/1495
Messes up the lib and dcm for each of my displays pushes

**Comment by Misca1234** [comment]
This push have been repalced by 
https://github.com/KiCad/kicad-library/pull/1647

**Pull request closed without merging**
