### PR TITLE
Add 3d model for leds of 10mm and 8mm

### PR DESCRIPTION
**Pull request by andres53016**
in this pull request  https://github.com/KiCad/LEDs.pretty/pull/9 are the corresponding footprint.

### CODE REVIEW

**Comment by Caerbannog** [comment]
The files named with a `wings~` suffix are backups and probably shouldn't be included in this pull request.

**Comment by andres53016** [comment]
In the last commit I remove the backup files.

**Comment by ricardocrudo** [comment]
merge along KiCad/LEDs.pretty#9

**Comment by ricardocrudo** [comment]
thanks @andres53016. sorry for delay.

**Comment by andres53016** [comment]
you welcome!

**Pull request merged**
