### PR TITLE
Improved Vsource and Isource symbols

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Makes the Vsource and Isource symbols smaller, fixing issue https://github.com/KiCad/kicad-library/issues/1684

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi @SchrodingersGat ... those symbols seem all a bit off in style ... do you know how the PSPICE integration works? Couldn't one simply use the existing symbols? If not, we should make sure these have unique names (When placing an R from pspice.lib, you actually get the R from device.lib) and they should conform in style to the existing symbols?

best,
JAN

**Comment by SchrodingersGat** [comment]
Honestly I have no idea. I don't know what these symbols are for.

**Comment by evanshultz** [comment]
I'd like to take a look. I've got quite a bit of SPICE and other simulator experience. I believe the interface is a bit rough right now. If this isn't an emergency to figure out, I'll come back to it in a few weeks.

**Comment by jkriege2** [comment]
In think it's not an emergency ;-) ... just saw it when reviewing Oliver's PR.
Maybe we can contact the developer, responsible for the integration to explain this?

Best,
JAN

**Pull request merged**
