### PR TITLE
adding +/-9VA to power lib

### PR DESCRIPTION
**Pull request by ricardocrudo**

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Please also create/update documentation fields for aliases.

**Comment by ricardocrudo** [comment]
Can you help with this? what do you suggest to write in this fields? All the other power symbols doesn't have documentation field, so I don't have parameter.

**Comment by keruseykaryu** [comment]
I was talking about the MCP1754 components from a second commit and his aliases.
Power symbols does't have any aliases.

**Comment by ricardocrudo** [comment]
done

**Pull request merged**
