### PR TITLE
Added MPXA6115A pressure sensor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added MPXAZ6115A alias
Added MPXH6115A alias
Added MPXHZ6115A alias

Ref: http://www.nxp.com/files/sensors/doc/data_sheet/MPXA6115A.pdf

### CODE REVIEW

**Comment by diggit** [comment]
Same symbol question as for #470.

Try to match symbol for all components (same purpose visible pins #470), that share same visible pins -&nbsp;> easily replaceable in schematic. [For explanation look here.](https://github.com/KiCad/kicad-library/pull/455#issuecomment-207978528)

**Comment by SchrodingersGat** [comment]
@diggit I have changed the symbol to match the 40PC sensors. LMK if you are happy (or otherwise) with the graphical style of these sensors

**Comment by diggit** [comment]
Today, my happiness is low. Fortunately, it has nothing to do with kicad. :)
Same as #470

**Comment by SchrodingersGat** [comment]
@diggit answer same as https://github.com/KiCad/kicad-library/pull/470 ! if you can find a better symbol, LMK (or I can just remove it if you think it's confusing). Hope your happiness improves ;)

**Comment by diggit** [comment]
Unfortunately no FP available in KiCAD atm.
Nice work you did, merging.

**Pull request merged**
