### PR TITLE
MAX1112 & MAX1113

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds the MAX1112 (8-channel) and MAX1113 (4-channel) ADCs to the adc-dac library.
[Datasheet](http://datasheets.maximintegrated.com/en/ds/MAX1112-MAX1113.pdf)

I am not really sure about the type of the COM and REFIN ports. Currently both are set to power input. I am not sure whether that is correct for voltage references.

max1112
max1113

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work!

Two small requests though:
1. please add the keyword `ADC` to the tags
2. please make pins shorter ... 100mil (as in most ADCs/DACs in the lib) should be enough.

Thanks,
JAN

**Comment by lorem-ipsum** [comment]
Hi JAN,

thanks for the review, I've adjusted the schematics as requested.

Cheers,
Hendrik

**Comment by evanshultz** [comment]
I think it would look better if the pin text offset was moved from 40mil down to 20 or 10.

**Comment by lorem-ipsum** [comment]
I agree (at least with 20), but I am not sure about changing it for this specific component. A general standard as requested in your issue seems to be the better approach.

**Comment by jkriege2** [comment]
Since there is currently no real standard, change to a setting that looks visually pleasing to you ;-)

Let me know, ehn done so I can merge! (I often also use 10, especially in small symbols like VRegs ;-)

Best,
JAN

**Comment by lorem-ipsum** [comment]
I've changed it to 20. If you're happy with them you can merge

**Comment by jkriege2** [comment]
Thanks, Great work!
JAN

**Pull request merged**
