### PR TITLE
Logic_74xx: Add 74LCX07

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

When adding symbols it is beneficial if you push some screen shoots as well, like in this push

https://github.com/KiCad/kicad-library/pull/1712

**Comment by piotr-wiszowaty** [comment]
Screenshots.

74lcx07

74lcx07_descr

74lcx07_footpr

**Comment by poeschlr** [comment]
The logic libs are already in the process of being transferred over to the v5 repo.
For this reason please re submit your contribution once pull request https://github.com/KiCad/kicad-symbols/pull/11 has been merged.

**Comment by SchrodingersGat** [comment]
Hi @piotr-wiszowaty sorry for the inconveniece - please resubmit this PR to https://github.com/kicad/kicad-symbols

**Pull request closed without merging**
