### PR TITLE
Added SOT-23W

### PR DESCRIPTION
**Pull request by Misca1234**
3D models for merged push 
https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/59

They are made with kicad-3d-models-in-freecad

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

looks good ... could you please post a screenshot with the 3D model on the footprint?
Also: Could you post the FCStd-file here: https://github.com/KiCad/packages3D-source

Thanks,
JAN

**Comment by Misca1234** [comment]
Here they are 

bild

bild

**Comment by Misca1234** [comment]
Here they are 

bild

bild

**Comment by jkriege2** [comment]
great work!
Thanks,
JAN

**Pull request merged**
