### PR TITLE
Added Molex KK 6410 series 3D models

### PR DESCRIPTION
**Pull request by hackscribble**
Added 15 `STEP` and `WRL` models for KK 6410 series connectors.  

Footprint updates PR: 
https://github.com/KiCad/Connectors_Molex.pretty/pull/36

Other related PRs: 
https://github.com/KiCad/packages3D/pull/34 
https://github.com/KiCad/packages3D-source/pull/4
https://github.com/pointhi/kicad-footprint-generator/pull/31

image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Nice! I will wait until you have submitted the other PRs and merge them once they are all finalized :)

**Comment by hackscribble** [comment]
Hi @SchrodingersGat 

There are two 7.4 errors being reported on the footprints (https://github.com/KiCad/Connectors_Molex.pretty/pull/36)

One is missing REF designator, which is quick to add with the --fix option.  The other is missing outline on Fab layer.

I think you may have been the author of these footprints?  Did you use a script to generate them?  If so, updating that script might be the best way to fix the errors.  If not, I don't mind going through manually and updating them.

Please let me know what you think.

**Comment by SchrodingersGat** [comment]
IIRC this is a script that @pointhi wrote, it's available [here](https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Molex/connectors_molex_kk_6410_top.py)

**Comment by hackscribble** [comment]
Cool.  I'll take a look and see if I can add the missing items that way.

**Comment by hackscribble** [comment]
I have fixed the footprints and updated PR https://github.com/KiCad/Connectors_Molex.pretty/pull/36

All PRs should be OK to merge now, I think.

**Pull request merged**
