### PR TITLE
Modified LT1761 LDO regulators family.

### PR DESCRIPTION
**Pull request by mpkopec**
More compact design now. Changed names of particular devices to match
pinouts and part numbers from the datasheet (page 2, section Pin
configuration).

### CODE REVIEW

**Comment by diggit** [comment]
needed changes.
- make all symbols same size where their common pins are on same place for all. It makes replacing simpler.
Here is little explanation.
```
  sym. 1          sym. 2          sym. 3
  -------         -------         -------
-| A   B |-     -| A   B |-      |       | 
 |     D |-     -| C     |      -| C   D |-
  -------         -------         -------
```
(eg. place for D pin is occupied by D pin or is left unused, for all symbols)

- [KLC 3.3](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt#L34) Origin is placed in the middle of symbol.
- replace suffix *-X* with fixed voltage suffix (LT1761-5, LT1761-1.2,... - use **aliases** to one of them)
- add keyword **adjustable** to symbols with suffix *-SD* *-BYP*  and to description too
- TSOT-23\* filter is ok - leave it there, but add SOT-23\* because there are no TSOT package FootPrints at the moment. And the only difference is package height - their FPs are compatible.
- change SOT-23 to TSOT-23 in description to match reality

**Comment by mpkopec** [comment]
Ok, I followed all your suggestions, but one thing buffles me - how to use aliases. Do I make one symbol, e.g. LT1761-5 and put aliases LT1761-1.2 and so on in the aliases tab there, or do I make more components and alias them together? First seems more sensible, but I would like to be sure.

**Comment by mpkopec** [comment]
nvm, I tested the first solution and it works perfectly, so I'll upload it shortly.

**Comment by mpkopec** [comment]
Checked dcm file and the description, as well as keywords are intact, I don't undesrstand failing checks.

**Comment by diggit** [comment]
Alias uses same drawing but i has separate:
- name (identification of alias)
- documentation
 - description
 - keywords
 - datasheet

So when you create aliases, you have to select it from top right menu and fill documentation for each alias. As these aliases have only different voltage, button "Copy Document from parent" comes handy...

Use checklib.py from [kicad-library-utils](https://github.com/KiCad/kicad-library-utils) wit -vv switch to get more verbose error output.

```
checklib.py -vv --enable-extra  -c LT1761-5 library/regul.lib
library: library/regul.lib
checking component: LT1761-5
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    documentation OK
    checking alias: LT1761-3.3
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-2.5
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-2
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-1.2
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-2.8
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-1.8
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-3
      missing whole documentation (description, keywords, datasheet)
    checking alias: LT1761-1.5
      missing whole documentation (description, keywords, datasheet)
```
Keep in mind, that -c parameter for selecting component works with *symbol name only*.

At LT1761-BYP you have F2 (footprint) field placed differently, please unify it with others. (Fields>Foorptint>PosY 0.350->0.250)

**Comment by mpkopec** [comment]
How can I change the name? I don't know where to find it in the library editor.

**Comment by diggit** [comment]
Name of what?
Basically, all parameters are accessible through Fields editor (big **T** icon) or through documentation editor (ABC, opamp, gear icon)

**Comment by mpkopec** [comment]
Name (Value) field is greyed out and cannot be edited.

Screenshot (one of the aliases opened):
[image: Obraz w treści 1]

2016-04-13 23:19 GMT+02:00 Patrik Bachan <notifications@github.com>:

**Comment by diggit** [comment]
In library editor, move mouse over component name and hit key **E**. Then you can edit value. This value belongs to main component. Aliases won't be affected.

**Comment by mpkopec** [comment]
Thanks, the rest should be good

**Comment by diggit** [comment]
Please:
- add keywords: *fixed, positive, adjustable,...* accordingly
- expand keyword *regul* to full word *regulator*
- LT1761-BYP set FP field *posY* to 0.250 to match your other symbols

**Comment by diggit** [comment]
Thanks, for your contribution.
Nice work you did, merging.

**Pull request merged**
