### PR TITLE
create Intersil lib and add ICL3232 component

### PR DESCRIPTION
**Pull request by jjuyon**
Hello I'm a new user of KiCAD (Eagle CAD background). This is my first comit and I have some other modification coming soon.

The RXx_out pin are intentionally on the left and RXx_in pin on the right for an easy use in schematic design.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. What I can say from a quick glance (will have a closer look this evening):
1. Please provide keywords and datasheet-link info
2. Maybe move this device to interface.lib? MAX3232 is already there!

Generally:
 we have a set of rules that a symbols/footprint has to follow (KLC). You can find them here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention Also note that we are currently discussing an updated version with more explanations (see https://github.com/SchrodingersGat/kicad-library/wiki/KLC and https://github.com/KiCad/kicad-library/issues/879)

Best,
JAN

**Comment by jjuyon** [comment]
Ok Thanks,
I haven't seen the MAX3232 which is the same. So I just remove Intersil.lib that I have created and I hve added an alias "ICL3232" into the MAX3232 component.
Is that right?

**Comment by diggit** [comment]
Please fill documentation for ICL3232. It is specific for each alias. You can copy it from parent (there is button for it) then edit it to match ICL3232 specs and preserve format.
Then, please solve conflicts.

What KiCAD version do you use? It made changes in line endings.

**Comment by jjuyon** [comment]
Ok thanks, it's done. Documentation is filled.

I'm using KiCAD 4.0.5-e0-6337 from Ubuntu 16.04 repository

**Comment by jjuyon** [comment]
Hi,
Conflicts have just been solved.

**Comment by jjuyon** [comment]
Hi,
Conflicts have been solved

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Pull request merged**
