### PR TITLE
Ak4182 a

### PR DESCRIPTION
**Pull request by Misca1234**
This is push for AK4182A

AK4182A
http://www.akm.com/akm/en/file/datasheet/AK4182AVN.pdf

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
FPFIlter should be `QFN*4x4mm*Pitch0.65mm*`
Best,
AJN

**Comment by jkriege2** [comment]
Also it appears that you have doubled a pin10!

**Comment by Misca1234** [comment]
Mmm, that how it goes if checking a copy paste, I forgot to add pin 17 as well

**Comment by jkriege2** [comment]
Nice Work!
JAN

**Comment by Misca1234** [comment]
I suspect that the travis script errors should be ignored, The VBAT is actually an input and not power input and the VREF is redirectional according to data sheet

**Comment by Misca1234** [comment]
Oh, you was fast, thanks

**Pull request merged**
