### PR TITLE
Lm2990

### PR DESCRIPTION
**Pull request by dejfson**
LM2990 Negative low-dropout regulator and its three variants available in DDPAK. 

Note that this does not pass the KDC tests due to symbol having ground pin at the top of the schematic. I believe that this is commonly used (and regul.lib is full of examples as well). If that is not acceptable, let me know where the ground pin should be located.

thaaanks

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

Please note that I'm currently working on a big ovrhaul of regul.lib (see https://github.com/KiCad/kicad-library/pull/948) ... 

Please ensure that your symbol conforms to the style set in that PR (symbol size and all) ... I will review/merge this PR, when my overhaul is completed (to keep noise as low as possible ;-)
OK?

Best,
JAN

**Comment by dejfson** [comment]
ok

**Comment by Misca1234** [comment]
This push can be closed and deleted

Re push of LM2990 is here 
https://github.com/KiCad/kicad-library/pull/1712

**Comment by SchrodingersGat** [comment]
Thanks @Misca1234 and @dejfson

**Pull request closed without merging**
