### PR TITLE
Created AS3935 lightning sensor in sensors.lib.

### PR DESCRIPTION
**Pull request by openelectron**
Datasheet is free but behind a registration link.

digikey has a mirror;
https://media.digikey.com/pdf/Data%20Sheets/Austriamicrosystems%20PDFs/AS3935.pdf

### CODE REVIEW

**Comment by openelectron** [comment]
by the way, which version of kicad is recommended for contributing to the libraries? stable or nightlies?

**Comment by Misca1234** [comment]
Both will due, but the nightly build have a cool feature so your screen shoots show the type pins , like in this push

https://github.com/KiCad/kicad-library/pull/1712

**Comment by openelectron** [comment]
screenshot_2017-12-04_09-49-59

**Comment by SchrodingersGat** [comment]
@openelectron we have begun the transition process to a new consolidated symbols library at https://github.com/kicad/kicad-symbols 

The sensors libraries have now been transferred - please re-open this PR at the new repository. Sorry for the inconvenience.

To match the new naming scheme, please make a new library called `Sensor.lib`

**Pull request closed without merging**
