### PR TITLE
Updated pretty library descriptions for fp-lib tables

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds the harwin connector footprint library to the fp-lib tables

https://github.com/KiCad/Connectors_Harwin.pretty

It also begins to improve the description fields for the various .pretty repositories in the fp-lib tables, moving away from the "as you like them" description.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I have also now added in references to the new Battery_Holders repo. @diggit  @ashtonchase any other improvements you can see?

**Comment by diggit** [comment]
There were another one repo addition: https://github.com/KiCad/Connectors_Amphenol.pretty

Word **various** is useless, because it is expected from library. 

**Buzzers_Beepers** - Audio signaling devices
**Choke_Axial_ThroughHole** - Chokes, axial, through hole
**Choke_Radial_ThroughHole** - Chokes, radial, through hole
**Choke_SMD** - Chokes, surface mount
**Displays_7-Segment** - 7 segment displays
**Housings_SOIC** - SOIC *packages/housings*
**Housings_SSOP** - SSOP, TSSOP, MSOP, QSOP, VSO packages
**IR-DirectFETs** - DirectFet packages from International Rectifier
**Measurement_Points** - terminals for test equipment
**Measurement_Scales** - measurement scales, gauges
**Mechanical_Sockets** - sockets for board to board connection

Not sure about these libs, they look old and should be reorganized/renamed/removed/sorted to other libs in future, ignore for now, maybe "deprecated" to description?
**Discret** - looks like some mix of polarized capacitors and resistors
**Divers** - "various" from french? several transformer FPs
**EuroBoard_Outline** - missing reference documents
**Connect** - mix of connectors, THT, SMT, non english docs
**Inductors** - mix of several FPs without doc
**Labels** - silkscreen drawings of some kind of labels for _National People's Army_?

**Comment by CarlPoirier** [comment]
Hi guys,

Here are my suggestions for the remaining ones.

Discret - Discrete components
Divers - Miscellaneous (That's what Divers means in french)
EuroBoard_Outline - PCB outlines
Connect - Miscellaneous Connectors
Inductors - Inductors
Labels - Labels for writing indications by hand

**Comment by diggit** [comment]
Hi @CarlPoirier,

**Discret** - capacitors, resistors, transistors, diodes,... all have their footprints somewhere else. This library is imo deprecated and should be removed. (I know, removing is problem for back compatibility. So "deprecated" in description would be enough for now.)

**Labels** - I don't know about any generalized labels. This shouldn't be in community repo.

**Inductors** - All current inductor FPs are heading to Choke* repos. (eg. https://github.com/KiCad/Choke_SMD.pretty/pull/6 ). I don't know if it's right, but now we have 2 places (considering all Choke repos as 1) and this one looks less active.

**Comment by SchrodingersGat** [comment]
Some more improvements have been made as per suggestions here. I think a lot of this hinges on pending library cleanup and consolidation. 

In particular, the issues regarding the multiple Inductors / Chokes libs:

https://github.com/KiCad/Choke_SMD.pretty/pull/6
https://github.com/KiCad/kicad-library/issues/257

**Comment by CarlPoirier** [comment]
Hi @diggit 

Are you sure all components in Discret.pretty have their footprints somewhere else? If so, indeed we'll mark it as deprecated. As for labels, I'm not sure what you mean about "generalized" labels. They are simple placeholders if ever you need to write indications on the PCB.

@SchrodingersGat, I replied in the https://github.com/KiCad/kicad-library/issues/257.

**Comment by pointhi** [comment]
we should update fp-lib in the next days, because it look like KiCad 4.0.3 would be released soon.

Please don't forget **Connectors_Phoenix.pretty**

**Comment by SchrodingersGat** [comment]
I have made further changes. Please look over this and decide. Even if it's not "everything" it's a whole lot better than it has been.

Cheesr

**Comment by pointhi** [comment]
**Battery_Holders** does not contain footprints yet
**Connectors_Amphenol** doesn not contain footprints yet
**Connectors_Samtec.pretty** missing

**Pull request merged**
