### PR TITLE
Added NXE2S0505MC

### PR DESCRIPTION
**Pull request by Matyro**
Added Low Cost 2W isolated power supply

http://power.murata.com/data/power/ncl/kdc_nxe2.pdf

You can find the foodprint under:
https://github.com/KiCad/Converters_DCDC_ACDC.pretty/pull/16

schematic

### CODE REVIEW

**Comment by hackscribble** [comment]
Hi @matyro I will review this PR and your related footprint PR.  But I would like to check something ...

@SchrodingersGat This device package has five pins numbered non-consecutively.  Should these numbers be used in the symbol and footprint, rather than 1 .. 5?

image
image

**Comment by poeschlr** [comment]
I vote to use the non consecutive numbers. (The datasheet numbers should be used.)

**Comment by hackscribble** [comment]
Thanks @poeschlr  Also, is it OK to name the unused pin `NA` as per datasheet? KLC 4.7.iii specifies `NC`.

**Comment by hackscribble** [comment]
Many thanks for the further contribution :smile:

**Pull request merged**
