### PR TITLE
added Tianbo-4102-L relay symbol (DIL-type package)

### PR DESCRIPTION
**Pull request by jkriege2**
datasheet: https://cdn-reichelt.de/documents/datenblatt/C300/DS_HJR4102E.pdf

symbol conforms to KLC, 

footprint is available here: https://github.com/KiCad/Relays_ThroughHole.pretty/pull/8

hjr4102
hjr4102s
tianbo

### CODE REVIEW

**Comment by jkriege2** [comment]
symbol conforms to KLC, 

footprint is available here: https://github.com/KiCad/Relays_ThroughHole.pretty/pull/8

hjr4102
hjr4102s
tianbo

**Comment by SchrodingersGat** [comment]
Hi Jan, please fix conflicts here :)

**Comment by jkriege2** [comment]
fixed!

**Comment by SchrodingersGat** [comment]
Great thanks :)

**Pull request merged**
