### PR TITLE
Update powerint lib for KLC-compliance and add TOP-JX family

### PR DESCRIPTION
**Pull request by evanshultz**
I added the TNY-4 family in PR #845, but found there were a lot of KLC violations in the library. So I went to work updating and expanding it. Here are my notes as I modified:

powerint.lib (and general changes)
- add missing parts and packages when reviewing datasheets
- changed LNK459 to LNK460
- make footprint text KLC-compliant
- pass KLC
- correct LNK632DG package
- TOP214 moved to alias of TOP200 family
- TOP210PFI moved to alias of TOP209P

powerint.dcm (in addition to supporting the changes required from the LIB file)
- use open frame 85-265Vac power rating (only a few didn't use this rating)
- add package name in description for all parts

Please review and comment.

I've also created the [TOP-JX family](https://ac-dc.power.com/sites/default/files/product-docs/topswitch-jx_family_datasheet.pdf) and will be happy to add it to this patch or create a separate PR.

And finally, as you can see from the first page of the datasheet above there is a "K" and "V" package. To make this lib work together properly with Power Int's nomenclature, a few footprint changes are in order. See https://github.com/KiCad/Power_Integrations.pretty/pull/2 and https://github.com/KiCad/Power_Integrations.pretty/pull/3. And if I know this will happen, I need to update this PR to change "eSOP-12" to "eSOP-12B". Let me know and I'll happily do it before merging.

Thank you!

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks to Jan for merging https://github.com/KiCad/Power_Integrations.pretty/pull/3! In light of that merge, please don't merge this PR so I can update the footprint names for the "V" package.

Review would be appreciated!

**Comment by evanshultz** [comment]
Updated the lib to match with the PR mentioned above regarding the "V" package name correction.

I also added the [TOPSwitch-JX family](https://ac-dc.power.com/sites/default/files/product-docs/topswitch-jx_family_datasheet.pdf). No KLC violations.

Symbol images:


There are multiple symbols in this PR which need Power Int's "K" package. Please review and merge https://github.com/KiCad/Power_Integrations.pretty/pull/2 in conjunction with this PR.

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 Are you guys available to review and answer the questions above? What do I need to do to get this PR merged?

**Comment by jkriege2** [comment]
Hi!
nice work!

for me the "overlapping pins" trick or the visible pins is fine ... BUT: Generally I would try and orient on the style set by the other parts in this lib, so it is consistent ... i.e. use separately visible pins

About TOP264 (pin5-missing can be ignored ... that's due to the pin-numbering of the manufacturer):
```
checking component: TOP264EG
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP265EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP266EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP267EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP268EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP269EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP270EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP271EG
      missing datasheet, please provide a datasheet link if it isn't a generic component
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 200, posy 350, recommended posx -300, posy 325
    field: reference, justification L, recommended R
    field: name, posx 200, posy 250, recommended posx -300, posy 250
    field: name, justification L, recommended R
    field: footprint, posx 0, posy 0, recommended posx 250, posy -250
    field: footprint, justification C, recommended L
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 6 is missing
checking component: TOP264KG
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP265KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP266KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP267KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP268KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP269KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP270KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP271KG
      missing datasheet, please provide a datasheet link if it isn't a generic component
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 200, posy 350, recommended posx -300, posy 325
    field: reference, justification L, recommended R
    field: name, posx 200, posy 250, recommended posx -300, posy 250
    field: name, justification L, recommended R
    field: footprint, posx 0, posy 0, recommended posx 250, posy -250
    field: footprint, justification C, recommended L
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 5 is missing
checking component: TOP264VG
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP265VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP266VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP267VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP268VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP269VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP270VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
    checking alias: TOP271VG
      missing datasheet, please provide a datasheet link if it isn't a generic component
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 200, posy 350, recommended posx -300, posy 325
    field: reference, justification L, recommended R
    field: name, posx 200, posy 250, recommended posx -300, posy 250
    field: name, justification L, recommended R
    field: footprint, posx 0, posy 0, recommended posx 250, posy -250
    field: footprint, justification C, recommended L
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 5 is missing
```

Also, the fpfilters should usually follow this style (IMHO): `eSIP*C*` The pin-number is not necessary. But maybe here (due to the missing pin5) I would only replace the separators by wildcards, e.g.: `eSIP?7C*`

Best,
JAN

**Comment by evanshultz** [comment]
Doh! Added TOP-JX datasheet.

For the footprint filter, in this case it's linked to a specific footprint in Power_Integrations.pretty. And each symbol definition is linked to a specific footprint. What's the reason for making the FPLIST so loose? To allow underscores, hyphens, etc.?

**Comment by jkriege2** [comment]
Hi!

yes, ? will allow for a limited rename (e.g. _ --> - ...), also usually we match the pin number with the pin number filter. But in this case the latter does not seem necessary to me.

I'll have a closer look at the other changes soon, so we can move forward towards merging.

Best,
JAN

**Comment by jkriege2** [comment]
Some more thing I noticed:
- TOP209P TOP209G is missing several pins (2,3,6,7). Please add them as NC
- TNY284K has pins 9 and 10 duplicated several times
- LNK457V LNK457K has pins 1,4,5 missing
- LNK362P LNK362G has missing and duplicated pins
- CAP002DG has missing pins

Could you fix those?

Thanks,
JAN

**Comment by evanshultz** [comment]
I'm happy to. I don't see these issues even with the "-vvv" switch to checklib.py; can you let me know if you found these manually or used some automation? Anyway, these appear to be mostly issues with the existing powerint.lib parts so it's nice to update them.

Let me address these one-by-one for clarity:
- TNY284K has pins 9 and 10 duplicated several times: fixed, and I've seen this happen other times as well but I don't know the conditions

**Comment by evanshultz** [comment]
One note about the changes above:
- LNK457K/K: I also found pin 13 was overlapping pin 12 on"K" package. Pin 5 is not present on these parts.

And also one question:
-CAP002DG has actual connections only on pins 2,3,5,7. However, it's recommended to connect the other 4 pins (datasheet, page 2, 2nd paragraph). How to handle that? Use visible NC pins?

**Comment by evanshultz** [comment]
CAP002DG:
- See above about pin connections. I addressed in a way that makes it easiest to connect the NC pins if desired and also doesn't grow the body size.
- I'm not super happy with the text locations but it avoids schematic wires.
- This little arcs are a bit weird and not shown in the datasheet. Remove?

**Comment by evanshultz** [comment]
A few more changes to CAP002DG, but please see the above comment too:
- Changed the NC pin type from Not Connected to Passive. Oops.
- I moved the text locations thinking that if a user read the datasheet and wants to use the NC pins, they can move the text on the schematic. Moving the text is probably likely to happen anyway. Is there a better location?

**Comment by jkriege2** [comment]
To me the CAP002DG looks fine ... maybe remove the little arcs if it is not desired to say that is a sine oscillator (that's how I would understand them) ... Maybe move all pins to upper/lower border? Maybe looks better (not sure myself)???
2016-12-31 15_42_38-part library editor d__kicad_kicad-library-review_library_powerint lib

About the multiple-pins: For me a current version of the check scripts reports them (I provoked it for this example:
```
D:\KiCAD\kicad-library-review\library>..\..\kicad-library-utils\schlib\checklib.py -vv --enable-extra powerint.lib -p LNK457
checking component: LNK457K
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: FB (2), posx 525, posy -300
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 0, posy 350, recommended posx -500, posy 325
    field: reference, justification L, recommended R
    field: name, posx 0, posy 250, recommended posx -500, posy 250
    field: name, justification L, recommended R
    field: footprint, posx 0, posy 0, recommended posx 450, posy -250
    field: footprint, justification C, recommended L
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 2 is duplicated
    2 - FB @ 400,-300
    2 - FB @ 525,-300
    2 - FB @ 600,-300
    Pin 5 is missing
checking component: LNK457V
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 0, posy 350, recommended posx -500, posy 325
    field: reference, justification L, recommended R
    field: name, posx 0, posy 250, recommended posx -500, posy 250
    field: name, justification L, recommended R
    field: footprint, posx 0, posy 0, recommended posx 350, posy -250
    field: footprint, justification C, recommended L
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 5 is missing
```

Some things I still spotted:
- LNK362P has the wrong pinout (it should be the same as the G version, NOT as the D version)

Best,
JAN

**Comment by evanshultz** [comment]
Hi Jan,

CAP002DG:
KLC 3.3 states that the origin should be in the middle of the symbol. Without making the body bigger, I didn't see a way to improve things without pins on the side. It appears in your screenshot that the origin is no longer in the middle. That would mean that a schematic update could shift the symbol and break connections (though of course updating the symbol is optional). So which is the best way to go? I do like your symbol's look a little more, but I'm inclined to keep my patch.

LNK457:
For both packages, pin 5 is actually missing. So that's not a real problem. With regards, to the other issues, I don't see any duplicate or off-grid pins. Here is my [latest patch](https://github.com/evanshultz/kicad-library/commit/6f7ff528ec7256ef89e47a55ba61e2b34d08caf9):
image

What am I missing? I don't see it.

Also, thanks for the code above. There are even more useful CLI switches than I knew about! :)

LNK362P:
Fixed. Thank you.

**Comment by jkriege2** [comment]
Looks good now ... will you change CAP002DG? After that I can merge!

best,
JAN

**Comment by evanshultz** [comment]
Thanks for the comment, Jan. Above you said that CAP002DG looked fine and made some suggestions that seemed optional. I asked some questions about centering the symbol. Are you saying you won't accept CAP002DG without changes? I didn't feel there was a conclusion to the discussion.

**Comment by jkriege2** [comment]
Ahhh ... OK, didn't read thoroughly enough :-( ... sorry ... I'll merge!

Thanks for all the work you put in!!!
Best,
JAN

**Comment by evanshultz** [comment]
You're very welcome! If a change is required, I'll happily do it, I just didn't realize if our discussion was finished. Thanks!!

**Pull request merged**
