### PR TITLE
Add linear power factor controllers

### PR DESCRIPTION
**Pull request by raiden00pl**
Datasheets:
http://www.linear.com/docs/3968
http://www.linear.com/docs/3129
http://www.linear.com/docs/1119

### CODE REVIEW

**Comment by diggit** [comment]
using checklib.py from [kicad-library-utils](https://github.com/KiCad/kicad-library-utils)

checking component: LT1248
  Violating Rule 3.8
checking component: LT1249
  Violating Rule 3.8
checking component: LT1509
  Violating Rule 3.8

refer to [KiCad_Library_Convention](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt)

**Comment by raiden00pl** [comment]
it's weird becouse checklib.py returns to me:

checking component: LT1248
  No violations found
checking component: LT1249
  No violations found
checking component: LT1509
  No violations found

**Comment by diggit** [comment]
Yeah, yeah, my fault. I had dcm file in different directory. I've realized my mistake after posting comment, so I immediately deleted it.

**Comment by ricardocrudo** [comment]
Hello @raiden00pl besides not a rule, new sch part uses fill background and 0.010" lines. Can you change it please? Also check the pin type for power pins of LT1509.

**Comment by raiden00pl** [comment]
Done

**Comment by hackscribble** [comment]
Hi @raiden00pl 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
