### PR TITLE
Add 4 pin crystal symbol

### PR DESCRIPTION
**Pull request by yaqwsx**
There are footprints for 4 pin SMD crystals, however there was no corresponding schematic symbol (with the adequate pins)

### CODE REVIEW

**Comment by reportingsjr** [comment]
Hi, it looks like your symbols aren't quite matching up with the library convention (see the Kicad Library Convention text file in this repo).

The automatic check shows the following:
checking component: Crystal_Four_pin
  Violating Rule 3.1
  Violating Rule 3.2
  Violating Rule 3.6
  Violating Rule 3.8

If you update this pull request with fixes the automatic checks will run again, just an FYI.

**Comment by yaqwsx** [comment]
Thank you for the notification. I have fixed 3.1, 3.2 and 3.6. I was suprised by the rules violation since I modified an already existing symbol (and all the violation comes from the original symbol). I also changed the original components Crystal and Crystal_Small to be consistent.

**Comment by yaqwsx** [comment]
How should I mark component as a generic one in order to satisfy rule 3.8?

**Comment by yaqwsx** [comment]
I think this PR is useless, if KiCad/Crystals.pretty#10 will be merged. So it can be closed unmerged.

**Comment by SchrodingersGat** [comment]
@yaqwsx yep looks like the other PR supersedes this one. Feel free to close it!

**Comment by yaqwsx** [comment]
Hope KiCad/Crystals.pretty#10 will be merged soon!

**Pull request closed without merging**
