### PR TITLE
Added ADA4807-1

### PR DESCRIPTION
**Pull request by ValeronDeportivo**
http://www.analog.com/en/products/amplifiers/operational-amplifiers/rail-to-rail-amplifiers/ada4807-1.html

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi! First of all: Thanks for your contribution.

We have a set of rules for new symbols here, called the KLC and the scripts (Travis) check against some of these rules. You can find the rules at https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention and some FAQs on them at https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions.

This part should go into the `linear` library with all the other opamps. However, there are major improvements being done to that library so it will take just a bit to get this PR merged.

A few quick comments:
- Datasheet link is wrong; should be http://www.analog.com/media/en/technical-documentation/data-sheets/ADA4807-1_4807-2_4807-4.pdf
- This part comes in two packages, but you've specified only the SC-70 one.
- Align the description with other parts in PR #1081

**Comment by jkriege2** [comment]
Hi!

uuups, I think you accidentally deleted your part with the last commit (merge) ...

cu
JAN

**Comment by ValeronDeportivo** [comment]
Hi,
And sorry for the lack of response to the last mail.

I am somewhat new to git, but I have my backups and will sort it out - and fix everything as it should have been in the first place (right library etc.)

Just busy at the other parts of my project...
I will get to it soon.

Thanks for the close attention and for managing the repository, I will try to help whenever I can.

Best,
Assaf

**Comment by ValeronDeportivo** [comment]
Hi Jan,
I believe all is in place and as it should be now?
Please let me know if there is anything else out-of-line and I'll fix it.

Best,
Assaf

**Comment by jkriege2** [comment]
Hi!

nice work mostly! Only two minor things to change:
1. The FPFilters should also have the `-` replaced by `?`or `*`, i.e. `SC?70*` and `SOT?23*`
2. Please mpty the footprint field. It should only be filled when there is a single footprint/package. If there are several, they are simply listed in the FPFilters and the user can select the package he uses.

Best,
JAN

**Comment by ValeronDeportivo** [comment]
I think its all good now, thanks for the patience and 1st-time guidance.

**Comment by jkriege2** [comment]
Thanks for the work!
JAN

**Pull request merged**
