### PR TITLE
Add MEC 5G series of tactile pushbutton switches

### PR DESCRIPTION
**Pull request by MatthewStephenson**
These are nice (but expensive) PCB-mount tactile switches with optional LED illumination, single or bi-colour.

Datasheet: http://www.apem.com/int/index.php?controller=attachment&id_attachment=488

image

I wanted to use the generic symbols for switch and illuminated switch, but the pin numbering is different, so I opted to make manufacturer-specific symbols - especially as there wasn't a bi-colour illuminated switch symbol. So I've added 3 symbols: Non-illuminated, 1 LED, and 2 LEDs.

Non-illuminated:

image

One LED, based on the existing illuminated switch symbol:

image

Two LEDs (bi-colour):

image

SMD footprint PR: https://github.com/KiCad/Buttons_Switches_SMD.pretty/pull/27
THT footprint PR: https://github.com/KiCad/Buttons_Switches_THT.pretty/pull/26

As always, comments and suggestions welcome :)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@MatthewStephenson symbols look great. Please address the issues raised for the footprints and then we can merge :)

**Comment by MatthewStephenson** [comment]
@SchrodingersGat Symbol issues fixed now, I think. Let me know if anything else needs changing.

**Comment by SchrodingersGat** [comment]
Now that the footprints are merged you will also need to slightly adjust the name of the footprint association, so that the symbols map to the correct footprints

**Comment by MatthewStephenson** [comment]
Actually I think they're ok - the current footprint filter for all three symbols is "SW*MEC*5G*" which still matches both SMD and THT footprints after the name change.

**Comment by SchrodingersGat** [comment]
Ah yes my mistake. Thanks for your work :)

**Pull request merged**
