### PR TITLE
Added AUIR3315S to transistor Library

### PR DESCRIPTION
**Pull request by openelectron**

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by ricardocrudo** [comment]
Hello @openelectron. can you please improve the design of the symbol? usually output pins stay in the right edge of the box. Also, you can make it smaller.

**Comment by openelectron** [comment]
Incorporated changes as requested.

**Comment by diggit** [comment]
Needed changes:
- place origin into center of symbol
- add TO package info into description
- remove commas from keywords (keywords are space separated)
- clear Datasheet Field of symbol, it is filled in documentation
- simplify FP Field (name of library may change in future)
- place Reference field outside of symbol (you can use checklib.py from [kicad-library-utils](https://github.com/KiCad/kicad-library-utils/)) `your_path_to/checklib.py -vv --enable-extra -c AUIR3315S  --fix transistors.lib`

Sth like this... (not required exactly)

**Comment by openelectron** [comment]
updated as requested.

**Comment by diggit** [comment]
Please change FP field back to: *TO_SOT_Packages_SMD:TO-263-5Lead*
Remove FP filter: *D2-PAK*\*
At last, solve conflicts by merging upstream master to your branch.

Sorry that I was not sure about FP field format and late reply. Busy month.

**Comment by openelectron** [comment]
I think that should do it.

**Comment by openelectron** [comment]
Is there anything I can do to help get this merged?

**Comment by diggit** [comment]
Sorry for delay, end of semester... Symbol is great!
Nice work you did!

**Pull request merged**
