### PR TITLE
Cx56-12: added a 3d image

### PR DESCRIPTION
**Pull request by Fat-Zer**
The model is exported directly from freecad. I don't see any glitches in it, but IMO it should be heavier tested on various systems to be sure.

See #186

### CODE REVIEW

**Comment by ricardocrudo** [comment]
@Fat-Zer wow, looks very nice. I checked it here and the model is not matching with footprint. The offset I have here are: (0, 0, 0.039370) is it according yours?

**Comment by Fat-Zer** [comment]
yes, it's already matches information in the footprint:
https://github.com/KiCad/Displays_7-Segment.pretty/blob/master/Cx56-12.kicad_mod
```
(model Displays_7-Segment.3dshapes/Cx56-12.wrl
(at (xyz 0 0 0.03937))
(scale (xyz 0.393701 0.393701 0.393701))
(rotate (xyz 0 0 0))
)
```

**Comment by ricardocrudo** [comment]
@Fat-Zer I meant was, with this offset value (at (xyz 0 0 0.03937)) the display does not match. Should be something like (at (xyz 0.254000 0.300000 0.03937)) to match. can you check that?

**Comment by Fat-Zer** [comment]
Oh, I see... I made the model before adjusted the origin to first pin... the right offsets are:
 (xyz 0.250000 0.300000 0.03937)
could you fix it in the footprint too?

**Comment by easyw** [comment]
@ricardocrudo 
Hi, would be possible to add also the STEP model exported from FreeCAD file Cx56-12.fcstd?
https://github.com/easyw/kicad-3d-models-in-freecad/raw/master/misc/Cx56-12.step
the STEP model is useful to be used with kicad stepup script
This script is aimed to give kicad the ability to have an identical view of board and modules in kicad 3d-viewer and in FreeCAD or MCAD software
it can be found from http://www.kicad-pcb.org/display/KICAD/External+Tools, kicadstepup
https://sourceforge.net/projects/kicadstepup/
kicadstepup-3d-comparison

thank you
Maurice

**Comment by ricardocrudo** [comment]
@easyw I don't know too much about 3D in KiCad. I'm bumping your comment here: https://github.com/KiCad/kicad-library/issues/186

**Pull request merged**
