### PR TITLE
Add SG3030CM

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: https://support.epson.biz/td/api/doc_check.php?mode=dl&lang=en&Parts=SG-3030CM

imagen
imagen
imagen
imagen

Thanks!

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
You do not need to have the suffix `-4Pin_3.2x1.5mm` - please remove this

**Comment by antoniovazquezblanco** [comment]
Done

Thank you very much @SchrodingersGat

**Comment by antoniovazquezblanco** [comment]
By the way, from Travis I get:
```
+ SG-3030CM
Checking symbol 'SG-3030CM':
  Violating S3.1
    Origin is be centered on the middle of the symbol
    Symbol not centered on origin
     - Center calculated @ (100, 0)
```
Which I think is because one of the sides does not have pins but the body is centered.
Should I center the body or the whole component?

**Comment by SchrodingersGat** [comment]
looks good to me, thanks :)

**Comment by antoniovazquezblanco** [comment]
Thank you again!

**Pull request merged**
