### PR TITLE
added MCP16331

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
image

**Comment by poeschlr** [comment]
This component is available in two different (incompatible) packages.
Your version looks like it is the sot23-6 version.
Set the footprint filter and footprint field accordingly.
Add the human readable name of the package to the description.

For symbol naming: (datasheet page 42)
Use the manufacturer part number including the package code (sadly "/" can not be used): MCP16331x-x_CH

I would use input type for the vfb pin

**Comment by Misca1234** [comment]
This push have been replaced by this push
https://github.com/KiCad/kicad-library/pull/1661

This push can be closed and deleted

**Comment by poeschlr** [comment]
Similar with other pull requests. Thanks @ilya-epifanov for creating the symbol and thanks for @Misca1234 for fixing it in a separate pull request.
Closing this because the replacement PR has been merged.

**Pull request closed without merging**
