### PR TITLE
Housings_SON: add 3D models

### PR DESCRIPTION
**Pull request by hackscribble**
image

Note: The models were generated by adding new parameters to the existing QFN script by @easyw.  Some of the SON packages in reality have additional end pins / visible metal that would require the script to be redesigned.  My feeling was that the small improvement in realism did not warrant this effort.
  
## Related PRs
Footprints: https://github.com/KiCad/Housings_SON.pretty/pull/7
Copy of 3D models: https://github.com/KiCad/packages3D/pull/63
Script: https://github.com/easyw/kicad-3d-models-in-freecad/pull/69

## Datasheets
NXP_XSON-16.wrl	http://www.nxp.com/documents/outline_drawing/SOT1341-1.pdf
Texas_S-PDSO-N12.wrl	http://www.ti.com/lit/ml/mpds289a/mpds289a.pdf
Texas_S-PVSON-N10.wrl	http://www.ti.com/lit/ml/mpds117k/mpds117k.pdf
Texas_S-PVSON-N8.wrl	http://chip.tomsk.ru/chip/chipdoc.nsf/Package/C2A39EE36E516F85C62578B20022E0E7!OpenDocument
USON-10_2.5x1.0mm_Pitch0.5mm.wrl	http://www.ti.com/lit/ds/symlink/tpd4e02b04.pdf
USON-20_2x4mm_Pitch0.4mm.wrl	http://www.ti.com/lit/ds/symlink/txb0108.pdf
VSON-10-1EP_3x3mm_Pitch0.5mm_ThermalPad.wrl	http://chip.tomsk.ru/chip/chipdoc.nsf/Package/D8A64DD165C2AAD9472579400024FC41!OpenDocument
VSON-8_3.3x3.3mm_Pitch0.65mm_NexFET.wrl	http://www.ti.com/lit/ds/symlink/csd87334q3d.pdf
WSON-16_3.3x1.35_Pitch0.4mm.wrl	http://www.chip.tomsk.ru/chip/chipdoc.nsf/Package/C67E729A4D6C883A4725793E004C8739!OpenDocument
WSON6_1.5x1.5mm_Pitch0.5mm.wrl	http://www.ti.com/lit/ds/symlink/tps717.pdf
WSON8_4x4mm_Pitch0.8mm.wrl	http://www.ti.com/lit/ds/symlink/lm5107.pdf
X2SON-8_1.4x1mm_Pitch0.35mm.wrl	http://www.ti.com/lit/ds/symlink/pca9306.pdf

### CODE REVIEW

**Comment by poeschlr** [comment]
The exposed pad variants are missing their two pins on top and bottom. (example VSON-10-1EP_3x3mm_Pitch0.5mm_ThermalPad) Are these the visible end pins you mentioned above?
vson_10

Would it be a good idea to add the links you provided above to the description fields of the footprints?

**Comment by hackscribble** [comment]
Yes, those were the pins I meant.  

I think some of the footprints already have datasheet links, but I'll go through them all and raise a PR to add the missing ones.

**Comment by poeschlr** [comment]
In this case i will merge this. (We have documented why these "pins" are missing so i think if someone wants to sink some time into it they can add these pins and create a new pull request.)

**Comment by easyw** [comment]
@hackscribble @poeschlr 
why not adding simply to the parameters

>         npy = 2,  # number of pins along y axis (length)

vson-10-1ep_3x3mm_pitch0 5mm_thermalpad

PS sorry for delay in this conversation, but I was busy on FC STEP exporting new feature! 😸 
https://forum.freecadweb.org/viewtopic.php?f=10&t=22811

**Comment by easyw** [comment]
PPS it can be done also with rounded pads 😄 
vson-10-1ep_3x3mm_pitch0 5mm_thermalpad-rounded

```
 'VSON-10-1EP_3x3mm_Pitch0.5mm_ThermalPad': Params( # from http://chip.tomsk.ru/chip/chipdoc.nsf/Package/D8A64DD165C2AAD9472579400024FC41!OpenDocument
        c = 0.2,        # pin thickness, body center part height
#        K=0.2,          # Fillet radius for pin edges
        L = 0.45,        # pin top flat part length (including fillet radius)
        fp_s = True,     # True for circular pinmark, False for square pinmark (useful for diodes)
        fp_r = 0.6,     # first pin indicator radius
        fp_d = 0.1,     # first pin indicator distance from edge
        fp_z = 0.01,     # first pin indicator depth
        ef = 0.0, # 0.05,      # fillet of edges  Note: bigger bytes model with fillet
        cce = 0.01,      #0.45 chamfer of the epad 1st pin corner
        D = 3.0,       # body overall length
        E = 3.0,       # body overall width
        A1 = 0.02,  # body-board separation  maui to check
        A2 = 0.9,  # body height
        b = 0.24,  # pin width
        e = 0.5,  # pin (center-to-center) distance
        m = 0.0,  # margin between pins and body  
        ps = 'rounded',   # rounded pads
        npx = 5,  # number of pins along X axis (width)
        npy = 2,  # number of pins along y axis (length)
        epad = (2.4, 1.6), # e Pad #epad = None, # e Pad
        excluded_pins = None, #no pin excluded
        modelName = 'VSON-10-1EP_3x3mm_Pitch0.5mm_ThermalPad', #modelName
        rotation = -90, # rotation if required
        dest_dir_prefix = '../Housings_SON.3dshapes/'
        ),


```

**Comment by hackscribble** [comment]
Thanks @easyw I hadn't spotted that the pairs of end pins are (at least approximately) on the same pin spacing as the main pins.  There is one device (top row, third item in the image at the top of the PR) that won't work that way, unless there is a parameter to miss out pins?

And I'll look at adding the rounded pads to the devices that have them.

So another PR to come ...

**Comment by easyw** [comment]
> unless there is a parameter to miss out pins selectively on only one pair of sides?

@Shackmeister added a parameter to exclude selectively pins

>         excluded_pins = None, #no pin excluded

>         excluded_pins = (2,4,6),

**Comment by Shackmeister** [comment]
Exactly :)

**Pull request merged**
