### PR TITLE
add Grove_1x04 3d package, based on PDF https://statics3.seeedstudio.…

### PR DESCRIPTION
**Pull request by penoud**
reopen previous PR  #517

### CODE REVIEW

**Comment by jkriege2** [comment]
please change the directory to Connectors.3dshapes ... as noted already elsewhere ;-)

With which software did you build thisß If you used freeCAD, cold you also provide the raw file?

Best,
JAN

**Comment by jkriege2** [comment]
aaahhh ... just saw you used OpenScad ... could you also add the script you used to this PR?

Best,
JAN

**Comment by penoud** [comment]
Ok, updated.

**Comment by jkriege2** [comment]
Thanks!

**Comment by SchrodingersGat** [comment]
@jkriege2 I think that in the future we should be linking to generator scripts in the README.md file, rather than including the scripts themselves - the lib should really only be for the .kicad_mod scripts.

The *Generator_Scripts* repo (not yet created) is where these scripts should go.

**Pull request merged**
