### PR TITLE
Device

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added description fields to the inductors, and fixed some text sizes

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello Oliver, can you please update your branch to fix the conflicts?

**Comment by SchrodingersGat** [comment]
Hi @ricardocrudo maybe I'm missing something simple but how do I see what the specific conflicts are?

**Comment by ricardocrudo** [comment]
@SchrodingersGat That's happening because someone has change the same lines in master as you did here in your PR. Merge the master to your PR and check the conflicts. You can use some merge tool (e.g.: meld) to help you with this task.

**Comment by SchrodingersGat** [comment]
@ricardocrudo I have merged the kicad/master branch in - still says "All checks have failed". Anything else I can do on my end?

**Comment by SchrodingersGat** [comment]
@ricardocrudo I've fixed the conflicts in this branch now.

**Comment by SchrodingersGat** [comment]
Failing checks due to KLC errors in https://github.com/KiCad/kicad-library/pull/370

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
Cool, the erroneous rule 3.8 errors should be gone!

**Comment by SchrodingersGat** [comment]
@ricardocrudo fixed all the merge issues. any suggestions here?

**Pull request merged**
