### PR TITLE
Add BeagleBone Black cape template

### PR DESCRIPTION
**Pull request by jzrebiec**

### CODE REVIEW

**Comment by michal777** [comment]
Looks good. If you want the 3d models to be safe (independent of unpredictable changes in libraries) you can copy them to template folder and use KIPRJMOD - examples are arduino templates:
(model ${KIPRJMOD}/Socket_Arduino_Nano.3dshapes/Socket_header_Arduino_1x15.wrl

**Comment by jzrebiec** [comment]
Hi, I added 3d models into template folder

**Comment by Caerbannog** [comment]
You probably shouldn't include `BeagleBone-Black-Cape-cache.bck`, it's a backup file.

**Comment by jzrebiec** [comment]
Sorry, my bad.

**Comment by ricardocrudo** [comment]
Thank you @jzrebiec

**Pull request merged**
