### PR TITLE
From Freecad Library with permission from Obijuan

### PR DESCRIPTION
**Pull request by Shackmeister**
https://github.com/FreeCAD/FreeCAD-library
rightangle switch

### CODE REVIEW

**Comment by poeschlr** [comment]
This part is under cc-by licence. (according to the readme of the linked repo.)
Does anybody know if this might be a problem? (reminder: this repo is under GPL.)

**Comment by Shackmeister** [comment]
I talked directly to the author @(Obijuan) and he agrees to relicense all his models under the modified GPL used for all the other 3d models..
Also he will try to talk to the rest of the freecad library teams about relicensing the rest for compatibility between Kicad and Freecad

**Comment by Obijuan** [comment]
I totally agree with the relicensing of the 3D models, so that they are compatible with the Kicad Library License (GPL + exception)

Thanks a lot for your work! It is amazing!! :-)

**Comment by poeschlr** [comment]
Very good work. Thanks at @Obijuan for creating this amazing model and another big thanks at @Shackmeister for organizing everything necessary to have them in our lib.

@Shackmeister please also add these models into the [packages3D repo](https://github.com/KiCad/packages3D)
@Obijuan or @Shackmeister if possible can the freecad source file also be added to the [packages3D-source repo](https://github.com/kicad/packages3d-source)?

**Comment by Shackmeister** [comment]
@poeschlr probably should have referenced them, but already added it :)
https://github.com/KiCad/packages3D/pull/53
https://github.com/KiCad/packages3D-source/pull/10

**Pull request merged**
