### PR TITLE
AVR-ISP-6: Replace symbol

### PR DESCRIPTION
**Pull request by matthijskooijman**
This PR changes the AVR-ISP-6 connector from:
selection_004
to:
selection_006

This should more closely follow the KLC, supplemented by the discussion
at #1627. I've just done AVR-ISP-6 now, if this is accepted, I'll also
do AVR-ISP-10 and AVR-JTAG-10.

As suggested in #1627, I've used a logical layout (as opposed to mimicing the
physical 2x3 pin layout). An extra advantage is that the layout of the
AVR-ISP-10 connector will be identical (it only adds more GND and NC pins), so
the symbols are interchangeable.

I can imagine (as I suggested in #1627 as well) that it can be useful to have
an alternative version of the symbol that does follow physical layout,
especially for the AVR-ISP-10 symbol, which has multiple GND pins and one NC
pin that you might want to wire differently. You can always use a generic 2x3
connector symbol for that, of course, but that does not have the pins labeled
with their names (but I guess it's enough of a corner case to just accept this
minor downside).

The new part does not completely pass checklib.py, remarks below.

        $ checklib.py -p AVR-ISP-6 -v -v atmel.lib
        Checking symbol 'AVR-ISP-6':
          Violating Rule 4.10 - Part metadata
            Part meta-data is filled in as appropriate
            Component AVR-ISP-6 has metadata errors:
             - Missing DOCUMENTATION FILE NAME field on 'Properties > Description' tab
          Violating Rule 4.12 - Footprint filters
            Footprint filters should match all appropriate footprints
            Minuses and underscores in footprint filter 'IDC-Header*2x03*' should be escaped with '?' or '*'.
            Minuses and underscores in footprint filter 'Pin_Header*2x03*' should be escaped with '?' or '*'.
          Violating Rule 4.6 - Pin types
            Pin electrical type should match pin function
            Power pins should be of type POWER INPUT or POWER OUTPUT
             - Pin VCC (2) @ (-100,500) is of type PASSIVE
             - Pin GND (6) @ (-100,-400) is of type PASSIVE

    - Missing DOCUMENTATION FILE NAME field on 'Properties > Description' tab

I could not find any official documentation on this particular pinout from
Atmel (only some images as part of documentation on specific programmers), so I
left this blank. KLC says "Documentation field contains URL to part
documentation if applicable, or is left blank", so this error seems too strict?

    Minuses and underscores in footprint filter 'IDC-Header*2x03*' should be escaped with '?' or '*'.
    Minuses and underscores in footprint filter 'Pin_Header*2x03*' should be escaped with '?' or '*'.

I'm not sure what is meant here. The KLC does not mention this rule at
all, and the examples aren't clear either.. I can imagine that all `_`
that separate different parts of the name be replaced with `*` so you
could potentially insert more qualifiers later and still match (but that
does not explain why you would wait to replace them with `?`). Also,
replacing a the `-` or `_` with `*` or `?` in these cases seems silly,
since they are just contained in a single part of the name (e.g. "IDC"
and "Header" aren't really separate parts AFAICS).

    Power pins should be of type POWER INPUT or POWER OUTPUT
     - Pin VCC (2) @ (-100,500) is of type PASSIVE
     - Pin GND (6) @ (-100,-400) is of type PASSIVE

This part contains pins named VCC and GND, but this is just a connector, so
they can be either INPUT or OUTPUT, depending on how the connector is used. I
think this warrants an exception to this rule?

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

about the FPFilters, simply use `IDC?Header*2x03*` and `Pin?Header*2x03*` ... this way the FPFilter is still valid, even if someone should rename `'Pin_Header` to `'Pin-Header`.

ABout the symbol itself, could you add small squares that we commonly use for other connectors, e.g. 
2017-10-17 20_53_03-library browser d__kicad_kicad-library_library_connector lib
2017-10-17 20_52_43-library browser d__kicad_kicad-library_library_connector lib

**Comment by matthijskooijman** [comment]
> about the FPFilters, simply use IDC?Header*2x03* and Pin?Header*2x03* ... this way the FPFilter is still valid, even if someone should rename 'Pin_Header to 'Pin-Header.

Ah, so that's the idea. Sounds like there would be better ways to solve this (e.g. let KiCad match _ as - and vice versa), but if this is the current policy, I've updated the symbol to match.

> ABout the symbol itself, could you add small squares that we commonly use for other connectors, e.g

Oh, I was planning to, but apparently forgot. I now added them, using 10x30mil boxes (seems there is some variation, the generic connectors use 10x50mil, the USB3 connector you linked uses 20x40mil, the USB1/2 connectors use 10x30mil). I used 30mil long boxes, since 40 mil comes uncomfortably close to the text.

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Comment by matthijskooijman** [comment]
Thanks for merging! I'll try to do AVR-ISP-10 and and AVR-JTAG in the same style soon.

**Comment by jkriege2** [comment]
Great!

JAN

**Comment by matthijskooijman** [comment]
@jkriege2, I just submitted #1810 for the other AVR connectors.

**Pull request merged**
