### PR TITLE
Rename How_To_Contribute to CONTRIBUTING

### PR DESCRIPTION
**Pull request by samdolt**
Github automatically show a link to the CONTRIBUTING file in issues and pull-requests.

picture
See https://github.com/blog/1184-contributing-guidelines

### CODE REVIEW

**Comment by samdolt** [comment]
Github also recognize CONTRIBUTING.txt, maybe better?

**Comment by CarlPoirier** [comment]
Nice find, I didn't know that. CONTRIBUTING.txt will be better since the kicad-library repo might be viewed by Windows users.

**Comment by samdolt** [comment]
Ready to merge ;)

**Comment by CarlPoirier** [comment]
Thanks!

**Pull request merged**
