### PR TITLE
added Arduino UNO R2/R3 + Leonardo symbols

### PR DESCRIPTION
**Pull request by jkriege2**
see https://github.com/KiCad/Modules.pretty/pull/2 for footprints

2017-02-19 21_16_08-part library editor d__kicad_kicad-library_library_modules lib
2017-02-19 21_16_48-part library editor d__kicad_kicad-library_library_modules lib
2017-02-19 21_17_09-part library editor d__kicad_kicad-library_library_modules lib

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Conflicts! :)

**Comment by jkriege2** [comment]
solved ...

**Comment by SchrodingersGat** [comment]
Sorry, please solve again!!

It will be so good when the libraries are one-component-per-file!

**Comment by jkriege2** [comment]
fixed!

**Comment by jkriege2** [comment]
@SchrodingersGat Could you have a look at this? Travis reports missing Docu, but it's (obviously) there ...

best,
JAN

**Comment by SchrodingersGat** [comment]
That's odd - testing this offline with up-to-date KLC scripts reveals no errors for these symbols.

Is this the same for you? I can't see why there would be a difference.

**Comment by jkriege2** [comment]
Hi!

locally all symbols check out OK now with a current master of the utils and the only option `-vv`

Best,
JAN

**Comment by jkriege2** [comment]
PS: I fixed some violations of text-sizes (was 60mil) and a pintyp (AREF was POWERINPUT) on two other devices!

**Comment by jkriege2** [comment]
@SchrodingersGat can this be merged?
JAN

**Comment by SchrodingersGat** [comment]
Yep, thanks for the additions

**Pull request merged**
