### PR TITLE
Adding Si photodiodes

### PR DESCRIPTION
**Pull request by yhlien**
Adding:
FDGA05
FDS010
FDS025
FDS100
FGA01
S5971
S5972
S5973

### CODE REVIEW

**Comment by poeschlr** [comment]
Your pins are not aligned to a 100mil grid.
Also the pin lengths should be at least 100mil.
See the (new) KLC: https://github.com/SchrodingersGat/kicad-library/wiki/KLC Rule 3.1

Screenshot of the currently supplied symbols for reference.
screenshot from 2017-02-25 19-01-59

**Comment by yhlien** [comment]
The screen dump of one revised symbol:

image

Please let me know whether it is working for you.

**Comment by poeschlr** [comment]
The pin placement and pin lengths look ok now.
But as you might have noticed there is still a problem remaining.
The automated build system tells you us that the manufacturer field has a text size of 60mil instead of the 50mil specified in the KLC.
(Yes this is pedantic but it looks like the testscript stops at the first error it finds. This means such a minor error could mask a bigger problem.)

**Comment by yhlien** [comment]
No worries at all.

I tried to use checklib.py to check the library before syncing it. Hopefully it can pass the system this time.

**Comment by yhlien** [comment]
I am bit confused now. Did it fail again? But I could not see the errors?

**Comment by poeschlr** [comment]
I can not see an error either. There seems to be a bug in the travis test system.

**Comment by jkriege2** [comment]
About pin-lengths and grids: Although the KLC do not state that (yet) we do not enforce these rules for small symbols such as diodes, resistors, ... and even transistors. As you might notice most symbols from `device.lib` violate that rule. If we would enforce it, we would get way too large symbols.

So please revert back to the original pin-length and placement (in sync with the generic symbols from `device.lib`).

Best,
JAN

PS: As any component to this lib is also checked by a librarian, we will ignore the Travis/check-lib warnings in those cases ... also it's not really possible to mark a symbol, so one or the other set of rules is applied ... so ...

**Comment by jkriege2** [comment]
Hi!

So have you heard from Thorlabs on the TO-46 packages?

One more thing: Please remove the Manufacturer fields ... we don't accept additional fields according to KLC!

Best,
JAN

**Comment by yhlien** [comment]
Hi Jan,

I have not heard back from Thorlabs yet.

I will remove the manufacturer field.

Best regards,

Yu-Hung

**Comment by jkriege2** [comment]
Hi!

we have our new Travis check scripts online now ... please have a look at the output
2017-03-11 15_19_49-update ftdi lib by mcvanili pull request 1097 kicad_kicad-library

For these diodes you can ignore KLC 4.1 as we do not consider it for small components like resistors, diodes, ...
But please correct KLC 4.9 violations, i.e. set the datasheet field invisible:
2017-04-07 14_40_55-part library editor d__kicad_kicad-library-review_library_atmel lib

Also I noted that you use these footprints:
- `TO-18-3_Window_20`
- `TO-18-3_Lens_15`
- `TO-18-3_Window_30`

Will you add these footprints? And if so what does the extension `_NUMBER` stand for?

Best,
JAN

**Comment by jkriege2** [comment]
Please fix coonflict above by merging in the trunk!

THanks,
JAN

PS: Waht's the status of this PR?

**Comment by jkriege2** [comment]
I had a quick look at the errors from Travis:
1. The errors for 50mil-grid can be ignore for THESE symbols
2. Please hide the datasheet-fields as shown above in the screenshots!

Have you heard from Thorlabs concerning the 3D models?

Best,
JAN

**Comment by jkriege2** [comment]
What's the status of this (news on 3D models)?
I had a short look (again) and found a few minor things:
- please revert the changes to modules.dcm from this PR
- please ensure that the FPFilters match the footprint names!

Best,
JAN

**Comment by yhlien** [comment]
Well, Thorlabs did not reply so I guess I will need to make my own copy to replace those 3D models.

**Comment by yhlien** [comment]
By the way, do you guys agree on the naming of 3D packages for Hamamatsu photodiodes?

**Comment by SchrodingersGat** [comment]
As we are now close to moving all the symbols to the new kicad-symbols repository, this PR will have to be reissued at https://github.com/kicad/kicad-symbols

Thanks for your contributions, and sorry for the inconvenience

**Pull request closed without merging**
