### PR TITLE
4538

### PR DESCRIPTION
**Pull request by feichtinger**
Changed 4538 according to KLC
bildschirmfoto vom 2017-09-04 19-51-56

### CODE REVIEW

**Comment by Misca1234** [comment]
Just recently I started to use this gem
https://github.com/KiCad/kicad-library-utils
Fork it and clone it, then you can both test schematic and foot prints before a push, like this

To test a specific footprint, change to directory pcb in kicad-library-utils and enter the following
(in the following example I test the footprint WSON-12-1EP_3x2mm_Pitch0.5mm_ThermalPad.kicad_mod in directory Housings_SON.pretty)
 python ./check_kicad_mod.py {Your path to your kicad clone of KiCad/pretty}/pretty/Housings_SON.pretty/WSON-12-1EP_3x2mm_Pitch0.5mm_ThermalPad.kicad_mod -vv

To test a specific symbol, change to schlib in kicad-library-utils and enter the following
(in the following example I test the symbol LMC7660 in library dc-dc.lib)
python ./checklib.py  {Your path to your kicad clone of KiCad/kicad-library}/library/dc-dc.lib -vv -c LMC7660

The -vv give you maximal information

**Comment by feichtinger** [comment]
> Just recently I started to use this gem
https://github.com/KiCad/kicad-library-utils

Thanks. I already know the library utils and always use them. They are very useful most of the time but sometimes they are quite niggling or simply not coherent with the KLC.

Here are the results for this part:
`./checklib.py ../../kicad-library/library/cmos4000.lib -c 4538 -vv
Checking symbol '4538':
  Violating Rule 4.10 - Part metadata
    Part meta-data is filled in as appropriate
    Component 4538 has metadata errors:
     - Missing DATASHEET field
    ALIAS 4528 has metadata errors:
     - Missing DATASHEET field
    ALIAS 14538 has metadata errors:
     - Missing DATASHEET field
  Violating Rule 4.12 - Footprint filters
    Footprint filters should match all appropriate footprints
    No footprint filters defined
`

The hint regarding KLC 4.10 (missing datasheet) is simply wrong because the KLC 4.10 does not mention the DATASHEET field, only the DOCUMENTATION field. The DATASHEET field should be left blank according to KLC 4.9.

The hint regarding KLC 4.12 is true, but useless because these chips are available in almost every package with the right pin number, so a footprint filter is pretty senseless.

**Comment by feichtinger** [comment]
> Just recently I started to use this gem
https://github.com/KiCad/kicad-library-utils

Thanks. I already know the library utils and always use them. They are very useful most of the time but sometimes they are quite niggling or simply not coherent with the KLC.

Here are the results for this part:
`./checklib.py ../../kicad-library/library/cmos4000.lib -c 4538 -vv
Checking symbol '4538':
  Violating Rule 4.10 - Part metadata
    Part meta-data is filled in as appropriate
    Component 4538 has metadata errors:
     - Missing DATASHEET field
    ALIAS 4528 has metadata errors:
     - Missing DATASHEET field
    ALIAS 14538 has metadata errors:
     - Missing DATASHEET field
  Violating Rule 4.12 - Footprint filters
    Footprint filters should match all appropriate footprints
    No footprint filters defined
`

The hint regarding KLC 4.10 (missing datasheet) is simply wrong because the KLC 4.10 does not mention the DATASHEET field, only the DOCUMENTATION field. The DATASHEET field should be left blank according to KLC 4.9.

The hint regarding KLC 4.12 is true, but useless because these chips are available in almost every package with the right pin number, so a footprint filter is pretty senseless.

**Comment by evanshultz** [comment]
KLC 4.10.v uses the term *Documentation* because that matches the UI, but the sole purpose of that field for parts in the official KiCad libraries (with some allowance for older parts that haven't been updated) is for the datasheet URL. It does look weird in combination with 4.9.iv and I'll chase down this discrepancy. Thanks for pointing this out.

The info regarding 4.12 is not useless, because there are often footprint variations which the user may choose to select. For example, extra large pads by the `_Handsoldering` suffix or a version with vias using the `_ThermalVias` suffix. We cannot forsee the future and so supporting matching footprints that aren't the default allow the footprint library to change/grow without changing the symbol. The user can choose any of these alternate footprints by using the FPfilter.

**Comment by feichtinger** [comment]
> The info regarding 4.12 is not useless, because there are often footprint variations which the user may choose to select.

Of course a footprint filter is useful in some/most cases. But a filter can only REDUCE the number of footprints that fit to this symbol. The CMOS 4528/4538/14528/14538 chips are available in DIP, SOIC, SOP, TSSOP and probably some others somewhere. So what would be an appropriate footprint filter in this case?

**Comment by feichtinger** [comment]
OK, I didn't realize that the metadata fields are different for every alias. Fixed that in the latest commit.

**Comment by evanshultz** [comment]
@feichtinger 
Your comment about DESCRIPTION versus DATASHEET fields in KLC is not valid. 4.8 and 4.9 are referring to fields in the first section of the symbol in the LIB file. These are named F1 through F4 and map to the respective fields. It's not super clear when looking at the text files, but they do have a defined purpose. 4.10 is talking about the metadata in the DCM file which has fields labelled with D, K, and F. Again, not super descriptive but their purpose is clearly started in the screenshot above.

KLC clearly covers this case where the part is available in different packages. You seem to be referring to MC14538B, so let's figure out the FPfilters for it. There are 4 packages, 3 of which are in the library already. Looking at the datasheet and the footprint libraries, you can come up with:
$FPLIST
 SOIC*3.9x9.9mm*Pitch1.27mm*
 SOIC*7.5x10.3mm*Pitch1.27mm*
 SOEIAJ*5.275x10.2mm*Pitch1.27mm*
 TSSOP*4.4x5mm*Pitch0.65mm*
$ENDFPLIST

The third footprint is currently missing, and I'd encourage you to add that footprint, if you can, to make the library complete. Please always note if you have or will create a missing footprint in the PR body.

Alternatively, if a footprint is missing you may leave it out of the FPfilter and also note that in the PR so it can be considered during review.

In this case, because there are 4 available packages there will be no default footprint.

Some other comments:
- There are many changes to the library files not associated with 4538. Did you change anything else? Sometimes KiCad will re-arrange the files which can cause this.
- There is no subject for the description (all the words are referring to a subject which is missing), and all major words should be capital.
- Add the available packages to the end of the description.
- The above two items will result in `Dual Monostable Multivibrator, SOIC-16` for MC14528B and `Dual Precision Retriggerable/Resettable Monostable Multivibrator, SOIC-16/SOIC-16W/SOEIAJ-16/TSSOP-16` for MC14538B.
- The keywords should certainly include the word `multivibrator`.

**Comment by feichtinger** [comment]
First of all I have to say, that for me as a KiCad user, I don't really care about the details of the file format of the library files. Like probably most of the KiCad users, I use the KiCad Library Editors for symbols and text files, and not a text editor.
So what I see is a dialog "Field Properties" which mentions a "datasheet" field, which I left empty (I assume KLC 4.8, 4.9 refers to this.)
Also there is a dialog "Properties for <symbol>" with a text field called "Documentation File Name" where i put in the URL to the datasheet. (This is most likely what KLC 4.10 is talking about.)
So far so good. Nothing wrong with the KLC. What I was criticizing was not the KLC but the library utils. It claims that I was violating KLC 4.10 because there was no DATASHEET field. But in KLC 4.10 THERE IS NO DATASHEET FIELD!

OK, my second comment about the footprint filter was due to the large variety the 4538 and aliases chips, which are part of the CMOS 4000 logic family. (This symbol is NOT only for the MC14538B, the linked datasheet is only one possible example.) Probably every semiconductor company that has ever existed has/had at least one variant of the 4538 in its product range, each with many possible footprints. (Lets ask google about it: [https://www.google.com/search?client=ubuntu&channel=fs&q=CMOS+4538+datasheet&ie=utf-8&oe=utf-8](https://www.google.com/search?client=ubuntu&channel=fs&q=CMOS+4538+datasheet&ie=utf-8&oe=utf-8))
So what is the point in creating a footprint filter that includes literally ALL possible footprints? Do you expect me to find every single variant of the 4538 and their possible footprints?

OK, now to the other comments:

> There are many changes to the library files not associated with 4538. Did you change anything else? Sometimes KiCad will re-arrange the files which can cause this.
Yes, KiCad did it, that was my first commit in this PR.

> There is no subject for the description (all the words are referring to a subject which is missing),
Well the subject is "monostable". (Also some datasheets write it this way.) I will change it to "monostable multivibrator" to make it clear.

> and all major words should be capital.
OK.

> Add the available packages to the end of the description.
See my comment about footprint filters.

> The keywords should certainly include the word multivibrator.
OK, I will change it.

**Comment by evanshultz** [comment]
Some users do use a text editor. While I can see you use to UI, I had no way to know if you also looked at the text file before.

Your first commit had no DCM file. This caused the issue. Now you know that "Documentation File Name" in the UI is for the datasheet. KLC has already gotten a few clarification updates and we'll look at doing more. I do understand what you're saying.

If you can find all 4538 packages, that would be great. If you only cover the ones in the example datasheet, that will do a lot. This is a community effort so someone can come along later and add additional footprints if they find some that were missed. The entire footprint library contains footprints for capacitors, connectors, discrete transistors, and many others which are obviously unsuitable for this particular IC. The FPfilter will catch only the footprint that match available packages for each part. This is core to the design of KiCad and is used on every symbol in the library (there may be some outliers).

"monostable" is an adjective. It is describing the part. "multivibrator" is the subject and type of part. Multivibrators could be unstable, bistable, etc. Without "multivibrator", the description is incomplete.

If you have other questions when making updates please post them.

I encourage you to ask questions. This is your first contribution and so it's understandable there will be new things to learn. KLC and the existing libraries aren't perfect, but I and the other librarians are taking our personal time to assist you in getting your part into the library. I really want to see this merged and I hope to see many more contributions from you in the future. There is no need for all caps or your attitude. Ask questions when something seems odd to you and this will be more pleasant.

**Comment by jkriege2** [comment]
Hi!

please also have a look at this PR by @bobc : https://github.com/KiCad/kicad-library/pull/1601

It might even already contain what you're proposing ...

Best,
JAN

**Comment by feichtinger** [comment]
You are right, of course. He did a rework of the whole library! We should stop this nit-picking and go ahead with @bobc 's work.

**Pull request closed without merging**
