### PR TITLE
adding new component on texas lib

### PR DESCRIPTION
**Pull request by jeromebeguin**
- LM5175
- TUSB8041
-TPS2560
-TPS2561

### CODE REVIEW

**Comment by jeromebeguin** [comment]
This time it should be ok.

**Comment by jkriege2** [comment]
- LM5175: please set the text-size of the (empty) datasheet-field to 0.05" ... this causes KLC-errors
- Please fix these:
```
`checking component: TPS2560
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: TO_SOT_Packages_SMD:VSON-10-Th_11SC_3x3mm_Pitch0.5mm at posx -400 posy -600 size 60
    field: UNKNOWN at posx 0 posy 0 size 60
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    symbol name should not be included in description
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin GND (1): I (INPUT), expected: W (POWER INPUT)

checking component: TPS2561
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: TO_SOT_Packages_SMD:VSON-10-Th_11SC_3x3mm_Pitch0.5mm at posx -400 posy -600 size 60
    field: UNKNOWN at posx 0 posy 0 size 60
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    symbol name should not be included in description
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin GND (1): I (INPUT), expected: W (POWER INPUT)
```
- TPS2560/TPS2561/CSD19537Q3: set FPFilter to `VSON*3x3mm*Pitch0.5mm*`
- please fix
```
checking component: TUSB8041
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing whole documentation (description, keywords, datasheet)
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin NC (60) is no-connect, should be set to invisible
```
- rest of CSD19537Q3: OK

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

- Please add an asterisc `*`at the end of EVERY FPFilter, so it can alaos match e.g. `_Handsoldering`-variants!
- TUSB8040: The FPFilter and footprint differe a bit:
2017-01-23 23_41_39-part library editor d__kicad_kicad-library-review_library_texas lib
- remove commas from keywords (e.g. TUSB8040, TPS2561, ...)
- TPS2560/2561/TPS563200/TPS62130: maybe move GND and ThermalPad (rename PAD???) pins to bottom-edge
- TPS563200: please fix FPFilter: 
2017-01-23 23_45_00-part library editor d__kicad_kicad-library-review_library_texas lib
- TPS62130 please fix FPFilter (remove `X`and add `*`at end)
2017-01-23 23_46_40-part library editor d__kicad_kicad-library-review_library_texas lib




best,
JAN

**Comment by jeromebeguin** [comment]
I'm not convinced about moving the GND and PAD to bottom edge. I personally prefer having all the pins on the sides edges. But if it's a convention I'll move them but I thought it should be at the bottom of the schematics not necessary on the bottom edge. Then we have to find another place for the  component name.

**Comment by jkriege2** [comment]
yes it is a convention (see KLC 3.5 in the new Version we're currently preparing: https://github.com/SchrodingersGat/kicad-library/wiki/KLC) ... at least I would Interpret it as bottom/top-edge ... at least that's how we do it everywhere else (in new symbols)!

Best,
JAN

**Comment by jeromebeguin** [comment]
Ok, I'll change that. So we should move also the VDD to top edge ? 
Where should we put name and ref of the component ?

**Comment by jeromebeguin** [comment]
I don't really understand the purpose of putting the GND pins on bottom edge. It's just makes the components bigger and the schematics less compact.

**Comment by jkriege2** [comment]
1. FPFilter for TPS562200 should be `SOT-23*`
2. please reduce pin-length of TPS562200 to 100mil and move text a bit closer to box

Best,
JAN

**Comment by jeromebeguin** [comment]
I'm testing the components with the checklib script. And I often have that issues. what does it mean ? 

  Violating Rule 3.8
    Description and keywords properties contains information about the component.
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment

there is a description and keyword, and don't know what to check with the footprint position and name.

**Comment by jkriege2** [comment]
Usually violation 3.8 means that you have the component name in the description (which you should not!)
EC03 is a proposal of how to position these fields. You can have a look at what the script proposes using the --fix option ... But usually I would decide on how you think it looks better and how the positioning is done with comparable symbols in the lib.

Best,
JAN

**Comment by jkriege2** [comment]
I spotted some more stuff:
1. TPS563200 is missing description+keywords+datasheet link
2. LM5175: move gND to bottom and VCC to the top
3. TPS563200 still has a wrong FPFilter! Should be `SOT-23*`
4. TUSB8041: Please also move the power pins here

Having Power at top/bottom helps (IMHO) to group pins a bit by function and make use of all available space. Also it clearly separates power-supply from other pins (wlthough completely separate power pins would be even better for that ,-) ... just my view on that

Best,
JAN

**Comment by jkriege2** [comment]
Please add description+keywords+datasheet for Alias TPS562200

Otherwise I'll merge when that is fixed ;-)

best,
JAN

**Comment by jkriege2** [comment]
nice work!
thanks,
JAN

**Pull request merged**
