### PR TITLE
[enh] add 3D shapes of EVQQ2 switch (3 variants)

### PR DESCRIPTION
**Pull request by pointhi**
The naming of the files is not exactly as mentioned in the KLC, because there are 3 variants which are using the same footprint, but have different button heights.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@ricardocrudo  @pointhi  these files have the \* character in the filename(s) which is a big no-no for Windows (not sure if it is allowed in *nix).

This merge has broken kicad-library/master for me, and any other windows users.

**Comment by SchrodingersGat** [comment]
"Broken" might be a bit harsh but Windows cannot handle these files

**Comment by nickoe** [comment]
Is it intentional that the filenames contains an asterisk?

This makes the make install fail, at least on windows on the msys2 environment. I have not tested this on linux.

```
00:00:03.557 -- Installing: C:/Jenkins/workspace/windows-kicad-msys2-nightlies/pkg/mingw-w64-x86_64-kicad-git/mingw64/share/kicad/modules/packages3d/Buttons_Switches_SMD.3dshapes
00:00:03.557 CMake Error at modules/cmake_install.cmake:73 (file):
00:00:03.558   file INSTALL cannot find
00:00:03.558   "C:/Jenkins/workspace/windows-kicad-msys2-nightlies/src/kicad-libs/modules/packages3d/Buttons_Switches_SMD.3dshapes/SW_SPST_EVQQ2?01W.wings".
00:00:03.558 Call Stack (most recent call first):
00:00:03.607   cmake_install.cmake:33 (include)
00:00:03.733 
00:00:05.626 
00:00:05.644 Makefile:61: recipe for target 'install' failed
00:00:06.702 make: *** [install] Error 1
00:00:07.154 ==> ERROR: A failure occurred in package().
00:00:07.244     Aborting...
```

Notice that the asterisk is shown as a question mark. I don't know if this is a cmake thing or not.

**Comment by ricardocrudo** [comment]
Fixed

**Comment by SchrodingersGat** [comment]
Thanks @ricardocrudo, merge works for me now :)

**Pull request merged**
