### PR TITLE
Changed AD5593R according comment in PR #499

### PR DESCRIPTION
**Pull request by penoud**

### CODE REVIEW

**Comment by diggit** [comment]
Symbol looks good, diff is nice :).
Your symbol is matching TSSOP package pinout only.
- remove incorrect FP filters, set remaining one to `TSSOP-*` to let kicad match only pkg type, pincount is matched by separate filter
- set FP field to `Housings_SSOP:TSSOP-16_4.4x5mm_Pitch0.65mm` , invisible
- add TSSOP-16 to description as this symbol is for single FP

**Comment by penoud** [comment]
Improve has recomended

**Comment by diggit** [comment]
1. > - add *TSSOP-16* to description as this symbol is for single FP

 ^^ to let people know this is FP specific symbol

2. Set FP filter to `TSSOP-*` without pin count.

**Comment by penoud** [comment]
Sorry, didn't read well your recommandations

**Comment by diggit** [comment]
NP, no rush :)
BTW you'll have to solve conflicts, by merging changes from upstream to you branch.

**Comment by diggit** [comment]
- Correct FP is `Housings_SSOP:TSSOP-16_4.4x5mm_Pitch0.65mm`, put it below symbol
- append `,TSSOP-16` to **description**
- revert 2dbb56a5daf1fae279cd601eca1d5eecf442d7b1, it is not part of this PR

**Pull request closed without merging**
