### PR TITLE
Improvements to regul.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR does the following:
a) Removes battery management related ICs from regul.lib (BQ2003, MAX164?, MCP7381??)
b) Adds some TI and Microchip LDOs
c) Change text fields from 40mil to 50mil as per KLC for all components

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
The battery related components have been moved here https://github.com/KiCad/kicad-library/pull/465

**Comment by CarlPoirier** [comment]
Hi Oliver,

Most changes have been incorporated via your other pull request #465. Can you fix the conflicts so that the remaining changes can be merged?

Thanks

**Comment by SchrodingersGat** [comment]
@CarlPoirier I've merged and tweaked and suchlike

**Comment by CarlPoirier** [comment]
Thanks for your contribution.

**Pull request merged**
