### PR TITLE
Create Hirose

### PR DESCRIPTION
**Pull request by savenlid**
Hirose connector FX10A-168P-SVx

can you add a Hirose lib for all hirose parts, TE lib for tyco electronic and one molex and one leno lib  ?

I am a professional designer that worked with cadence and mentor for many years.

pls fix the directory structure to include some brands today is a mess, sorry to say, few components are generic.

### CODE REVIEW

**Comment by pointhi** [comment]
Hy @savenlid,

I could create a Connectors_Hireose.pretty repository for you, but would suggest you first to check your part(s) again the [KLC](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt). You could use https://github.com/KiCad/kicad-library-utils to find most basic KLC errors.

Also look onto conn.lib and use the same pin numbering scheme for your footprint. Otherwise people wouldn't be able to use your footprints.

For Molex, there is already a library: https://github.com/KiCad/Connectors_Molex.pretty

I would suggest you to use your own Connectors_***.pretty Repositories first and try to fix all KLC issues. After that you contact me or another kicad librarian to create the required repositories so you are able to create the specific pull request for it and we are able to merge them.

also look into #368 to check out how the footprints should probably be named.

**Comment by savenlid** [comment]
Yes, I will do what you say, with KLC

I am a veteran footprint maker but not with Ki-cad, so bare with me a short
while, i will fix it.

but....  for the pinning I always follow the pinning numbers-scheme of the
datasheet if available otherwise it will get very confusing for everybody
if you read datasheet and relies on that just to find out when your pcb
dont work that footprint had a jome-made numbering not matching datasheet.


can we agree ?

thanks
/Nicholas


2016-02-11 23:24 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
For the pinnumbering, we should ask @CarlPoirier @ricardocrudo for an appropriate recommendation. 

You can leave this point open and we handle it later when there is a corresponding recommendation from the other kicad maintainers.

**Comment by savenlid** [comment]
ok


2016-02-11 23:48 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by SchrodingersGat** [comment]
I also have some Hirose connectors in the works - I'm slowly bring the DF13 series towards KLC compliance

https://github.com/SchrodingersGat/Connectors_Hirose.pretty

@pointhi let us know when there's a kicad/Connectors_Hirose.pretty repo to pull against.

Cheers

**Comment by El3ctr0nic** [comment]
Hi i pin in to the discussion. 
I need development_boards pretty repo to add nucleo pinout. Could
 U create it 4 me?

**Comment by El3ctr0nic** [comment]
When will be next merging wave? Request montain is growing up ;)

**Comment by pointhi** [comment]
Ok, I created the repository: https://github.com/KiCad/Connectors_Hirose.pretty

@El3ctr0nic 
For development_boards.pretty I will contact the other Maintainers first

for the merging wave: I have much of free time soon, and have planned to go over every issue and PR in the Kicad repositories to look for mergable stuff and to point out possible KLC problems.

But i'm only a junior maintainer so I'm only merging stuff where I have enough knowledge it should be fine. (In other words: no component changes unless there are easy to check, no big pull requests, no special cases,...). Furthermore, I pointed out some edge cases in normal PR where I'm not sure, so the other maintainers have to give their opinion about that. This is also a process which slows down merging a lot.

**Comment by El3ctr0nic** [comment]
Thx for fast replay ;) I have more components to add but i waiting if my KLC rules restict is ok ;] Regards

**Comment by savenlid** [comment]
Hi

Sorry for mixing footprint name with pinnumbering.

For a footprint residing in connectors_hirose (pointing out manufacturer)
I strongly suggest we use manufacturers part-no or if manufacturer as in
the case of maxim-ic and others have generic footprint names those could be
used as well.

Datasheets should dictate footprint names in dedicated manufacturers
directories more than kicad community convention.

Is there a connectors_tyco repo for tyco electronics already?

Many thanks
Nicholas
Den 12 feb 2016 5:10 AM skrev "El3ctr0nic" <notifications@github.com>:

**Comment by pointhi** [comment]
> Is there a connectors_tyco repo for tyco electronics already?

I'm unsure for the naming, because the company now is named [TE Connectivity](https://en.wikipedia.org/wiki/TE_Connectivity). So the repository would be named ```Connectors_TE-Connectivity.pretty``` or ```Connectors_TE.pretty``` or something similar.

**Comment by savenlid** [comment]
perfectly ok with me



2016-02-12 15:29 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
Ok, I created the repository: https://github.com/KiCad/Connectors_TE-Connectivity.pretty

**Comment by savenlid** [comment]
Could we create the Connectors_JAE  also ?

http://jae-connectors.com/jump_en.cfm


2016-02-12 19:30 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
ok, no problem: https://github.com/KiCad/Connectors_JAE.pretty

**Comment by pointhi** [comment]
Because, the main topic was fulfilled, I close this PR.

When you need new repostiories you could also write me or another maintainer via IRC.

**Pull request closed without merging**
