### PR TITLE
Added STMPE1600

### PR DESCRIPTION
**Pull request by Misca1234**
Component STMPE1600
http://www.st.com/resource/en/datasheet/stmpe1600.pdf

16 bits IO expander

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
This travis requirement on the text size is a little bit annoying, it differ from kicad's default setting and therefore it is necessary to manually edit the .lib file to change the F2 and F3 text field sizes.

**Comment by SchrodingersGat** [comment]
@Misca1234 you can change the default setting in KiCAD to make it easier for yourself.

**Comment by Misca1234** [comment]
In a way, it would be even easier for me if the travis script adapted to the kicad default or if kicad changed the default settings to match travis ^^

**Comment by Misca1234** [comment]
Nice, thx

**Pull request merged**
