### PR TITLE
Ltc4054 x 4.2

### PR DESCRIPTION
**Pull request by Misca1234**
THC4052ES5
alias LTC4054XES5

https://www.elfa.se/Web/Downloads/42/xf/405442xf.pdf

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

great wokr!
please change FPFilter to `SOT?23*` ... Then I can merge!

THanks,
JAN

**Comment by Misca1234** [comment]
Fixed footprint filter

**Comment by jkriege2** [comment]
Thanks,
nice work!

JAN

**Comment by aliteke79** [comment]
Hi @Misca1234, footprint of the LTC4054 looks like TSOT-23 in documents.

**Comment by jkriege2** [comment]
Hi!

I made a quick PR to fix this problem: #1559 

Best,
JAN

**Pull request merged**
