### PR TITLE
Changed AD5593R according PR#503

### PR DESCRIPTION
**Pull request by penoud**

### CODE REVIEW

**Comment by penoud** [comment]
Please close PR#503

**Comment by diggit** [comment]
Reverting that commit in #503 would be enough, but ok. At least commit history will be non breaking.
Please use `,` as separator on description instead of double space in front of TSSOP-16.
Rest looks good.

**Comment by diggit** [comment]
And `,` is followed by space (missing twice), every time. Sorry that i forgot to mention it.

**Comment by penoud** [comment]
Sorry I'm new I will improve.

**Comment by diggit** [comment]
Not bad for a starter ;)
Nice work you did, merging.

**Pull request merged**
