### PR TITLE
Added Various Cypress PSoC 4/5LP Components (Large Component Count Pull Request) 

### PR DESCRIPTION
**Pull request by ashtonchase**
Added PSoC 5 100-pin TQFP parts (CY8C52xx/CY8C54xx/CY8C56xx/CY8C58xx series)
Added PSoC 4100/4200M 64-QFN, 64-TQFP,  48-TQFP parts.
Added PSoC 4100/4200 44-TQFP parts. 

If if helps, the base parts with aliases are:
- [ ] CY8C4xx4AXI-4xx
- [ ] CY8C4xx7LQI-4xx
- [ ] CY8C4xxxAXI-M4xx
- [ ] CY8C4xxxAZI-M4x3
- [ ] CY8C4xxxAZI-M4x5
- [ ] CY8C4xxxLTI-M4xx
- [ ] CY8C5888AXQ-LP096

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Wow, nice effort. Are these scripted, or created manually?

I shall continue to check through them - two things that jump out at me:

* The width of the symbol rectangle should be set to 0.01" 
* Some documentation fields just say "DOCUMENTATION"
* Some default footprint fields don't have the Library-Name: prefix. e.g. for CY8C4xx4AXI-4xx, default footprint should be:

` "Housings_QFP:TQFP-44-1EP_10x10mm_Pitch0.8mm"`

**Comment by diggit** [comment]
Hi @ashtonchase, write some message about finished changes here. Otherwise we won't get notification.

Please fix these:
- documentation cleanup
 - some parts have excessive leading space(s)
 - do not multiple spaces `...ENSE,  IDAC,...` (2 here)
 - remove info like *NO UDB*, *NO CAP-SENSE*, *NO IDAC*, list only features that are present
- symbols
 - clear datasheet field, we use datasheets from documentation
 - use full name for FP field FP_library:FootPrint, if it exists...
 - set FP filters accordingly, example FP: `Housings_QFP:TQFP-44-1EP_10x10mm_Pitch0.8mm` -> FP filter: `TQFP-*-1EP_10x10mm_Pitch0.8mm*`

**Comment by ashtonchase** [comment]
I haven't forgotten this, just haven't had time to complete it. Thanks..

**Comment by ashtonchase** [comment]
@diggit @SchrodingersGat 
I have finally updated these.

**Comment by diggit** [comment]
Please set links in documentation to point to PDF datasheets.
Set NC pins invisible.

Symbols look generally ok, I'll have deeper look after you fix doc. links.

**Comment by ashtonchase** [comment]
@diggit ,
You comments have been incorporated. Datasheet PDF links were added to part specific aliases.

**Comment by diggit** [comment]
- We need datasheet link like this one: `http://www.cypress.com/file/230631/download`, because we want link to pdf download. (otherwise, I a not able to verify pin name/number/type assignment)

- In FP filters, match only package: type, dimensions and pitch.
  `Housings_QFP:TQFP-44_10x10mm_Pitch0.8mm` -> `TQFP*10x10mm*Pitch0.8mm*` and so...

- Unify description format. Some symbols have package at first place, some don't.

- Can you make some unnecessarily large symbols smaller? (CY8C4xx4AXI-4xx) FP field can be outside.

*(Yes, that base symbol list helps a lot!)*

**Comment by ashtonchase** [comment]
I would prefer to not incorporate the 4th item. 
I made them where they should be symbol swappable between the different symbols. I.E. CY8C4xxxAZI-M4x3 is swappable with CY8C4xxxAZI-M4x5, even thought they have different PCB footprints and different sub aliases.

**Comment by ashtonchase** [comment]
Hi @diggit . 

Any chance we could move this one forward?

**Comment by hackscribble** [comment]
Closing and re-opening to run Travis CI checks.

**Comment by SchrodingersGat** [comment]
Hi @ashtonchase looks like this one has gathered some dust. Any interest in continuing forward? If you fix the merge conflicts we can proceed :)

**Comment by SchrodingersGat** [comment]
@ashtonchase bump :) I am trying to whittle down the outstanding PRs so we can start transitioning to the v5 library release. Please indicate if you are able to address the outstanding issues :)

**Comment by SchrodingersGat** [comment]
@ashtonchase please resubmit this PR to the new symbols library at https://github.com/kicad/kicad-symbols

Thanks :)

**Pull request closed without merging**
