### PR TITLE
Added PIC32MX1XXFXXXD-I/PT microcontroller

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contrib ... one thing remains to be done:
- the aliases don't have the proper description (keywords, datasheet, ...). Note that unfortunately these are not inherited automatically.

Best,
JAN

**Comment by jkriege2** [comment]
PS: The FPFilter should be `TQFP*10x10mm*Pitch0.8mm*`

**Comment by crackerizer** [comment]
Hi Jan, the symbols are updated accordingly.

**Comment by jkriege2** [comment]
As I understand, the different aliases differ in memory ... could you put the correct memory sizes in the descriptions?

Thanks,
JAN

**Comment by crackerizer** [comment]
Done

**Comment by jkriege2** [comment]
Nice work!
Thanks,
JAN

**Pull request merged**
