### PR TITLE
updated Pin Header models to scripted parametric Models

### PR DESCRIPTION
**Pull request by Shackmeister**
pinheader_3d
pinheader_side
pinheaders_sideview

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@Shackmeister please wait until [this issue](https://github.com/KiCad/kicad-library/issues/1411) been discussed until this will be merged.

- This will NOT effect the same models being added to the packages3d repo :)

Thanks for the contribution!

**Comment by Shackmeister** [comment]
I have now added the pinheaders to packages3D
https://github.com/KiCad/packages3D/pull/84

**Comment by Shackmeister** [comment]
@SchrodingersGat since the old models are not compatible with the new footprints I would suggest to add these to this repo before the "freeze"

**Comment by SchrodingersGat** [comment]
@Shackmeister that makes sense - thanks for your continued contributions

**Comment by Shackmeister** [comment]
Please also add the ones in packages3D :)

**Comment by SchrodingersGat** [comment]
Way ahead of you :)

**Pull request merged**
