### PR TITLE
[enh] add S102S01 and similar solid state relais

### PR DESCRIPTION
**Pull request by pointhi**
I created symbols for solid state relais like [S102S01](http://www.sharp-world.com/products/device/lineup/data/pdf/datasheet/s102s01_e.pdf) and similar types.

I also created a footprint (which is equal for all added SSR, but I don't know how to name it because it is named as "SIP 4pin", but has special sizing and pin spaces.

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
Apologies for the spammy messages, needed to test the check bot.

**Comment by CarlPoirier** [comment]
Hi Thomas,

The only minor comment I have is if you could make the value field (U) position uniform between all of your relays they would be perfect.

**Comment by pointhi** [comment]
I fixed the footprint as mentioned, and also created a PR for the footprints

**Comment by ricardocrudo** [comment]
Hello @pointhi, could you please fix the typo: relais > relays
Also, generally, keywords field contains words that are present in the description.

**Comment by pointhi** [comment]
ok, fixed symbol as mentioned.

**Comment by ricardocrudo** [comment]
Thank you.

**Comment by CarlPoirier** [comment]
@tormodvolden Indeed, thanks for flagging it.

**Comment by CarlPoirier** [comment]
Upon further verification, the S102S01 is a series of relays so we'll leave it as plural.

**Pull request merged**
