### PR TITLE
Remove duplicate of the MC34063 regulator in the conn library.

### PR DESCRIPTION
**Pull request by hzeller**
The 'conn' library had an exact copy of the switching DC/DC converter which was out of place. It is already in the proper location in the 'regul' library.

This removes a component, so I guess this might be problematic if someone was using the conn:MC34063 symbol somewhere, but better a clean library than an annoying legacy. Are there ways in the library to 'hard redirect' eeschema to the canonical location ?

Suggested commit message:
  - Remove duplicate of the MC34063 regulator in the conn library
  - Add datasheet link to the MC34063 in regul library.

### CODE REVIEW

**Comment by keruseykaryu** [comment]
MC34063 is a switching regulator. His place is in `dc-dc.lib` library.

**Comment by hzeller** [comment]
Alright, in addition I can also move it from regul to dc-dc. Hold on ...

**Comment by hzeller** [comment]
Alright done. Moved from regul -> dc-dc

**Comment by keruseykaryu** [comment]
BTW: https://github.com/KiCad/kicad-library/pull/223

**Comment by hzeller** [comment]
That pull requests also adds keywords to this regulator, but leaves it in regul.
So since my change now moves it out of regul to dc-dc after the discussion, these changes conflict; so whatever change is first merged, the other would need a tiny rework.

(The #223 change though only adds superfluous keywords as these words are already in the description so are anyway found by the component chooser. So that change is a no-op).

**Comment by ricardocrudo** [comment]
@hzeller that pull request isn't finished yet. Soon, I'll move all switching regulators to dc-dc, as you can see in the conversation between me and Kerusey. I suggest that in this PR you leave only the remotion of the MC34063 of conn library.

If you want to improve the keywords of MC34063 or any other in regul/dc-dc libs I suggest you to pull request it over the regul-KLC branch.

**Comment by hzeller** [comment]
Ok. I think I'll create a separate pull request that only contains the single removal commit, then wait for the other pull request to settle before I change keywords.
So I am closing this now and will re-open a fresh, simplified pull request that just removes it from conn.

**Comment by hzeller** [comment]
Alright, see #233

**Comment by ricardocrudo** [comment]
@hzeller #223 is updated.

**Pull request closed without merging**
