### PR TITLE
Added TMP20 temperature sensors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds the TMP20 temperature sensors from Texas Instruments

**URL** http://www.ti.com/lit/ds/symlink/tmp20.pdf

tmp20

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@pointhi  @ashtonchase anyone want to have a look at this one?

**Comment by SchrodingersGat** [comment]
Merged kicad/master as this PR was pretty old! All conflicts fixed now.

**Comment by jkriege2** [comment]
Hi
- TMP20AIDCK: OK :+1: 
- TMP20AIDRL: package is wrong ... the package is SOT-563-6 according to datasheet, which is smaller than SOT-23 (see http://www.onsemi.com/site/cdroms/micropackages/pdf-docs/onsemi/SOT563%20footprint-prof%23B3380.pdf) ... and it seems we don't have it yet ...

Could you fix?

JAN

**Comment by ashtonchase** [comment]
I'll take a look at this one in a day or two @SchrodingersGat .

**Comment by SchrodingersGat** [comment]
Conflicts have been fixed

**Comment by ashtonchase** [comment]
Hi @SchrodingersGat,

I concur with @jkriege2, please update the package for TMP20AIDRL to SOT-563-6.

Merry Christmas!

**Comment by SchrodingersGat** [comment]
Alright, thanks for pointing that out :)

**Comment by jkriege2** [comment]
can you alter FPFilters to `SC?70*` and `SOT?563*`

The rest looks good to me ... and I'll merge when done!

Best,
JAN

**Comment by SchrodingersGat** [comment]
As requested

**Comment by jkriege2** [comment]
nice work!

JAN

**Pull request merged**
