### PR TITLE
Russian MCUs from Milandr

### PR DESCRIPTION
**Pull request by chipiki**
Library with Russian MCUs and transceivers form Milandr:
1. К1986ВЕ92QI - ARM Cortex-M3 80MHz, Flash 128Kb, RAM 32 Kb
2. MDR32F1QI (К1986ВЕ1QI) - ARM Cortex-M0 144MHz, Flash 128Kb, RAM 32 Kb
3. K5559IN10BSI (К5559ИН10БSI) - RS485 transceiver
4. K5559IN14AY (K5559ИН14АУ) - CAN-bus transceiver

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi @chipiki 
Please provide datasheets for all parts and also post an image of the symbols.

We're in the process of grouping symbols by function, not vendor, and so the transceivers should definitely go in interface.lib. For these MCUs, there's really no place good for them to go and they'll have to move anyway. @jkriege2 @SchrodingersGat In what library should these MCUs live (for now, anyway)?

**Comment by chipiki** [comment]
Hello, @evanshultz !

Official site of Milandr: http://ic.milandr.ru/products/mikroskhemy_v_plastikovykh_korpusakh/

1. К1986ВЕ92QI - ARM Cortex-M3 80MHz, Flash 128Kb, RAM 32 Kb
Datasheet: http://ic.milandr.ru/upload/iblock/2ea/2ea1fef16f4aa9132a3ca415a66ab92c.pdf
Image (Part A): k1986be92qi-parta
Image (Part B): k1986be92qi-partb

2. MDR32F1QI (К1986ВЕ1QI) - ARM Cortex-M0 144MHz, Flash 128Kb, RAM 32 Kb
Datasheet: http://ic.milandr.ru/upload/iblock/99f/99f74da953b04d24a73da45ae1730faa.pdf
Image (Part A): 
mdr32f1qi-parta
Image (Part B): 
mdr32f1qi-partb
Image (Part C): 
mdr32f1qi-partc
Image (Part D):
mdr32f1qi-partd

3. K5559IN10BSI (К5559ИН10БSI) - RS485 transceiver
Datasheet: http://ic.milandr.ru/upload/iblock/126/12691e33d6a6d6c83470c31df8bc9b07.pdf
Image: k5559in10bsi

4. K5559IN14AY (K5559ИН14АУ) - CAN-bus transceiver
Datasheet: http://ic.milandr.ru/upload/iblock/1ea/1ea3f95b1f53255efa9cd3a4f5881bd7.pdf
Image: k5559in14ay


In the kicad-library already exists vendor specific libraries like Altera, Lattice, Zilog, allegro,  	analog_devices, atmel, bosch, infineon, intel, maxim, microchip...
So, why do not include all this chips from Milandr in vendor specific library "milandr.lib"?

If you wish you can place the transceivers (K5559IN10BSI and K5559IN14AY) in the library "interface.lib". 
MCUs (К1986ВЕ92QI and MDR32F1QI) can be placed in "microcontrollers.lib".

**Comment by jkriege2** [comment]
Dear @chipiki ,
we have a set of rules for symbols in the official libs. They are called KLC and can be found there:
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
Also there are FAQs that explain these rules in more details:
https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions

Please ensure that your symbols follow these rules (and the examples set by other symbols in this lib). The automatic checking at the end of this PR-page will assist you in this, by pointing out errors in the symbols. 

About the placement: As we are trying to remove all simple vendor-specific libs, please follow the comment of @evanshultz about lib-placement. Here's a link to the ongoing discussion: https://github.com/KiCad/kicad-library/issues/1402

Best,
JAN

**Comment by evanshultz** [comment]
Hi @chipiki 
Thanks for working on the symbols. Please ask if you have any questions. Until then, I'll assume you're reading about KLC and working to make your symbols conform. When you're ready for a review, please post updated images of the symbols, as you did above, and let us know.

Also, please move the rs422 transceivers out of this new library and into interface.lib as mentioned above.

**Comment by chipiki** [comment]
Hello!

I made some changes in components.
Also I move K5559IN10BSI and K5559IN14AY from "milandr.lib" to "interface.lib".
Please, check it again.

1. К1986ВЕ92QI - ARM Cortex-M3 80MHz, Flash 128Kb, RAM 32 Kb
Datasheet: http://ic.milandr.ru/upload/iblock/2ea/2ea1fef16f4aa9132a3ca415a66ab92c.pdf
Image (Part A):
k1986be92qi-parta

Image (Part B):
k1986be92qi-partb

2. MDR32F1QI (К1986ВЕ1QI) - ARM Cortex-M0 144MHz, Flash 128Kb, RAM 32 Kb
Datasheet: http://ic.milandr.ru/upload/iblock/99f/99f74da953b04d24a73da45ae1730faa.pdf
Image (Part A):
mdr32f1qi-parta

Image (Part B):
mdr32f1qi-partb

Image (Part C):
mdr32f1qi-partc

Image (Part D):
mdr32f1qi-partd

3. K5559IN10BSI (К5559ИН10БSI) - RS485 transceiver
Datasheet: http://ic.milandr.ru/upload/iblock/126/12691e33d6a6d6c83470c31df8bc9b07.pdf
Image:
k5559in10bsi

4. K5559IN14AY (K5559ИН14АУ) - CAN-bus transceiver
Datasheet: http://ic.milandr.ru/upload/iblock/1ea/1ea3f95b1f53255efa9cd3a4f5881bd7.pdf
Image:
k5559in14ay

**Comment by jkriege2** [comment]
Hi!

a few comments on your symbols:
1. Are these devices available commercially? On the homepage of the company I only see that they DESIGN chips, not sell them (just curious)?
2. Power-inputs for positive volatges (VCC, ...) should be at the top of the symbols, Power-inputs for GND/neg. volatges should be at the bottom of the symbols.
3. Could you provide english description and tags please?
4. FPFilters should not contain the pin-count (there is a pin-count filter), but they should contain the size of the package, e.g. if a device is available in SOIC-8 (in KiCAD that would be `Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm` in the footprint field) , the FPFilter should be `SOIC*3.9x4.9mm*Pitch1.27mm*`
5. If a device is available in only one package, please fill the footprint field with that package and provide ONE FPFilter which mathces that package.

Best,
JAN

**Comment by chipiki** [comment]
Hello, @jkriege2 !

Yes, all this devices available commercially. You should look at russian version of site here:
http://ic.milandr.ru/products/mikroskhemy_v_plastikovykh_korpusakh/

Also for example, here you can look for developer boards:
https://www.ldm-systems.ru/catalog/milandr

I tryed to put Power-inputs at top and bottom... Sorry, but, it's looks very agly...

There are no english datasheets. Only russian. It's good language :)

Ok, I will correct FPFilters.

**Comment by jkriege2** [comment]
Just a quick note on language: I would say: leave the datasheets as is (if there are only russian ones available). If there are english datasheets it would be better to link these, so the part is usable also for non-russian-speakers. The one thing that you really need to change is the description ... if it's in russian, the part won't be usable outside russia, as people would have to guess what the device does (if they don't know it)!

About the power-pins: We try to keep the symbols in the lib in a common style ... so please orient your symbols on that standard (simply refer to other MODERN RS485 smybols in the lib ... note that we haven't updated all symbols yet!).

Best,
JAN

**Comment by jkriege2** [comment]
please fix conflicts

**Comment by jkriege2** [comment]
... i.e. merge in the master trunk ;-)

Best & Thanks,
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 the conflicts have been fixed here - are you ready to merge?

**Comment by jkriege2** [comment]
No, the overall look has not yet been fixed. Currently these symbols stand out very much from the other symbols that we have (placement of power-symbols, design, ...).
Also: The footprint field should be set if the devices are available in one package only and the FPFilters do not follow the rules in the KLC ... see warning at https://travis-ci.org/KiCad/kicad-library/builds/264656898?utm_source=github_status&utm_medium=notification

Best,
JAN

**Comment by SchrodingersGat** [comment]
@chipiki thanks for your work thus far on this. We have begun the transition process to a new consolidated symbols library at https://github.com/kicad/kicad-symbols 

Please re-open this PR at the new repository. Sorry for the inconvenience. Your symbols should be placed in the following libraries:

* K555 - Interface_UART.lib
* MCUs - MCU_Milandr.lib

Thanks :)

**Pull request closed without merging**
