### PR TITLE
Add WS2812 LED family & their 3D models

### PR DESCRIPTION
**Pull request by yaqwsx**
I have added all these missing "smart" LEDs from the Worldsemi manufacturer, I have also posted a PR for the footprints in LEDs.pretty

### CODE REVIEW

**Comment by yaqwsx** [comment]
Is there a way to find out what failed during test in jenkins? I'd like to fix it.

**Comment by El3ctr0nic** [comment]
I'm sorry ;( Im newbie on GitHub. Maybe i did something wrong, but strange
it works for me fine. I made some libs for KiCad before (all dsPIC lib) and
i havent any problems. I try find out what is going on.
PS sorry for my english it's not my primary language.

2016-01-25 10:37 GMT+01:00 Jan Mrázek <notifications@github.com>:

**Comment by El3ctr0nic** [comment]
I think it's not mail for me LOL. I was too hurry up with replay

2016-01-25 16:40 GMT+01:00 Marcin Szumlański <szumlanski.marcin@gmail.com>:

**Comment by El3ctr0nic** [comment]
I have question.
Someone now haw run checklib.py in windows? I Im green with pyton ; / I try
serch byt no result. When i run script i always get error in first
parameter.

2016-01-25 16:49 GMT+01:00 Marcin Szumlański <szumlanski.marcin@gmail.com>:

**Comment by reportingsjr** [comment]
@yaqwsx Yeah, it is a little convoluted right now.

Clicked the red X next to the failed test. Click either Details link (they are the same link). Then on that page you will see an Archive called results.txt. Click the view button next to that and you will see the test results.

**Comment by El3ctr0nic** [comment]
HTTP ERROR 404

Problem accessing /job/kicad-lib%20checker/31/. Reason: not found.

Yesterday i have no permission to read/write ;/

2016-01-25 21:48 GMT+01:00 Jon Neal <notifications@github.com>:

**Comment by yaqwsx** [comment]
I am having the exactly same problem with acessing jenkins logs as @El3ctr0nic .

**Comment by reportingsjr** [comment]
Oops, try again! I think I fixed the issue.

**Comment by yaqwsx** [comment]
Thanks for fast response! The jenkins log shows rule 3.8 is violated, however local check passes and if I check manually, there is a desription, keywords and link to manufacturer website for each component.

**Comment by El3ctr0nic** [comment]
Oh I know now i can see now .txt log. I haven't link to to documentation of
TLP i fix it and try again
Thx 4 help

2016-01-26 9:44 GMT+01:00 Jan Mrázek <notifications@github.com>:

**Comment by El3ctr0nic** [comment]
If i can make this lib live i shouldyn't have problems in future ;]

2016-01-26 9:55 GMT+01:00 Marcin Szumlański <szumlanski.marcin@gmail.com>:

**Comment by El3ctr0nic** [comment]
How to make again symbols check without creating new pull request??

2016-01-26 10:01 GMT+01:00 Marcin Szumlański <szumlanski.marcin@gmail.com>:

**Comment by yaqwsx** [comment]
@reportingsjr Could you please look what's wrong with automated tests/parts in the library? When I run the tests locally, there are no reports. And I personally doesn't see why should be the rule 3.8 violated.

**Comment by yaqwsx** [comment]
Name of the 3D models for the LEDs was changed according to the feedback received in the LEDs.pretty repository

**Comment by CarlPoirier** [comment]
test this please

**Comment by yaqwsx** [comment]
@CarlPoirier: I have tested the library locally (using the kicad-library-utilities) and no rules violation was found. I have no clue, why the automated tests show rule 3.8 is violated.

**Comment by CarlPoirier** [comment]
@yaqwsx Me neither. Let me have a look at the parts.

Link to footprint pull request: https://github.com/KiCad/LEDs.pretty/pull/13

**Comment by CarlPoirier** [comment]
@yaqwsx The WS2812 has no description and keywords. Also please put RGB in the keywords for all of them if that is the case.

Also, please shorten the pins to 100mils.

Thanks!

**Comment by yaqwsx** [comment]
Thank you for your feedback. I have fixed the mismatched pin legths and added a missing description to WS2812.

However I am still confused - local check doesn't allow me to check component WS2812 and the automated test are still failing becouse of rule 3.8. Am I assuming right rule 3.8 is "Description and keywords properties contain the relevant information."?

**Comment by yaqwsx** [comment]
Is there any progress with the jenking check failure? Is there something I can do to help you?

**Comment by CarlPoirier** [comment]
test this please

**Comment by CarlPoirier** [comment]
Thanks for your contribution!

**Pull request merged**
