### PR TITLE
Added LM5165 dc-dc converter

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.ti.com/lit/ds/symlink/lm5165.pdf

* Adjustable voltage version
* Fixed voltage version (3.3V and 5.0V)

symbol

Also created footprint as per the datasheet: https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/18

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Footprint filters match the existing DFN-10-3x3mm footprint and the newly defined footprints.

**Comment by SchrodingersGat** [comment]
these symbols has some specific footprint requirements which have been addressed in the linked DFN_QFN PR

**Comment by SchrodingersGat** [comment]
@diggit  @CarlPoirier  @ashtonchase anyone want to take a look at this?

**Comment by SchrodingersGat** [comment]
Merge conflicts have been fixed

**Comment by SchrodingersGat** [comment]
Fixed merge conflicts once again. @pointhi  @diggit  want to take a look before I have to merge too many more changes? :p

**Comment by diggit** [comment]
@SchrodingersGat Symbol looks good, can you set PGOOD type to open collector?
Also, when did kicad switch from CRLF endings to LF? This is gonna be painful transition. Back to `git diff -b` :/

**Comment by diggit** [comment]
Lookig on #563, you used one symbol for adj and fixed version, here you have 2 symbols. Which is better? In the end, we should choose only approach.
*I prefer 1 symbol with combined pin name.*

**Comment by SchrodingersGat** [comment]
I'm happy with that solution - they have now been consolidated into a single symbol

**Comment by SchrodingersGat** [comment]
Merged kicad/master once more. I shall learn to rebase in the future ;)

**Comment by SchrodingersGat** [comment]
Conflicts fixed, again, for the last (hopefully) time

**Pull request merged**
