### PR TITLE
Add 3d models worldsemi WS2812 and WS2812B

### PR DESCRIPTION
**Pull request by ptm-tm**

### CODE REVIEW

**Comment by jkriege2** [comment]
Can you give/upload the source for these 3D models?
Thanks,
JAN

**Comment by ptm-tm** [comment]
yes, but i create it in catia. its closed format.
i can convert it in step 203 or 204

**Comment by jkriege2** [comment]
Hi!

if you would have used FreeCad it could have made sense to also upload that.
In general about your PR: We already have these 3D models as `LED_WS2812B_PLCC4` and `LED_WS2812_PLCC6`: 
2017-01-07 08_41_13-3d betrachter led_ws2812b-plcc4

Are there any improvements in your 3D models? If so, please overwrite the old models in this PR, they will not be found by a footprint under the name/lib you used, if you don't also push a footprint1

best,
JAN

**Comment by ptm-tm** [comment]
only more informative
ws2812b
ws2812

**Comment by jkriege2** [comment]
I would say: your#s looks nicer ;-) ... So please overwrite the two models we already have with your version and I will merge. Could you post an image with the existing footprints+your new models, so we see whether they fit without altering the offset ...

cu
JAN

**Comment by ptm-tm** [comment]
ws2812-01
ws2812-02

kicad project i public in 
https://bitbucket.org/PTM/kicad

is it enough?
or i must owerwrite models and create new pull request(commit)?

oh... my eng is not so good:(

**Comment by jkriege2** [comment]
Hi!

you can use this PR, just remove the two file you added and save them as these:
- `kicad-library/modules/packages3d/LEDs.3dshapes/LED_WS2812-PLCC6.wrl`
- `kicad-library/modules/packages3d/LEDs.3dshapes/LED_WS2812B-PLCC4.wrl`
Then ensure that KiCAD finds these, put the two footprints `LEDs/LED_WS2812-PLCC6` and `LEDs/LED_WS2812B-PLCC4` to a PCB and post a screenshot of the 3D view here ... that should be it. If we would merge your footprints, you would have to change them significantly, as they currently don't conform to KLC (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention), as e.g. F.FAB is missing...

Best,
JAN

PS: Just ask, we'll get through with this ;-) ... your english seems not too bad to me?

**Comment by ptm-tm** [comment]
Hmm... may be need replace with
LEDs/LED_WS2812-PLCC6
LEDs/LED_WS2812B-PLCC4
because
1. default scale is not =1
2. smd pads dont like recomended datasheet. 
 I think i understood my errors. ( this pull request can close without merge).
wstest 2
wstest

**Comment by ptm-tm** [comment]
ps... i can create more pretty models if need for other devices...

**Comment by jkriege2** [comment]
Hi!

the size thing is known ... the factor 0.38...=1/2.54 commonly happens when you design a 3D symbol in true coordinates and export it to VRML (that format does not seem to know true units). So I would propose to open a second pR for `LEDs.pretty` that modifies the scaling factors in the footrprints and i can review+merge them together. Just reference this PR in the other one!

best,
JAN

**Comment by Shackmeister** [comment]
Hi @ptm-tm 
PR's for 3D models are no longer being accepted into this repo.
If you would still like to contribute this models, please add a new PR on the new 3D repository which can be found here: https://github.com/KiCad/packages3D

**Pull request closed without merging**
