### PR TITLE
Adjusted PIC10xxx symbol names to the new KLC

### PR DESCRIPTION
**Pull request by lavadew**
Adjusted PIC10xxx symbol names to the new KLC and created aliases for the LF variants

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks for the efforts here, great work :) I know that you did not cause these errors, but as there are only four outstanding, can you please address the errors [raised by Travis](https://travis-ci.org/KiCad/kicad-library/builds/302427855?utm_source=github_status&utm_medium=notification)

**Comment by lavadew** [comment]
Yeah, i'm @ it atm. :)

**Comment by lavadew** [comment]
fixed it. @SchrodingersGat

**Comment by SchrodingersGat** [comment]
Almost! There is no footprint called `DFN-8` in that library - you will need to pick one that actually exists

**Comment by lavadew** [comment]
accidentally deleted the branch.
will close this PR and restart.

**Pull request closed without merging**
