### PR TITLE
Added LFxxABDT-TR to the regul library.

### PR DESCRIPTION
**Pull request by michalkona**

### CODE REVIEW

**Comment by diggit** [comment]
Please add FP filter: `TO-252*`
Why did you skip 6V and 8.5V versions?

**Comment by michalkona** [comment]
I used table on this web site http://www.st.com/content/st_com/en/products/power-management/linear-voltage-regulators/low-dropout-ldo-linear-regulators/lfxx.html and I added to library only the LFxxABDT-TR with explicitly assigned output voltage. if it is necessary I can add all LFxx voltage regulators in DPAK package.

**Comment by michalkona** [comment]
I think all is done.

**Comment by michalkona** [comment]
What is the reason why the "need to improve" label has not been erased yet?

**Comment by jkriege2** [comment]
Nice work! Thanks,
JAN

**Pull request merged**
