### PR TITLE
Add LM75CIM temperature sensor

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
[Datasheet](http://www.ti.com/lit/ds/symlink/lm75b.pdf)

imagen

imagen

imagen

imagen

### CODE REVIEW

**Comment by Misca1234** [comment]
I guess you should change the name from
LM75CIM
to 
LM75C


I guess the description should be changed from 
Digital Temperature Sensor & Thermal Watchdog
to
Digital Temperature Sensor & Thermal Watchdog, SOIC-8 and VSSOP-8

The foot print filter should be changed from
SOIC*8*3.9x4.9mm*Pitch1.27mm*
to
SOIC*3.9x4.9mm*Pitch1.27mm*

If you remove the specific foot print ("Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm")
and add 
VSSOP*3.0x3.0mm*Pitch0.65mm*
to the foot print filter you get the VSSOP variant as well


If so

duplicate LM75C to LM75B
and use the following description for LM75B
Digital Temperature Sensor & Thermal Watchdog with LP on I2C and bus fault timeout, SOIC-8 and VSSOP-8

Then you have both in all variants.

**Comment by antoniovazquezblanco** [comment]
LM75CIM is the SOIC8 variant. I was only considering that one. I can make it more general and also add the B model as an alias. 

Probably tomorrow. 

Thanks Misca1234.

**Comment by antoniovazquezblanco** [comment]
Done! Thank you also for the VSSOP push @Misca1234!

**Comment by Misca1234** [comment]
Oh, you noticed, well, we can not let a component like this be incomplete, can we ;) ?

**Comment by antoniovazquezblanco** [comment]
Anything else preventing this from merge @Misca1234  @SchrodingersGat ?

Thanks again!

**Comment by SchrodingersGat** [comment]
Thanks @antoniovazquezblanco

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
