### PR TITLE
Added PAM8302A

### PR DESCRIPTION
**Pull request by nuntipat**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @nuntipat please read the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) and then address the issues raised by the [Travis script](https://travis-ci.org/KiCad/kicad-library/builds/218750591)

**Comment by nuntipat** [comment]
Hi @SchrodingersGat, I've fixed the issues. Thank you

**Comment by SchrodingersGat** [comment]
Hi @nuntipat thanks for making those changes. A couple of queries:

1. I am a little confused by the [datasheet](https://www.diodes.com/assets/Datasheets/PAM8302A.pdf) - in particular it seems to suggest that the [DFN footprint](https://www.diodes.com/assets/Datasheets/SBR3U100LP.pdf) only has two pins and is for a diode. Is this a mistake in the datasheet? Have you used the DFN variant?

2. Please add pin-2 as NC, invisible:

image

**Comment by nuntipat** [comment]
Hi @SchrodingersGat thanks for catching that. 

I've added the NC pin and removed the DFN footprint because there're some conflicts between two revisions of the data sheet ([old data sheet from Adafruit](https://cdn-shop.adafruit.com/datasheets/PAM8302A.pdf) and [new data sheet from Diodes Incorporated](https://www.diodes.com/assets/Datasheets/PAM8302A.pdf)). Also, both Digikey and Mouser don't have the part in DFN variant in their stocks. 

I will create another PR after receiving some news from the manufacturer. 

Thanks you.

**Pull request merged**
