### PR TITLE
Added Vigortronix 10W

### PR DESCRIPTION
**Pull request by Gasman2014**
Add Vigortronix 10W monolithic PSU range

vtx-214-010-103

[10WattAC-DCConverters.pdf](https://github.com/KiCad/kicad-library/files/1042284/10WattAC-DCConverters.pdf)

screen shot 2017-05-29 at 18 43 12

Footprint & 3D model to follow

### CODE REVIEW

**Comment by Gasman2014** [comment]
I have also made a model of this but as I have already submitted a PR on this branch it won't upload yet. It is my own version and entirely copyright free.

screen shot 2017-05-29 at 18 43 12

**Comment by poeschlr** [comment]
Please resolve the merge conflicts. (Resync your branch with the master branch of the official repo.)

**Comment by Gasman2014** [comment]
Thank you - will do!

Just when I thought I was getting the hang of git! I have followed your really helpful ‘How to work with git’ guide but still seem to have a few problems!

I wil give it another go next week.

John

**Comment by poeschlr** [comment]
It seems you have some of the files of another of your own pull requests also included in this pull request. (This pull requests adds 2 more aliases than what you added in the other one. The VTX-214-010-110 and VTX-214-010-108 do not exist in the library as is.)

**Comment by Gasman2014** [comment]
I think I am going to rebase my whole repo (sorry but I think will end up tidier that way) and have another go. I am still very confused about git workflow (I am not a programmer) and I have a particular problem with where to keep the footprint files. I want to keep the modules within the local checkout version of my repository. The footprints.pretty that get downloaded via the Kicad git tool get added to my local repo and then get pushed back to my fork on github when i do a git push - so I now have 5000+ 'added' files in my checkout - so these seem to be added to the amended pull request I was going to send - not so good :(.

I have tried following the instructions that you sent using the command line but some of the git incantations fail. Essentially my workflow has been 

  *  Fork the original repository
  *  Download it locally. 
  *  Branch this for my added 'feature'. 
  *  Do my edits.
  *  Add any new files (like 3d , save and then commit the changes. 
  *  Push this back to my forked repository
  *  Put a pull request in **from** the master repository **to** pull from my branch.

But my branch doesn't seem to keep up today with the master branch and I can't seem to update it from within Github. I thought it should track the master automatically but it is not clear how to do that within Github.

Also, where should I put the modules (the pretty files)? Should I have a special gitignore to stop them being added/tracked?

I would really like to help to contribute to the Kicad project as I think it is really useful piece of software but I fear I am making more work for everyone!

**Comment by Gasman2014** [comment]
Just to clarify my workflow as I really don't understand what i am doing wrong - and with some comments regarding the tutorial you helpfully provided. I think (for noobs like me) that it would be very helpful to have a complete, reliable and error free series of incantations to get this working. I have read Scott Chacon's Pro Git book and watched a number of podcasts to try and get up to speed. I have managed to get a few pull requests right but I fear this is more due to luck than judgement.


This is what I have been doing (following your cheat sheet).

1. Go to GitHub, register for an account, login and find the Kicad-library.
2. Fork this library using the button on the toolbar (which makes a copy in my user space on GitHub.
3. Go to my fork of this repository in GitHub.
4. Clone a copy of this repository to my local machine - I used GitHub Desktop to do this.
5. Open the checkout in a terminal and check I have the correct remote connections with git remote -v  
>
KiCad https://github.com/KiCad/kicad-library.git (fetch)
KiCad https://github.com/KiCad/kicad-library.git (push)
origin https://github.com/Gasman2014/kicad-library.git (fetch)
origin https://github.com/Gasman2014/kicad-library.git (push)

6. git checkout master
> already on master.

7. Then git fetch upstream
> fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Slightly confused but press on...

8. Then git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Slightly more confused but press on again...

9. git push
> Everything up to date

Sounds good :)

10.  AAAH - no footprints. I don't have any footprint modules in my local modules directory so need to download them all again using the git tool. Half an hour (and a lot of bandwidth later)

11. git checkout -b my_new_branch
>switched to a new branch 'my_new_branch'

12. Do my edits.

13. git add -u

14. Massive pile of footprints get added to my local repo....

15. Go and have a lie down in a dark room with a paracetamol for a while. When I come back, looking at GitHub my local repository is now behind the master so I do...

16. git fetch upstream

> fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

17. I still haven't sorted out the footprints or added the footprint for my device!

18. Doing a git push now (more in hope than expectation) and a pull request leaves me in the position that this repo was in.

Whilst I am sure that for many people git is second nature, I see quite a few 'git headache' comments. I use fossil for scm in my projects so I am not totally unfamiliar with the process of dcm but having two parallel repositories and a checkout of my branch that doesn't seem to keep up to date with the master is quite confusing - add into the mix what happens to the footprints and it all gets too much. I am sure more non-programmers would submit good quality library entries, models and footprints if it wasn't for the burdensome git requirements. :(.

I am happy to blindly follow a recipe - perhaps I would begin to understand it better if I had a workflow that worked absolutely without throwing these errors. Perhaps there is a missing step - especially if something was set up some time ago it is easy to overlook a vital step.

I think the major problem is how I should handle the footprints - if ththere was a clear description of this I think I would understand the whole process better. Asi t is I am just going round in circles -  I want to keep all the footprints together in the modules directory in the library. Also I would very much like to keep the 3dpackages a a top level folder in the library with modules/3dpackages being an alias to it. Perhaps I should be cloning each one of the .pretty directories separately and aliasing them to the modules folder? Perhaps I need to do something with a .gitignore file? Perhaps I shouldn't be using th git download tool within Kicad.

I appreciate that the whole library management will be undergoing a massive rejig soon but a real idiots guide to how to do things both now and in the future would be really helpful! 

I use a Mac - don't know if that is likely to add to the problems :) but I like the way that Kicad supports Mac users.

And finally I think the librarians are doing an ABSOLUTELY BRILLIANT JOB!!!! There have been so many additions and quality improvements over recent months - you guys rock - well done!! I think it is because of this that I am really keen to try and add some of my own components to help the cause - and which is causing me so much grief.

BW

John







On Jun 03, 2017, at 09:18 PM, Rene Pöschl <notifications@github.com> wrote:

Please resolve the merge conflicts. (Resync your branch with the master branch of the official repo.)

**Comment by hackscribble** [comment]
> 7. Then git fetch upstream

You need to add `upstream` as a remote for your clone.  `upstream` is the conventional name for the original repo from which you created your fork (i.e. it is the repo to which you want to contribute).  

```
$ git remote add upstream https://github.com/KiCad/kicad-library
```
Your steps 6, 7 and 8 probably won't change your clone if you have just forked and cloned.  But you will need to do them later to resync your clone with `kicad-library` as it changes (for example, after your PR is merged).

> I want to keep all the footprints together in the modules directory in the library.

The footprint modules are in separate repos from the schematic symbols - they don't belong in `kicad-library` which is why you are hitting problems when you copy them in to the same folder.  

Are you trying to make changes to some footprints, or do you just want to have them on your system?

**Comment by Gasman2014** [comment]
Hi

Thanks for getting back to me. OK, that is beginning to make sense. I think you would agree that when HEAD and origin are accepted name why I might have thought upstream was ok too. Its things like that that are confusing!

So, even though the result of git remote -v  is

KiCad https://github.com/KiCad/kicad-library.git <https://github.com/KiCad/kicad-library.git> (fetch)
KiCad https://github.com/KiCad/kicad-library.git <https://github.com/KiCad/kicad-library.git> (push)
origin https://github.com/Gasman2014/kicad-library.git <https://github.com/Gasman2014/kicad-library.git> (fetch)
origin https://github.com/Gasman2014/kicad-library.git <https://github.com/Gasman2014/kicad-library.git> (push)

 I still need to do?

$ git remote add upstream https://github.com/KiCad/kicad-library


When I installed the original library with kicad the footprints are stored in the ‘modules' directory. So should I now move the actual modules somewhere else outside the library directory and set my $KISYSMOD to reflect that? The need to do something like this might discourage people from adding their own work if it means you have to set your environment up differently if you want to develop. Alternatively - it would be much better to set it up out of the box in a way that is possible to easily work with.

I am trying to add a number of power supplies that I am using in a several of my projects. These are the Vigortronix monolithic AC-DC stabilised power supplies - specifically the 10 & 15W models but would add others if it were easier! I have made a library (including all voltage variants) for these models. I also have made the footprints and a 3d models (step/wrl). I also have another transformer (with FP and 3d step / wrl). So I need to modify the library files, add a module to Converters_DCDC_ACDC.pretty and the model files to the packages3d/Converters_DCDC_ACDC.3dshapes (and the transformer to the appropriate Transformer files).

So in answer, I am already using these footprints  - which is easy - they are all in my personal library.

However, I would also like to share them which is proving frustrating.

BW

John

**Comment by hackscribble** [comment]
>  I still need to do?
$ git remote add upstream https://github.com/KiCad/kicad-library

Yes, that will let you resync with the KiCad repo after your PR has been merged, and in some other circumstances.

> When I installed the original library with kicad the footprints are stored in the ‘modules' directory.

That sounds like it might be an old version of KiCad?  The `library\modules` folder is now only used for the `packages3D` folder and its subfolders with 3D models.  

The footprints are now grouped into separate repos each of which holds a `xxxx.pretty` folder (e.g. `Housings_SOIC.pretty`). Inside the `.pretty` folder are the individual `yyyy.kicad_mod` files, one for each footprint.  

Instructions for installing local copies of the `.pretty` repos are here: https://forum.kicad.info/t/creating-your-own-offline-libraries-in-new-kicad/1169/15?u=hackscribble

If you want to submit the footprints, you will need to fork and clone the `Converters_DCDC_ACDC` repo and submit a separate PR.

**Comment by Gasman2014** [comment]
OK thanks - that is clearer now.

I am using the nightly from a few days back. The 'Add Footprint Libraries Wizard' by default seems to want to put the footprints into library/modules… This is clearly adding to my difficulties so will install them somewhere else and adjust $KISYSMOD accordingly! Why is there still a ‘modules’ directory that only contains packages3d -  it does rather invite putting your modules in it… And I am sure that that is where they used to be some iterations ago.

Advice re FP - received and understood.

BW

John

**Comment by poeschlr** [comment]
@Gasman2014 
Thanks for not simply giving up when hitting the first roadblock.
> Why is there still a ‘modules’ directory that only contains packages3d

Because the new version of handling 3d files is not finished yet. @SchrodingersGat is still looking for someone to help with the development of a new git plugin that will handle this stuff in future releases. 
(In kicad 3 the footprints where managed like the symbols are managed now. Sadly the 3d models and the symbols are still managed in the old style. At least in the stable release. The nightly builds already include a simple 3d modules downloader.)

---
A tip for developing components for the oficial libs (This describes my work-flow. It is definitely not the only way to do this. Remember: never change a running system! I also think you already know most of this. But just in case you are unsure.):
Setup one location where you have your git repos. Put the repo for the symbol libs and a all footprint repos that you need in this one location. (I give the footprint repos a special name by adding the prefix FPdevel_ to the libraries name. This makes it easier to find them in the footprint editor. Sadly this can not be done for symbol libs.)
This repos should have your fork as the origin remote location and a second remote location that points to the official repo. (I called it upstream in my description. @hackscribble gave you the directions of how to add this remote location.)

After you have setup your file system, create one project for developing symbols/footprints.
Add the footprint libs as local libs to this project (via the library wizard) and add the location of your github symbol libs to the searchpath of your symbol development project. (I find that it is enough to just add the github repo location in the project search path under eeschema->component libs. Some of the libs that are in this repo are not added to new projects by default. Just add them if you need them.)

**I hope this description does not confuse you instead of helping. (I deleted it at least two times already. I'm still not certain that it will help.)**

**Comment by poeschlr** [comment]
**@hackscribble thanks for your great support.**
Also:
> I am a contributor, not a librarian, so not the authority on this.

You have contributed enough to know what is going on here. (I think you have contributed at least as much as i have. You have definitely contributed more to the symbol libs than i have.)

Remember this is a community repo. Not only members should have a voice. 
The ultimate authority is not some librarian but the library convention. The later should be agreed upon by the community. This is why all changes to the KLC are discussed in public. (Even if this slows down progress.)

**Comment by Misca1234** [comment]
@Gasman2014 
Will you finish this one ?
If you are familiar with python I can show you how to use existing python wrappers and framework 
to generate both footprint and 3d models so the whole serie 
"10 Watt Miniature AC-DC Converters" can be auto generated from scripts and you get them all in "one go".

**Comment by Gasman2014** [comment]
I will have another go at this. I am not really sufficiently competent with python to really be able to script the whole series but I will try and get the 10W & 15W versions .submitted I have the footprints and 3d models for both ready but it is mainly the wrangling with git that puts me off - sorry! I also have another  transformer and model to submit too - if this goes OK I will try to add that one as well.

BW
John

**Comment by Misca1234** [comment]
I already made the foot print for you, and they are merged, the push is here 
https://github.com/KiCad/Converters_DCDC_ACDC.pretty/pull/22
If you want I can make the 3D models ass well

**Comment by Gasman2014** [comment]
I have already made the models - I am just tearing my hair out trying to share them. The footprint you have added is rotated 90 degrees compare to the one I made so I have now rotated the models 90degrees too.

**Comment by Misca1234** [comment]
Pin 1 should always be closest to the upper left corner, on both foot prints and 3D models
for both pin and smd footprints

for pin models , pin1 shall always be in origo
for smd models the center of the pins should be in origo.

**Comment by Misca1234** [comment]
@Gasman2014

For the .step and .wrl models, did you use FreeCad and if so, did you use stepup macro to create the .step 
and .wrl files ?
The stepup macro will rescale and set right properties for the 3D model in the .step and .wrl files

**Comment by Shackmeister** [comment]
Hi @Gasman2014 
PR's for 3D models are no longer being accepted into this repo.
If you would still like to contribute this models, please add a new PR on the new 3D repository which can be found here: https://github.com/KiCad/packages3D

**Pull request closed without merging**
