### PR TITLE
Added IRF5303, IRF9530N, IRLZ44N mosfets (try #2)

### PR DESCRIPTION
**Pull request by emesik**
As before, the new mosfets, this time applied to the latest upstream version.

I added the fourth pin, another drain connection, which is the big rear tab in TO-220.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi @henrikbrixandersen. I know I'm bumping an old thread. Would you want to resolve the branch conflicts so we can merge that?

The solution that was discussed on the mailing list (https://lists.launchpad.net/kicad-lib-committers/msg00297.html) consisted in adding a variant of the symbol with a fourth collector pin. I suggest a "_MountingTab" suffix. Then, the footprint would simply need a board-level edit to set the mounting tab pad number.

Carl

**Comment by henrikbrixandersen** [comment]
Me? It's not my pull request?

**Comment by CarlPoirier** [comment]
Oops indeed, I poked the wrong person. Sorry!

**Comment by CarlPoirier** [comment]
@emesik, please have a look at my message above!

**Comment by CarlPoirier** [comment]
@emesik, please have a look at #568 to know how we are managing the mounting tab.

**Comment by hackscribble** [comment]
Hi @emesik I'm bumping this old thread.  Would you want to resolve the branch conflicts or should we close this PR?

Many thanks.

**Comment by poeschlr** [comment]
It might be better for such old pull requests to close them and open a new one than to merge all the changes that happened in the mean time back into this request. (Export the changed symbols and reimport them into a branch that is up to date with the current master branch.)

**Comment by hackscribble** [comment]
Hi @poeschlr that makes sense.  Is it OK do you think for the librarians to close the PR with a comment along those lines, or should we always leave it up to the originator to close?

**Comment by poeschlr** [comment]
When i see that too much merging is required i normally close it with a comment similar to:

@emesik Sorry this got forgotten for so long, if you are still interested in contributing please open a new pull request (in synch with the current master branch) and adjust your contribution to the new [library convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

But to be honest i don't have a lot of hope that the original poster will do anything here. (They have been inactive for 2.5 years.)

**Comment by poeschlr** [comment]
As i thought, the original poster did already delete the branch responsible for this pull request. (A good test is also to close and reopen a pull request to trigger travis to run. If the original poster deleted their branch and or repo you can not reopen it of course.)

**Pull request closed without merging**
