### PR TITLE
Added PIC18F25K80-I/ML series of microcontroller

### PR DESCRIPTION
**Pull request by SchrodingersGat**
28-pin QFN package

PIC18F25K80-I/ML
PIC18F26K80-I/ML (alias)
PIC18LF25K80-I/ML (alias)
PIC18LF26K80-I/ML (alias)

I have created schematic symbols for the PIC18(L)F2xK80-I/ML series of microcontrollers from microchip

http://www.microchip.com/wwwproducts/Devices.aspx?product=PIC18F25K80

Checked against KLC

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Also added symbols corresponding to the SSOP-28 footprints

**Comment by SchrodingersGat** [comment]
@ricardocrudo I have fixed the aliases for this series also, adding documentation / part info for each alias

**Comment by SchrodingersGat** [comment]
Added some more PIC18 series chips

**Comment by CarlPoirier** [comment]
test this please

**Comment by CarlPoirier** [comment]
Hi Oliver,

Please fix these issues. BTW once you are in sync with the master, the one about TEST_1P will disappear.

checking component: TEST_1P
  Violating Rule 3.6
  Violating Rule 3.8
checking component: PIC18F1220-SO
  Violating Rule 3.8
checking component: PIC18F45K80-I/ML
  Violating Rule 3.1
checking component: PIC18F45K80-I/PT
  Violating Rule 3.1

If you can do it soon, we'll be able to merge it in time for the KiCad 4.0 release.

**Comment by SchrodingersGat** [comment]
Changes to the PIC chips have been made and tested with checklib.py

**Comment by CarlPoirier** [comment]
Great, thanks!

**Pull request merged**
