### PR TITLE
fp-lib-table updates

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR updates fp-lib-table to point to new Inductor libraries which consolidate all existing Inductor and Choke footprints

The old libs have been marked as "deprecated" but still remain for compatibility.

Eventually, footprints in these (old) libs should be removed.

### Old Libs
* https://github.com/KiCad/Air_Coils_SML_NEOSID.pretty
* https://github.com/KiCad/Choke_Axial_ThroughHole.pretty
* https://github.com/KiCad/Choke_Radial_ThroughHole.pretty
* https://github.com/KiCad/Choke_Toroid_ThroughHole.pretty
* https://github.com/KiCad/Choke_Common-Mode_Wurth.pretty
* https://github.com/KiCad/Choke_SMD.pretty
* https://github.com/KiCad/Filters_HF_Coils_NEOSID.pretty
* https://github.com/KiCad/Inductors_NEOSID.pretty
* https://github.com/KiCad/Inductors.pretty
* https://github.com/kicad/Transformers_CHK.pretty
* https://github.com/kicad/Transformers_SMPS_ThroughHole.pretty
* https://github.com/kicad/NF-Transformers_ETAL.pretty

### New Libs
* https://github.com/KiCad/Inductors_SMD.pretty
* https://github.com/KiCad/Inductors_THT.pretty
* https://github.com/KiCad/Transformers_SMD.pretty
* https://github.com/KiCad/Transformers_THT.pretty

### References
Original issue - https://github.com/KiCad/kicad-library/issues/257
Mailing List - https://lists.launchpad.net/kicad-lib-committers/msg00471.html

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@diggit @CarlPoirier @jkriege2 if someone is happy with this approach please merge :)

**Comment by SchrodingersGat** [comment]
Added:

* https://github.com/KiCad/Transformers_SMD.pretty
* https://github.com/KiCad/Transformers_THT.pretty

**Comment by SchrodingersGat** [comment]
Added:
https://github.com/KiCad/Enclosures.pretty

**Comment by CarlPoirier** [comment]
Sounds good to me, are you done?

**Comment by SchrodingersGat** [comment]
Yep, all done :)

**Comment by SchrodingersGat** [comment]
Ok *NOW* I am done

**Comment by CarlPoirier** [comment]
@SchrodingersGat BUMP. If the answer is no, I simply suggest marking the repository as read-only more than calling it deprecated.

**Comment by SchrodingersGat** [comment]
@CarlPoirier sorry I have been away - I shall check over the SMD_Packages library and get back to you.

**Comment by SchrodingersGat** [comment]
So it appears that the SMD_Packages repo does contain footprints that are not replicated elsewhere - specifically the BGA footprints.

I have marked this as `read only` rather than `deprecated`. I have also created an (empty) .pretty repo for BGA footprints.

**Comment by SchrodingersGat** [comment]
Also added an entry for the new `Modules.pretty` library

**Comment by CarlPoirier** [comment]
This is all good. Please create the Modules.pretty repo and this can then be merged.

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Modules.pretty

**Comment by SchrodingersGat** [comment]
Agh fat-fingered that one. Anyway, `Modules.pretty` is available.

**Comment by CarlPoirier** [comment]
As always, deprecated pretties need to stay online. I know you know, I'm just leaving more traces about it.

**Comment by SchrodingersGat** [comment]
Thanks Carl. Footprint library wiki page has been updated - https://github.com/KiCad/kicad-library/wiki/Footprint-Libraries

**Comment by jkriege2** [comment]
nice!

please note that there still some PRs to pull int `Transformers_THT` and `Transformers_SMD`.
- https://github.com/KiCad/Transformers_SMD.pretty/pull/1
- https://github.com/KiCad/Transformers_THT.pretty/pull/1

Best,
JAN

**Comment by jkriege2** [comment]
Hi @SchrodingersGat a small note:

Please have a look at my last comment there: https://github.com/KiCad/kicad-library/pull/970

Best,
JAN

PS: Is there a tool (from Github) to send somebody a message other than in a discussion? Or to send someone a note to read e.g. a comment?

**Pull request merged**
