### PR TITLE
So 20 12.8x7.5mm pitch1.27mm 3 d 2

### PR DESCRIPTION
**Pull request by Misca1234**
This is foot print SO-20_12.8x7.5mm_Pitch1.27mm
It is used by SA605D
https://www.nxp.com/docs/en/data-sheet/SA605.pdf

kicad-library
https://github.com/KiCad/kicad-library/pull/1706

Housings_SOIC.pretty
https://github.com/KiCad/kicad-packages3D/pull/141

kicad-packages3D
https://github.com/KiCad/kicad-packages3D/pull/141

kicad-footprint-generator
https://github.com/easyw/kicad-3d-models-in-freecad/pull/110

bild

### CODE REVIEW

**Comment by sandhan26** [comment]
Looks pretty cool. What software did you use?

**Comment by Shackmeister** [comment]
Hey @sandhan26 this is made with Cadquery scripts in Freecad :) you can find them here: https://github.com/easyw/kicad-3d-models-in-freecad

**Comment by Misca1234** [comment]
The 3d model is a script based system developed by the librarians
The original one repository is here 
https://github.com/easyw/kicad-3d-models-in-freecad

You add the data in a python parameter file which then use FreeCad to render the object.


There is a fork which contain a lot more but i do not have the url at hand right now.

To do this 3 D model you need
1) Fork the repository
2) Download latest build of FreeCad, at least version 0.17
3) Add your capsule to the parameter file
4) Feed FreeCad with it 


so this particular model is in file
[Your path to to your forked repository of kicad-3d-models-in-freecad ]/kicad-3d-models-in-freecad/cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SO/cq_parameters_soic.py

and you render it with 
[Your path to FreeCad]/FreeCAD_0.17.11223_x64_dev_win/FreeCAD_0.17.11223_x64_dev_win/bin/FreeCAD.exe main_generator.py SO-20_12.8x7.5mm_Pitch1.27mm

and you find the models in (this might vary between the different scripts)
[Your path to to your forked repository of kicad-3d-models-in-freecad ]\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels\GullWings_packages\SOIC

**Comment by sandhan26** [comment]
Thanks for the info.

**Comment by Misca1234** [comment]
To @sandhan26

If you want to create your own models, let say like this one that does not exists as scripts 
you have two choices.

1) Either you dig into how the scripts works and create your own, this is really recommended when it comes to repeatable models, such as connectors
2) You "hand design" the model from scratch in FreeCad

So your situation is the following
A) You want to add a single "standard" IC capsule, see earlier post
B) You want to create a number of models, such as a serie of connectors, tell me and i will post additional information
C) You want to hand design a specific one shoot 3D model, see below

I guess the preferred way is always using the python scripts, even for one shoot hand design, in this way the models are easily re created

I would need some better format to explain everything, such a homepage or such, but this will be a start


--- hand design ---
If you choose to "hand design" the model you have a few other things to bear in mind,

Because kicad uses a very strange scale factor in the .wrl files which you need to compensate for when you design and you have to have deep knowledge of the object properties it might be a step uphill for you.

or you can design as usual and then use the kicad-stepup-tools.FCMacro to export the model from FreeCad into the format of .wrl and .step files that KiCad require.

So you need to do the following for a 3D model that is hand design from scratch

1) Fork the repository https://github.com/easyw/kicad-3d-models-in-freecad
2) Fork the repository https://github.com/SchrodingersGat/freecad-scripts
3) Download latest build of FreeCad, at least version 0.17, perhaps even a nightly build
4) Add the macro kicad-stepup-tools.FCMacro to FreeCad
5) Add your capsule to the parameter file
6) Feed FreeCad with it as described in earlier post
7) Export the model to .wrl and .step format using the macro

To do the export, follow these steps
At the end you will get up some boxes to ask you to define the colours and other properties just before the creation of the .wrl and .step file, so use your own colours in the model, remeber those and then match them against the KiCad own defined ones.


bild

bild

bild

**Comment by sandhan26** [comment]
To @Misca1234 Thanks for the exhaustive list of options. I want to go for option 2, along with option 1, because i love to program in python. But always lacked real world experience. I guess this is my chance.

I have some specific breakout boards in mind, which are used and soldered as it is on PCBs. Like the AI-Thinker esp8266 modules.

Also, i need to design some metal package ICs.

Secondly, i hear this term often at many places, 'nightly build'. What does it actually mean.

**Comment by sandhan26** [comment]
Hey i didn't find FreeCAD 0.17 but i got only 0.16

**Comment by poeschlr** [comment]
Nightly builds are development builds of kicad. They are generated every night hence the term nightly.

Freecad 0.17 is also a development build.

**Comment by Misca1234** [comment]
@poeschlr 
I would not mind to write the hands on instructions both for creating hand design one shoot 3D model and the "using python scripts" , is it possible for me to make a html page and then it will be added to 
http://kicad-pcb.org/help/documentation/ 
or should I make a pdf file ?

@sandhan26 
You must use 0.17, version 0.16 contain a bug in the .step export.
https://github.com/FreeCAD/FreeCAD/releases/tag/0.17_pre

**Python generated foot prints**
See push 
https://github.com/pointhi/kicad-footprint-generator/pull/52
and 
https://github.com/KiCad/Inductors_THT.pretty/pull/7

This is a push of python generated foot prints for a serie of Schaffner Chokes.
The file 
scripts/Inductors/Choke_Schaffner_RNXXX.py
was created from scratch because no schaffner file existed before.
But in general, check first f there is a python script that already exist that might already create the package you want, for example .
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Housings_DFN_QFN
Then you only have to update the the parameter file
(I think schrödingersGat have a more extensive fork but I dont have the url at hand atm)

In either case you need two pushes, the python script update and the foot prints itself

**Python generated foot prints**
The principle is the same, check out 
https://github.com/easyw/kicad-3d-models-in-freecad

The scripts are in
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator

If you want something that does not exist, then you have to add the file
And you generate them with FreeCad
for example for 
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/Molex_90325
you enter
[Your path to FreeCad]/FreeCAD_0.17.11223_x64_dev_win/FreeCAD_0.17.11223_x64_dev_win/bin/FreeCAD.exe main_generator.py

**Comment by sandhan26** [comment]
To @Misca1234   It will be great, if can do it. Html is better then pdf.

**Pull request merged**
