### PR TITLE
Invisibleize footprint & datasheet

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR sets the *Footprint* and *Datasheet* field to *Invisible* for **every** symbol in the library.

See https://github.com/KiCad/kicad-library/issues/893 and https://github.com/KiCad/kicad-library/issues/894

### CODE REVIEW

**Comment by jkriege2** [comment]
Since you're at it: Could you also go through and set the text-size of all fields to 50mil? I think there are still some with e.g. 60mil ...

Best,
JAN

**Comment by evanshultz** [comment]
Love the word "invisibleize"...

**Comment by SchrodingersGat** [comment]
All field sizes have been adjusted (there were surprisingly few that were wrong!)

**Comment by SchrodingersGat** [comment]
@jkriege2 I incorrectly rebased this instead of merging (to fix conflicts) and it has included noise from the other recently-merged PRs.

If you check the changed files you will see that only the field-size and field-visibility have been fixed.

Ready to merge?

**Comment by SchrodingersGat** [comment]
I have also changed all *IC?* RefDes to *U?* for consistency

**Comment by SchrodingersGat** [comment]
@jkriege2 ignore this one. I have cleaned it up here -> https://github.com/KiCad/kicad-library/pull/931

**Pull request closed without merging**
