### PR TITLE
Add TCMT1600/4600/4606, fix TLP290 description

### PR DESCRIPTION
**Pull request by svheymann**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Congratulations - you are PR number 1000!!

8078339330_0cd29d7238_b

Please fix conflicts introduced by merge after you made this PR :)

**Comment by svheymann** [comment]
hooraay :D

**Comment by svheymann** [comment]
whoohooo, what happend there? My commit looked a lot smaller than this conflict... I have to look into this.

**Comment by svheymann** [comment]
done, i hope i got it all.

**Comment by svheymann** [comment]
I think i had kicad open for too long. It does not re-read changed lib files even if you open a lib again so the last commit was overwritten by the cached version i guess.

**Comment by SchrodingersGat** [comment]
The large number of changes are to do with different line endings between windows and unix. We are working to fix this.

Your symbols look great, thanks for the contribution :)

**Pull request merged**
