### PR TITLE
Added LPC812M101JD20 to nxp_armmcu.

### PR DESCRIPTION
**Pull request by michalkona**
This pull request based on #339.

### CODE REVIEW

**Comment by diggit** [comment]
This symbol is for SOIC-20 package only. 
- put SOIC-20 into description instead of "SOIC package".
- fill footprint field with SOIC-20 (don't leave this field inside of symbol, you can use `some_path/checklib.py -vv  --enable-extra  -c LPC812M101JD20 --fix nxp_armmcu.lib` for recommended fields position, but you'll have to set pin 18 back to bidir.)
- footprint filter SOIC\*

**Comment by michalkona** [comment]
Done

**Comment by diggit** [comment]
Nice, just change VDDCMP type to BiDir, VDDCMP is reference for comparator and it is covered by input type well. So BiDir is correct, it can be configured as output too. Fix this and we are ready for merge.

**Comment by michalkona** [comment]
I think all is done.

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
