### PR TITLE
Added MAX15062 series of DC-DC converters

### PR DESCRIPTION
**Pull request by SchrodingersGat**
* Master component MAX15062A (3.3V output)
* Alias MAX15062B (5.0V output)
* Alias MAX15062C (adjustable output)

max

**Footprint**
New footprint has been added here: https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/17

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This part does NOT have an exposed pad so I created a new footprint to match. See linked PR.

**Comment by diggit** [comment]
You should match DFN dimensions in FP filter, I bet there are other sizes of 8pin DFNs.
Vcc should be set to Power output, it can deliver about 30mA.

**Comment by SchrodingersGat** [comment]
Done and done

**Comment by SchrodingersGat** [comment]
Hey @diggit  anything else you want done for this one?

**Comment by diggit** [comment]
@SchrodingersGat No changes needed here. Just solve conflicts and look what I wrote in #571.

**Comment by SchrodingersGat** [comment]
Fixed conflicts

**Comment by diggit** [comment]
Here we go!
Nice work you did, merging.

**Comment by diggit** [comment]
Oh, this PR reverts your PR with device description update, so please pull changes from master here. #571 will probably have same problem.

**Comment by diggit** [comment]
[This can be useful in future](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request), you won't need constant master merging to you branch.

**Comment by SchrodingersGat** [comment]
Alright, merged back in. I'll rebase in future, thanks for the advice :)

**Comment by diggit** [comment]
A am afraid you'll have to merge master back to your branch after each of these PR merges, we'll see.
Nice work you did, merging.

**Comment by SchrodingersGat** [comment]
Lesson learned

**Pull request merged**
