### PR TITLE
intel: added the 8288 bus controller chip for the 8086/88/186/188 and 8088 in maximum mode

### PR DESCRIPTION
**Pull request by nickysn**
I've added the 8288 bus controller chip to the 'intel.lib' library and also pinouts for 8088 in maximum mode (that's when you need 8288 together with 8088).

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

I looked into your PR a bit. First of all: thanks for the contribution. Second: We have some rules for contributing to this lib, the KLC (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention). There are also some Python-script to check some of these rules automatically. Looking into your PR; I got the following output:

```
checking component: 8288
  Violating Rule 3.9
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint field 'DIP-20' should be set to invisible.
    Footprint field 'DIP-20' should be of the format Library:Footprint
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin ~S1~ (3): double inversion (overline + pin type:Inverting)
    pin ~AEN~ (6): double inversion (overline + pin type:Inverting)
    pin ~MRDC~ (7): double inversion (overline + pin type:Inverting)
    pin ~AMWC~ (8): double inversion (overline + pin type:Inverting)
    pin ~MWTC~ (9): double inversion (overline + pin type:Inverting)
    pin ~IOWC~ (11): double inversion (overline + pin type:Inverting)
    pin ~AIOWC~ (12): double inversion (overline + pin type:Inverting)
    pin ~IORC~ (13): double inversion (overline + pin type:Inverting)
    pin ~INTA~ (14): double inversion (overline + pin type:Inverting)
    pin ~S2~ (18): double inversion (overline + pin type:Inverting)
    pin ~S0~ (19): double inversion (overline + pin type:Inverting)
```

So, could you change the following:
1. footprint should be `Housings_DIP:DIP-20_W7.62mm_LongPads` and the field should be hidden
2. The inverted output pins: switch them back to normal pin style and leave the overline, or remove the overline and switch them to inverted pins ... either way should be fine ;-)

Best,
JAN

**Comment by nickysn** [comment]
Ok, done. Just a side note, the 8284 chip (not contributed by me) from the intel library also has double inversion (overline + inverted pin type). Should I fix that as well?

**Comment by jkriege2** [comment]
Hi!

just go ahead and correct them. I'll have time to look into the PR again 
earliest on tuesday.

Best,
JAN

Am 28.10.2016 um 21:36 schrieb nickysn:
> Ok, done. Just a side note, the 8284 chip (not contributed by me) from
> the intel library also has double inversion (overline + inverted pin
> type). Should I fix that as well?

**Comment by jkriege2** [comment]
Hi!

thanks for the changes so far ... some stuff is left though:
- could you remove the `_LongPads` from the footprints please? The FP-field should link to the basic package and the suer can still select another option via the filters
- the `8088` and `8088_Max_Mode` still have the sold-sytle footprints (DIP-40)
- The `8088_Max_Mode` still has double-inversions
- as you're at it ... could you also set the datasheet of 8284, e.g. http://www.cpu-galaxy.at/cpu/ram%20rom%20eprom/other_intel_chips/other_intel-Dateien/D8284A_Datasheet.pdf ?

Thanks,
JAN

**Comment by nickysn** [comment]
done :)

**Comment by jkriege2** [comment]
The documentation (datasheet, description, keywords) for `8088_Min_Mode` is still missing ... Otherwise looks good to me! And could you add the width of the DIP-packages to the FPFilters? E.g. `DIP*W15.24mm*` for DIP-40 and `DIP*W7.62mm*` for DIP-18.

Thanks!
JAN

**Comment by nickysn** [comment]
ok, done :)

**Comment by jkriege2** [comment]
Thanks again for your work!

JAN

**Pull request merged**
