### PR TITLE
moving, renaming, small fixes

### PR DESCRIPTION
**Pull request by michal777**
3d models renaming

### CODE REVIEW

**Comment by CarlPoirier** [comment]
This goes along Crystals.pretty/pull/1

**Comment by CarlPoirier** [comment]
Michal, you seem to have lost the 3d models for the KXO-200 and KXO-200_LargePads in the process. I'm merging this now but please add them in another pull request and reference it here. Thanks!

**Comment by michal777** [comment]
The 3d models were incorrect so I've dropped them intentionally, sorry I haven't commented it.
I found the correct models in unused.3dshapes.

**Comment by CarlPoirier** [comment]
Thanks Michal for the update, sorry I haven't got to it earlier.

**Pull request merged**
