### PR TITLE
Add 3d model for leds

### PR DESCRIPTION
**Pull request by andres53016**
Delete wrong 3d model from Diodes_ThroughHole.3dshapes 
Delete model of led 3mm and 5mm
Add more realistic model of leds 3mm and 5mm (from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm  licensed under Creative Commons)
Add dip4 3d model for the opto (PC817)

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @andres53016, there is a big merge coming to happen, it's related to diodes/leds. Maybe would be better merge this your pull resquest after the big merge.

**Comment by andres53016** [comment]
Ok, no problem!

**Comment by CarlPoirier** [comment]
As per the CC-BY, how does the author want the credits given? I haven't seen anything about it on his website.

**Comment by andres53016** [comment]
In #135 mentioned a conversation with the author and he agree, I guess mentioning the author in the commit, it would comply with the CC-BY. For example:
"3d model for led 3mm and 5mm created by W. Lain"

**Comment by ricardocrudo** [comment]
@andres53016 the LEDs footprints got new names after the big merge that I told before. Please, could you rename your files and also check if the 3D settings are fine?

**Comment by ricardocrudo** [comment]
merged without DIP-4__300_ELL.* files, please open a new pull request to add them. Thank you.

**Pull request merged**
