### PR TITLE
Added Microchip MCP1650

### PR DESCRIPTION
**Pull request by Frankkkkk**
My first commit. I checked with checklib and no warnings on this component. I hope it's OK !

Thanks

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work ... some minor things to do:
1. pin length 100mil is enough
2. outline whould be 0.01" thick
3. I would rearrange the REFDES (top) and symbol name (bottom), i.e. mirrored ;-)
4. GND should be at bottom
5. please add the two NC pins as invisible NC-pins (run checklib with `--enable-extra`) as otherwise the pin-count filter does not work
6. move datasheet link to DCM-file (i.e. document properties) and clear datasheet field
7. I think this device fits better into dc-dc.lib ... please move it there 

... and have a look e.g. at MCP16301 for an example how your symbol could look:


Also note: We are currently discussing some clarifications of the KLC ... these should also really help with the symbol, as that is what we currently actually require ;-)
  - https://github.com/SchrodingersGat/kicad-library/wiki/KLC
  - https://github.com/KiCad/kicad-library/issues/891
  - https://github.com/KiCad/kicad-library/issues/879

Best and thanks for your contribution again!
Cheers,
JAN

**Comment by Frankkkkk** [comment]
Hi,
I modified the thing (I left-out moving it into dc-dc. Will do that in a new "clean" branch once it's all ok).

There is still a EC03 warning, I don't know what it is.

What do you think ?

Thanks,
Frank

**Comment by jkriege2** [comment]
Hi!

looks great to me ... only one thing would remain: Also if the footprint is fully specified, you need a FPFilter (so wre can match variants, e.g. `_HandSoldering` of the footprin. So please add the FPFilter `MSOP*3x3mm*Pitch0.65mm*`.

The EC03 is a bit cumbersome (IMHO), it tries to advice on the location and orientation of the labels. You can run the scripts with the option `--fix` to autofix several problems. Then you would get something like that:
2017-01-08 13_23_19-part library editor d__kicad_kicad-library-review_library_microchip lib

But either change it (if you like that style9 or leave it as it is right now. I would merge this now after you fixed the FPFilter, so could you move it to the dc-dc.lib? Also: Would you be willing to also contribute the other parts from the datasheet? That should be copy+minor mods ...

best,
JAN

**Comment by Frankkkkk** [comment]
Here we go: on dc-dc.lib and MCP1650/51/52/53

PS: how do you know how FP filter regex to use ? Is it "manual" or is there a picker ?
PS2: how do you display the blue output types on the library editor ?

Thanks,
Frank

**Comment by jkriege2** [comment]
Hi!

nice work ... I spotted one more bug: in MCP1653 you have the wrong package, it should be `Housings_SSOP:MSOP-10_3x3mm_Pitch0.5mm` and FPFilter `MSOP*3x3mm*Pitch0.5mm*`

Best,
JAN

PS: It matches all footprints that match ANY RegExp
PS2: In a current KiCAD nightly, click in the smybol editor here:
2017-01-08 16_02_56-part library editor d__kicad_kicad-library-review_library_dc-dc lib

**Comment by Frankkkkk** [comment]
Whoops, forgot to update.
Here it is ;-)

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
