### PR TITLE
Multiple symbol fixes. All components pass the rule check script

### PR DESCRIPTION
**Pull request by FabianInostroza**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work ... some things that still need changing:
1. please remove the pin-cpunt from the fpfilters, but add the housing sizes ... e.g.:
  - SOIC*W*7.5x12.8mm*Pitch1.27mm*
  - DIP*W7.62mm*
  - PDIP*W7.62mm*
  - QFN*1EP*6x6mm*Pitch0.65mm*
  - SOIC*W*7.5x17.9mm*Pitch1.27mm*
  - DIP*W15.24mm*
  - TQFP*10x10mm*Pitch0.8mm*
  - ...
2. There are still some symbols that have missing pins: could you add them as invisible NC-pins? My run of the script found these: 
  - PIC18F96J60-I/PT
  - PIC18F45K80-I/ML
  - PIC18F4455-I/ML
  - PIC18F4450-I/ML
  - PIC18F442-I/PT
  - PIC18F4331-I/PT
  - PIC18F4331-I/ML


Best,
JAN

**Comment by FabianInostroza** [comment]
Ok, I also noticed the missing pins but I didn't bother to add them. I ran the checklib.py script and it did not warn me about the missing pins, what script you ran?.

What is the rationale to not filter footprints by pin count?

**Comment by jkriege2** [comment]
... and please fix conflicts!

**Comment by jkriege2** [comment]
still some conflicts there ... could you fix them?
JAN

**Comment by FabianInostroza** [comment]
Yes, I'm pushing my merged repo

**Comment by jkriege2** [comment]
Nice work so far!

Could I ask you to add the missing pins, as indicated by this script-run:

```
D:\KiCAD\kicad-library-review\library>..\..\kicad-library-utils\schlib\checklib.py -vv --enable-extra microchip_pic18mcu.lib -p pic -rEC05
checking component: PIC18F4331-I/ML
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 13 is missing
checking component: PIC18F4331-I/PT
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 12 is missing
    Pin 13 is missing
    Pin 33 is missing
    Pin 34 is missing
checking component: PIC18F442-I/PT
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 12 is missing
    Pin 13 is missing
    Pin 33 is missing
    Pin 34 is missing
checking component: PIC18F4450-I/ML
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 13 is missing
checking component: PIC18F4455-I/ML
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 13 is missing
checking component: PIC18F45K80-I/ML
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 12 is missing
    Pin 13 is missing
    Pin 33 is missing
    Pin 34 is missing
checking component: PIC18F96J60-I/PT
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 9 is missing
```

Otherwise this can be merged ;-)
JAN

**Comment by FabianInostroza** [comment]
It's done!

**Comment by jkriege2** [comment]
nice work!
JAN

**Pull request merged**
