### PR TITLE
swaping A/K diodes pins + adding new 3d packages

### PR DESCRIPTION
**Pull request by ricardocrudo**

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Ricardo,

do you plan on putting colors on your 3D models? They are all black, at least on my end.

**Comment by ricardocrudo** [comment]
@CarlPoirier 
1. I got the 3d models from manufacturer website and I did the conversion to wrl using freecad. They get black after the conversion. I'll try fix this.

3.
Connectors: KiCad/Connect.pretty#16
Relay:  KiCad/Relays_ThroughHole.pretty#4

**Comment by CarlPoirier** [comment]
Well, gray is at least better than black. I'm ready to merge this at the same time as Diodes_SMD.pretty/pull/6 and Diodes_ThroughHole.pretty/pull/6.

**Comment by CarlPoirier** [comment]
I merged the aforementioned pull requests. Sorry for not getting to them earlier, I did not see you had updated them since my last comments.

**Comment by ricardocrudo** [comment]
Hello @CarlPoirier
I fixed the Diodes_*.pretty issues and also create a new pull request: KiCad/LEDs.pretty#5. I was forgetting of this one.
I removed the LEDs from Diodes_ThroughHole because they were duplicated with LEDs.pretty. 
Thanks for merging and checking.

**Pull request merged**
