### PR TITLE
Fix MSP430G2230 symbol

### PR DESCRIPTION
**Pull request by welterde**
Had the wrong pin number mapping and footprint.

### CODE REVIEW

**Comment by Fat-Zer** [comment]
Just wondering, why you changed the datasheet link?
Note that it redirects to the same file as before...

**Comment by welterde** [comment]
Indeed. So no real reason other than perhaps it looks a teeny bit nicer.
But I can remove that change again if wanted.

**Comment by Fat-Zer** [comment]
I've only noticed you replaced "www" with "focus" subdomain... I supposed that was intentionally so I wondered if there goes some magic out-there on ti.com's side... nevermind...

**Comment by ricardocrudo** [comment]
Thank you.

**Pull request merged**
