### PR TITLE
Add some 3D models.

### PR DESCRIPTION
**Pull request by jbdwi**
Pls. advice !

### CODE REVIEW

**Comment by michal777** [comment]
To add footprints with 3d models please make a pull request to one or more .pretty repositories and pull request to kicad-library with 3d models named the same as added footprints, placed in folders named the same as .pretty repository (in packages3d). Only wings and wrl files corresponding with pull requests to .pretty repositories should be in the pull request to kicad-library.

In .kicad_mod footprints files the path to the 3d model should be LibraryName/FootprintName
So instead of:
D:/KICADLIB_JBD/kicad-library/modules/packages3d/Terminal_Block/PowerTerminal_CarAudio_3pin_11_Up.wrl
should be:
Terminal_Blocks.pretty/PowerTerminal_CarAudio_3pin_11_Up.wrl

**Comment by CarlPoirier** [comment]
Just to make it more clear, we need the matching footprint to first and foremost allow the use of the 3D model in KiCad but also to validate the 3D model.

For example, the diode here:

https://github.com/KiCad/Diodes_SMD.pretty/blob/master/DO-214AB.kicad_mod

It links with the footprint:

https://github.com/KiCad/kicad-library/blob/master/modules/packages3d/Diodes_SMD.3dshapes/DO-214AB.wrl

Don't give up, you're almoooost there!

**Comment by CarlPoirier** [comment]
Also, make sure you check beforehand if the 3D model already exists. For example you created a vertical TO-247, however there is one already here:

https://github.com/KiCad/kicad-library/tree/master/modules/packages3d/Diodes_ThroughHole.3dshapes

Are you able to visualize the existing footprints and 3D models directly in KiCad?

**Comment by CarlPoirier** [comment]
Hi Josef,

Let me recap. Michal made a small mistake in the email he sent us. By the way, please reply here on Github so that other librarians and contributors can see.

The footprint :
Terminal_Blocks.pretty/PowerTerminal_CarAudio_3pin_11_Up.kicad_mod
The 3D model :
kicad-library/modules/packages3d/Terminal_Blocks.3dshapes/PowerTerminal_CarAudio_3pin_11_Up.wrl

On Github, the repositories are Terminal_Blocks.pretty and kicad-library. Both already exist. What you will need to create are the files PowerTerminal_CarAudio_3pin_11_Up.kicad_mod and PowerTerminal_CarAudio_3pin_11_Up.wrl. For the latter, you will need to create the Terminal_Blocks.3dshapes directory as well.

As for the paths in the files, what Michal meant is that you need to use relative paths such as what I just wrote above. If your files contain absolute paths from your setup, they will not work except on your computer.

I hope this is clearer.

Carl

**Comment by CarlPoirier** [comment]
Hi Josef, regarding what you committed in your fork (https://github.com/jbdwi/kicad-library/tree/master/modules/packages3d), you aaalmost got it right. Here is what you need to adjust.

1. The "Terminal Block" folder should be named exactly the same as the .pretty folder in kicad-library, except for the extension. So it should be "Terminal_Blocks.3dshapes". It's important you match this exactly.

2. The "Transistor" folder is more tricky. If you go to the Github webpage for your fork (https://github.com/jbdwi/kicad-library/tree/master/modules/packages3d), it says it is 44 commits behind KiCad:master. This means some other contributions have been done since the time you forked kicad-library. You have to sync your fork with the original repo. There are instructions to do so (https://help.github.com/articles/syncing-a-fork/). If it seems to complicated, you can create a new fork which will be up to date and simply reapply your changes.

In an updated kicad-library (https://github.com/KiCad/kicad-library/tree/master/modules/packages3d), you will see that we have some new folders with one of them being TO_SOT_Packages_SMD.3dshapes. There is thus no need to create a new folder for transisters, as this one contains the TO-263 package already.

Maybe you should start with adding 3D models for existing footprints instead, as it is simpler. There are plenty of them which don't have 3D models yet. The only thing you would have to do is add the .wrl and .wings file in the right .3dshapes folder as well as add the path to the 3d model in the already existing .kicad_mod file.

**Comment by jbdwi** [comment]
Hi Carl,
I can not rename the folder "Terminal Block" to "Terminals_Block.3dshapes".

**Comment by jbdwi** [comment]
Carl,
For testing, I put TOP3_Ver in "TO_SOT_Packages_THT.pretty" ... with .wrl and .wings in TO_SOT_Packages_THT.3dshapes.

Hope this correct. Pls advise.

**Comment by CarlPoirier** [comment]
Hi Josef,

You got your pull requests just right. Your 3D models look awesome as well. What I suggest now is you close this pull request and reopen a new one containing only the needed files and changes. For example, we don't need the hello file and the .jpg files. Although for the latter, you can paste them directly in a comment to your pull request, such as here, and it will allow the librarians to have a quick general idea.

You can divide your pull requests in smaller chunks as well, so even though you have some mistakes in one, we will be able to accept the others. For example. you could do one pull request containing only packages for existing footprints such as TO-12_TO-33_4Pin.

**Comment by jbdwi** [comment]
Hi Carl,
I d try to add 3dmodels TO-12_TO-33_4Pin  to  folder TO_SOT_Packages_THT.3dshapes  , commited it ...  then Syncing to the master .... and always fail and got message : FAILS TO SYNC THIS BRANCH.

I use WIndows Github Desktop, since I do not familiar with text command. What's going on ?

**Comment by CarlPoirier** [comment]
You committed your 3d model to your branch as you should in this commit:

https://github.com/jbdwi/kicad-library/commit/bcf37ae6edf87ff4b74fd917da94aba41d922924

I never used the Windows Github desktop, but this "sync to master" command might actually be for pushing your changes to the master kicad-library branch. In this case, you don't have the rights so it fails. They will instead be merged once one librarian approves your pull request.

Once you committed your models as in the commit above, your pull request is automatically updated if it's already open. You don't need to do anything else.

**Comment by jbdwi** [comment]
// Once you committed your models as in the commit above, your pull request is automatically updated if it's already open.


I dont know it's already open or closed. How to know, where is this information ?  { Sorry with my 'stupid' question. }

**Comment by CarlPoirier** [comment]
Your pull request is opened once you have done this (disregard the section
"Changing the branch range and destination repository") :

https://help.github.com/articles/using-pull-requests/

On Tue, Sep 29, 2015 at 11:13 PM, Josef B. Dwiyono <notifications@github.com

**Pull request closed without merging**
