### PR TITLE
add Ads1243 ADC 24bits 8channels

### PR DESCRIPTION
**Pull request by penoud**
I check the componnent with the tool named checklib.py

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work. I spotted a bug though (you could run our chechlib.py-scripts with `--enable-extra`):
The GND pin should be 15 and not 9!

Also the footprint field should be set to `Housings_SSOP:TSSOP-20_4.4x6.5mm_Pitch0.65mm` and the FPFilter to `TSSOP*4.4x6.5mm*Pitch0.65mm*`

Best,
JAN

PS: We're currently discussing an improved version (more explanations/examples) of our KLCs: https://github.com/SchrodingersGat/kicad-library/wiki/KLC and the discussion here: https://github.com/KiCad/kicad-library/issues/879

**Comment by penoud** [comment]
I updated as your requested. Sorry for GND pin misnumbering.

**Comment by jkriege2** [comment]
??? for some reason you removed the .lib-file from this PR???

In the description TSSOP-20 is enough ;-) but the full housing-path should be set in the foorprint field!

best,
JAN

**Comment by jkriege2** [comment]
??? for some reason you removed the .lib-file from this PR???

In the description TSSOP-20 is enough ;-) but the full housing-path should be set in the foorprint field!

best,
JAN

**Comment by penoud** [comment]
Sorry, I did a wrong manipulation with Git. Now I understand what you mean with the FP field. I hope this is better.

**Comment by jkriege2** [comment]
OK, could have explained better ;-)

... one thing is left: the footprint field should be hidden ... please still change that, then I can merge!

Best, JAN

**Comment by penoud** [comment]
I changed the footprint to invisible field.

**Comment by jkriege2** [comment]
Nice work!

Thanks,
JAN

**Pull request merged**
