### PR TITLE
adding HCPL-316J

### PR DESCRIPTION
**Pull request by Anastien**
this is a common gate drive ic.

### CODE REVIEW

**Comment by diggit** [comment]
Needed changes:
- pin length 150mil is enough (don't forget to realign them to 100mil grid)
- make symbol narrower
- clear Datasheet field in symbol
- simplify FP field to SO-16
- change outline thickness to 0.010"
- add FP filter SO\*
- add optocoupler to keywords
- improve description (look what other optocouplers have...)

**Comment by diggit** [comment]
- sorry about FP field, use full format `Housings_SOIC:SOIC-16_7.5x10.3mm_Pitch1.27mm`, set invisible a place below symbol
- set FP filter `SOIC-*_7.5x10.3mm_Pitch1.27mm*`
- center symbol at least horizontaly
- SPICE filed - link does not point to freely available model, please remove
- shift GND1 and Vin- down, near to Vled1-

**Comment by Anastien** [comment]
regarding this improvement :
shift GND1 and Vin- down, near to Vled1-
I think you want them to be close together as they all connect to GND, but this is only true in certain configurations, Vled- is always grounded.

**Comment by diggit** [comment]
Yes, it was due to common connection to ground.
V<sub>in1</sub> - ok
V<sub>LED1-</sub> and GND1 are grounded always. I think, at least these 2 could be near to each other.

Set rectangle fill to BG.
Use double dashed lines to indicate electric separation. Like you can see at ISO7320C, and other isolators.

**Comment by Anastien** [comment]
I thought I should keep the ordering of the pins as in the layout, as it is not a block.
anyway I have done the reordering, and the dashed line.

**Comment by diggit** [comment]
Thanks.
Set those dashed lines thickness to minimum (0), it is not outline.

**Comment by Anastien** [comment]
you can review it now.

**Comment by diggit** [comment]
Can you merge changes from upstream back to your branch? Now your PR deletes TLP250 and HCPL3120 what, I believe, you didn't intend to.
Sorry for late reply, busy month.

**Comment by Anastien** [comment]
I've resorted the missing components manually, I don't remember how I lost them.

**Comment by hackscribble** [comment]
Hi @Anastien 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
