### PR TITLE
Ref designator update for relays library

### PR DESCRIPTION
**Pull request by n0dyjeff**
Changed OMRON G5Q series reference designators to IEEE standard "K"

### CODE REVIEW

**Comment by poeschlr** [comment]
Would it be possible for you to also fix the KLC errors of this symbol?
(Fill out the symbol documentation and set the datatsheet field to invisible)

**Comment by n0dyjeff** [comment]
Took me a while to figure out how to fill out the symbol documentation, but I think I've got it. I'm going to close this pull request and open another because I'm not too confident in my github skills.

**Comment by poeschlr** [comment]
You just need to push to the same branch to get this pull request updated. (This is the reason why you should open a separate branch per pull request.)

If you want to learn about git, i could highly recommend this (1 hour long) video:
https://www.youtube.com/watch?v=ZDR433b0HJY 

There are also quite good tutorials on the atlasin webside:
https://www.atlassian.com/git/tutorials

think this explains the github workflow:
https://www.atlassian.com/git/tutorials/comparing-workflows#forking-workflow

**Comment by poeschlr** [comment]
To Long To read version:
Very first step only needed for an already existing pull request:
copy the files from this pull request somewhere where you find them again. (outside the repo!)

First add the official repo as upstream repo to your local repository.
> git remote add upstream https://github.com/KiCad/kicad-library.git

after that get the newest master commit:
> git fetch upstream
git checkout upstream master

create your new branch:
> git checkout -b [meaningful branch name]

make your changes (copy your current files into your repo and make the klc changes.) If you are done:
> git add -u
git commit -m "meaningful commit message"

create a pull request and add a screenshotof the new symbol as well as a link to the datasheet  to the description of the pull request.

**Pull request closed without merging**
