### PR TITLE
Ds2745 u

### PR DESCRIPTION
**Pull request by Misca1234**
Maxim DS2745U

https://datasheets.maximintegrated.com/en/ds/DS2745.pdf

Travis complain about VIN, it is not a power pin but it is an input pin

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Travis complain about VIN, it is not a power pin but it is an input pin

**Comment by jkriege2** [comment]
Hi!

nice work again.
- Please move this to battery_Management.lib
- Also the PFIlter should be `TSSOP*3x3mm*Pitch0.65mm*` (i.e. don't wildcard out the `x` in `3x3mm` + wildcard at the start is not needed).

Best,
JAN

**Comment by Misca1234** [comment]
Travis complain about VIN, it is not a power pin but it is an input pin

**Comment by jkriege2** [comment]
Hi!

two last changes:
1. please add `, TSSOP-8` to the description.
2. please revert the changes to maxim.dcm in your PR.

Then I can merge!

JAN

**Comment by Misca1234** [comment]
Fixed

**Comment by Misca1234** [comment]
Travis complain about VIN, it is not a power pin but it is an input pin

**Comment by jkriege2** [comment]
nice work!

JAN

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
