### PR TITLE
Symbol and footprint fixes for 2x accelerometer ICs

### PR DESCRIPTION
**Pull request by SchrodingersGat**
I have fixed the footprint filters and added default footprints for:
LIS2DH
LIS2331HH

Also I have consolidated symbols for LIS2DH and LIS331HH such that they are (almost) drop-in replaceable in a schematic.

### CODE REVIEW

**Comment by diggit** [comment]
Nice fixes!
Please polish descriptions and keyword to be uniform (easier comparison):
- merge *3-Axis...* and *3 axis...* to single format, *2/4/8/16g*  and *6g/12g/24g* (single g is enough) as well as the rest, you know what I mean...
- add *MEMS*, *SPI*, *3-axis* to keywords accordingly

Other accelerometers might be subject for some future PR. :)

**Comment by SchrodingersGat** [comment]
@diggit I have improved descriptions and also updated the fp filters as per our previous discussions for other PRs

**Comment by diggit** [comment]
SDA/SDI pin should be bidir
LIS2DH has Reserved pins named *Res*.
LIS331HH has Reserved pins called VCC/GND according to their proper connection.
Unify this, VCC/GND names are better.

**Comment by SchrodingersGat** [comment]
Ugh, oops. The ol' delete-and-undelete. I have made the fixes and also improved pin names for the I2C/SPI interface.

**Comment by diggit** [comment]
At first, [I was like...](http://cdn.makeagif.com/media/9-06-2015/rQY9Hx.gif)
Please swap pin name order for SDA/SDI -> SDI/SDA, same thing for SCL/SPC, to have same interface pins in 1 column.

**Comment by SchrodingersGat** [comment]
puppt mstr

**Comment by SchrodingersGat** [comment]
PUPPT

**Comment by diggit** [comment]
Do you feel like puppet? :)
You made it simpler by swapping names of remaining 2 purpose pin. SPI now does not align with ~CS, but ok...
Nice work you did, merging.

**Pull request merged**
