### PR TITLE
rfcom: GPS modules NEO-7N/M.

### PR DESCRIPTION
**Pull request by Krakonos**
I propose creating it's own library, as I haven't found anything GPS-related. Feel free to suggest existing library, which is suitable for these modules.

### CODE REVIEW

**Comment by pointhi** [comment]
I would propose ```rfcom.lib```, which should contain in my opintion all rf related modules like bluetooth, wlan, gsm, gps,...

**Comment by Krakonos** [comment]
Allright. Also, do I need to worry about the jenkins problems? If so, I would need permissions to the Jenkins (I created user Krakonos, the same as on github).

**Comment by wolfgangbremen** [comment]
Hello,
isn't there a better name for the library than rfcom? I (and possibly many others) know what WLAN, GPS, ... are, but what stands RF for? I assume, COM stands for COMmunication?

**Comment by Krakonos** [comment]
Done. I've moved the modules into rfcom, and updated the branch.

**Comment by Krakonos** [comment]
I guess RF is Radio Frequency. GPS actually fits in, and I considered it initially, before I proposed new library, as it only contained two way communications (bluetooth, nrf24l01, some others).

**Comment by keruseykaryu** [comment]
@Krakonos "I've moved the modules into rfcom, and updated the branch."
But still have VCC and GND as BiDir pins. 

Guys, you're commiting **elementary** mistakes in your symbols!

**Comment by Krakonos** [comment]
Fixed that, thanks.

**Comment by ricardocrudo** [comment]
@Krakonos please check your symbols using checklib script. https://github.com/KiCad/kicad-library-utils/tree/master/schlib

**Comment by hackscribble** [comment]
Hi @Krakonos 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
