### PR TITLE
Ea e diptft43 a

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIPTFT43-A (and it's alias EA eDIPTFT43-ATP and EA eDIPTFT43-ATS)

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/ediptft43-ae.pdf

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1494

pretty push branch is 
https://github.com/KiCad/Displays.pretty/pull/26

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/109

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/36

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

**Comment by Misca1234** [comment]
I will remove the aliases as requested on the other displays
Shall i create a unique symbol for each of the different databusses?
That is 
EA eDIPTFT43-A-RS232
EA eDIPTFT43-A-SPI
EA eDIPTFT43-A-I2C

Or should I rename the pins to "carry" all their different functionality ?

**Comment by Misca1234** [comment]
Added the ATC variant on request in 
https://github.com/KiCad/kicad-library/pull/1494


bild

**Comment by Misca1234** [comment]
For all my displays that have multiple type of interfaces, such as RS-232, I2C and SPI, how do we want them?

Shall i create a unique symbol for each of the different databusses?
That is
EA eDIPTFT43-A-RS232
EA eDIPTFT43-A-SPI
EA eDIPTFT43-A-I2C

Or should I rename the pins to "carry" all their different functionality ?

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
