### PR TITLE
added 6418 Subminiature Pentode

### PR DESCRIPTION
**Pull request by jkriege2**
valvemini

### CODE REVIEW

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: CK6418
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
  Violating Rule 3.2
    For black-box symbols, pins have a length of 100mils. Large pin numbers can be accommodated by
    incrementing the width in steps of 50mil.
  Violating Rule 3.6
    Field text uses a common size of 50mils.
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
  Violating Rule 3.9
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
Components Added: 1
+ CK6418
```

**Comment by jkriege2** [comment]
I hope I fixed everything ... I also pushed a new footprint to Valves.pretty for this devoce (see https://github.com/KiCad/Valves.pretty/pull/1).
Best,
JAN

**Comment by jkriege2** [comment]
Here's a screenshot of the 3D symbol that I just added for this type of valve:

**Comment by jkriege2** [comment]
cleaned-up version is available here: https://github.com/KiCad/kicad-library/pull/724

**Pull request closed without merging**
