### PR TITLE
Add Maxim DS3231MZ RTC chip

### PR DESCRIPTION
**Pull request by aurel32**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work. some minor changes please:
1. FPFilter should be `SOIC*3.9x4.9mm*Pitch1.27mm*`
2. reduce pin-length to 100mil (enough for 1-digit pincounts

Otherwise looks good!
JAN

**Comment by aurel32** [comment]
Thanks for the review. I have just done the changes you suggested.

**Comment by jkriege2** [comment]
Hi1

nice. One small thing left to change: Please remove the datasheet from the datasheet field (that should be empty) F3 in teh .lib-file. the datasheet is already stored in the component properties (.cmp-file).

Then I will merge!

JAN

**Comment by aurel32** [comment]
Thanks, I have just removed the link from the F3 field.

**Comment by jkriege2** [comment]
thanks for all the work!
JAN

**Pull request merged**
