### PR TITLE
Added MAX4080 unidirectional current shunt monitor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://datasheets.maximintegrated.com/en/ds/MAX4080-MAX4081.pdf

This PR adds the MAX4080 current shunt monitor and its aliases

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Bump @ashtonchase @diggit

**Comment by diggit** [comment]
Can you make MAX4081* drop-in replace compatible? Eg. like AD82*, you can share their design/pin layout..
Also please unify descriprions of MAX408*

**Comment by SchrodingersGat** [comment]
Done - lmk what you think

**Comment by diggit** [comment]
Good.
Hmm, someone merged changes made by old KiCad, damn those double spaces.
Nice work you did, merging.

**Pull request merged**
