### PR TITLE
Add symbol for LTR-303ALS-01 ambient light sensor.

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet](http://optoelectronics.liteon.com/upload/download/DS86-2013-0004/LTR-303ALS-01_DS_V1.pdf).

Meant to be used with [this footprint](https://github.com/KiCad/Opto-Devices.pretty/pull/20).

ltr-303als-01

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I like the symbol but I don't think that the footprint should have the function in the name.

Please change the footprint name to  simply `LTR-303ALS-01`, then update the symbol association too.

thanks

**Comment by antoniovazquezblanco** [comment]
Sorry to start an out of topic conversation here but, do anyone of you guys have seen the lux formula for any of the LTR light sensors?

Thanks

**Comment by ppelleti** [comment]
> Please change the footprint name to simply `LTR-303ALS-01`, then update the symbol association too.

@SchrodingersGat, I changed it to `Lite-On_LTR-303ALS-01`, since you suggested prefixing the manufacturer name in the other thread.

@antoniovazquezblanco, no I haven't seen the lux formula.  The datasheet says the formula is in Appendix A, but the datasheet doesn't have an Appendix A.

**Comment by antoniovazquezblanco** [comment]
@ppelleti yeah, that is what I have found in several of their datasheets. The thing is that I have not seen that formula in any of them. I once tried to contact with them but no answer to my email. What formula do you use?

**Comment by ppelleti** [comment]
@antoniovazquezblanco I haven't gotten that far yet.  This is my first time using this part, and I'm still working on laying out the PCB.  I haven't started thinking about the software yet.

**Comment by antoniovazquezblanco** [comment]
Thanks @ppelleti. If you ever get a hand of that formula please share ;).

**Comment by SchrodingersGat** [comment]
Thanks @ppelleti  :)

**Pull request merged**
