### PR TITLE
added Analog Devices ADP5054 quad buck regulator

### PR DESCRIPTION
**Pull request by ashtonchase**
[Datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/ADP5054.pdf)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @ashtonchase very nice looking symbol. A couple of suggestions:

* Change symbol shape width from 0.012" to 0.01" as per "standard"
* Change FP filter to TQFP*48*1EP* to match more generically
* Remove the _1 _2 _3 suffices to match the naming conventions of the datasheet. The pins that are labelled the same in the datasheet should be labelled the same in the symbol.

cheers

**Comment by SchrodingersGat** [comment]
Thanks for changing the pin names! I realise that I misled you regarding the FP filter because the extra * characters were removed from my comment, and I didn't realize...

The FP filter should be:

TQFP * 48 * 1EP * 

(But without the space characters)

**Comment by SchrodingersGat** [comment]
Ha, sorry once again @ashtonchase , please remove the space characters from the fp filter.

I only added them in because the github comment formatting stuffs them up.

**Comment by ashtonchase** [comment]
Tried with  `TQFP*48*1EP`  and the footprint didn't show up. So I changed it to `TQFP-48-1EP` and it worked.

**Comment by SchrodingersGat** [comment]
@ashtonchase  are you certain? I get the opposite results, see below:

1. *Filter does not work*
b

2. *Filter works*
a

**Comment by ashtonchase** [comment]
I haven't forgotten this, just haven't had time to complete it. Thanks..

**Comment by ashtonchase** [comment]
@SchrodingersGat. I've finally updated this.

**Comment by SchrodingersGat** [comment]
Thanks for your contribution :)

**Pull request merged**
