### PR TITLE
add max1248 / max1249

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This is my first self made schematic, I hope it is not too bad. I am especially unsure about how to link the footprints correctly. I will gladly adjust it based on comments if necessary.

### CODE REVIEW

**Comment by diggit** [comment]
It looks ok, maybe unnecessarily too wide, but ok.

IDK how strictly are extended checks required...
```
checking component: MAX1248
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
```

But, I am not maintainer. I'm waiting for my PR to get merged too. Just walking around...

**Comment by lorem-ipsum** [comment]
Thanks for your comment. You are right, it is quite wide. I made it square for no real reason. Probably better to decrease that a bit.

Were can I found information on the extended checks? I found the KLC, but the extended checks aren't part of it. And checklib sadly is very unspecific about the errors it encounters.

**Comment by ricardocrudo** [comment]
@lorem-ipsum Indeed extended checks isn't part of KLC that's why they aren't enable by default. However, some of them (like EC04) are very common to see in the symbols. To enable this checking use option `--enable-extra` and to improve the error feedback use verbose flag: `-v` or `-vv`. But, unfortunately, some checking rules, doesn't implement verbose yet.

**Comment by lorem-ipsum** [comment]
I now reduced the width of the box and adjusted the border width. I don't really get what EC03 is trying to tell me, even with maximal verbosity I don't get a better message.

**Comment by ricardocrudo** [comment]
@lorem-ipsum Patrik has done a great improvement this weekend in the verbosity of the messages, please give a pull on your kicad-library-utils clone. Anyway, EC03 can be ignored.

**Comment by diggit** [comment]
MAX1249 is missing documentation. They are almost identical, so just use "copy document from parent" and append info about difference into description.
This is last thing to do, before merging.

**Comment by lorem-ipsum** [comment]
I added the documentation and stated the difference in the description of the MAX1248

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
