### PR TITLE
Added MCP23XXX IO Expanders (SPI & I2C)

### PR DESCRIPTION
**Pull request by jkriege2**
- Symbols conform to KLC
- added: MCP23016, MCP23S16, MCP20317, MCP23008, MCP23S08 including special symbols MCP23X08_SSOP for SSOP packages with different pinout

mcp23

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 this is a great addition. There are a couple of small things that will be revealed with the --enable-extra flag in the KLC check script

`checklib.py microchip.lib --enable-extra -vv -p=MCP23` will check all these.

**Comment by jkriege2** [comment]
Oh,  nice option ... I used it together with --fix and checked in the results (look good ;-)

**Comment by SchrodingersGat** [comment]
Great, nice work on this one :)

**Comment by wolfgangbremen** [comment]
Did nobody notice the typo in the log-message?
   added: MCP23016, MCP23S16, MCP20317, 
a) There is no MCP20317. It is the MCP23017. In the library the value is correct.
b) Library contains the MCP23S17, too

**Pull request merged**
