### PR TITLE
Added MCP73831/OT to regul.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Single cell lithium (ion, polymer) charge management IC
SOT23-5 package
http://www.microchip.com/wwwproducts/Devices.aspx?dDocName=en024903

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
What is the difference between regul.lib and dc-dc.lib? dc-dc seems much more KLC compliant, is regul.lib scheduled for replacement?

What's the best lib for battery charging components?

**Comment by ricardocrudo** [comment]
> What is the difference between regul.lib and dc-dc.lib? dc-dc seems much more KLC compliant, is regul.lib scheduled for replacement?

I don't know. I newer here than this libraries. Probably @CarlPoirier knows.

**Comment by keruseykaryu** [comment]
Because I've made up this partitioning let me answer. The regul.lib was designed for linear voltage/current regulator. The dc-dc.lib was designed for low voltage switching regulators (buck, boost, etc.). The ac-dc.lib was designed for SMPS controllers.

**Comment by ricardocrudo** [comment]
Hi @SchrodingersGat 

Could you please do some adjustments?

**MCP73831/OT:**
* make pin name position offset shorter, like 20
* arrange inputs on left side and output on right side
* if possible, place vdd on top and vss on bottom
* remove package information from description
* I guess you can *charge* from keywords *charger* seems enough. also I would remove *management*, it's quite generic word that does not say too much about the device function

**bq76940:**
* even though datasheet use small letters, part number uses capital, so please, use capital letters to symbol name
* arrange inputs on left side and output on right side
* fix pins electrical type
* remove balance *monitor front end analog* from keywords (maybe add *AFE* )
* add i2c interface to description
* I would go to keep 21,22,23 pins placed along the box, even them are not visible

**Comment by SchrodingersGat** [comment]
Adjustments have been made as suggested.

**Comment by SchrodingersGat** [comment]
Should we make a new library for battery related devices?

**Comment by SchrodingersGat** [comment]
@ricardocrudo All conflicts with the master branch have been fixed. This pull request also moves towards KLC compliance for a lot of the parts already in regul.lib (other than the new ones that I have added)

**Comment by ricardocrudo** [comment]
test this please

**Comment by SchrodingersGat** [comment]
@ricardocrudo I have moved all the battery-related components from regul.lib to batt.lib

See - https://github.com/KiCad/kicad-library/pull/465

**Comment by SchrodingersGat** [comment]
I shall resubmit this as a new PR as it's getting too complicated.

**Pull request closed without merging**
