### PR TITLE
[enh] add ADNS-9800 Laser Gaming Sensor

### PR DESCRIPTION
**Pull request by pointhi**
datasheet: http://www.pixart.com.tw/upload/ADNS-9800%20DS_S_V1.0_20130514144352.pdf

footprint: https://github.com/KiCad/Opto-Devices.pretty/pull/2

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @pointhi. please move this symbol to sensors.lib. Also, please, improve the pins arrangement. Page 6 of datasheet has a very good example.

**Comment by pointhi** [comment]
ok, I applied the improvements as mentioned

**Comment by pointhi** [comment]
test this please

**Comment by ricardocrudo** [comment]
test this please

**Comment by pointhi** [comment]
test this please

**Comment by CarlPoirier** [comment]
Hi Thomas, I would like to have a look at this pull request. Can you fix the conflicts?

Thanks

**Comment by pointhi** [comment]
@CarlPoirier I fixed the conflicts

**Comment by CarlPoirier** [comment]
Hi @pointhi,

Please add the missing ENDDRAW, ENDDEF as well as fill the description, keywords and documentation file name. Otherwise it's good to go.

**Comment by pointhi** [comment]
@CarlPoirier thanks.
I'm likely made some errors when merging my changes with master.

**Comment by SchrodingersGat** [comment]
@pointhi have these symbols already been integrated into opto.lib?

If so, we should close this PR. Thanks :)

**Comment by SchrodingersGat** [comment]
@pointhi ok to close?

**Comment by SchrodingersGat** [comment]
Bump @pointhi

**Comment by SchrodingersGat** [comment]
Closing due to inactivity.

**Pull request closed without merging**
