### PR TITLE
Old motorola

### PR DESCRIPTION
**Pull request by Misca1234**
Re push of, of the seemingly abandoned push
https://github.com/KiCad/kicad-library/pull/895

It consist of a bunch of hopeless outdated and obsolete Motorola parts, 
I guess they was pushed for nostalgic reasons

I put them all in motoroloa.lib, 
Should I have created a MCU_Motorola.lib for the CPU's ?

I have not checked the pins, I just copied them from the older push

MC6800
ALIASES MC68A00 MC68B00
http://pdf.datasheetcatalog.com/datasheet/motorola/MC68A00L.pdf

MC6809
ALIASES MC68A09 MC68B09
http://pdf.datasheetcatalog.com/datasheet/motorola/MC68A00L.pdf

MC6809E
ALIASES MC68A09E MC68B09E
http://pdf.datasheetcatalog.com/datasheet/motorola/MC68B09S.pdf

MC6840
ALIAS MC68A40 MC68B40
http://pdf.datasheetcatalog.com/datasheet/motorola/MC6840.pdf

MC6843
http://www.datasheetarchive.com/pdf/download.php?id=355f4f5379c550317997643252fd5cac1bb08e&type=M&query=MC6843P

MC6844
ALIAS MC68A44 MC68B44
http://pdf.datasheetcatalog.com/datasheets/560/501527_DS.pdf

MC6845
ALIAS MC68A45 MC68B45
http://pdf.datasheetcatalog.com/datasheet_pdf/motorola/MC6845L_and_MC6845P.pdf

MC6850
ALIAS MC68A50 MC68B50
http://pdf.datasheetcatalog.com/datasheet/motorola/MC6850.pdf

bild

bild

bild

bild

bild

bild

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Gosh, kicad have affect a lot other symbols as well, let me have a look at them

**Comment by Misca1234** [comment]
MC68332
Added propertiy information
Fixed VSS and VDD pin lenght and type
Added FP and dedicated footprint

**Comment by Misca1234** [comment]
The motorola.lib is really in a mess

**Comment by Misca1234** [comment]
It seems that kicad have changed MPC8641D and P4080-BGA1295 on its own, 
shall we let them pass, they have A LOT of problems or shall we skip this push ?

**Comment by SchrodingersGat** [comment]
Yep I'm happy to merge this as is. Any improvement is welcome. Perhaps we will have time to revisit this library - we will need to work out where all the parts go in the v5 rearrangement.

**Pull request merged**
