### PR TITLE
Add LTC1044 to dc-dc.lib

### PR DESCRIPTION
**Pull request by kinichiro**
- add Switched Capacitor Voltage Converter LTC1044 to dc-dc.lib
- alias LT1054, MAX1044 and ICL7660
- KLC compliance

Here is a image for components.
ltc1044
Thanks.

### CODE REVIEW

**Comment by diggit** [comment]
Please rearrange ping in more sensible way. You are not limited to package's pin arrangement.

- CAP+ and CAP- are mostly tied together through capacitor, they should be next to each other.
- GND and LV are mostly connected to ground and you can find ground on bottom of schematics (most common)
- rule 3.5 might help `3.5.  Whenever possible, inputs are on the left and outputs are on the right.`

**Comment by kinichiro** [comment]
Hi,
Thanks for your advice. I rearranged pins.

- V+(8) is main input and VOUT(5) is main output for this component.
- BOOST(1) should be placed near V+(8).
- OSC(7) is oscillator input, place left side.
- CAP+(2) and CAP-(4) should be placed side by side.
- GND(3) should be placed bottom and LV(6) should be near GND(3).

Here is a image for components.
ltc1044-2
Could you take a look at this, please ?
Thanks.

**Comment by diggit** [comment]
Good progress.
 I am probably nitpicking, but you can tweak it little bit more.
Shove _VOUT bit higher_ (like V+) and place _CAP+ and CAP- on right side_. Then you can split them with 300mil space which matches length of capacitor (and it is placed between CAP+ and CAP- almost all times). Then _LV can be placed on left side_, somewhere CAP+ is now. These changes will eliminate unnecessary wiring around symbol.
Maybe put GND where CAP- is now? IDK, I'll leave it up to you. You can try it in real schematic.

I know, 1 symbol and such a long process. But people will benefit from it in future.

I'll be happy to merge it soon afterwards.

**Comment by kinichiro** [comment]
Hi,

For LTC1044, I fixed issues.
- move up VOUT
- move CAP+ and CAP- to right side and gave them a space for CP or CP1
- mv LV to left side where once CAP+ was thre
- left GND on bottom. I feel it is good.

BTW, I found that alias LT1054 has 2 different pin names.
pin 1 is "FB/SHDN" and pin 6 is "VREF".
I was confused since datasheet said, 
"The LT1054 is pin compatible with previous converters such the LTC1044/ICL7660."
So, I added LT1054 as new component.

I read datasheet and noticed pin 1 "FB/SHDN" is same as pin 1 "BOOST" of LTC1044.
pin 6 "VREF" is reference output and a bit differ with pin 6 "LV" of LTC1044.
But VREF(6) seems to be used with OSC(7) or FB/SHDN(1) so often in datasheet sample application circuit.
Then, I decided to put pin 6 on left side near by OSC(7).

Here is a image for current progress.
ltc1044-3
Sorry for additional new component.
Thanks.

**Comment by diggit** [comment]
It looks OK for me, please make a commit. I'll review changes and merge it.

**Comment by kinichiro** [comment]
Hi,
I commited changes to this PR.
https://github.com/kinichiro/kicad-library/commit/45bdad129a01764abb7cea3377f627f6e553a539

Please review this.
Thanks.

**Comment by kinichiro** [comment]
Hi,
I uppdated descriptions and keywords.
And I'm sorry, I had amended original commit.
This time I put additional commit for this update.

**Comment by diggit** [comment]
Nice work you did, merging.

**Comment by kinichiro** [comment]
Thanks for merging :-)

**Pull request merged**
