### PR TITLE
Various: Add/correct components

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add various components (MAX16910, MAX3072, RF modules...) and several fixes.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Note : I have look at the results of the checker nut I do not understand why there are errors. Please help! Thanks.

**Comment by diggit** [comment]
Hi!
If you have problem understanding automatic test outputs,  use checklib.py from [kicad-library-utils](https://github.com/KiCad/kicad-library-utils) to get more verbose info.

```
checklib.py -vvv --enable-extra  -c "SMA" library/conn.lib                        Mon 04 Jul 2016 07:50:17 PM CEST
library: library/conn.lib
checking component: SMA
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: RF (1), posx -250, posy 300
    pin: GND (2), posx -150, posy 100
    pin: GND (3), posx -50, posy 100
    pin: GND (4), posx 50, posy 100
    pin: GND (5), posx 150, posy 100
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: UNKNOWN at posx 0 posy 0 size 60
    pin: RF (1), text size 0, number size 0
    pin: GND (2), text size 0, number size 0
    pin: GND (3), text size 0, number size 0
    pin: GND (4), text size 0, number size 0
    pin: GND (5), text size 0, number size 0
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing datasheet, please provide a datasheet link if it isn't a generic component
```

KLC 3.1 - connection point of all pins must lie in 100mil grid with respect to origin of grid (wrong posx)
KLC 3.6 - set all fields, pin names, pin numbers to 50mil text size
KLC 3.8 - this is generic component -> ignore

That's all for KLC check.

You are using old KiCad version. Please update and resave library. This will eliminate massive whitespace changes. (Nightly builds works ok.)

**Please fix these too:**
- clear FP field
- center component to grid origin
- improve drawing - it is not clear, that bottom 4 pins are shielding

**Comment by myfreescalewebpage** [comment]
Thanks for your help. Finaly found the errors with "-vvv --enable-extra" (I was not using it before). Updated following your comments. Only KLC 3.8 remaining.

I'm using the last KiCad version (4.0.2), installed maybe 3 weeks ago now on a new computer. I have seen the spaces, but thinking it was because the library was not edited since a long time .... or a bug in the last KiCad version ? My computer is running Windows 7 64 bits.

**Comment by diggit** [comment]
I fact, library was saved with newer version. 4.0.2 is quite old with respect to KiCad development pace. Please use more recent version. [Nightlies are here](http://downloads.kicad-pcb.org/windows/nightly/). 
Once whitespace changes are gone, I'll take a look on all modified parts.

**Comment by myfreescalewebpage** [comment]
Done with latest version. Thanks for the link.

**Comment by diggit** [comment]
There are changes in many files. Quite uneasy to review. Eg. I can see added iM880A, but you don't mention it. Could you split this PR into separate ones with info what was changed?

**Comment by myfreescalewebpage** [comment]
No problem. Opened #608 to #615.

**Pull request closed without merging**
