### PR TITLE
De 113 rs 20

### PR DESCRIPTION
**Pull request by Misca1234**
Here is the replacement for the old DE-113-RS-20 displays

I added all three types and their variants from display-elektronik
wich have the same size and form factor as the DE-113-RS-20

There are 3 main symbols and the rest are aliases to those
DE 113-MS-20/7,5
DE 114-RS-20/6,35
DE 170-RS-20/7,5

I only added the 3D model of the 6.35mm pin lenght varaints, 
if you want I can add all variants as well, including 3D models

DE 113-MS-20/7,5
http://www.display-elektronik.de/filter/DE113-RS-20_122.pdf

DE 113-RS-20/12,2
http://www.display-elektronik.de/filter/DE113-RS-20_122.pdf

DE 113-RS-20/6,35
http://www.display-elektronik.de/filter/DE113-RS-20_635.pdf

DE 113-RS-20/7,5
http://www.display-elektronik.de/filter/DE113-RS-20_75.pdf

DE 113-RS-20/8,4
http://www.display-elektronik.de/filter/DE113-RS-20_84.pdf

DE 113-RU-30/7,5
http://www.display-elektronik.de/filter/DE113-RU-30_75.pdf

DE 113-TS-20/7,5
http://www.display-elektronik.de/filter/DE113-TS-20_75.pdf

DE 113-TU-30/8,4
http://www.display-elektronik.de/filter/DE113-TU-30_84.pdf

DE 114-RS-20/6,35
http://www.display-elektronik.de/filter/DE114-RS-20_635.pdf

DE 114-RS-20/7,5
http://www.display-elektronik.de/filter/DE114-RS-20_75.pdf

DE 114-RS-20/8,4
http://www.display-elektronik.de/filter/DE114-RS-20_84.pdf

DE 170-RS-20/7,5
http://www.display-elektronik.de/filter/DE170-RS-20_75.pdf

DE 170-RU-30/6,35
http://www.display-elektronik.de/filter/DE170-RU-30_635.pdf

DE 170-TS-20/6,35
http://www.display-elektronik.de/filter/DE170-TS-20_635.pdf

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1454

pretty push branch is 
https://github.com/KiCad/Displays_7-Segment.pretty/pull/8

packages3D push branch is 
https://github.com/KiCad/packages3D-source/pull/28

packages3D-source push branch is 
https://github.com/KiCad/packages3D/pull/94

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
# Review of the Symbols:

I think because you only have 3 footprints (and therefor only 3 3d models) it would be better to remove the aliases and rename the symbols such that the pin lenght and other non functional parts of the manufacturer part number are replaced with a wildcard. (In other words: give the symbol the same name as the footprint.)

I would suggest to order the pins differently. Don't order them by placement on the component but by function. (put all pins for a digit close to each other and order them xa, xb, ..., xg, DPx)
You can move the NC pins towards the top/bottom.

For the de-114 version the triangle could be filled better then by using a spiral of lines. Just draw the 3 outer lines and set the color foreground flag. Similarly for the arrow in the de-170 version.
screenshot from 2017-07-29 21-01-33


---

# Review of the 3d models

The 3d model sits a bit too low. The lower part of the pin mounting beneath the board.
There also seems to be some sort of protrusion on the bottom of the display that is missing in your model.
(Marked in magenta) Sadly there are no dimensions given for it in the datasheet.
screenshot from 2017-07-29 20-25-09

The 3d model for the DE113-xx-xx has gold pin as the color for the pcb. It might look better if it would have brown as the other models have.

The 3d models are missing the ":" between the digits. (not a dealbreaker. Just something i noticed.)

**Comment by Misca1234** [comment]
I have removed all aliases, they are named as the footprints and look like this 

bild

**Comment by Misca1234** [comment]
See 
https://github.com/KiCad/packages3D-source/pull/28
For new 3D models

**Comment by Misca1234** [comment]
Currently I am away for 7-10 days, i will fix it when I come back

**Comment by Misca1234** [comment]
DE 114 look like this now

bild

**Comment by poeschlr** [comment]
Very nice contribution. Thanks

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
