### PR TITLE
3 d hdsm 441 b hdsm 443 b 3

### PR DESCRIPTION
**Pull request by Misca1234**
This is the first of a series of segment displays

I placed the 3D model into Displays.3dshapes because i guessed that the directory 
"Displays_7-Segment.3dshapes" would be removed and all displays goes into "Displays.3dshapes"

Foot print for 
HDSM-441B and HDSM-413B

Datasheet 
https://docs.broadcom.com/docs/AV02-1589EN

Foot print
https://github.com/KiCad/Displays.pretty/pull/19

Source code
https://github.com/KiCad/packages3D-source/pull/20

3D model in kicad-library
https://github.com/KiCad/kicad-library/pull/1403

3D model in package3D
https://github.com/KiCad/packages3D/pull/82

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Reminder to self: This contains the 3d models and the symbols.

**Comment by poeschlr** [comment]
Symbol is ok to merge.

**Comment by poeschlr** [comment]
Thanks for contributing.

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
