### PR TITLE
Added LPC812M101FD20 to nxp_armmcu

### PR DESCRIPTION
**Pull request by michalkona**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
@michalkona please check KLC: http://kicad-pcb.org/contribute/librarians/

**Comment by michalkona** [comment]
Apologies for violating rules.

**Comment by michalkona** [comment]
Everything should be ok

**Comment by CarlPoirier** [comment]
Hi @michalkona,

You can make the symbol 0.5" smaller on the x axis. Also, please shorten all pins to 100mils and it will be good to go.

Regards,

Carl

**Comment by michalkona** [comment]
Hi,
Sorry, but a can't reduce size of the symbol because VDD pin label overlap to GPIO label.

**Comment by michalkona** [comment]
How should I change the schematic symbol of  LPC812M101FD20 in order to be possible to merge my pull request?

**Comment by diggit** [comment]
You mean LPC812M101JD20?
> Sorry, but a can't reduce size of the symbol because VDD pin label overlap to GPIO label.

Increase symbol height and then you can reduce width...
Also
- set outline thickness to 0.010
- add alias filter SOIC*

**Comment by michalkona** [comment]
Yes you right I really mean LPC812M101JD20. I thing it would be beater and more clear if I create a new pull request because I cant change incorrect commit message.

**Comment by diggit** [comment]
Ok, and you can add LPC812M101FD20.  It can't see difference. Maybe alias in KiCad? I did not check it thoroughly. Add reference to this PR into new PR. `#339`

**Pull request closed without merging**
