### PR TITLE
Tlp 2703 2745 2748 2761 2761 2767 2768

### PR DESCRIPTION
**Pull request by Misca1234**
TLP2703
https://toshiba.semicon-storage.com/info/docget.jsp?did=15216&prodName=TLP2703

TLP2745
https://toshiba.semicon-storage.com/info/docget.jsp?did=29405&prodName=TLP2745

TLP2748
https://toshiba.semicon-storage.com/info/docget.jsp?did=29407&prodName=TLP2748

TLP2761
https://toshiba.semicon-storage.com/info/docget.jsp?did=28819&prodName=TLP2761

TLP2767
https://toshiba.semicon-storage.com/info/docget.jsp?did=36717&prodName=TLP2767

TLP2768A
https://toshiba.semicon-storage.com/info/docget.jsp?did=36717&prodName=TLP2768A

bild

bild

bild

bild

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Some of the pin names are behind graphical lines.
I think these symbols might look better if you disable "show pin names". (In the symbol properties)
That way you can give all pins a name.

The datasheet link for TLP2768A does not work. (I can't figure out why though.)


TLP2703
should the output pin be of type open collector?

TLP2761
One if the small lines of the arrow in the smitt trigger has a different line width as the others. (It looks a bit odd for this reason. At least in kicad 4.0.2)
The diode also has thinner lines than its connectors to the pins.
(I think all of your other symbols have the thinner line width for drawings on the in side.)

TLP2768
should the output pin be of type open collector?

TLP2768A:
should the output pin be of type open collector?

**Comment by Misca1234** [comment]
The link do not work for me either anymore
https://toshiba.semicon-storage.com/eu/top.html cant not find it
However it can be found here
https://toshiba.semicon-storage.com/ap-en/product/opto/photocoupler/detail.TLP2768A.html
and the datasheet specifically here 
https://toshiba.semicon-storage.com/info/docget.jsp?did=28764&prodName=TLP2768A

> TLP2703
> should the output pin be of type open collector?

Yes
bild

> TLP2768
> should the output pin be of type open collector?

I wrote wrong number in my comment section, it shall be TLP2767, but it is not an open collector

> TLP2768A:
> should the output pin be of type open collector?

Yes,
bild


> TLP2761
> One if the small lines of the arrow in the smitt trigger has a different line width as the others. (It looks a > bit odd for this reason. At least in kicad 4.0.2)
> The diode also has thinner lines than its connectors to the pins.
> (I think all of your other symbols have the thinner line width for drawings on the in side.)

I give them an overhaul while I breaking up the lines as you suggested

**Comment by Misca1234** [comment]
bild

**Comment by poeschlr** [comment]
I reviewed your changes. (Not sure if you where ready for that.)
The hidden NC pin should be named NC
I would also name the LED pins (A and K maybe?)
Use one line width for the inner artwork for all symbols. (currently you use 0.010 and 0.000)

TLP2703:
- The output pin is now of type passive. Why not open drain?
- Some lines of the inner artwork have a differing line width
screenshot from 2017-06-30 09-48-35


TLP2748 has different line widths within the inner artwork. 
- especially in the arrows of the smitt trigger. 
- The led has a thinner line with then the connection wires
screenshot from 2017-06-30 09-52-14

TLP2745
different line widths:
screenshot from 2017-06-30 10-01-35

TLP2761
different line widths:
screenshot from 2017-06-30 10-07-16

TLP2767
different line widths:
screenshot from 2017-06-30 10-11-48

TLP2768A
why is the output pin of type output instead of open drain?

**Comment by Misca1234** [comment]
I fix it
(on my screen they look the same)

**Comment by Misca1234** [comment]
Added A, NC and K names to pin 1, 2 and 3 , made all lines 0.0254 mm wide

bild

bild

bild

bild

bild

bild

**Comment by poeschlr** [comment]
I found two small problems with line widths
screenshot from 2017-07-08 13-56-32
screenshot from 2017-07-08 13-56-45

**Comment by Misca1234** [comment]
Done

(the lines on my screen are equal width if they they are below a certain width so i have to scan the file manually)

**Comment by poeschlr** [comment]
Thanks for contributing.

**Pull request merged**
