### PR TITLE
Added 3D models for JST PH series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Downloaded under CC from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm

Associated footprints are available at https://github.com/SchrodingersGat/Connectors_JST.pretty (along with many other JST footprints)

I am happy for the JST footprints to be used in the Kicad library.

mod_conn_jst-ph

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Same as I commented in your others pull request. Apply KLC to footprints.

**Comment by SchrodingersGat** [comment]
3D file names have been fixed.
KLC applied to JST footprints -> https://github.com/SchrodingersGat/Connectors_JST.pretty

**Comment by SchrodingersGat** [comment]
All file names have been updated to match the JST part naming convention.
I am slowly moving towards KLC on https://github.com/SchrodingersGat/Connectors_JST.pretty

Some components now have courtyards.

**Comment by pointhi** [comment]
I would inform you, the JST PH connectors are already in the kicad repository: https://github.com/KiCad/Connectors_JST_PH.pretty

Now, only the 3d models are missing

**Comment by SchrodingersGat** [comment]
See - https://github.com/KiCad/Connectors_JST.pretty

**Comment by SchrodingersGat** [comment]
I'm working on replacing all the wings/wrl pairs with STEP/wrl pairs for MCAD future proofing. Closing for now.

**Pull request closed without merging**
