### PR TITLE
Added ADuM4160 and ADuM6000

### PR DESCRIPTION
**Pull request by dfro**
Added symbols for ADuM6000 (isolated dc-dc-converter) and ADuM4160 (usb isolator)

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Please, change the text size as in [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention).

Following is the output of [checklib](https://github.com/ricardocrudo/kicad-utils) script.

```
library: library/analog_devices.lib
	component: ADuM4160
	Violations of rule 3.6
		field: "U", text_size: 60
		field: "ADuM4160", text_size: 60
	component: ADuM6000
	Violations of rule 3.6
		field: "U", text_size: 60
		field: "ADuM6000", text_size: 60
```

**Comment by ricardocrudo** [comment]
Please check the following:
ADuM6000, pin 10 is defined as Bidirectional, must be same as pin 16.
ADuM6000, pin 15 is defined as Bidirectional, must be same as pin 9.

Fixing this, everything will be OK to merge.
Thanks.

**Comment by keruseykaryu** [comment]
Please provide also the minimal documentation of proposed symbols: description, keywords, link to datasheet; by filling the appropriate fields in symbols properties.

**Comment by dfro** [comment]
Hi!
Could you be more specific, please?
I have filled all appropriate description fields and I can see it in analog_devices.dcm file.
Do I need to fill anything else?

**Comment by keruseykaryu** [comment]
Sorry. My bad. Forget it.
I don't know why, but I didn't seen the .dcm file from `e17e771` commit.

**Comment by ricardocrudo** [comment]
@dfro sorry for the late response. I think pins 10 and 16 should be power output instead of power input.

**Comment by dfro** [comment]
@ricardocrudo If both pin 10 and pin 16 will be connected on schematic it will give ERC error (two power outputs connected together). One can make pin 10 as power output and pin 16 as power input or make both pins as power input and use PWR_FLAG on schematic.

How should i do this?

**Comment by ricardocrudo** [comment]
The same problem happens with RT9701, in this component one of the pins is defined as power output and another as passive. Could be good follow the same idea.

**Comment by ricardocrudo** [comment]
Thank you.

**Pull request merged**
