### PR TITLE
conflict correction for esd-protection lib.

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

1. `IP3319CX6` still has a strange footprint `Gamaya:WLCSP-6`
2. `TPD2EUSB30`, `TPD4EUSB30` please remove commans from keywords
3. Will you also post the packages? If so I would wait with this until the package names are clear (e.g. please use `2.5x1.0mm` instead of `2.5x1mm`).

Best,
JAN

**Comment by jkriege2** [comment]
PS: This PR follows up on https://github.com/KiCad/kicad-library/pull/967

**Comment by jeromebeguin** [comment]
Hi Jan, 

1. I still don't know in which Library I should include the WLCSP footprint. The Gamaya library is our own library for private component. I put it here while I don't know in which other lib to put it. 

2. Sorry for comma I missed them. 

3. I'll provide the packages, just waiting for the current PR (#32 of TO_SOT_SMD) to be merged and I'll submit the other packages. 

Best

Jérôme

**Comment by SchrodingersGat** [comment]
@jkriege2 @jeromebeguin we could make e.g. `Housings_CSP.pretty`

**Comment by jkriege2** [comment]
CSP stands for Chip-Scale-Package (https://de.wikipedia.org/wiki/Chip_Scale_Package)? If so: Go ahead!
JAN

**Comment by jeromebeguin** [comment]
Actually the WLCSP chip is something like this: [WLCSP](http://media.digikey.com/Photos/Fairchild%20Semi%20Photos/6-WLCSP.jpg)

**Comment by jeromebeguin** [comment]
Quick question related to ESD chip. Where should I find / create the foot print for 0603 ESD suppressors ?

**Comment by jkriege2** [comment]
Why not put WLCSP into https://github.com/KiCad/Housings_BGA.pretty?

Thei 0603 I would put there (or even use the existing): https://github.com/KiCad/Diodes_SMD.pretty

**Comment by jeromebeguin** [comment]
Ok, I'll put the WLCSP into BGA library. 
Thank you for the 0603, I'll add it.

**Comment by SchrodingersGat** [comment]
@jeromebeguin the datasheet indicates that this is truly a CSP - could you please put the footprint here - https://github.com/KiCad/Housings_CSP.pretty

**Comment by jeromebeguin** [comment]
yes sur. I'll remove it then from Housing_BGA.

**Comment by jkriege2** [comment]
What's the status of this?

**Comment by jeromebeguin** [comment]
I've changed the WLCSP library link now it's fine.

**Comment by jkriege2** [comment]
Please also change the FPFilter, it has different sizes for the WLSCP and therefore will not match the footprint. It should be `WLCSP*1.4x1.0mm*Pitch0.4mm*`.

**Comment by jkriege2** [comment]
Otherwise OK and I will merge when the FPFilter is fixed!

Best,
JAN

**Comment by jkriege2** [comment]
Thanks!

JAN

**Pull request merged**
