### PR TITLE
Added 40PC pressure sensor range

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.honeywellscportal.com//index.php?ci_id=138832

### CODE REVIEW

**Comment by diggit** [comment]
Nice symbol design, but it does not seem to be self explanatory. Is is standard symbol for pressure sensor?

When someone say pressure sensor, I visualize [sth. like this](http://www.ax-09.com/gruppa/materials/biblioteka/Shemotehnika/Sensors/Introduction%20to%20Sensors_files/Pressure.gif), without bottom inlet. 

Please add to description
- 5V supply
- 0.2% accuracy

3 pins are used, but this sensor has 6 pin package -> add 3 NC, invisible pins

**Comment by SchrodingersGat** [comment]
Hey @diggit , the symbol is per ISO representation
http://hydraulicspneumatics.com/other-technologies/chapter-4-iso-symbols-and-glossary-part-3-0
http://www.fluid-control.com/wp-content/uploads/2012/10/SIMBOLOS-NEUMATICOS.pdf
etc

I have improved the symbol graphics a little in my latest commit. LMK if you are happy with this symbol design.

I have also added invisible NC pins and improved the description

**Comment by diggit** [comment]
Everything look ok.

I am not sure about gauge symbol for pressure sensor. Gauge is visual indicator.
Leaving open for discussion.

**Comment by SchrodingersGat** [comment]
I'm happy to change it if you can show me a symbol that is simple and clearly denotes "pressure sensor" :)

**Comment by diggit** [comment]
@SchrodingersGat You got me. I don't know about anything closer or more explaining than what you offered.
Ok then, anybody can submit change in future. That's the magic of opensource. :)

Nice work you did, merging.

**Pull request merged**
