### PR TITLE
Ads7843

### PR DESCRIPTION
**Pull request by Misca1234**
This is push for ADS7843

ADS7843E with aliases ADS7843E/2K5, ADS7843EG4 and ADS7843IDBQRQ1

ADS7843E, ADS7843E/2K5, ADS7843EG4
http://www.ti.com/lit/ds/symlink/ads7843.pdf

ADS7843IDBQRQ1
http://www.ti.com/lit/ds/symlink/ads7843-q1.pdf

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work! I spotted a few things that need fixing thugh:
1. Please rename pins 7 and 8 to the names specified in the datasheet (i.e. 7=IN3, 8=IN4)
2. Optionally you can stack the power-inputs +Vcc to clean up the symbol a bit
3. Why s Dout Bidi? Shouldn't that be an output?
4. Remove the pin-count from teh FPFilter, i.e. it should be `SSOP*3.9*4.9mm*Pitch0.635mm*`

Best,
JAN

**Comment by Misca1234** [comment]
Hi

Thanks for your feeback, I will be back in a week or so, so I can not fix the symbol before that.

Regarding the Dout, let me re read the datasheet.

**Comment by Misca1234** [comment]
I tried to make an update of the symbol on another computer but apparently the travis script assume I have updated a lot more symbols than the ADS7843 so it have to wait until I am back

**Comment by poeschlr** [comment]
Old kicad stable introduces a lot of whitespace characters. (Makes it hard for us librarians to see what really changed.)

**Comment by Misca1234** [comment]
I terminate this branch and create a new one

See new one
https://github.com/KiCad/kicad-library/pull/1488

**Pull request closed without merging**
