### PR TITLE
added MAX17572, MAX17574

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
image
image

**Comment by evanshultz** [comment]
@ilya-epifanov 
Thanks for submitting so many new parts. Please be patient as the librarians will need a bit of time to review all the contributions you've made in the last day.

Three quick comments:
- Do not show the datasheet URL. It appears you edited this already. Thank you.
- In general, we want the ref des on the top while the PN can be on the top or below the part. It varies. Please take a look at this and on your other recent PRs.
- Unless there is a reason to do otherwise, the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) requires power pins on top and ground pins on the bottom (section 4.5). Please review this on all your recent PRs.

Thanks again!

**Comment by poeschlr** [comment]
Note on pin placement
For power supply symbols, @jkriege2 set the precedent in his resent regul lib update.
Power input on top the left, power output on the top right side.
Common on the bottom (or top for negative supplies, left/right bottom for isolated supplies.)

**MAX17572**
- The exposed pad should be connected to gnd not pgnd (If you do not stack it with another pin you can name it EP)
- FB should be an input
- RT/SYNC should be an input

**MAX17574**
- The exposed pad should be connected to gnd not pgnd (So either put it in the gnd stack or give it the name ep and place it outside of the gnd stacks.)
- Add the nc pins to the symbol. (Name: NC, type NC, invisible) To not stack them!
- VCC should be power output
- Reset could be open "collector" (electrically the same as open drain)
- Mode pin should be input
- SS is a normal input not the power input
- FB should be input

**Comment by poeschlr** [comment]
@ilya-epifanov could you make the changes requested above?

**Comment by Misca1234** [comment]
This push can be closed and deleted,
re push is here 
https://github.com/KiCad/kicad-library/pull/1679

**Comment by poeschlr** [comment]
The replacement pull request has been merged. Closing this one. Thanks @ilya-epifanov for creating the symbols and thanks @Misca1234 for fixing all the problems.

**Pull request closed without merging**
