### PR TITLE
Added DFPlayer Mini

### PR DESCRIPTION
**Pull request by EvansMike**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

could you also add the description, datahseet, ...?

Thanks,
JAN

**Comment by jkriege2** [comment]
Hi!

I looked a bit more thoroughly into your component. We have some conventions for contributions to the KiCAD lib (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) and also some script to check the and fix some of the problems automatically (https://github.com/KiCad/kicad-library-utils). The output of such a check for your component is:

```
checking component: DFPlayer_Mini
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: IO_1 (9), posx 450, posy -400
    pin: GND (10), posx 450, posy -300
    pin: IO_2 (11), posx 450, posy -200
    pin: ADKEY_1 (12), posx 450, posy -100
    pin: ADKEY_2 (13), posx 450, posy 0
    pin: USB+ (14), posx 450, posy 100
    pin: USB- (15), posx 450, posy 200
    pin: BUSY (16), posx 450, posy 300
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin GND (7): P (PASSIVE), expected: W (POWER INPUT)
    pin GND (10): P (PASSIVE), expected: W (POWER INPUT)
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -350, posy -550, recommended posx 0, posy 475
    field: name, posx -50, posy -100, recommended posx 0, posy 400
    field: footprint, posx -100, posy -50, recommended posx 0, posy -500
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10
```

So could you look into this and fix the problems? Also please shorten the description a bit, as it seems to me a bit long and a bit too much advertisement for my taste ,-)

Best,
JAN

**Comment by jkriege2** [comment]
Hi @EvansMike 

I'm very sorry that you closed your two PRs... any specific reasons, if I may ask?

Best,
JAN

**Comment by EvansMike** [comment]
Too busy at the moment. I'll probably get back to them (and probably others) when the project is finished.

**Comment by jkriege2** [comment]
That would be great ... looking forward to them ;-)

**Pull request closed without merging**
