### PR TITLE
Added parts of the cyclone V chip familty of Altera

### PR DESCRIPTION
**Pull request by Groonie**
Some of the Altera Cyclone V ic's have been added. Created using the pin-out files.

### CODE REVIEW

**Comment by Groonie** [comment]
Updated the text sizes and documentation, hopefully it will pass now.

**Comment by CarlPoirier** [comment]
Hi @Groonie,

That's nice work but I think there is room for improvement on their size. I suggest you separate them into units using the groups you used already.

Regards,

Carl

**Comment by Groonie** [comment]
The individual chips are now split into units, some are still quite large. Bet let me know what you think.
kicad_cyclonev_parts

**Comment by Groonie** [comment]
It looks like this now
altera_banks_cv

**Comment by diggit** [comment]
Please put all non PIN fields outside of symbols. Some symbols have overlapping texts due to it. Then you can shrink symbols even more.

**Comment by Groonie** [comment]
What exactly do you mean by putting the PIN fields outside of the symbols? Normally
the pin descriptions (green text) is always inside the symbol. And the pin number outside (red text).
The problem is maybe there is a label in the center, But all banks in a package always have the same label position.
And since the banks all have different sizes, it's difficult to find a correct spot. Therefore I have put it in the middle. Take a look, I hope it's not that bad.

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Hi @Groonie 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
