### PR TITLE
Add 3D model of ACDC Converter MeanWell IRM-02-x

### PR DESCRIPTION
**Pull request by Roman3349**
Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

### CODE REVIEW

**Comment by poeschlr** [comment]
Please add a correctly scaled wrl file for the use of the kicad internal 3d viewer. (use [kicad stepup](https://sourceforge.net/projects/kicadstepup/) to export the file from within freecad.)
Freecad stepup has the added benefit of helping with [colors](https://cld.pt/dl/download/64e39e99-c5b6-451b-accd-9e25331ceafe/KiCad_3D-Viewer_component-materials-reference-list_MarioLuzeiro.pdf?download=true), (your black is way too dark to be useful.)

The [new repo for 3d models](https://github.com/KiCad/packages3D) has a good readme section and some wiki entries that might also help for creating good models. If you are done with the models add them to this repo as well. (Maybe wait until this pull request is successfully merged until creating a pull request over there.)

The freecad file itself should not be part of this pull request but should go into the [packages3d-source repo](https://github.com/kicad/packages3d-source)

To help us with the pull request handling please add a screenshot of how this 3d model looks like from within the kicad 3d viewer.

**Comment by poeschlr** [comment]
@Roman3349 did you loose interest?

**Comment by Roman3349** [comment]
I am sorry that I did not progress with this pull request. Because I had not got enough free time to finish work on this pull request. I want finish work on this pull request as soon as possible.

**Comment by Shackmeister** [comment]
Hi @Roman3349 
PR's for 3D models are no longer being accepted into this repo.
If you would still like to contribute this models, please add a new PR on the new 3D repository which can be found here: https://github.com/KiCad/packages3D

**Pull request closed without merging**
