### PR TITLE
Adding RN42 and RN42N Bluetooth Module

### PR DESCRIPTION
**Pull request by pointhi**
Adding RN42 and RN42N Bluetooth Module from Microchip:

http://ww1.microchip.com/downloads/en/DeviceDoc/50002328A.pdf

The Footprints are located in my Repository:

https://github.com/pointhi/Bluetooth_Modules.pretty

I don't know how to add the shield connectors correctly to the library/footprint (adding non existing pin number, or is there a better way?), but the rest should fit.

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @pointhi  . Please apply [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) and check your symbol using [checklib](https://github.com/KiCad/kicad-library-utils/tree/master/schlib) script.

**Comment by pointhi** [comment]
the footprints and schematic should now be KLC compatible.

I think the footprints should be located in a new repository named RF_Modules.pretty or similar (which is not so specific like my Bluetooth_Modules.pretty)

**Comment by ricardocrudo** [comment]
Hello @pointhi the microchip lib is only for [microchip](http://microchip.com/) devices, the RN42 devices fits better in rfcom lib. Would be better if you group the pins logically instead of numerically.

**Comment by CarlPoirier** [comment]
test this please

**Comment by CarlPoirier** [comment]
Hi,

Please shorten all pins to 100mils and it will be ready to go! You can use this script to help you: https://github.com/KiCad/kicad-library-utils/blob/master/schlib/fix-pins.py

**Comment by pointhi** [comment]
ok, i shorten all pins as mentionend

thx

**Pull request merged**
