### PR TITLE
Added BAS40-04, AD8591, AD8592, and AD8594

### PR DESCRIPTION
**Pull request by FJRocha**
Added BAS40-04 to the diode library, and AD8591, AD8592, and AD8594 to the "analog-devices" library.

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

When adding symbols it is beneficial if you push some screen shoots as well, like in this push

https://github.com/KiCad/kicad-library/pull/1712

**Comment by FJRocha** [comment]
image

**Comment by FJRocha** [comment]
image

**Comment by FJRocha** [comment]
I think the library update are ok, but I can't make them pass the Travis-ci check. 

Does anyone know why this error keeps coming up in the Travis-ci check?: 
`if line[0] in self._KEYS:`
`IndexError: list index out of range`

**Comment by FJRocha** [comment]
Closing this pull request to separate the pull requests of Diode from the Analog Devices libraries.

**Comment by FJRocha** [comment]
OK, I couldn't figure out how to split the pull request, so here I try again.

**Comment by jkriege2** [comment]
@SchrodingersGat could you have a look at the script output?

Thanks,
JAN

**Comment by FJRocha** [comment]
image

**Comment by evanshultz** [comment]
Opamps and comparators should go into linear.lib. Please make that change and then I will review.

**Comment by FJRocha** [comment]
@evanshultz, Moved the OpAmps to "liner.lib". All checks passed. ;-)

**Comment by poeschlr** [comment]
The linear lib will be transferred over to the new repo with PR https://github.com/KiCad/kicad-symbols/pull/116.

This means we can no longer accept this contribution in the legacy repo. So please re open this in the new repo https://github.com/KiCad/kicad-symbols.
I think they need to be moved into Amplifier_Operational.lib

Sorry for the inconvenience.

**Comment by SchrodingersGat** [comment]
As we are now close to moving all the symbols to the new kicad-symbols repository, this PR will have to be reissued at https://github.com/kicad/kicad-symbols

Thanks for your contributions, and sorry for the inconvenience

**Pull request closed without merging**
