### PR TITLE
FIX: PIC18(L)F4455-I/PT and add PIC32MX795F512L

### PR DESCRIPTION
**Pull request by sirpete83**

### CODE REVIEW

**Comment by sirpete83** [comment]
Hey how it should go on?

**Comment by reportingsjr** [comment]
The automatic symbol checker is showing these issues with the KLC:
checking component: PIC32MX795F512L-TQFP100
  Violating Rule 3.1
  Violating Rule 3.6
  Violating Rule 3.8

Try to fix those and then give the library maintainers a good amount of time, there aren't a lot of them to do a big job!

**Comment by sirpete83** [comment]
Hey reportingsjr,
where can I find a list of the Rules? I really want to support the cominuty, it is not as easy ithought....

**Comment by keruseykaryu** [comment]
Go to the Wiki pages https://github.com/KiCad/kicad-library/wiki

**Comment by sirpete83** [comment]
I hope now everthing should be ok. Maybe you can merge it? 

I have got a question:
Now I'm 6 commits ahead and 59 behind the master. Will it be synchronizing after the merge?

**Comment by ricardocrudo** [comment]
@sirpete83 Is better to have uC pins arranged logically (instead of numerically) as in the others symbols.

**Comment by sirpete83** [comment]
Hello,
I think it is not applicable for PIC microcontroller, since almost all of the pins have multiple functions. I believe no one is using the ports as a data bus, and if it is so, it is only a special application, as well as Ethernet, SPI and I²C.
Thus, I see in the numbered icon more benefits, for example, in routing the signals, as in a logical arrangement of the blocks in the symbol, which is then torn due to the multiple use of PINs.

**Comment by sirpete83** [comment]
Hallo,
would something happen with this commit?
Thanks Peter

**Comment by CarlPoirier** [comment]
Hi,

Well, if you want this merged, you need to rework the pin order. Please have a look at the other PIC microntrollers as an example. They group pins according to the ports, so RAx, RBx, RCx, etc.

Closing the pull request won't get your work merged.

Regards,

Carl

**Comment by sirpete83** [comment]
Sorry for my late support. Maybe now it is ok to merge?

**Comment by jkriege2** [comment]
Hi!

looks good to me so far ... please add FPFilter `TQFP*12x12mm*Pitch0.4mm*`

Best,
JAN

**Comment by jkriege2** [comment]
Please fix the errors indicated by out check-scripts:
2017-03-08 22_03_01-created footprint library housings_lcc by yo3iti pull request 1 kicad_housi

**Comment by poeschlr** [comment]
@sirpete83 could you take a look at the suggestion by jan?

**Comment by sirpete83** [comment]
maybe its now ok?

**Comment by SchrodingersGat** [comment]
@sirpete83 sorry for the mucking about. We are now moving all the symbols to the new library in preparation for the new software release. We will no longer be accepting PRs to this repo. Please resubmit this PR to https://github.com/kicad/kicad-symbols

Thanks (and sorry!)

**Pull request closed without merging**
