### PR TITLE
Modify resistor 3 dmodels

### PR DESCRIPTION
**Pull request by jkriege2**
- added all new resistor 3D models
- complements: https://github.com/KiCad/Resistors_THT.pretty/pull/18

res3d1
res3d2
res3d3

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This is fantastic!

I would like to see the *Resistor_* prefix changed to *R_* to match the *Resistors_SMD* lib and the various capacitor footprint libraries.

This will require a change to the footprints (https://github.com/KiCad/Resistors_THT.pretty/pull/18) also.

Thoughts?

**Comment by jkriege2** [comment]
rename done ... also in https://github.com/KiCad/Resistors_THT.pretty/pull/18

**Comment by SchrodingersGat** [comment]
Hmm merging the caps PR has broken this one. Fix conflicts and we'll merge :)

**Comment by jkriege2** [comment]
conflicts fixed

**Pull request merged**
