### PR TITLE
 OPA4314 and LMV331 added

### PR DESCRIPTION
**Pull request by aliteke79**

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi @aliteke79. First, thanks for being willing to improve KiCad's library by making a new part and submitting a PR here. We really appreciate this community involvement.

Due to the library organization, linear.lib is the correct place for this part. Yes, I know it is confusing. There is a currently a re-organization of the library ongoing to make things better.

But furthermore, I've been overhauling the linear library at https://github.com/KiCad/kicad-library/pull/1081 (I will need to create a new PR) and I've already included OPA4134. So if that will satisfy your needs, you could close this PR.

Thanks again for contributing to KiCad!

**Comment by aliteke79** [comment]
Hi @evanshultz, i thought linear.lib is for the Linear company, thats why i have added it to texas.lib.
You told me that you have already included it, i can abort the request but couldn't find it on the repository, where is the OPA4134?
Thanks,

**Comment by evanshultz** [comment]
Yes, the library names are confusing. I thought the same thing at first.

The PR I linked above has not been merged so you will not see it in the repo yet. There are just a couple loose ends before it can be merged. Once it does, however, your fork will likely be broken since the changes are dramatic. You would then have to merge the trunk, close this and create a new PR, etc.

**Comment by aliteke79** [comment]
Okay i get it now, thank you.

**Pull request closed without merging**
