### PR TITLE
Added NXP S08 and Kinetis libraries

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Contribution to the KiCad libraries by creating a new "nxp_s08" and "nxp_kinetis" libraries following the example of all the "microchip_*" libraries.

I'm using NXP (previously-Freescale) devices very often and plan to add several common references (well the maximum I can do).

This is my first pull request to your repository, please feel free to add any comment if something is wrong. Thanks!

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Please feel free to merge. I will create a new Pull Request for next commits.

**Comment by diggit** [comment]
Whoa, this is massive! Did you do it by hand or some script?

Quickly browsing some ICs...
- is PTD2 really just input and not bidir like rest of GPIO pins? (all MCUs, so I guess script...)
- core types info in description, like ARM Cortex-M0, is missing, it is quite useful though
- you have aliases, but they are not different from parent, probably various Flash/RAM sizes?
 - Flash and RAM info in description is useful, it is so important, that position after MCU frequency is adequate (maybe after core info)
- description like *Small Form Factor* comes from package -> redundant info IMO

**Comment by myfreescalewebpage** [comment]
No it's done by hand ! :-) However I have used copy/paste a lot to not start all components from nothing. I'm using a lot NXP (ex Freescale) components so I know them very well. I was previously using Eagle but a very old version and now looking new features that Kicad is offering. That's why I want to participate to thank people working on the project.

Regarding your remarks:
- PTD2 was probably only input on one of the reference and then I have copy/paste it and forget to modify. I will correct.
- Core info, RAM/Flash size etc: yes I can add them.
- Form factor in descriptor: I will remove I agree it is redundant.

Let me some few weeks to complete the modifications. If you have some other remarks, please feel free to give them!

**Comment by diggit** [comment]
Oh, at least, use some advanced text editor to do multiple changes at a time directly in lib/dcm files. (Atom, SublimeText,...)
You can use [xls file from product selector](http://www.nxp.com/products/microcontrollers-and-processors/arm-processors/kinetis-cortex-m-mcus/e-series:KINETIS_E_SERIES?cof=0&am=0) as data source. (Delete unneeded columns, copy text to some text editor and do mass editing. If you are comfy with some high level programming language like Python, you can use it to do some part of the job for you. :)

**Comment by myfreescalewebpage** [comment]
According to previous comments:
- Fix some pins direction
- Added core/Flash/RAM/EEPROM info in description
- Removed package name in description

Thanks for your comments!

**Comment by myfreescalewebpage** [comment]
Any comments ?
Thanks!

**Comment by diggit** [comment]
> Added core/Flash/RAM/EEPROM info in description

good!

> Removed package name in description

Umm what? Probably misunderstanding. I meant that info like *Small Form Factor* should be removed not package. Package itself is highly useful info!

**Description** in nxp_armmcu has imo better structure.
*32-bit ARM Cortex-M0 microcontroller, 8kB Flash, 4k SRAM, UART, I2C, SPI, ADC 8ch*
Most important things first.

here...
*40 MHz, Entry-Level, High-Robustness, ESD/EMC performance Microcontroller, Cortex-M0+ core, 16kB Flash, 2kB RAM*
**->**
*32-bit ARM Cortex-M0+ Microcontroller, 40 MHz, 16kB Flash, 2kB RAM,* **PACKAGE**

Things like "high robustness" are quite subjective, there is no scale and thus useless. On the other hand, info about available busses, adc, timers, pwm channels,... really helps. (this is not necessary, but valuable)

You might want to wait for more comments before further changes.

**Comment by myfreescalewebpage** [comment]
Thanks for your review.

Regarding "Small Form Factor" in this case I don't know what it is in KiCad. My interface is in french so it's difficult to understand clearly the field your are speaking about. Which part is it in the lib file ? I have keep the footprints so the information is not lost.

I not agree with your comment about the descriptions. Well peripherals are interesting but this kind of device have lot of peripherals : several kind of timers, uart, spi, i2c, usb, ethernet, lcd controller, memory interfaces, can, adc, dac, etc etc. The description will be too long and I'm afraid it will not be very good. Engineers don't chose their microcontrollers with KiCad, they look at the suppliers websites  ;-)
Regarding to the comment "Entry-Level, High-Robustness, ESD/EMC performance Microcontroller" I have written, in fact it is not a personal comment but the description of the chip family on NXP website itself, so you can easily found the device by browsing their website :-)

**Comment by myfreescalewebpage** [comment]
Up?

**Comment by myfreescalewebpage** [comment]
@diggit Package restored in description, sorry for the delay. Can you review the pull request and status?
Thanks,
Joel

**Comment by jkriege2** [comment]
please remake FPFilters in the way I explained there: https://github.com/KiCad/kicad-library/pull/615

Best,
JAN

**Comment by myfreescalewebpage** [comment]
@jkriege2 I have done it for #615, but do you realize there are several hundred of devices in this pull request ? I have already review them several times and it's a lot of job, I realize I have now to redo it again. I was just asking @SchrodingersGat in #613 how the reviews are organized ? (see my last comment in #613).

**Comment by jkriege2** [comment]
a short note on KLC for now:

We are currently working on an extension/better explanations. Here you can view the current status:
- https://github.com/SchrodingersGat/kicad-library/wiki/KLC
- https://github.com/KiCad/kicad-library/issues/879

That should explain a bit more ... I hope

Best,
JAN

**Comment by myfreescalewebpage** [comment]
@jkriege2 : footprints filters modified (done with a macro from footprint field "F2").
Also, thanks for the link, I have read a part and I understand that some job is currently done to enhance KLC.

**Comment by jkriege2** [comment]
I just ran our autocheck-scripts (https://github.com/KiCad/kicad-library-utils) and some of the symbols in `nxp_s08.lib` are missing some NC-pins. Please also add these (made invisible and with type not connected), so our pin-count filter when selecting a footprint works!

These are affected:
```
checking component: MC9S08AC128xFGE
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 37 is missing
    Pin 38 is missing
    Pin 39 is missing
    Pin 40 is missing

checking component: MC9S08JS16CFK
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 6 is missing
    Pin 12 is missing
    Pin 18 is missing

checking component: MC9S08LG32J0xLF
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10

checking component: MC9S08LG32J0xLH
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10

checking component: MC9S08LG32J0xLK
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10

checking component: MC9S08QG4xPAE
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 5 is missing
    Pin 6 is missing
    Pin 7 is missing
    Pin 8 is missing
    Pin 9 is missing
    Pin 10 is missing
    Pin 11 is missing
    Pin 12 is missing

checking component: MC9S08QG8xDNE
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 5 is missing
    Pin 6 is missing
    Pin 7 is missing
    Pin 8 is missing
    Pin 9 is missing
    Pin 10 is missing
    Pin 11 is missing
    Pin 12 is missing

checking component: MC9S08QG8xFKE
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 7 is missing
    Pin 8 is missing
    Pin 9 is missing
    Pin 11 is missing
    Pin 19 is missing
    Pin 21 is missing
    Pin 22 is missing
    Pin 23 is missing

checking component: MC9S08QG8xFQE
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 5 is missing
    Pin 6 is missing
    Pin 7 is missing
    Pin 8 is missing
    Pin 9 is missing
    Pin 10 is missing
    Pin 11 is missing
    Pin 12 is missing

checking component: MC9S08SH8xFK
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 2 is missing
    Pin 20 is missing
    Pin 21 is missing
    Pin 22 is missing
```

FPFilters look good.

Best,
JAN

PS: Did you do these by hand or with a script?

**Comment by t3hcatpaw** [comment]
Aw, snap. Just started working on a Kinetis lib I wanted to integrate to nxp_armmcu.lib without looking through the pull requests first. Would you guys mind me somehow contributing to this one or should I issue a seperate pull request?

So far, I have 33 parts, consisting of KL04, KL05 and KL27 series as well as MK20DX128VFM4. Wanted to do KL03 and KL02 next.

BR, t3hcatpaw

**Comment by myfreescalewebpage** [comment]
@jkriege2 just run the klc check seems ok now. I let you doing your review.
@t3hcatpaw I can integrate the parts I have not already added to my PR if you want. let me known.

**Comment by t3hcatpaw** [comment]
@myfreescalewebpage As far as I can tell, you have added KL0x and KE02 devices to the a new lib named `nxp_kinetis.lib`. In #1540 I have already submitted another PR that doesn't contain KE devices, but does add KL0x and KL2x subfamilies as well as some K20's to `nxp_armmcu.lib`.
Would be nice if there was a function to somehow "merge" these PRs, but I guess it would be best for me to wait for @jkriege2's review result and then decide whether to either rebase my work (which would be only the KL2x/K20 part) on your new lib in another PR or somehow modify my existing one as appropriate.

**Comment by myfreescalewebpage** [comment]
@t3hcatpaw yes I ave seen, my PR is quite old now but still not merged because of evolutions of the KLC and also not always the time to fix them. Hope now it is ok but I let @jkriege2 have a look.

**Comment by t3hcatpaw** [comment]
Okay, I've taken a quick look into your Kinetis lib. Our approaches seem to differ quite a lot. :) I'll wait until your PR is merged though, and propose some changes later.

**Comment by SchrodingersGat** [comment]
@myfreescalewebpage thanks for your contribution here, I think it is very impressive! Sorry that it has taken so long to merge. We are slowly reeling in the number of PRs out in the wild :)

I'm happy to merge this as is - it is a massive contribution! Thanks again.

**Comment by myfreescalewebpage** [comment]
Hello @SchrodingersGat I'm happy it is now merged :-) Thanks. I will continue to provide new devices, long life to Kicad !

**Pull request merged**
