### PR TITLE
KLC fixes for dc-dc.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Fixed TL497
- Fixed TPS60500DGS

This is also another Travis test (thi s one should not fail!)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Woohoo! Travis passed :)

**Comment by jkriege2** [comment]
nice!

**Comment by bruneau77** [comment]
To draw first my schema I do not find the SN7404 component in the KICADE library, with its 14 legs, I find a reference, but it does not propose the whole box and places me the symbols of the inverters contained in the SN7404 ???? You can help me ?

**Comment by jkriege2** [comment]
Apaprt from this thread beeing the wrong place to ask such question (I would suggest: https://forum.kicad.info/). There is a `74HC04`, which has the same pinout. Note that this symbol is split into 6 separate inverter symbols and the power-supply-pins are hidden. So add a GND and a VCC-powe-symbol to your schematic to connect them ... this is a bit non-obvious, but might change at some time in the future ;-)

Best,
JAN

**Pull request merged**
