### PR TITLE
Hdsp 48 xx 2

### PR DESCRIPTION
**Pull request by Misca1234**
Recreated the push because this amateur piece of S of this F to git messed up my master
This is an replacement of 
https://github.com/KiCad/kicad-library/pull/1370

3D models for 
HDSP-48xx, HDSP-4830, HDSP-4832, HDSP-4836, HDSP-4840, HDSP-4850, HLCP-J100

https://docs.broadcom.com/docs/AV02-1798EN

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
48XX (please rename it to 48xx)

**Comment by Misca1234** [comment]
Ok, one sec

**Comment by Misca1234** [comment]
This will take some time, this junk software refuse to commit its own "git rn" command

**Comment by Misca1234** [comment]
sigh

**Comment by poeschlr** [comment]
git rm not rn you can use -f like in all unix style commands or --force
or delete the file in any file browerser and add the changes via git add -u

**Comment by poeschlr** [comment]
lol

**Pull request closed without merging**
