### PR TITLE
Ads7843 2

### PR DESCRIPTION
**Pull request by Misca1234**
This is push for ADS7843

ADS7843E with aliases ADS7843E/2K5, ADS7843EG4 and ADS7843IDBQRQ1

ADS7843E, ADS7843E/2K5, ADS7843EG4
http://www.ti.com/lit/ds/symlink/ads7843.pdf

ADS7843IDBQRQ1
http://www.ti.com/lit/ds/symlink/ads7843-q1.pdf

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
What about stacking the +VCC pins?

**Comment by jkriege2** [comment]
Also, FPFilter should be `SSOP*3.9x4.9mm*Pitch0.635mm*`

Best,
JAN

**Comment by Misca1234** [comment]
Uhm, what do you mean with "stacking", adding to pin number to same pin ?

**Comment by jkriege2** [comment]
stacking: see KLC 4.3 (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

**Comment by Misca1234** [comment]
Like this ?

bild

**Comment by jkriege2** [comment]
no, you simply have one pin +VCC,POWER-INPUT,visible and one pin +VCC,PASSIVE,invisible and move them to the same spot. You'll only see the visible pin in the schematic, but if you connect to it, both pins will be connected to the same signal. See regul.lib for several examples.

**Comment by Misca1234** [comment]
Ok, I see, let me fix it.

But I think this "stacking pins" is a terrible concept. 
At least I would be confused of the symbol and would wonder where the "other VCC" pin is 
and that the designer of the symbol have forgot one pin.

**Comment by Misca1234** [comment]
bild

**Comment by jkriege2** [comment]
yes, the concept is not perfect, but the best we can do with KiCAD's current feature set.

Best,
JAN

PS: Nice work on this symbol :-)

**Comment by Misca1234** [comment]
Thx, live well

**Pull request merged**
