### PR TITLE
added MAX481, MAX483, MAX485, MAX487 and MAX1487.

### PR DESCRIPTION
**Pull request by sujitth**
Hi,

I was looking for an RS485 transceiver and its not there, so I added the MAX485 and MAX481,483,487 and 1487 as aliases of it.

image

This is my first contribution, Please let me know if anything needs to be changed.

Best Regards,

Sujith.

### CODE REVIEW

**Comment by Schlumpf** [comment]
Hi, thanks for these symbols!

Before they will merged into the library, they have to follow the rules of the KLC (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention). There are some scripts for checking symbols, which show you some KLC violations directly (https://github.com/KiCad/kicad-library-utils).

The artwork inside the symbol is really nice :)

**Comment by Schlumpf** [comment]
If you have python installed, you can run it from the windows cmd shell, too.
Try:
`c:\>cd "pathToScript"`
`c:\>python checklib.py -v "pathToLib"`

I currently don't have a windows machine here, so maybe I made a typo somewhere...

**Comment by sujitth** [comment]
@Schlumpf Thanks for your inputs.
I have checked first in my local library,it works partially, please find the screenshot.

image

**Comment by SchrodingersGat** [comment]
@sujitth  you can either install [colorama](https://pypi.python.org/pypi/colorama) or add the `--nocolor` flag to disable color output.

**Comment by Schlumpf** [comment]
@sujitth and you have to set all pathes with spaces inside in quotes (")

**Comment by sujitth** [comment]
@SchrodingersGat Thank you,it works.
@Schlumpf I am getting 2 errors as shown:
image

I have used 50mils grid while crating the symbol and ensured the pin lenghts were 100mils as I read the KLC.
image

and regarding the field texts, its already set to 1.270 mm right?
image

**Comment by Schlumpf** [comment]
Your Pins are not on the vertical 100mil grid ;)
The horizontal position is correct.
And could you move VCC to the top and GND to the bottom?

Best regards
Schlumpf

PS: I suggest to activate the `-v`option oft the script to show more hints.

**Comment by sujitth** [comment]
Hi,
I just alignd it vertically then also the same 100milgrid error is showing.
image

still I have done it in wrong way?
and what needs to be changed on the field texts?

Best Regards,
Sujith.

**Comment by Schlumpf** [comment]
Hi,
back home on my PC, I cloned your repo to check your symbol. Because your PR and your github repo are public, no direct file sharing is needed.

The option `-vvv` is the option for more output. It gives the hint, whats going wrong:

```library: /home/schlumpf/tmp/max485/kicad-library/library/interface.lib
checking component: MAX485
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: RO (1), posx -400, posy 150
    pin: ~RE (2), posx -400, posy 50
    pin: DE (3), posx -400, posy -50
    pin: DI (4), posx -400, posy -150
    pin: GND (5), posx 400, posy -150
    pin: A (6), posx 400, posy -50
    pin: B (7), posx 400, posy 50
    pin: VCC (8), posx 400, posy 150
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: U at posx 30 posy 320 size 60
    field: MAX485 at posx 25 posy -300 size 60
    field: UNKNOWN at posx 25 posy 0 size 60
    field: UNKNOWN at posx 25 posy 0 size 60
```
It seems, that you forgot to save the symbol before rechecking. It works for me ;)
The output shows the wrong text sizes, too: `U`, `MAX485` and 2 empty texts. These are Footprint and Datasheet. You can edit them by clicking the big T at the top toolbar.

As far as I know, you should move the VCC and GND pins, but let's ask some of the library maintainer: @SchrodingersGat, @jkriege2. It's not explicitly written in the KLC.

Another thing I spotted: Maybe the artwork line to B should connect to the other wire?
And please update the footprint filter.

best regards
Schlumpf

**Comment by SchrodingersGat** [comment]
Yes PWR pins should be at the top, GND at the bottom

e.g.

gnd

I shall look at the KLC and see if this requirement can be added somewhere.

Thanks

**Comment by sujitth** [comment]
@Schlumpf thank you very much for the detailed instructions.it resolved the issues and it was nice learning.
I was editing it in my local folder for experimenting, not was in the git repo.
The rule 3.1 error was caused because I was using the demorgan symbol option to get a filled background version, and I forgot to edit the pins on the second symbol.
image
Alternate demorgan symbol:
image
Power and Gnd pin changed:
image

@Schlumpf @SchrodingersGat - regarding the Pin name position offset I could't find anything mentioned in the KLC, default is set to 40, but if we use 10 or 20 - will get some neat space inside the body if we need to draw something.
and does the use of demorgan symbol is allowed? I felt that- all the ALT version symbols in the device libray can be done using this option.

and how to update my pull request with the new changes? shall I do like:
switching to the edit branch of my local repo by git checkout, then after making the changes
git commit -a
git checkout master
git merge mybranch
git push origin master

Best Regards,
Sujith.

**Comment by SchrodingersGat** [comment]
I do not agree with using the DeMorgan symbol simply to change the background. 

If you run the KLC scripts with the `--enable-extra` flag, you will see that rule EC04 (not yet documented on the KLC page, sorry) says that symbols should generally have background fill and a line width of 0.01" (10 mil)

**Comment by sujitth** [comment]
@Schlumpf - I have changed the part according to KLC and commited.

Plase let me know if anything needed to additionally for merging.

**Comment by Schlumpf** [comment]
Hi,
sorry for late response. Some things I found:
 - `checklib.py interface.lib -c max485 -vvv --enable-extra` shows a violation of EC03.
 - Violation of rule 3.3
 - Remove commas from keywords
 - Don't double words in keywords and description

Let's ask @SchrodingersGat or @jkriege2 for review and merge.

**Comment by Schlumpf** [comment]
And I would swap pin 6 and pin 7. `A` should be over `B`.

**Comment by jkriege2** [comment]
Hi!

I'm just looking into this PR:
1. Please ensure that the label-text does not overlay the internal drawings:
2017-01-22 12_11_35-part library editor d__kicad_kicad-library-review_library_interface lib
2. Please remove the MFN field
3. FPFilters should be: `DIP*W7.62mm*` and `SOIC*3.9x4.9mm*Pitch1.27mm*` (including geometric info, but without the pin-number!)
4. remove comma from keywords
5. The violations of field-placement can be ignored ;-)
6. Please add FPFilter for µMAX (will provide packages soon): `uMAX*3x3mm*Pitch0.65mm*`

Otherwise this looks great!
Best,
JAN

**Comment by jkriege2** [comment]
Hi!

instead of `uMAX*3x3mm*Pitch0.65mm*` please use `MSOP*3x3mm*Pitch0.65mm*`

Best,
JAN

**Comment by jkriege2** [comment]
please fix confilct!

**Comment by sujitth** [comment]
@jkriege2  @Schlumpf - I did a git fetch upstream before doing the work.

image

am not able to proceed now, can you please merge this PR so that I can edit the symbol again, or is there any other way to do this properly?

Best Regards,

Sujith

**Comment by jkriege2** [comment]
You Need to solve your merge conflict ... and then commit the solution to your branch and push it here.

https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

I usually do it with TortoiseGIT, which provides a GUI for such stuff ...

Best,
JAN

**Comment by jkriege2** [comment]
you still have some merge comments (and doubled Contents) in the Interface.dcm file!

Best,
JAN

**Comment by sujitth** [comment]
@jkriege2 I have updated the symbol as per the KLC requirements.

Best Regards,

Sujith

**Comment by jkriege2** [comment]
Will check this evening, but you still have the merge-comments in the Interface.dcm-file: https://github.com/KiCad/kicad-library/pull/875/files#diff-30ecce9dd01608b638b2686855bd2ea7

Please fix that!

Best,
JAN

**Comment by evanshultz** [comment]
Would it make more sense to have the MAX481 as the base part and the other as aliases? I realize it ultimately doesn't matter, but all other parts I've seen have used the lowest number as the base symbol.

**Comment by Schlumpf** [comment]
@evanshultz: but the MAX485 is the most used part, I think...

**Comment by jkriege2** [comment]
I had a look ... and everything looks good. Please fix the merge problem and I'l merge this PR!

JAN

**Comment by sujitth** [comment]
@jkriege2 - sorry, i tried but not yet figured out how to do it (newbie to git). I could see that the interface.dcm has repetitive contents as "<<<<<<<  =======  >>>>>>>" but not sure which one to delete.

here is what happened actually:
before i editing the symbol again in my local branch, i did a git fetch upstream and it was not allowing me to do a git merge upstream/master, saying there is a conflict and the git suggsted to add the interface.dcm file, and after that i was able to merge. (added the commit message "resolved merge conflict")

after that i switched to my edit branch and did the changes for the MAX485 symbol and committed, merged and pushed.

Best Regards,

Sujith

**Comment by jkriege2** [comment]
When that happens you have to edit the merge conflict, i.e. look at the file and generate a version that is as it should be and just then commit. 

In this case I would recommend this: find the half with your parts in it and copy them. then delete your part and paste your description into the other one. Finally open and resafe in KiCAD. When all description is there you should be fine (simply commit and then check the dcm-file in the files-changes-tab of this webpage: https://github.com/KiCad/kicad-library/pull/875/files

Hope that helps,
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 are you able to take another look at this?

**Comment by jkriege2** [comment]
The problem still persists ... @sujitth are you still working on this PR and could you fix the problems?

Best;
JAN

**Comment by SchrodingersGat** [comment]
@sujitth are you able to make the required changes to this PR? Otherwise I shall close it. Thanks

**Comment by poeschlr** [comment]
The interface lib has already been transferred over to the new repo for v5. For this reason we can not accept this pull request in the old repo any more. If you are still interested in contributing, re submit your symbol over at the new repo.
https://github.com/KiCad/kicad-symbols

**Pull request closed without merging**
