### PR TITLE
corrected INT pin on TCA9555 from output to open collector

### PR DESCRIPTION
**Pull request by Shackmeister**
and removed some windows line endings
didnt change anything else
tca9555

### CODE REVIEW

**Comment by jkriege2** [comment]
please remove all the other files from this PR, in which there is no fix (regul.lib, ...) ...

Could you also please fully fix the FPFilters, as described in the KLC/FAQ on them (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention, https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions)

Best,
JAN

**Comment by Shackmeister** [comment]
@jkriege2 sure, but shouldnt windows line endings be removed?

**Comment by jkriege2** [comment]
uupps ... sorry, just saw the first line of your PR (the pixture distracts the eye ;-) ... then it's fine with me. Are there any other changes to those other files than line-endings?

cu
JAN

**Comment by Shackmeister** [comment]
@jkriege2 not at all :)

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
