### PR TITLE
Added RC1602A

### PR DESCRIPTION
**Pull request by Misca1234**
Pimped up RC1602A, both foot print and 3D model

See 
https://github.com/KiCad/Displays.pretty/pull/15

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
The k pins are on the wrong position. (I did not check it with a cad program. Only looked at it in the 3d viewer.)
screenshot from 2017-07-08 01-36-11

**Comment by Misca1234** [comment]
Hmm, it looks like this on the freecad drawing

**Comment by Misca1234** [comment]
Yes, you are correct, i see it now

**Comment by Misca1234** [comment]
I looks like this now 

bild

**Comment by poeschlr** [comment]
Looks good. Thanks

**Comment by Misca1234** [comment]
great, thanks

**Pull request merged**
