### PR TITLE
Added LT3032

### PR DESCRIPTION
**Pull request by matyro**
Added [LT3032](http://cds.linear.com/docs/en/datasheet/3032ff.pdf)

Slightly modified footprint is needed:
https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/40

lt3032

### CODE REVIEW

**Comment by jkriege2** [comment]
Please wait with mergein until PR https://github.com/KiCad/kicad-library/pull/948 is merged ...

Thanks,
JAN

**Comment by jkriege2** [comment]
@matyro Pleas epost a screenshot of the new symbol in the PR ... this makes reveiw easier. Also please orient the style (haven't checked you symbol yet) on the style in my PR above, which does a complete overhaul of regul.lib.

Thanks,
JAN

**Comment by matyro** [comment]
Added image top opening post

**Comment by matyro** [comment]
Added Adjustable LT3032
unbenannt

**Comment by jkriege2** [comment]
Hi!

there are brand new rules for stacking power-pins in the KLC (since yesterday) ... and an overhauled version of regul.lib (#948) will use these rules (see https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention rule 4.3.vi). Please also use this tool here, i.e. you can stack all the GND-pins and all the INN pins.
To do so, make one pin a visible POWER-INPUT and all other pins invisible PASSIVE pins and put them in the same loction. This should allow you to make the overall symbol smaller. Also the Travis check-script now recognize such stacks.

Best,
JAN

**Comment by evanshultz** [comment]
Hi @matyro!

There should be different symbols for the suffix-less version, and all the versions with NC pins. LT3032 will be one symbol, and LT3032-3.3 could be another symbol which would have 4 ALIASes. This is what I see currently, so that looks fine. Hopefully I haven't missed anything.

The fixed-output versions, without ADJ* pins, will need the NC pins present on the symbol to properly match up with the footprint in KiCad. There are currently only 14 pins on the fixed-output symbols.

Also, the symbol would look nicer, at least to me, if INN and OUTN were aligned across the symbol like INP and OUTP. This also matches the datasheet symbol.

Lastly, please update the footprint field since the footprint name has changed since your original submission. It is named `Linear_DE14MA`.

**Comment by matyro** [comment]
lt3032_fixed
lt3032_fixed

Added the mentioned changes

**Comment by evanshultz** [comment]
Thanks for the quick work!

I looked briefly. The fixed-output symbol is missing pin 13. NC pins must be present for the symbol and footprint to be matched. On the adjustable version, all 3 NC pins should be present and named `NC`.

**Comment by SchrodingersGat** [comment]
@evanshultz can you take another look here?

@matyro please fix merge conflicts :)

**Comment by evanshultz** [comment]
@matyro In addition to fixing the branch conflicts:
1. Due to recent changes in the library, the footprint needs updated. Please change `Housings_DFN_QFN:Linear_DE14MA` to `Packages_DFN_QFN:Linear_DE14MA`.
1. The OUTx pins should be power output type (capital W).
1. Bury all not connected pins inside the part body. This goes for the ADJx pins on fixed output versions.

Also, and this is optional, but you could shrink the symbol vertically. Not required for me to merge.

Sorry for letting this PR slip!

**Comment by SchrodingersGat** [comment]
@matyro we are moving the symbols to kicad-symbols for the new software release. Please resubmit a PR to https://github.com/kicad/kicad-symbols

Thanks

**Pull request closed without merging**
