### PR TITLE
Added TPL9201

### PR DESCRIPTION
**Pull request by RaceMouse-of-Denmark**

### CODE REVIEW

**Comment by poeschlr** [comment]
You might have noticed that the automatic test system does complain a bit about your pull request.
Please fix them. 
* The main problem is that a lot of your pins are not on a 100 mil grid. 
* Supply pins should be on the top side and ground pins on the bottom side of the symbol. 
* If your symbol has only one possible footprint, don't add a footprint filter but fill out the footprint field.

You can ignore the problems it points out about the symbol you did not really change. (Your pull request changed some whitespace characters of this second symbol.) But nobody would be mad if you fixed it anyways.

**Comment by evanshultz** [comment]
[4.11.v of the KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) states that footprint filters should be used even if a default footprints is provided.

**Comment by jkriege2** [comment]
Hi!

which KiCAD version did you use? Those extra whitespaces are introduced by older versions. Please use a current version (or nightly) to resave you contribution, so this whitespace noise goes away. In the current form we cannot merge that, as this noise will otherwise drag through the next PRs ...

Best,
JAN

**Comment by RaceMouse-of-Denmark** [comment]
Sorry about the inconvenience. I'll check it up against KLC 4.11.v. I used Kicad from the Mint repository. I'll pull the latest stable before recommitting. Thanks for the feedback!
/Fink

**Comment by RaceMouse-of-Denmark** [comment]
I believe I have squashed the last bugs in the PR, but please let me know if there are any more issues I have overlooked.
BR

**Comment by RaceMouse-of-Denmark** [comment]
While pending the review I took the liberty of adding a DRV8860 Relay driver as well...

**Comment by jkriege2** [comment]
Hi!

nice work!

Please make these changes:

## DRV8860: 
* [ ] pin-type of FAULT should be Open-Collector
* [ ] footprint should be `Housings_SSOP:TSSOP-16_4.4x5mm_Pitch0.65mm`
* [ ] FPFilter should be `TSSOP*4.4x5mm*Pitch0.65mm*`
* [ ] Think about adding a variant of this symbol with an additional pin 17 "PAD" next to GND that links to the footprint `Housings_SSOP:TSSOP-16-1EP_4.4x5mm_Pitch0.65mm`

## TPL9201 
* [ ] please ove the GND-pins 100mil lower so the text does not intersect
* [ ] Maybe elongate all pins to 150mil or 200mil so the pin-numbers do not interesct with the negation-circles (e.g. pin 14)
* [ ] move pin 18 "5Vout" to the top of the symbol
* [ ] rename to `TPL9201_TSSOP` and add `, TSSOP-20` to the description and set footprint to `Housings_SSOP:HTSSOP-20-1EP_4.4x6.5mm_Pitch0.65mm_ThermalPad` and the FPFilter to `HTSSOP*4.4x6.5mm*Pitch0.65mm*ThermalPad*`
* [ ] add a pin 21 "PAD" for the thermal pad (next to GND)
* [ ] maybe add variant `TPL9201_DIP` without the PAD-pin (add `, DIP-20` to the description) that links the appriopriate DIP-footprint: `Housings_DIP:DIP-20_W7.62mm` with FPFilter `DIP*W7.62mm*`

Best,
JAN

**Comment by RaceMouse-of-Denmark** [comment]
Hi Jan,

Thanks for great input!

DRV8860 updated as requested.
TPL9201 is a different matter. I have not moved 5Vout to the top since KLC 4.11-4.5.iv states that output should be placed on the right hand side of the symbol - and 5Vout is an output from the TPL9201, not a power pin for the TPL9201. Please correct me if I'm wrong.

BR
Fink

**Comment by jkriege2** [comment]
Hi!

all fine with me ... about the 5Vout: You're right ;-)

One more thing: Are you willing to also add the DIP variant? If not I'll merge, if yes, I'll wait until done ... Please let me know ;-)

Thanks,
JAN

**Comment by RaceMouse-of-Denmark** [comment]
Hi Jan,

You're right about the DIP variant. I might as well put it in. Then it's done and I have all the docs at hand anyways.


I'll add it so please wait with the merge :-)


Thanks again
Fink

---- On Thu, 27 Apr 2017 07:11:54 +0200 Jan W. Krieger &lt;notifications@github.com&gt; wrote ---- 

Hi!
 all fine with me ... about the 5Vout: You're right ;-)
 One more thing: Are you willing to also add the DIP variant? If not I'll merge, if yes, I'll wait until done ... Please let me know ;-)
 Thanks,
 JAN

**Comment by RaceMouse-of-Denmark** [comment]
Hi again,

Further investigation reviles that (apparently) only the HTSSOP package 
can be ordered. At least I could not find and DIP variants of the chip. 
I'll leave it for now.

Please merge :-)

BR

Fink

**Comment by jkriege2** [comment]
OK! THanks for the work you put in!

JAN

**Comment by Shackmeister** [comment]
yay danish people :D

**Pull request merged**
