### PR TITLE
Add D_2x2_ACom & Aliases

### PR DESCRIPTION
**Pull request by WillBickerstaff**
Added Switching Diode Arrays, 2 pair Common Anode

BAT54ADW
http://www.diodes.com/datasheets/ds30152.pdf

Rohm_UMP11N
http://rohmfs.rohm.com/en/products/databook/datasheet/discrete/diode/switching/ump11n.pdf

BAW56DW
http://www.diodes.com/datasheets/ds30146.pdf

BAW56S
http://www.nxp.com/documents/data_sheet/BAV756S_BAW56_SER.pdf

MMBD4448HADW
http://www.diodes.com/datasheets/ds30153.pdf

Toshiba_HN1D01FU
http://www.toshiba.com/taec/components2/Datasheet_Sync/200901/DST_HN1D01FU-TDE_EN_1882.pdf

### CODE REVIEW

**Comment by ricardocrudo** [comment]
same as in KiCad/kicad-library#254

**Comment by WillBickerstaff** [comment]
Corrected in last commit

**Comment by ricardocrudo** [comment]
> Corrected in last commit. Is this what you mean?

Almost.
As all part numbers have the same pin out, you just need to create one symbol and make others an alias of it.  This is, open BAT54ADW, click in 'edit component properties' (OpAmp ABC icon), go to Alias tab and add Rohm_UMP11N, BAW56DW, BAW56S, ...
Each alias can hold your own documentation, so just make sure you copied them before delete the other symbols you have done. Also, please adjust the symbol to be in agreement with KLC. You can use BAV99 as reference.

**Comment by WillBickerstaff** [comment]
Symbol has been redrawn using BAV99 as a template. Rohm_UMP11N is the parent element with all others aliased off this and documented independently. I've also changed the footprint filter to *SC-70-6* which negates the need, at least for these parts, for https://github.com/KiCad/SMD_Packages.pretty/pull/27 and https://github.com/KiCad/kicad-library/pull/253

**Comment by ricardocrudo** [comment]
hello @WillBickerstaff can you please update the PR to solve the conflict?

**Comment by WillBickerstaff** [comment]
Branch updated to resolve conflicts

**Comment by ricardocrudo** [comment]
Hi @WillBickerstaff, just to check, is this pic symbol supposed to be along with this PR?

**Pull request closed without merging**
