### PR TITLE
Added C[CA]56-21* display schematics

### PR DESCRIPTION
**Pull request by Fat-Zer**
Schematic for 7-segment displays:
CA56-21*
CC56-21*

PS: I'm not quite sure about the rules on the vertical align of the components...

### CODE REVIEW

**Comment by keruseykaryu** [comment]
IMO the common anode/cathode pins should be on the top not on the bottom.

**Comment by Fat-Zer** [comment]
> IMO the common anode/cathode pins should be on the top not on the bottom.

I've started with common cathode and more straightforward position for it is on the bottom. I had an idea to put pins for CA to the top, but dropped it in favour of convince.

Also In that case DP label slides to the line and that means that the should be redone completely. 

IMO it's not so big deal where the pins will be placed, but if you insist on moving them top I'll do that.

**Comment by keruseykaryu** [comment]
Many people uses this kind of schematic structure for LED displays:

displays

I think it is the best solution. Of course, not everyone may agree with such a statement.

**Comment by Fat-Zer** [comment]
Take a look.

**Comment by CarlPoirier** [comment]
I think it's great now!

**Comment by keruseykaryu** [comment]
It would be great if the pin endings will lay on the 100mils grid in Y direction too.

**Comment by Fat-Zer** [comment]
@keruseykaryu, thanks, missed that after the redraw...

**Comment by ricardocrudo** [comment]
Thanks @Fat-Zer

**Pull request merged**
