### PR TITLE
Added FAN3268 component

### PR DESCRIPTION
**Pull request by michalkona**
Added FAN3268 component (MOSFET driver) to ON Semiconductor library
fan3268

Documentation:
[FAN3268.pdf](http://www.onsemi.com/pub/Collateral/FAN3268T_F085-D.PDF)

### CODE REVIEW

**Comment by Misca1234** [comment]
You should change the description from
Low-Voltage 18V PMOS-NMOS Bridge Driver.
to
Low-Voltage 18V PMOS-NMOS Bridge Driver**, SOIC-8**

It is beneficial is you post a screen shoot of the component
have look at this contribution to get an idea
https://github.com/KiCad/kicad-library/pull/1712

**Comment by michalkona** [comment]
I fixed the description.

**Comment by jkriege2** [comment]
Hi!

sorry for the delay in reviw ... could you do some more minor changes please:
1. remove comma from keywords
2. I think this symbol looks better with pin name offset = 20mil (see image at end)
3. INB should be an INPUT not a POWER_INPUT

Thanks,
JAN

2017-11-06 21_01_28-part library editor -- d__kicad_kicad-library-review_library_onsemi lib

**Comment by michalkona** [comment]
Thank you for review, I fixed the reported issues.

**Comment by jkriege2** [comment]
great work,

Thanks,
JAN

**Pull request merged**
