### PR TITLE
added melexis MLX90363 line

### PR DESCRIPTION
**Pull request by oninoshiko**
This adds a library for Melexis, and the MLX90363 line of 3-axis Hall-effect sensors.

### CODE REVIEW

**Comment by diggit** [comment]
- Please arrange pins logically. SPI interface together on left, VDD on top, VSS bottom.
- Set rectangle outline thickness to 0.01" and BG fill.
- use `~`prefix for SS pin to overline it.
- 100mil pins are enough
- Keywords:
 - remove *mlx90363 melexis*
 - add *spi*
- FP filters:
 - use `SOIC-*` or `TSSOP-*` accordingly
- fix/extend description, nobody know between all aliases: Vsupply, resolution, interface, package (for single package symbols -  this case), order by importance (what is it > resolution > power supply > interface > ..... > manufacturer should be on last place)
- fix all - make all \*GO symbol parts looks same (all \*GO subparts should match with \*DC)

**Comment by diggit** [comment]
Oh and.
- SS and MOSI are inputs
- test is bidir

**Comment by oninoshiko** [comment]
Thanks for going over this for me,

I believe this corrects the deficiencies, although I'm not confident I did the FP filters correctly, so please take care there when re-reviewing.

**Comment by oninoshiko** [comment]
So, I've made these changes. Almost everything seems to work for me, except the Test pin. While the datasheet lists this pin as Bi-Directional, as far as I can tell, it is ALWAYS tied to GND. I certainly do, as does the reference circut. Unfortunately doing this, causes a "Conflict between pins" warning.

Any ideas for how I can resolve this conflict?

**Comment by diggit** [comment]
As test pins can be left floating or grounded, I'd set them as passive and place near to GND (bottom edge).
 
Also:
- place **Name** and **Reference** outside of symbol, above i preferred
- set **Reference** horiz. alignment appropriately - to prevent overlapping with symbol when it expands due to long reference like U1000.
- swap **VSS** and **VDEC** symbols, VSS is ground -> botom edge, VDEC is 3V3 power supply/decoupling
- set **VDEC** as passive, because with Vdd=5V is VDEC power output, and with Vdd=3.3V behaves like power input.

DUAL:
- set symbol FP to: **Housings_SSOP:TSSOP-16_4.4x5mm_Pitch0.65mm**, check invisible and place below symbol
- and FP filter to: __TSSOP\*4.4x5mm\*Pitch0.65mm\*__

SINGLE:
- set symbol FP to: **Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm**, check invisible and place below symbol
- and FP filter to: __SOIC\*3.9x4.9mm\*Pitch1.27mm\*__



Can you move your symbols to sensor library? Other won't have to add another library...

**Comment by oninoshiko** [comment]
Great, I'll get these changes done this week, hopefully tomorrow, and push again.

I can move them to whatever library makes you all happy, I just stuck it in a mfg library because I didn't know where you would want it.

Thanks!

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Hi @oninoshiko   Sorry your pull request got forgotten for so long. 

If you are still interested in contributing, please check the results of the KLC checks: https://travis-ci.org/KiCad/kicad-library/builds/249604043?utm_source=github_status&utm_medium=notification

The latest KiCad Library Convention is here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

@SchrodingersGat are you OK with a new manufacturer library `melexis.lib`?

Many thanks

**Comment by hackscribble** [comment]
Closing inactive PR.

**Pull request closed without merging**
