### PR TITLE
Ea e diptft57 a

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIPTFT57-A (and it's alias EA eDIPTFT57-ATP)

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/ediptft57-ae.pdf

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1495

pretty push branch is 
https://github.com/KiCad/Displays.pretty/pull/27

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/110

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/37

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

**Comment by SchrodingersGat** [comment]
Fix conflicts please :)

**Comment by Misca1234** [comment]
The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

**Comment by SchrodingersGat** [comment]
Darn looks like we're going to have to merge these one at a time. Please fix conflicts here (but not in other PRs yet). Once this is merged, we'll move on to the next one.

Sorry for the fuss.

**Comment by Misca1234** [comment]
Ok, np, (however i merged two others before I saw this comment)

**Comment by Misca1234** [comment]
Shall I recreate these pushes, we might get better control over what is merged ?

**Comment by SchrodingersGat** [comment]
@Misca1234 if you can recreate all your outstanding PRs as a single PR, that will make it easier

**Comment by Misca1234** [comment]
ok, but it will only concern the symbols.
I keep the pretty and 3D models pushes as they are ?

**Comment by SchrodingersGat** [comment]
That makes sense

**Pull request merged**
