### PR TITLE
KLC cleaning the audio library

### PR DESCRIPTION
**Pull request by maqifrnswa**
Changes:

- added missing datasheet (one symbol)
- added missing footprints and footprint filters (several symbols)
- fixed font sizes on all symbols
- set outlines to 10 mil thickness and background filled (on many symbols)
- moved pins to be on 100 mil grid (on LL1587, LM1875, LM1876, LM1877*, LM3886*) and made pins 50 mil increments

still more work to be done, but it's a starting point

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

I'm having a look now ... there is also a second contributor proposing changes to audio.lib. Please have a look here: https://github.com/KiCad/kicad-library/pull/1207

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

OK, I had a short look. Generally this is a good start.

One major thing: Travis (https://travis-ci.org/KiCad/kicad-library/builds/231028803?utm_source=github_status&utm_medium=notification) still complains about several pins not on a 100mil grid. Could you please fix this?

Also I've found several symbols that should be moved elsewhere:
1. the matched transistors should be in `transistors.lib` and the symbols should conform to the (new) standard from `device.lib`.
2. the transformer `TR-AUDIO-2P` should go to device.lib and match the standard there.
3. The actual transformer `LL1587` should go to `transf.lib` (which need serious cleaning and fusing/matching with device.lib)

Would be good if you could move the transistors and transformers (have a look at `Transformer_AUDIO` from `device.lib`). Then I would say we merge this PR for now and you can open an extended PR for more changes (styles ...). OK?

Best,
JAN

**Comment by maqifrnswa** [comment]
I've done the suggested changes as a first step of the clean up. They are listed below:

> Also I've found several symbols that should be moved elsewhere:
> 
> the matched transistors should be in transistors.lib and the symbols should conform to the (new) standard from device.lib.
> the transformer TR-AUDIO-2P should go to device.lib and match the standard there.
> The actual transformer LL1587 should go to transf.lib (which need serious cleaning and fusing/matching with device.lib)
> Would be good if you could move the transistors and transformers (have a look at Transformer_AUDIO from device.lib). Then I would say we merge this PR for now and you can open an extended PR for more changes (styles ...). OK?
>

**Comment by jkriege2** [comment]
Hi!

- please move `TR-AUDIO-2P` to `device.lib` (and use the style used there). We try to collect all generic symbols in device.lib and the special symbols in other libs.
- please use the transistor style from transistors.lib for the moved transistors.
- Why did you delete the docu for `TDA2003V`?
- please set correct footprints in `LM4950TA`, `LM4950TS`, `TDA2005R`, `TDA7294`
- please move `NSL-32` to opto.lib
- `SSM*` PGA4311, PAM8302A, MSGEQ7: add package to description
- LM1877M/N can be uified into one symbol with FPFilters-only
- SSM2220 is still in audio.lib
- `STK*` do you know which packages they need?

Best,
JAN

**Comment by jkriege2** [comment]
please fix merge conflicts!

**Comment by evanshultz** [comment]
@maqifrnswa 
Please reply to this comment if you're interested in contributing to KiCad. If I don't hear from you in 2 days I'll close this case due to inactivity. We appreciate your contributions and hope to merge your fixes!

**Comment by evanshultz** [comment]
Closing since https://github.com/KiCad/kicad-library/pull/1560 does all this and more.

**Pull request closed without merging**
