### PR TITLE
	add:       library/icroute.lib and icoute.dcm

### PR DESCRIPTION
**Pull request by tracing1017**
add:       library/icroute.lib  
add:       library/icroute.dcm

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Proposed symbol does not meet the [KiCad Library Convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) rules. Please fix these issues.

**Comment by keruseykaryu** [comment]
Many pins of LD3220 are still out of KLC recommended grid.

The documentation fields of ZETLER AZ850P2-X symbol (from `relays.lib`) will be removed if this request will be merged. Have no idea why these lines are marked for deletion.

**Comment by tracing1017** [comment]
Hi keruseykaryu. Can you give me some hints? For example

**Comment by CarlPoirier** [comment]
Kerusey says the pin ends must be aligned on a 100mil grid. Please make sure all rules are met and that no other symbol is worsened.

Thanks!

**Comment by tracing1017** [comment]
Hi CarlPoirier. I don't know how to align zhe pin on a 100mil grid. The max grid size is 50mil. The pin length is 150mil.

**Comment by keruseykaryu** [comment]
> I don't know how to align the pin on a 100mil grid. The max grid size is 50mil.
It's not the problem. Zoom out a bit until you see the grid in double spacing or use the coordinates shown on status bar.

**Comment by hackscribble** [comment]
Closing and re-opening to generate Travis checks.

**Comment by hackscribble** [comment]
Re-opening to generate Travis checks.

**Comment by hackscribble** [comment]
Closing to trigger Travis checks.

**Comment by hackscribble** [comment]
If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and adjust your contribution to the new library convention.

Many thanks

**Pull request closed without merging**
