### PR TITLE
Stm8 af6223

### PR DESCRIPTION
**Pull request by slartibartfas81**
add device STM8AF6223

### CODE REVIEW

**Comment by slartibartfas81** [comment]
http://www.st.com/resource/en/datasheet/stm8af6223.pdf
grafik

**Comment by SchrodingersGat** [comment]
It appears that the pinout you have used matches the STM8AF6223**A** part! There are a number of pins that don't match the datasheet.

**Comment by slartibartfas81** [comment]
@SchrodingersGat indeed i mixed up the pinout with the ..A part, sorry for that.

**Comment by slartibartfas81** [comment]
accidentally closed the branch...

**Comment by SchrodingersGat** [comment]
One small change:

Too much detail for package in description line: e.g. change `TSSOP20 (6.5 x 4.4 mm, 0.65 mm pitch)` to simply `TSSOP20`

**Pull request merged**
