### PR TITLE
added ST's LSM303C and LSM6DS3 mems sensor

### PR DESCRIPTION
**Pull request by nuntipat**
Two ST's mems sensor have been added ([LSM303C](http://www.st.com/resource/en/datasheet/lsm303c.pdf
) and [LSM6DS3](http://www.st.com/resource/en/datasheet/lsm6ds3.pdf)). The pull request for the footprint of the LSM6DS3 can be found [here](https://github.com/KiCad/Housings_LGA.pretty/pull/14). 

Thank you,
Nuntipat

### CODE REVIEW

**Comment by lavadew** [comment]
Could you please add a png screenshot of the symbol to this PR, so that we can have a look at it and maybe give advice, what should be changed.
Thank you :)

**Comment by nuntipat** [comment]
Here are the screenshots. Thank you.

lsm303c
lsm6ds3

**Comment by lavadew** [comment]
LGTM!

**Comment by SchrodingersGat** [comment]
To me, too. Thanks @nuntipat

**Comment by nuntipat** [comment]
Thank you. Could you please also look at pull request for the [footprint](https://github.com/KiCad/Housings_LGA.pretty/pull/14) of these parts?

**Comment by SchrodingersGat** [comment]
@nuntipat you will have to re-submit the footprint to the new footprints repository at https://github.com/kicad/kicad-footprints

We are working hard on the new libraries and have marked the old ones as legacy. Thanks.

**Comment by nuntipat** [comment]
@SchrodingersGat Thank you. I'll create a new pull request then.

**Pull request merged**
