### PR TITLE
Ea e dip160 xxx

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIP160B-7LW
Aliases: EA eDIP160B-7LWTP, EA eDIP160W-7LW and EA eDIP160W-7LWTP

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/edip160-7e.pdf

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1502

pretty push branch is
https://github.com/KiCad/Displays.pretty/pull/30

packages3D push branch is
https://github.com/KiCad/packages3D/pull/113

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/40

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
This one have aliases and default RS-232 as well, I guess it will be updated 
https://github.com/KiCad/kicad-library/pull/1494
is sorted out

**Comment by SchrodingersGat** [comment]
Please fix conflicts ):

**Comment by Misca1234** [comment]
Let us wait with this one until 
https://github.com/KiCad/kicad-library/pull/1495
is merged.
https://github.com/KiCad/kicad-library/pull/1495
Messes up the lib and dcm for each of my displays pushes

**Comment by Misca1234** [comment]
This push have been repalced by 
https://github.com/KiCad/kicad-library/pull/1647

**Pull request closed without merging**
