### PR TITLE
Kps 5130

### PR DESCRIPTION
**Pull request by Misca1234**
Fixing KPS-1530 in opto.lib

http://www.kingbright.com/attachments/file/psearch/000/00/00/KPS-5130PD7C(Ver.14).pdf

The foot print have been modified 
A 3D model have been created 

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1555

pretty push branch is
https://github.com/KiCad/Opto-Devices.pretty/pull/16

packages3D push branch is
https://github.com/KiCad/packages3D/pull/124

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/49

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
See my comment on the footprint: https://github.com/KiCad/Opto-Devices.pretty/pull/16 Please update here, when done there1

Thanks,
JAN

**Comment by Misca1234** [comment]
Yo! da blingy is in your turf man

**Comment by jkriege2** [comment]
Hi!

I already merged the 3D model-repos and footprint ... one last thing to change in this symbol:
In the older version there was a dot connecting the cathode wires at the juction, Could you please add that to you symbol?

Thanks,
JAN

**Comment by Misca1234** [comment]
Something like this ?

bild

**Comment by jkriege2** [comment]
exactly!

THanks,
JAN

**Pull request merged**
