### PR TITLE
Overhaul and additions to IR library

### PR DESCRIPTION
**Pull request by evanshultz**
Like some of my recent PRs, this is a big one to get as close to KLC compliant as I believe is possible for an entire library. My original intent was to just update the library and add a few parts, but when I saw how similar all the gate drivers and high-side switches were, I decided to implement those entire product categories. I did perhaps go too far, but hopefully having all IR parts will be a benefit to KiCad users.

Changes:
- Updated all datasheet links to Infineon website
- Added package type to all descriptions
- Standardized all descriptions to `<description>, <voltage>, <drive current>, <package>`
- Set pin name offset to 20mil
- Replaced '-' in FPfilter with '?'
- Added other packages/pinouts for existing parts (IRS2186/IRS21864, IR2181/IRS21814, etc.)
- Split IR2110/IR2113 into DIP and SOIC packages since the pinout is different (they were together!)
- Figured out a standard pinout and symbol for the standard/generic (non-class D) drivers
- Moved power pins to top and bottom of AUIPS* symbols
- Stacked pins where possible
- Used ALIAS instead of discrete symbols where possible
- Removed IR2186 (I only find a prelim datasheet online and nothing in Infineon's site)

Additions:
Added all active IR parts at these links:
- https://www.infineon.com/cms/en/product/power/smart-low-side-and-high-side-switches/automotive-smart-high-side-switch-profet/channel.html?channel=ff80808112ab681d0112ab69e2d40357
- https://www.infineon.com/cms/en/product/power/smart-low-side-and-high-side-switches/automotive-smart-low-side-switch-hitfet/channel.html?channel=ff80808112ab681d0112ab69de540349#goto_producttable
- https://www.infineon.com/cms/en/product/power/gate-driver-ics/level-shift-gate-drivers/half-bridge-drivers/channel.html?channel=5546d46259b0420a0159b21869676ee7
- https://www.infineon.com/cms/en/product/power/gate-driver-ics/level-shift-gate-drivers/high-and-low-side-drivers/channel.html?channel=5546d46259b0420a0159b21868816ee6
- https://www.infineon.com/cms/en/product/power/audio-driver-ics/class-d-audio-ics/channel.html?channel=5546d4624d6fc3d5014d9f02822355fb
- https://www.infineon.com/cms/en/product/power/gate-driver-ics/level-shift-gate-drivers/gate-driver-support-ics/channel.html?channel=5546d46259b0420a0159b2186b526ee9
- https://www.infineon.com/cms/en/product/power/ac-dc-power-conversion/ac-dc-pwm-pfc-controller/pfc-dcm-discontinuous-conduction-mode-ics/channel.html?channel=ff80808112ab681d0112ab6a73f6050c
- https://www.infineon.com/cms/en/product/power/ac-dc-power-conversion/ac-dc-pwm-pfc-controller/pfc-ccm-continuous-conduction-mode-ic/channel.html?channel=ff80808112ab681d0112ab6a716f0504
- https://www.infineon.com/cms/en/product/power/ac-dc-power-conversion/ac-dc-pwm-pfc-controller/synchronous-rectification-ics/channel.html?channel=5546d4624e765da5014e8d67a6396b78
- https://www.infineon.com/cms/en/product/power/audio-driver-ics/powiraudio-integrated-amplifiers/channel.html?channel=5546d4624d6fc3d5014d9f02813f55fa

Whew!

Since there are so many parts, I've gathered a representative group here:
image

Similarly, there are too many datasheets to list individually. Here are the ones for the parts above:
- https://www.infineon.com/dgdl/Infineon-AUIPS1041-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aae14a0524c63
- https://www.infineon.com/dgdl/auips6011.pdf?fileId=5546d462533600a4015355a787bf1309
- https://www.infineon.com/dgdl/ir1153.pdf?fileId=5546d462533600a4015355c42a5b1649
- https://www.infineon.com/dgdl/ir1155spbf.pdf?fileId=5546d462533600a4015355c431f9164b
- https://www.infineon.com/dgdl/ir1161lpbf.pdf?fileId=5546d462533600a4015355c439a5164d
- https://www.infineon.com/dgdl/ir11662spbf.pdf?fileId=5546d462533600a4015355c44195164f
- https://www.infineon.com/dgdl/ir11682spbf.pdf?fileId=5546d462533600a4015355c47188165a
- https://www.infineon.com/dgdl/ir11688spbf.pdf?fileId=5546d462533600a4015355c47c70165c
- https://www.infineon.com/dgdl/ir1169.pdf?fileId=5546d462533600a4015355c485c4165e
- https://www.infineon.com/dgdl/ir2010.pdf?fileId=5546d462533600a4015355c48f901660
- https://www.infineon.com/dgdl/ir2011.pdf?fileId=5546d462533600a4015355c49b831663
- https://www.infineon.com/dgdl/auips7111s.pdf?fileId=5546d462533600a4015355a7c94e1326
- https://www.infineon.com/dgdl/Infineon-IR2085S-DS-v01_02-EN.pdf?fileId=5546d4625b62cd8a015bb0f752184828
- https://www.infineon.com/dgdl/ir2101.pdf?fileId=5546d462533600a4015355c7a755166c
- https://www.infineon.com/dgdl/ir2103.pdf?fileId=5546d462533600a4015355c7b54b166f
- https://www.infineon.com/dgdl/ir2104.pdf?fileId=5546d462533600a4015355c7c1c31671
- https://www.infineon.com/dgdl/ir2108.pdf?fileId=5546d462533600a4015355c7dc321676
- https://www.infineon.com/dgdl/ir21091.pdf?fileId=5546d462533600a4015355c7f66f167c
- https://www.infineon.com/dgdl/ir2109.pdf?fileId=5546d462533600a4015355c7e85b1679
- https://www.infineon.com/dgdl/ir2111.pdf?fileId=5546d462533600a4015355c810e51682
- https://www.infineon.com/dgdl/ir2153.pdf?fileId=5546d462533600a4015355c8c5fc16af
- https://www.infineon.com/dgdl/ir2114ss.pdf?fileId=5546d462533600a4015355c836cd168a
- https://www.infineon.com/dgdl/ir2175.pdf?fileId=5546d462533600a4015355c9161216c6
- https://www.infineon.com/dgdl/ir25607.pdf?fileId=5546d462533600a4015355ca0e7916f5
- https://www.infineon.com/dgdl/ir25750lpbf.pdf?fileId=5546d462533600a4015355ca1d0e16f7
- https://www.infineon.com/dgdl/ir4301.pdf?fileId=5546d462533600a4015355d5fc691819
- https://www.infineon.com/dgdl/ir4302.pdf?fileId=5546d462533600a4015355d602a9181d
- https://www.infineon.com/dgdl/irs2052mpbf.pdf?fileId=5546d462533600a401535675d3b32788
- https://www.infineon.com/dgdl/irs2092.pdf?fileId=5546d462533600a401535675f1be2790
- https://www.infineon.com/dgdl/ir21771s.pdf?fileId=5546d462533600a4015355c9222c16c8
- https://www.infineon.com/dgdl/ir2177s.pdf?fileId=5546d462533600a4015355c92e7416cb
- https://www.infineon.com/dgdl/irs2093mpbf.pdf?fileId=5546d462533600a401535675fb892793
- https://www.infineon.com/dgdl/irs20957spbf.pdf?fileId=5546d462533600a401535676143e2799
- https://www.infineon.com/dgdl/irs20965spbf.pdf?fileId=5546d462533600a4015356761d8b279b
- https://www.infineon.com/dgdl/Infineon-IRS2452AM-DS-v01_00-EN.pdf?fileId=5546d462584d1d4a01584ee4f1f00713
- https://www.infineon.com/dgdl/irs2505lpbf.pdf?fileId=5546d462533600a40153567ad42c2819
- https://www.infineon.com/dgdl/irs25751lpbf.pdf?fileId=5546d462533600a40153567b31da2837
- https://www.infineon.com/dgdl/Infineon-IRS2890DS-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aad6fbc8a4bf4

Notes:
- I left these parts in ir.lib since they'll be reorganized anyway, but can move to infineon.lib if required
- I've separated symbols by package so each symbol only has "correct" footprints (see https://github.com/KiCad/kicad-library/pull/1498)
- Multichannel class D ICs (IRS2052M, IRS2093M, IRS2452AM, IR43x2) use multiple units
- I've confirmed with Infineon about the exposed pad connections where the datasheet doesn't say
- Some footprints don't use the expected number of pins; see [IR43x2](https://www.infineon.com/dgdl/ir4302.pdf?fileId=5546d462533600a4015355d602a9181d) which is "PQFN 44" but only has 31 pins and also where pins 15, 28, and 31 are all tied together (I used the EP pin number)
- I'm working on the 5 (quite complicated!) MLPQ and PQFN footprints now

I believe all KLC violations are OK:
IR2010/2010S/IR4301/IR4302/IRS2052M/IRS2092/IRS2093M/IRS20957S/IRS20965S/IRS2113M/IRS2452AM:
- GND, VSS, VAA, and VCC are best where they are (I believe)
IR25750L:
- CS is in fact an output
IRS2052M/IRS2092/IRS02093M/IRS20957S/IRS20965S:
- VREF is actually a regulator output

### CODE REVIEW

**Comment by evanshultz** [comment]
DO NOT MERGE YET! Infineon hasn't gotten back to me with the thermal pad connections for IRS2001M, IRS2005M, and IRS21844M.

**Comment by evanshultz** [comment]
See above. I received all the outstanding info so this can be reviewed. Please see the note above, especially about pin naming of the MLPQ/PQFN footprints since it's weird. Suggestions?

**Comment by evanshultz** [comment]
For reference, here are images of the unfinished footprints that go with this PR:
image

There are some questionable dimensions in the app note which I'm working out with Infineon.

**Comment by SchrodingersGat** [comment]
@evanshultz this is a huge contribution, I totally missed it!

I would suggest that the footprints are so specific that they should have the manufacture name prepended. They are very weird!

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks! I didn't push on this PR because the footprints weren't ready. But I finally got info on the last footprint and submitted footprints at https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/66. Once that PR is merged, I'll need to update footprint names here and then I'll push to get this PR merged.

**Comment by evanshultz** [comment]
Updated footprint names that were included in the two merged PRs above. This is now ready for review. Please read from the first post and take into account the comments and notes I've made. Thanks!

**Comment by SchrodingersGat** [comment]
I think I'm happy with this. Thanks for this great contribution :)

**Pull request merged**
