### PR TITLE
Adjusted the PIC12 symbol names to the new KLC

### PR DESCRIPTION
**Pull request by lavadew**
Adjusted the PIC12 symbol names to the new KLC and created an alias for every LF variant.

### CODE REVIEW

**Comment by lavadew** [comment]
saw some errors @ travis, will tackle them tomorrow.

**Comment by SchrodingersGat** [comment]
Looks like you are missing some documentation for some of the part aliases

**Comment by lavadew** [comment]
still not happy with the travis results, i'm on it.

**Comment by SchrodingersGat** [comment]
Thanks @lavadew :)

Just a heads up - if you make further commits, we do not get notified unless you make a comment here. So please bump the thread when it's ready for review!

Great work!

**Pull request merged**
