### PR TITLE
Added FQD13N06

### PR DESCRIPTION
**Pull request by AndrewKrill**
Added N-Channel QFET MOSFET

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi @AndrewKrill! Thanks for contributing to KiCad's library!

First, please see the [KLC ](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)and [FAQ](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions). It will give you details on how library parts must be constructed to be accepted into KiCad's library.

One thing that will help is to put the datasheet and an image of the symbol in the PR. Right here. That will make reviewing the submission much easier.

Also, many of the KLC rules are being checked automatically when your PR is submitted. You can see above that there were violations, and more information is available by clicking on the "Details" link above. Please have a look and resolve the issues there.

Thanks again!

**Comment by AndrewKrill** [comment]
Got it. I updated the part to fix the problems it was having. (I believe).

image

http://datasheet.octopart.com/FQD13N06LTM-Fairchild-Semiconductor-datasheet-30895186.pdf

**Comment by jkriege2** [comment]
Hi!

Thanks for the contribution.

We have a set of generic transistors in device.lib that should be used to make specific transistors (to ensure that the visual style is comparable over libs ... and yes I know that many symbols in transistors.lib do not comply with that). Please base you symbol on `Q_NMOS_GDS` (note the slight style differences):
2017-04-21 15_04_45-eeschema kicad-library-review _ d__kicad_kicad-library-review-project
Should travis complain about misplaced pins (on a 50mil-grid instead of a 100mil-grid): These errors can be ignored for symbols of small devices, such as resistors, transistors, ...


This symbol will only work with the verically mounted TO-251 variant. Therefore please set the footprint to `TO_SOT_Packages_THT:TO-251_IPAK_Vertical` and the FPFilter to `TO*251*Vertical*`. Also please rename the transistor to `FQD13N06_TO251`. Then we can make a second version for the D-PAK packag version. Finally: Maybe add `, TO-251/IPAK` to the description (so people can also search forIPAK).

Best,
JAN

**Comment by SchrodingersGat** [comment]
As we are now close to moving all the symbols to the new kicad-symbols repository, this PR will have to be reissued at https://github.com/kicad/kicad-symbols

Thanks for your contributions, and sorry for the inconvenience

**Pull request closed without merging**
