### PR TITLE
Added various OneWire symbols

### PR DESCRIPTION
**Pull request by samdolt**

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Why not create a simple `maxim.lib`? I have plan to add this library with symbols from `special.lib` #153.

**Comment by samdolt** [comment]
Because Maxim has a lot of 1-Wire chips (~50 IC).

And if we follow strictly KLC rules 1.1 and 1.3, maxim.lib should be Maxim.lib.

**Comment by CarlPoirier** [comment]
Indeed, all libraries should at one point be renamed!

It can be Maxim.lib. I'm not sure if 50 ICs needs their own library.

**Comment by El3ctr0nic** [comment]
Please hurry up with Maxim lib ;]. I want add MAX31855 and some A/D converters

**Comment by CarlPoirier** [comment]
Any of you can create the new library!

**Comment by keruseykaryu** [comment]
MAX31855 - We have `sensors.lib` for this kind of devices.
A/D converters - We have `adc-dac.lib` where they fit perfectly.

So. Even if you don't want to create `maxim.lib` library, you don't need to waste your time waiting for us.

**Comment by samdolt** [comment]
If we don't rename all library before the new library system, I think it is better to keep small caps for new library, to be consistent. So I have renamed Maxim_1-Wire to maxim.lib.

**Comment by keruseykaryu** [comment]
OK. I will commit as is now. Carl as a major commander will give the signal whether rename or not.

**Comment by CarlPoirier** [comment]
Thanks guys.

We definitely have to do the renaming before the KiCad stable release. I will warn people on the mailing lists and proceed to the renaming in one week from now, so on April 8th.

**Pull request merged**
