### PR TITLE
Pull request traco ten20

### PR DESCRIPTION
**Pull request by dejfson**
Hi guys,

I have added symbols for TRACO Isolated DC/DC 'win' (extended range of input voltages) converters. As I do it for the first time, I'd like to get some feedback, so I can improve for the next time. Footprint will follow

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

very nice work already! Only some minor changes please:
1. Please ensure that all pins are on a 100mil grid (your's are on a 50mil grid91
2. The FPFilter should be `DCDC?Conv?TRACO?TEN20?xxxx*` for the footprint you give (maybe wait for the FP to be merged/reviewed if there are name-changes ...).

As this is your first commit: We have a set of rules for symbols and footprints, called KLC. You can find them here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention There also exist a set of Python scripts (https://github.com/KiCad/kicad-library-utils) that check some of these rules and even correct some bugs. Finally we are working on an overhaul of these rules (mostly clarifications, adding what we learned of the pas months, better explanations, example images). The current version is here: https://github.com/SchrodingersGat/kicad-library/wiki/KLC So please orient your PR on the rules in the latter document!

best,
JAN

**Comment by jkriege2** [comment]
PS: A final question: I pressume you drew the 3D symbol yourself?

**Comment by jkriege2** [comment]
Hi!

OK. Please also change the footprint filter as stated above and let me know about the 3D model. Then I can merge!

JAN

**Comment by dejfson** [comment]
Hi Jan,

please wait a bit, i'm playing with footprint for the moment, you'll get all packed this afternoon. I had to make quite a lot of changes for footprint to make it compliant with the verification scripts and I guess it will need your eyes once more.

thanks
.d.

----------------------------------------------
Dr. David Belohrad, Div. BE-BI
C.E.R.N. Site de Prevessin, F-01631 CERN CEDEX
http://www.cern.ch
David.Belohrad@cern.ch
Tel +41.22.76.76318  Fax +41.22.76.69056
GSM +41.75.411.3455
----------------------------------------------

**Comment by dejfson** [comment]
ok, pushed. have a look please. and yes, the 3D model is done by me

**Comment by dejfson** [comment]
oops, yet footprint filter..

**Comment by dejfson** [comment]
ok, ready for review
thanks

**Comment by jkriege2** [comment]
Very ncie work!
JAN

**Pull request merged**
