### PR TITLE
Added Texas Instruments NexFET N-Channel MOSFETs in SON8_5x6mm package

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added the following aliases with complete descriptions:

CSD17578Q5A
CSD17579Q5A
CSD16570Q5B
CSD17577Q5A
CSD18509Q5B
CSD18540Q5B
CSD17573Q5B
CSD17576Q5B
CSD19534Q5A
CSD17570Q5B
CSD19533Q5A
CSD19502Q5B
CSD19532Q5B
CSD19531Q5A
CSD18563Q5A
CSD18537NQ5A
CSD18532NQ5B
CSD17556Q5B
CSD18502Q5B
CSD18532Q5B
CSD17552Q5A
CSD17559Q5
CSD18534Q5A
CSD18533Q5A
CSD17555Q5A
CSD17551Q5A
CSD18501Q5A
CSD18503Q5A
CSD18504Q5A
CSD18531Q5A
CSD17553Q5A
CSD16342Q5A
CSD17322Q5A
CSD17327Q5A
CSD17522Q5A
CSD17527Q5A
CSD17501Q5A
CSD17506Q5A
CSD17505Q5A
CSD17507Q5A
CSD17510Q5A
CSD17311Q5
CSD17312Q5
CSD17303Q5
CSD16415Q5
CSD17302Q5A
CSD17305Q5A
CSD17306Q5A
CSD17307Q5A
CSD17310Q5A
CSD17301Q5A
CSD16408Q5
CSD16322Q5
CSD16325Q5
CSD16321Q5
CSD16414Q5
CSD16401Q5
CSD16403Q5A
CSD16404Q5A
CSD16407Q5
CSD16410Q5A
CSD16412Q5A
CSD16413Q5A

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Added following aliases BSCxxx series of Infineon OptiMOS fets

BSC026N08NS5ATMA1
BSC030N08NS5ATMA1
BSC035N10NS5ATMA1
BSC037N08NS5ATMA1
BSC040N10NS5ATMA1
BSC040N08NS5ATMA1
BSC046N10NS3GATMA1
BSC047N08NS3GATMA1
BSC052N08NS5ATMA1
BSC057N08NS3GATMA1
BSC060N10NS3GATMA1
BSC061N08NS5ATMA1
BSC070N10NS3GATMA1
BSC070N10NS5ATMA1
BSC072N08NS5ATMA1
BSC079N10NSGATMA1
BSC082N10LSGATMA1
BSC098N10NS5ATMA1
BSC100N10NSFGATMA1
BSC105N10LSFGATMA1
BSC109N10NS3GATMA1
BSC117N08NS5ATMA1
BSC118N10NSGATMA1
BSC123N08NS3GATMA1
BSC123N10LSGATMA1
BSC159N10LSFGATMA1
BSC160N10NS3GATMA1
BSC196N10NSGATMA1
BSC252N10NSFGATMA1
BSC265N10LSFGATMA1
BSC340N08NS3GATMA1
BSC440N10NS3GATMA1

**Comment by diggit** [comment]
Why did you split Infineon and Ti transistors in last commit (6efcfdc)? Symbols are identical and manufacturer info does not affect symbol. This information should go to description.

Did you use scripts to modify files directly? I'm just curious, where these spacing changes come from.

**Comment by SchrodingersGat** [comment]
@diggit the split was done only so I could add the manufacturer field into the component itself. Is there a way to add field data to an alias (and not to the component itself?) If so, this would be a much better way to do it.

These were added using a simple python script to drag part info out of the manufacturer product table so updating will be easy. 

LMK if there's a way to add extra info to the ALIAS

**Comment by diggit** [comment]
@SchrodingersGat  There is no actual way how to add fields into documentation like it is possible for symbol. I'd like to see additional fields in documentation in future, but this is actual state.
Since symbol is identical, you should put manufacturer into description and alias them all to one symbol. Is shouldn't be problem to modify your script. A can't imagine situation, when you need to see manufacturer directly in schematics.

**Comment by SchrodingersGat** [comment]
Yep, fair enough. I've reverted the last commit so that all ALIASes are from the one symbol

**Comment by diggit** [comment]
- You left Manufacturer field in symbol. Please remove it.
- In closer look, junction dots in symbol are arcs, set their thickness to sth like 0.01 to make it look like dots.

Nothing else prevents merging.

**Comment by SchrodingersGat** [comment]
@diggit - done, thanks :)

**Comment by diggit** [comment]
@SchrodingersGat could you do the same for junctions inside transistor itself? :D (0.007 looks enough, if you wan to keep them smaller)

**Comment by SchrodingersGat** [comment]
@diggit  the things I do for you! ;)

**Comment by diggit** [comment]
You are doing it for all KiCad users :)
Nice work you did, merged.

**Pull request merged**
