### PR TITLE
- added Z32F06423AKE/AEE and made Z80CPU and Z8530 KLC compliant

### PR DESCRIPTION
**Pull request by lightlace**
Hi,

here is my second try on contributing to the KiCAD libraries.

What i've done:

- added Z32F06423AKE and Z32F06423AEE (one comes in LQFP-32 and one comes in LQFP-48)
- made Z80CPU and Z8530 more KLC compliant (adjusted the text size and added a datasheet for Z8530).

Best Regards,
Lightlace

### CODE REVIEW

**Comment by hackscribble** [comment]
Hi @lightlace 

Thanks for the contribution.  To help with the review process, could you post screenshots of the symbols and links for the datasheets.

Thanks

**Comment by lightlace** [comment]
Hi @hackscribble,

sorry, forgot that stuff completely in the morning..

Datasheets:
- Z8530: http://www.zilog.com/docs/serial/ps0117.pdf
- Z32F06423AKE/AEE: http://www.zilog.com/docs/PS0392.pdf
z32f06423aee
z32f06423ake

**Comment by lightlace** [comment]
@hackscribble *poke*

**Comment by hackscribble** [comment]
Hello @lightlace 

I've done an initial review of the two new components ...AEE and ...AKE. While you are making these changes, I will review your updates to the existing symbols today.

Many thanks
 

### Both symbols

1. Our preferred approach on multi-function pins in CPUs and similar is to shorten the pin name to just the GPIO part.  This allows the size of the symbol body to be reduced.  For example, `PA3` instead of `PA3/SCK/STBO/AN3`.  (See discussion here: https://github.com/KiCad/kicad-library/issues/1145)

2. With 2-digit pin numbers, the length of the pins can be reduced to 150mil.

3. When you redraw the symbol body, please make sure that it is centred about (0,0).

4. The datasheet calls the power supply pins `VDD` and `GND` in some places and `AVDD/VDD` and `AGND/GND` in others.  Whichever version you prefer, it should be the same across the two symbols. 

### AKE

5. Pins 11, 12 and 13 are missing.

6. Set the footprint field to `Housings_QFP:LQFP-32_7x7mm_Pitch0.8mm`.

### AEE

7. Set the footprint field to `Housings_QFP:LQFP-48_7x7mm_Pitch0.5mm`.

**Comment by poeschlr** [comment]
The footprint filters should also be made more specific. They should include the mechanical size specification of the footprint.
Example: for the one where you set the footprint field to `Housings_QFP:LQFP-32_7x7mm_Pitch0.8mm`
set the footprint filter to `LQFP*7x7mm*Pitch0.8mm*`

**Comment by hackscribble** [comment]
One review point on the Z8530.  Please change the footprint filter to match the package width as well as the type: `DIP*W15.24mm*`.

**Comment by hackscribble** [comment]
And review points on Z80CPU:

i. I believe the original Z80 represented by this symbol only came in the DIP-40 0.6 inch spacing package?  If so, then you can set the footprint field to `Housings_DIP:DIP-40_W15.24mm`.
ii. Please change the footprint filter to `DIP*W15.24mm*`.

**Comment by SchrodingersGat** [comment]
Hi @lightlace are you going to finish this one up? It would be a great addition :)

**Comment by SchrodingersGat** [comment]
@lightlace we are moving the symbols to kicad-symbols for the new software release. Please resubmit a PR to https://github.com/kicad/kicad-symbols

Thanks

**Pull request closed without merging**
