### PR TITLE
moved 3D models of terminal blocks around ...

### PR DESCRIPTION
**Pull request by jkriege2**
- moved Phoenix 3D models to correct location (+fixed names + removed old WINGS-models)
- moved bornierXX 3D models to correct locations
- removed D-SUB 3D models (and fixed FPFilters)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 looks like you've only deleted files here?

**Comment by jkriege2** [comment]
uuups ... yes I will have a look this evening (or on the weekend) ... 

Best,
JAN

**Comment by jkriege2** [comment]
No, some were moved AND renamed (I deleted the the WINGS only), see:
2017-11-18 17_30_32-d__kicad_kicad-library_modules_packages3d_terminal_blocks 3dshapes
2017-11-18 17_30_08-d__kicad_kicad-library_modules_packages3d_terminalblock_phoenix 3dshapes

Can this be merged? It should then be compatible with the status of the deprecated .pretty repos ... I hope!

cu
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan :)

**Pull request merged**
