### PR TITLE
Added MAX610x series of voltage references

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds the MAX610x series of precision voltage references

https://datasheets.maximintegrated.com/en/ds/MAX6100-MAX6107.pdf

**Files changed:**
**references.lib**
* Added MAX6100 symbol with multiple aliases
* File has been saved in new KiCad version so there are multiple small changes throughout the file

**references.dcm**
* Added description for each MAX610x ALIAS

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
bump

**Comment by diggit** [comment]
Thanks for good documentation of your changes. It speeds up review.

KLC 3.3 - centered symbol, what about this style? 


Set filter to `SOT-23*` current filter works for SOT-223 and more which are incorrect.

**Documentation**
- add package info, pinout is not package specific, but with single package why not put it there?
- you can add more specific info like 0.4% accuracy and so...

**Comment by SchrodingersGat** [comment]
Done

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
