### PR TITLE
Add Omron G5V-2 Relays  series symbol

### PR DESCRIPTION
**Pull request by ouinouin**
this is a miniature series of DPDT relays from omron, schematic taken from existing one and modified pin numbers , documentation reference
datasheet here : http://omronfs.omron.com/en_US/ecb/products/pdf/en-g5v_2.pdf

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

and thanks for your contribution ... will you also provide the footprints for these relays?
And a small remark: The datasheet does not give a prefered polarity of the coil, so could you please remove the + near pin 1?

Thanks,
JAN

**Comment by ouinouin** [comment]
I Will provide a footprint as soon as i finished it, but the learning curve was high to submit (learn github tools , fork etc etc). Expect at th end of this week for the footprint as i shall read carefully kicad rules.

Glad you saw the + sign , you re right, there is no polarity, i ll remove the + sign.
Regards.

**Comment by jkriege2** [comment]
OK, please link this PR, when submitting the footprint, which will make review easier. Also a screenshot of the footprint will help a lot ;-)

Best & thanks for the great work!
JAN

PS: Let me know if you need assistance with the footprint ...

**Comment by jkriege2** [comment]
PPS: Please submit your footprint here: https://github.com/KiCad/Relays_THT.pretty

**Pull request merged**
