### PR TITLE
here are some 3d models for a phoenix contact header

### PR DESCRIPTION
**Pull request by greyltc**

### CODE REVIEW

**Comment by greyltc** [comment]
here it is

**Comment by greyltc** [comment]
The pins even line up with the pads!
image

**Comment by greyltc** [comment]
Is there anything more I can do to get this merged?

**Comment by pointhi** [comment]
the models looks good to me. They are pretty detailed and have no source file, so I need to ask if you converted them from the official models. (Because this could lead to copyright problems)

**Comment by greyltc** [comment]
I started from the STEP CAD file from the manufacturer's website, scaled, rotated and translated as needed and converted to .wrl format. For example, from this page: 

https://www.phoenixcontact.com/online/portal/gb?uri=pxc-oc-itemdetail:pid=1776715&library=gben&pcck=P-11-02-11&tab=1

STEP-File  1776715_05.stp.zip

No login or agreement required to download. No license file provided in the downloaded zip. The only license information IN the step file is that of the program used to draw it:
`CoCreate SolidDesigner: 08.01  19-Jun-2000(C) CoCreate Software GmbH`

(I know it doesn't matter much what I think, but) I think Phoenix would be happy to have models of their parts included in various design suites such as KiCad since it should drive up usage for their products in various designs.

I'll email Phoenix to see if they'll grant consent for the model's inclusion here.

**Comment by greyltc** [comment]
Phoenix has some words on usage of their site in its terms and conditions:
> ```
You may download material from the Site only for your own personal, non-commercial use. While we
encourage you to download and print information to help understand our Services and shop for our
products, unless otherwise specified, no material on this Site, including but not limited to the content of
the Site, may be modified, copied, downloaded, transmitted, distributed, performed, reproduced,
published, licensed, transferred, sold, used to create works from or used in any other way, except with
prior written permission of Phoenix Contact USA and with express attribution to Phoenix Contact USA.
You may not alter or attempt to alter any material on the Site, or the Site itself. You also may not,
without our permission, "mirror" any material contained on this Site or any other server. Any
unauthorized use of any material contained on this Site may violate copyright laws, trademark laws,
laws of privacy and publicity, and communication regulations and statutes. You represent and agree
that you are at least 18 years of age and that if you are younger than 18 you will not use this Site.
> ```
I've asked for their consent to use these models.

**Comment by pointhi** [comment]
please do so. I made the same with Würth, and they agreed to include their models in KiCad (with some restrictions).

@CarlPoirier we would need some guidelines about manufacture downloaded models. Like how the permission of the manufacture should look like, (like, someone from there has to send the official permission to the mailing list using an email with their domain name), where we locate information's about such agreements,...

Otherwise we can also not merge #637

**Comment by poeschlr** [comment]
I would say we use script generated modes instead of this models.
https://github.com/easyw/kicad-3d-models-in-freecad
This scripts there are able to generate the models for the complete mstb and mc series. (both step and wrl)
And most importantly these models are under gpl.

**Comment by poeschlr** [comment]
The script generated models have been merged.
https://github.com/KiCad/kicad-library/pull/1054
I think this pr can be closed.

**Pull request closed without merging**
