### PR TITLE
Add UDA1334ATS

### PR DESCRIPTION
**Pull request by adamheinrich**
Add schematic library for the low power audio DAC by NXP (http://www.nxp.com/docs/en/data-sheet/UDA1334ATS.pdf):

uda1334

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi Adam,

Thanks for contributing to KiCad!

This should go into digital_audio.lib. Yes, the libraries are named confusing right now but will be reorganized before KiCad v5 (hopefully later this year).

However, I've submitted a major update to that lib (https://github.com/KiCad/kicad-library/pull/1460) which should get merged first and may break your fork. So please keep this PR on hold for the moment and then re-submit in the correct library later.

I haven't reviewed the symbol, but if you have questions please ask.

**Comment by adamheinrich** [comment]
Hi,
thank you, I'll subscribe to notifications for your PR and modify my commit once #1460 gets merged.

I also wanted to add TDA1308T (headphone amplifier by NXP) -- this should go to digital_audio.lib as well, I guess?

**Comment by evanshultz** [comment]
@adamheinrich Great!

TDA1308 is a class AB headphone amp. There is no digital component to it, so it should go into audio.lib. The (lengthy!) Issue discussing the library structure updates is at https://github.com/KiCad/kicad-library/issues/1402.

**Comment by adamheinrich** [comment]
Hi @evanshultz, your #1460 is finally merged. Therefore, I've just changed my commit as you requested.

**Comment by evanshultz** [comment]
@adamheinrich Thanks! I'll try to get to this later today or tomorrow.

**Comment by evanshultz** [comment]
@adamheinrich Thanks for your patience and your contribution.
1. Capitalize all major words in the description so it's `Low Power Audio DAC with PLL, SSOP-16`.
1. Put the ref des and PN on the right of the power pins or move the PN to the right side.
1. Make the pin name position offset 20mil:
image
1. Optional: You can shrink the symbol a bit if you like without compromising readability:
image
```
# UDA1334ATS
#
DEF UDA1334ATS U 0 20 Y Y 1 F N
F0 "U" -400 650 50 H V L CNN
F1 "UDA1334ATS" 150 650 50 H V L CNN
F2 "Housings_SSOP:SSOP-16_4.4x5.2mm_Pitch0.65mm" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 SSOP*4.4x5.2mm*Pitch0.65mm*
$ENDFPLIST
DRAW
S -400 600 400 -600 0 1 10 f
X BCK 1 -500 500 100 R 50 50 1 1 I
X WS 2 -500 400 100 R 50 50 1 1 I
X DATAI 3 -500 300 100 R 50 50 1 1 I
X VDDD 4 0 700 100 D 50 50 1 1 W
X VSSD 5 0 -700 100 U 50 50 1 1 W
X SYSCLK/PLL1 6 -500 100 100 R 50 50 1 1 I
X SFOR1 7 -500 0 100 R 50 50 1 1 I
X MUTE 8 -500 -100 100 R 50 50 1 1 I
X DEEM/CLKOUT 9 -500 -200 100 R 50 50 1 1 B
X PLL0 10 -500 -300 100 R 50 50 1 1 I
X SFOR0 11 -500 -400 100 R 50 50 1 1 I
X Vref(DAC) 12 500 -300 100 L 50 50 1 1 P
X VDDA 13 100 700 100 D 50 50 1 1 W
X VOUTL 14 500 300 100 L 50 50 1 1 O
X VSSA 15 100 -700 100 U 50 50 1 1 W
X VOUTR 16 500 200 100 L 50 50 1 1 O
ENDDRAW
ENDDEF
```

**Comment by adamheinrich** [comment]
Hi @evanshultz, thank you, I've just updated the commit to include your remarks. The ordering of pins on the left side is slightly altered (to have PLL* and SFOR* pins grouped together):

uda1334ats

**Comment by evanshultz** [comment]
@adamheinrich 
Thank you! Sorry this took a while to get to, but we all appreciate your contributions and I hope to merge more of your work in the future.

**Pull request merged**
