### PR TITLE
Maxx48 xexxx

### PR DESCRIPTION
**Pull request by Misca1234**
Git push for Maxims ±15kV electro-static discharge (ESD) shock protected RS-485/RS-422 drivers of the MAX48X serie
Both SOIC and PDIP socket

https://datasheets.maximintegrated.com/en/ds/MAX1487E-MAX491E.pdf

Main: MAX481ECPA
Alias: MAX481EEPA MAX483ECPA MAX483EEPA MAX485ECPA MAX485EEPA MAX487ECPA MAX487EEPA MAX1487ECPA MAX1487EEPA

Main: MAX488ECPA
Alias: MAX488EEPA MAX490ECPA MAX490EEPA

Main: MAX489ECPD
Alias: MAX489EEPD MAX491ECPD MAX491EEPD

bild

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work ... I found a few things to change/have some suggestions:
1. I think the internal schematic would benefit from using 0mil thick/thin lines and non-filled circles for the inverters: 
2017-08-18 19_42_36-part library editor -- d__kicad_kicad-library-review_library_interface lib
```
DRAW
C -17 -140 10 0 1 0 N
C -1 59 11 0 1 0 N
C 65 75 10 0 1 0 N
S -300 400 300 -500 0 1 10 f
S 50 125 50 125 0 1 0 N
P 2 0 1 0 -125 -200 -75 -200 N
P 2 0 1 0 -125 100 -50 100 N
P 2 0 1 0 -20 -200 200 -200 N
P 3 0 1 0 -125 -100 -50 -100 -50 -135 N
P 3 0 1 0 0 45 0 0 -125 0 N
P 3 0 1 0 50 125 150 125 150 -200 N
P 3 0 1 0 100 75 100 -140 -5 -140 N
P 4 0 1 0 -75 -125 -75 -225 25 -175 -75 -125 N
P 4 0 1 0 -50 100 50 150 50 50 -50 100 N
P 4 0 1 0 75 75 175 75 175 100 200 100 N
X RO 1 -400 100 100 R 50 50 1 1 O
X ~RE 2 -400 0 100 R 50 50 1 1 I
X DE 3 -400 -100 100 R 50 50 1 1 I
X DI 4 -400 -200 100 R 50 50 1 1 I
X GND 5 0 -600 100 U 50 50 1 1 W
X A 6 400 -200 100 L 50 50 1 1 B
X B 7 400 100 100 L 50 50 1 1 B
X VCC 8 0 500 100 D 50 50 1 1 W
ENDDRAW
```

2. The symbol MAX481ECPA has two FPFilters and no footprint, which is correct as the devices are available in DIP8 and SOIC8, but you added only the DIP8 (xyPz) variants. Therefore please rename all variants to something like `MAX481Exxx`, `MAX483Exxx`, ... or simpler `MAX481E`, `MAX483E`, ... the temperature range-variants do not need to be in the lib (i.e. wildcarded). A second option would be to duplicate the symbol and fix one to the DIP-package and one to the SOIC-8 package. then the naming should be `MAX481ExPA` for DIP and `MAX481ExSA` for SOIC.
3. the same (1&2) for MAX488 and MAX489
4. You could think about moving the NC-pins a bit inside for MAX489:
2017-08-18 19_53_29-part library editor -- d__kicad_kicad-library-review_library_interface lib
This has the advantage that the pins are not easily connected by error.
5. Please add the package info to the description in the usualy way of this lib `DIP-8`, `SOIC-8`, `DIP-8/SOIC-8`, ... as appropriate (e.g. instead of `8-DIP`)

Best,
JAN

**Comment by Misca1234** [comment]
> 1. I think the internal schematic would benefit from using 0mil thick/thin lines and non-filled circles for the inverters:

In other pushes I had to re make the symbols just because the lines inside was 0 thick

I have re named the symbols with CPA and EPA suffix, that is MAX481E, MAX483E etc.
I moved in the NC pins a little, like this

bild

**Comment by poeschlr** [comment]
0 mil thick lines look different in different kicad versions. Might i suggest 5 or 6 mil? (I think this is how thick 0 mil thick lines look like in stable.)

**Comment by jkriege2** [comment]
Hi!

I will also merge with thick lines ... that was just a suggestion: @Misca1234 let me know which variant you prefer. The rest in this PR looks fine to me!

best,
JAN

**Comment by jkriege2** [comment]
The symbols for MAX1487E, MAX1487E, MAX1487E, MAX1487E, MAX1487E, as well as the pair MAX491E and MAX491E look identical to me ... so could you ALIAS them or is there any reason why not?

Best,
JAN

**Comment by Misca1234** [comment]
I made aliases of them

**Comment by jkriege2** [comment]
So should I merge in the current style?

JAN

**Comment by Misca1234** [comment]
Uhm, do you think there is something wrong ?

**Comment by jkriege2** [comment]
no, just as we discussed above: I proposed the thinner lines and @poeschlr suggested even another line width, so I was not sure whether you decided to stay with the thick lines or wanted to do any changes ... I'm happy to merge now, just let me know ;-)

cu
JAN

**Comment by Misca1234** [comment]
Let us merge it and take the next one.

**Comment by jkriege2** [comment]
OK!
thanks for the contrib!
JAN

**Pull request merged**
