### PR TITLE
Rework barrel/audio jack connectors

### PR DESCRIPTION
**Pull request by jkriege2**
- sleeker look
- unified look and size
- pease ignore remaining KLC-errors: these are generic connectors and no ICs

2017-04-23 15_56_47-eeschema test_addlin _ d__kicad_test_addlin

### CODE REVIEW

**Comment by evanshultz** [comment]
@jkriege2 Great work! I dislike the name "JACK-4" and similar since they're so unspecific. What kind of jack is it? Perhaps add "phone" since Digi-Key, Mouser, and Farnell all use this term for this type of connector, or is there a better word for a generic connector symbol like this?

**Comment by jkriege2** [comment]
- I renamed to `Audio-Jack-N` 
- added a 5-pin version
- added additional naming schemes to description (see https://en.wikipedia.org/wiki/Phone_connector_(audio))

**Comment by SchrodingersGat** [comment]
These are great improvements, could you do the same to **JACK_TRS_6PINS** and make it conform with your new style?

**Comment by poeschlr** [comment]
Shouldn't these have the keyword connector? (At least the old symbols had this keyword. You still list connector in the description.)

**Comment by jkriege2** [comment]
@poeschlr @SchrodingersGat 
- keyword "connector" is there now + more keyword improvements
- replace `JACK_TRS_6PINS` with new version `Audio-Jack-3_3Switches`
2017-04-26 20_51_17-part library editor d__kicad_test_addlin_ _kicad-library_library_conn lib

Can be merged now?

**Comment by SchrodingersGat** [comment]
This looks good to me. Thanks for the fine work as always Jan

**Pull request merged**
