### PR TITLE
texas: add BQ24075

### PR DESCRIPTION
**Pull request by ChristianHirsch**
USB LiPo battery charging and power management IC

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: BQ24075
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
Components Added: 1
+ BQ24075
```

**Comment by SchrodingersGat** [comment]
In addition to making the fixes as above, I would suggest putting this in the battery_management library

**Comment by ChristianHirsch** [comment]
@reportingsjr : fixed EC03 and EC04.
@SchrodingersGat : moved component to battery_management.

**Comment by SchrodingersGat** [comment]
Great @ChristianHirsch  :)

Can you also add a "QFN*" footprint filter? Thanks

**Comment by ChristianHirsch** [comment]
@SchrodingersGat done :)

**Comment by SchrodingersGat** [comment]
You are also missing a PAD pin (#17). I would suggest placing it next to the VSS pin.

**Comment by ChristianHirsch** [comment]
I added the thermal pad and rearranged the pins on the left side so that VSS is on the bottom.

**Comment by SchrodingersGat** [comment]
I would suggest moving PAD just underneath VSS like so:

pad

Other than that I think it is good.

**Comment by ChristianHirsch** [comment]
Done :)

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
