### PR TITLE
Updated 3D model of LCD-016N002L

### PR DESCRIPTION
**Pull request by Misca1234**
3D model for 

https://github.com/KiCad/Displays.pretty/pull/13

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Please move this model to Displays.3dshapes

**Comment by Misca1234** [comment]
This push consist of two devices, the reason for this 
is that the old symbol "LCD12X2" had LCD-016N002L1" as an alias,
I could not just remvoe this alias becosue travis started to scan LCD12X2 (with errors)
so i had to "fix" LCD12X2 as well.
Which I discovered that LCD12X2 actuallay is actually WC1602A 

So I have 
Fixed LCD-016N002L1
Removed  LCD12X2
Added WC1602A

I have modified symbol, footprint, 3D models

LCD-016N002L1
http://www.vishay.com/docs/37299/37299.pdf

WC1602A
http://dl.btc.pl/kamami_wa/wc1602a0.pdf

bild

bild

**Comment by poeschlr** [comment]
This PR still adds the models to the Display.3dshapes repo instead of the Displays.3dshapes. Could you fix that?

**Comment by Misca1234** [comment]
Done
(This was pushed before it was decided to have the displays in Displays.3dshapes)

**Comment by poeschlr** [comment]
The wc1602a files are still added to the display.3dshapes repo instead of the displays.3dshapes repo

**Comment by Misca1234** [comment]
Removed WC1602A from this repo and updated the 3D model


bild

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Great, thanks

**Pull request merged**
