### PR TITLE
add irf7410 and make component pins smaller

### PR DESCRIPTION
**Pull request by mkschreder**

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi! Thanks for the contribution!

We have a standard for KiCad library parts, called KLC, and a new version is nearly ready to go live. You can see the preview of version 2.0 at https://github.com/SchrodingersGat/kicad-library/wiki/KLC.

Click on the "Details" link about to review the output from the rule-checker, which verifies many of the KLC rules. You will see that the wires need to be on a 100mil grid, and it appears your submission doesn't meet this requirement. There are also a number of smaller things to resolve.

You can make changes and submit them here in the same PR. Please ask if you have any questions.

**Comment by jkriege2** [comment]
Hi @mkschreder : Are you still on this?

Best,
JAN

**Comment by mkschreder** [comment]
I have made several symbols and use them myself as a local lib of a
project. Contributing them to the main lib seemed like too much hassle so I
never submitted them.

**Comment by jkriege2** [comment]
But you submitted this one here ... so will go through the review or should we close this PR?

**Comment by mkschreder** [comment]
Yes let's close it for now. I'll send a better pull request later.

**Pull request closed without merging**
