### PR TITLE
Clean up interface lib part 3

### PR DESCRIPTION
**Pull request by Misca1234**
Here is a partial clean-up of the interface library.

This library have A LOT of issues, so to not overwhelming the librarians I have only corrected a few of the errors so it would be more manageable if it is handled in small portions.

This push will not fix all issues but a few.

This push consist of the following changes

CH376T
Changed pin 20 (VCC) from Output to Power input
Changed pin 17 (SD_CS) from output to open collector
Changed pin 13, SCS, from output to input
Changed pin 14, SCK, from output to input
Changed pin 15, SDI, from output to input
Changed pin 16, SDI, from input to output
Changed pin  5, RXD, from output to bidirectional
Changed pint 2 name from RST to RSTI

Changed foot print from 
Housings_SSOP:TSSOP-20_4.4x6.5mm_Pitch0.65mm 
to
Housings_SSOP:SSOP-20_5.3x7.2mm_Pitch0.65mm
Set FP to SSOP*5.3x7.2mm*Pitch0.65mm*

DP83848C
Aligned 4 pins to 100 grid
Set the specific foot print to Housings_QFP:LQFP-48_7x7mm_Pitch0.5mm
Set the FP to LQFP*7x7mm*Pitch0.5mm*

DP83848I
Removed, it is an alias to DP83848C

DS7820
Added metadata
Complete redraw, did not spend much time on this oldie

DS7830
Added metadata
Complete redraw, did not spend much time on this oldie

DS90C124
Filled in metadata 
aligend pins to 100 grid
shortened pins to 100 
Set FP to TQFP*7x7mm*Pitch0.5mm*
Det specific foot print to Housings_QFP:TQFP-48_7x7mm_Pitch0.5mm

All TJAXXXT/3 was renamed into TJAXXX-3

EL7242C and EL2001
Cleaned up the drawing and filled out metadata

FD1771
Added meta data 
Cleaned up symbol

FD2791 and FD2795
Can not find datasheet any place, remobed both symbols

GD65232DB, GD75232N, GD65232DW
Fixed footprint filter

bild

bild

bild

bild

bild

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @Misca1234 we have now made a decision that if there are a lot of NC pins, they can be left off the symbols - https://github.com/KiCad/kicad-library/issues/1663

The only new requirement is that the pin count must be included in any footprint filters.

e.g. `TSOP?14*` instead of `TSOP*`

So for the EL2001 as shown above, you don't need to place all those NC pins.

Will this make your life any easier for this PR? Or do you want this merged as-is?

**Comment by Misca1234** [comment]
Naa, i can change it, give me an hour

**Comment by Misca1234** [comment]
I have have added the pin number on those I have changed in the push,
I have not changed the FP on those already merged, this to keep down the changes in this push

**Comment by jkriege2** [comment]
Hmmm ... the idea was to either add the pin number and have no NC-pins in a symbol, or have all NC-pins and no pin-number (I believe) ... @SchrodingersGat  WHat do you say? How should we interpret this?

**Comment by poeschlr** [comment]
I would agree with the interpretation of @jkriege2 
Include pin number in fp filter only if the number of pins in the symbol does not agree with the number of pins needed for the footprint.

**Comment by Misca1234** [comment]
The pin information in this push have been removed

**Comment by SchrodingersGat** [comment]
Thansk @Misca1234 for your contributions :)

**Pull request merged**
