### PR TITLE
Jst 3d models

### PR DESCRIPTION
**Pull request by SchrodingersGat**
I have added STEP/VRML pairs (the wrl files are scaled appropriately) for many JST connectors, such that they fit the footprints without any scaling, rotation or translation:

XH Straight
xh_straight
XH Angled
xh_angled
AUH
auh
EH Straight
eh_straight
EH Angled
eh_angled
GH Angled
gh_angled
J2100 Straight
j2100_straight
J2100 Angled
j2100_angled
PUD Straight
pud_straight
PUD Angled
pud_angled

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@ricardocrudo  @CarlPoirier  @pointhi any thoughts on these?

**Comment by pointhi** [comment]
I would propose to split the PR, so it's easier to review and merge. 

From my personal perspective, the color of the pins look a little bit wrong.

I'm a bit curious, how you created those 3d models. (Im personally interested to learn a simple parametric way to do it)

**Comment by Schlumpf** [comment]
@pointhi I Don't know how he did, but maybe OpenSCAD is something for you: http://happyrobotlabs.com/posts/tutorials/tutorial-3d-kicad-parts-using-openscad-and-wings3d/

**Comment by pointhi** [comment]
Ehm, I already created Kicad 3D Models with OpenSCAD, but it's too much effort. OpenSCAD is not able to export to VRML with colors, so you have to export every color part on your own, go to wings3d import that part and give them the color again, import the next color part,...

https://github.com/openscad/openscad/issues/1304

The other thing is, parametric generation is supported by OpenSCAD, but I don't know how to overwrite parameters via script (to get all the different pincounts for example). I know I could use regex for this task, but without color support, creation of 3d-models and the automation of it is not meaningful in OpenSCAD yet. I think FreeCAD is currently the best choice for such tasks, but I haven't scripted anything yet with it.

**Comment by SchrodingersGat** [comment]
Hi @pointhi, I also investigated many routes for generating 3D models, and found that the same guy who made the KiCAD StepUp plugin has been working on a parametric model generation tool using the  cadquery library.

https://github.com/easyw/kicad-3d-models-in-freecad

I have done a little bit of work assisting with this project.

The particular models in this PR are the models provided on the JST website. I have written a python script (using Freecad scripting API) to batch-convert these, with correct alignment, color, and also provide 1/2.54 WRL model pairs.

**Comment by pointhi** [comment]
I'm not so sure, if the official STEP models on the JST Website have the correct licences to be included in KiCAD.
More likely we have to clarify this issue with the company itself, or draw them on our own to include them legally.

**Pull request merged**
