### PR TITLE
Improved description for symbols in device.dcm

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR improves documentation for a number of symbols in the device library:

* Added description for CRYSTAL_SMD
* Fixed spelling of potentiometer
* fixed spelling and tags for a number of diodes
* Added missing tags to a number of symbols
* Fixed spelling of *filtre* to *filter*
* Added missing description for fuses / inductors / jumpers / LEDs
* Improved description for a number of switches

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@CarlPoirier  @pointhi  et al want to take a look here? There are a lot of (simple) changes that will turn into conflicts if left alone for a while as they touch a lot of components.

**Comment by SchrodingersGat** [comment]
The various switches / buttons have been cleaned up a lot in the most recent commit

**Comment by SchrodingersGat** [comment]
@ashtonchase now that you're on board want to have a look at this one? Seems that the other librarians are pretty busy ATM :)

**Comment by SchrodingersGat** [comment]
Checks are failing for rule 3.8 as these are generic symbols and do not have associated documentation files. Description and keywords have been improved significantly, however.

**Comment by ashtonchase** [comment]
I've review each of the commits in order. Looks good. A lot of effort here. 

Not too many fixes: 

- I see there are quite a bit of KLC violations, It was 3.1, 3.2, 3.6, 3.8.  I the only only I think worth pursuing that wouldn't be destructive is 3.6 for the text size. Running the KLC with --fix cleaned that up on mine. 

- In  "LIGNE_A_RETARD"  please add  "DELAY LINE" in the description. 

- please add description and keywords to SW_DPST. 

- there is a defect in the THERMISTOR as seen in the bottom right of the screenshot, please confirm:
image

- please provide better information for THYRISTOR

- you might want to consider leaving "resonator" as a keyword for all the crystals. 

- add description for emi-filter2

- I'm hesitant to merge 7eee821 commit. you're renaming (removing and adding ) components in this one. I don't comfortable to merging this with out concurrence. I would defer to @CarlPoirier .  Nonetheless, I like where you are going with the desire for consistency there. 

I would hence forth and roll the other changes while we get a third set of eyes on the switches. Sound good?

**Comment by SchrodingersGat** [comment]
I've applied all you suggestions. Happy to wait for extra input from @CarlPoirier or others on the switches side of things. Anything else that stands out to you?

**Comment by SchrodingersGat** [comment]
Any further input on this one @ashtonchase  @diggit  @CarlPoirier  @ricardocrudo  ?

**Comment by diggit** [comment]
It great, that you started improving this lib. Here are my notes and opinions:
- JACK-2P imo belongs to conn, if not already there
- L or INDUCTOR, not both
- D or DIODE, not both
- nice work with switches, but why *SW_SPST_Small* has 0.01" thick circles when others don't?
- TR1-SO8 is duplicity of TRANSFO-SO8
- VARICAP - missing keyword *diode*
- VR - VARISTOR, wrong symbol, [look here](https://en.wikipedia.org/wiki/Varistor)
- RR8, RR9 - probably "single ended" resistor networks, smaller exists too, should be added
- RELAY, needs redraw
- F_*, FP_*, FUSE - unify names, (FUSE, FUSE_POL,...)
- TEMPLATE - what? :o
- unify all names letter case (JUMPER then Jumper_NC_Small, LED_RGB then Led_RGB_CA,...)

**Comment by SchrodingersGat** [comment]
Ok I've made a lot of improvements based on what you said. Parts are a lot more consistent now. I removed "TEMPLATE" part altogether.

**Comment by diggit** [comment]
Nice work. You did a lot of improvements. :+1: 

So here you have more ideas:
- **TST** 
 - D:*Testpoint*
- **Photores** -> **R_PHOTO**
 - D: *photoresistor, light sensitive resitor*
 - K: *light photo resistor opto*
- **OPTO_NPN** -> **Q_PHOTO_NPN**
 - D: *phototransistor, light sensitive transistor*
 - K: *light photo opto transistor*
- **Coded_Switch** -> **SW_CODED**
 - K: +*switch*
- **Diode_Bridge** -> **D_BRIDGE** OR **DIODE_BRIDGE**, but then all D_* symbols rename DIODE_*
- **EMI_FILTER** and **FILTER** - both are EMI filters, unify names somehow, no idea here

Delete:
- **Darl_NPN** - delete, we have to create whole new bunch of these (EBC,BCE,... )
- **RELAY_2RT**
- **QUARTZCMS4** - duplicate of CRYSTAL_SMD if you not connect pin 2
- **PIC07** -  unknown undocumented part
- **PHTRANS** - already in opto library
- **PHDARL** - already in opto library
- **PHOTORESISTOR** - will be created in opto library in future

Do we need all these **SMALL** variants of components? IMO 1 decent size is enough.

**Comment by SchrodingersGat** [comment]
Some good ideas here, thanks. Implemented.

**Comment by SchrodingersGat** [comment]
Hey all, anyone have any further improvements to be made here? I think we should merge this soon before the number of changes spirals out of control!

Any urgent changes, let me know and I can make them.

Cheers

**Comment by ashtonchase** [comment]
I'll make the recommendation to merge. Seconds?

**Comment by SchrodingersGat** [comment]
@CarlPoirier  thoughts on this one? :)

**Comment by SchrodingersGat** [comment]
@diggit @pointhi either of you guys want to weigh in? This one has been sitting here for a while now...

**Comment by diggit** [comment]
@SchrodingersGat 
Descriptions look good. There are symbol changes (cleanup) that are needed to be done, but it is not part of this PR.
There are many conflicts (reverting already made changes by other commits), please solve them.

**Comment by SchrodingersGat** [comment]
There are no merge conflicts here - is there a particular error that you have spotted?

**Pull request merged**
