### PR TITLE
Added LM3480 series of ldo

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Ref http://www.ti.com/lit/ds/symlink/lm3480.pdf

### CODE REVIEW

**Comment by diggit** [comment]
Great, another SOT-23 LDO pinout :D

Description
- *Quasi* Low Drop....
- add *100mA* *positive* *fixed* into keywords
- FP field should be left empty of filled in full name format Library:FP (so long, that it should be set invisible)

**Comment by SchrodingersGat** [comment]
Done

**Comment by diggit** [comment]
\+ *fixed* *positive* to keywords

**Comment by SchrodingersGat** [comment]
Yup

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
