### PR TITLE
Analog devices library overhaul and new parts added

### PR DESCRIPTION
**Pull request by evanshultz**
Image:
image

Notes:
1. I have not moved power pins to the top and bottom of the isolator symbols. Since they have distinct power domains, I want to give everybody a chance to give feedback. Should they be moved to the top and bottom or not?
2. It would be helpful to get an answer for my question at https://github.com/KiCad/Housings_QFP.pretty/issues/18 since it affects this PR.

All:
- Added package type to description
- Standardized description and keywords
- Made pins 100mil in length

AD637: http://www.analog.com/media/en/technical-documentation/data-sheets/AD637.pdf
- New part
- VIN is not a power input so KLC error can be ignored
- Used "NC" instead of the datasheet's "NIC" so KiCad automatically recognizes this as a no connect pin

AD654: http://www.analog.com/media/en/technical-documentation/data-sheets/AD654.pdf
- New part

AD736: http://www.analog.com/media/en/technical-documentation/data-sheets/AD736.pdf
- New part
- VIN is not a power input so KLC error can be ignored

AD9831: http://www.analog.com/media/en/technical-documentation/data-sheets/AD9831.pdf
- New part

AD9852: http://www.analog.com/media/en/technical-documentation/data-sheets/AD9852.pdf
- New part
- Added EP as a discrete pad since it's not tied internally but is suggested to use a ground pad; see page 38 of datasheet
- VOUT is not a power output so KLC error can be ignored

AD9854: http://www.analog.com/media/en/technical-documentation/data-sheets/AD9854.pdf
- New part, ALIAS of above

AD9910: http://www.analog.com/media/en/technical-documentation/data-sheets/AD9910.pdf
- Stacked power and ground pins; shrunk symbol body
- Buried NC pins inside symbol body

ADE7758: http://www.analog.com/media/en/technical-documentation/data-sheets/ADE7758.pdf
- Moved VN pin to the right side since it's the VA/VB/VC reference and not ground

ADM2484E: http://www.analog.com/media/en/technical-documentation/data-sheets/ADM2484E.pdf
- Dramatically simplified the isolation barrier drawing to look like datasheet
- Stacked ground pins

AD2582E/2587E: http://www.analog.com/media/en/technical-documentation/data-sheets/ADM2582E_2587E.pdf
- Changed two isolation lines to one line datasheet
- Stacked power and ground pins; shrunk symbol body

ADuM6000: http://www.analog.com/media/en/technical-documentation/data-sheets/ADuM6000.PDF
- Hid and buried NC pins
- Stacked power and ground pins
- See figure 14 on page 13 of the datasheet for why some NC pins are visible and set to PASSIVE type

ADuM764x: http://www.analog.com/media/en/technical-documentation/data-sheets/ADuM7640_7641_7642_7643.pdf
- Simplified isolation drawing a bit
- Renamed pins to match datasheet
- Add other parts in the datasheet
- GND* pins are not stacked since they're internally connected and are recommended but not required to be externally connected; see tables 20-23

### CODE REVIEW

**Comment by jkriege2** [comment]
What about having simplified (!!!) internal schematics? as e.g. available for several ADCs or the isolators above? This might make the schematics more readable ...

JAN

**Comment by evanshultz** [comment]
@jkriege2 Thanks for taking a look. That would likely make the symbols larger and require more lines of code to describe them in the LIB file (bigger KiCad installer, bigger downloads, etc.). Everything is a tradeoff. Generally I dislike doing that for these reasons, and because it seems not necessary when designing as one can refer to the datasheet, but it is something that varies in our library. I've not seen any rules or even guidelines about if or when a simplified internal schematic is required or suggested. Perhaps it's a good time to think about this and decide how and what to do? @SchrodingersGat

**Comment by evanshultz** [comment]
How sad. My branch is now out of date with regards to the PR above. Can this PR be merged if I fixed the branch conflict? Are internal schematics required since we have no standard for this?

**Comment by jkriege2** [comment]
They are not required ... I like such things as it makes schematic more readable (IMHO) ... please fix the merge conflict and maybe I'll have some time this evening to have a look at this PR.

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 
Merge conflicts fixed. Please take a look, if you can, considering the two notes I made above. I expect there may be changes requested due to the notes, but see what you think and add more comments.

With regards to internal schematics, I suppose the DDS ICs (9831, 9852, and 9910) are the ones that you're most keen to see? The others are simple enough that an internal schematic would seem to have less value, to me. I'd like to get this merged, and then perhaps go back later and add them. Merge conflicts aren't such a pain, but I'd rather not have so many branches out there potentially getting stale.

Thanks!

**Comment by jkriege2** [comment]
- AD637: OK (I think this would benefit from simple internal drawing, as e.g. shown in DS) 
- AD654: OK (I think this would benefit from simple internal drawing, as e.g. shown in DS)
- AD736: OK (I think this would benefit from simple internal drawing, as e.g. shown in DS)
- AD9831: OK, maybe a very simple schematic, like this:
2017-08-16 20_54_05-part library editor -- d__kicad_kicad-library-review_library_analog_devices lib
- AD9910: I would unhide the PAD
- ADM2484E (and all other isolators): I would stick to the dashed barrier ... solid lines (I feel) are more to separate different functional units inside, then a dashed line could be the isolation. Text in between is maybe not a bad idea ;-) ... you could also make the internal drawing look like the ones in AD2582E?
- ADuM6000 Here's it's not at all clear, what the two lines symbolize ... again IMHO either dashed, or a more complex drawing or text
- ADuM764x as above ...

Generally speaking, I would try and come up with a common style for all isolaotors, which makes it clearer what is meant. Maybe the old drawings are a bit too complex, but at least dashed separation lines (maybe two + text in between) + triangles for the drivers on the lhs/rhs of the barrier...

Best,
JAN

**Comment by evanshultz** [comment]
Hi Jan,

Thanks for taking a look.

I should have been more clear about my goals from the beginning. I did add a couple parts, but my main intent was the get the library KLC compliant so I can move onto other libraries. I generally left the existing symbols alone. I care little about updating the internal schematics and would rather leave it as is. But... OK. If that's what I have to do to get this merged by someone else.

Feedback to your points:
- AD9910: Datasheet says "EXPOSED PAD SHOULD BE SOLDERED TO GROUND". Are you saying expose the pin to give flexibility to use AGND, DGND, etc.?
- ADM2484E: The current symbol is very much like the datasheet page 1 already.
- ADuM6000 / ADuM764x: I'll make these like AD2582E

**General complaints not directed at anyone. Not part of this PR's main objective. Ignore if desired.**
One objection of mine is filling the library files with all these details. Yes, we talked about them being just kB right now, but the libraries will only ever get bigger. There are dozens of lines in the LIB file which have absolutely zero value to connecting the symbol with a footprint and generating PCB documentation. That's the ultimate goal of KiCad and all of these internal schematics are nothing more than ornamentation. 

All the intricacies of a pin cannot be captured well with text and lines and so to know a part the user will need to pull up the datasheet. Or the part may be simple enough to recall. Either way, I simply don't see how stuffing the libraries full of decoration is useful. Putting some generalized details on the schematic does not explain the part.

If someone is capable to understand and use KiCad, I'm of the opinion that the datasheet is the reference documentation required to read the schematic. I've rarely seen these in professional schematics and, to me, it makes the schematic look like a hobby or toy. But that is my opinion.

The above are subjective and should not taken to affect the review of this PR. I think this discussion should happen and, if possible, turned into KiCad guidelines. It's often hard to interpret words online without seeing someone's face, so know I'm annoyed at how difficult it is to get this PR merged but I believe in KiCad and am happy to work with a team that is aggressively improving the libraries.

**Comment by jkriege2** [comment]
Hi!

about the internal schematics: As I said above that's my opinion ... I will not enforce them and for sure this will not decide the fate of this PR ... just expressing what "I think".

AD9910: The PAD-pin 101 is simply invisible in your PR ... thus it's hard to connect it. I simply proposed to make it visible!

ADM2484E and other isolators: Generally the symbols are all "acceptable" ... I just proposed to find a common style used for all those isolators (as you're already at it).

I can have a look at the rest of the symbols maybe tomorrow (depends on time ;-)

Best,
JAN

**Comment by jkriege2** [comment]
Oh ... one thing's strange: Travis complains about the NC-pins on `ADuM6000`, but in the `Files changed`-tab they look OK (not_connected+invisible) ... could you check on your side?

Thanks,
JAN

**Comment by evanshultz** [comment]
@jkriege2 Some of the ADuM6000 pins are visible and passive, which Travis complains about. This is intentional and please see the notes I wrote in the original PR for more details.

I'll work on the symbols a bit more within the next day and advise when I'm finished a round of updates.

**Comment by evanshultz** [comment]
@jkriege2 Since I think this is a nice improvement to the library, if it comes to making graphical changes or missing 4.0.7, can this be merged? I'll try to get to this by the weekend or early next week at the latest, but I'd rather not miss getting this library to KLC compliance in 4.0.7 if internal schematics are the only thing holding it back. If 4.0.7 won't be tagged and built for at least a few days, then I should be able to finish.

**Comment by jkriege2** [comment]
OK, then I'll merge this now and you can put your further changes into a new PR (BTW: I'll be away on holidays for 1.5 weeks starting from tuesday!)

Best,
JAN

**Pull request merged**
