### PR TITLE
Added NRF24L01_Breakout symbol

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds a symbol for the NRF24L01 breakout board which is a common way of using this module

742196562_o

e.g. http://www.ebay.com.au/itm/3pcs-NRF24L01-2-4GHz-Antenna-RF-Wireless-Transceiver-Module-for-Arduino-AU-Ship-/281281196404?hash=item417daa7174:g:5uUAAOxy69JTGmW-

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

very nice!

please set the correct footprint-field and filters!

Thanks,
JAN

**Comment by jkriege2** [comment]
I merge the footprint!
JAN

**Comment by SchrodingersGat** [comment]
Ok, footprint association and filter fixed

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
