### PR TITLE
Add Nucleo 144 board

### PR DESCRIPTION
**Pull request by El3ctr0nic**
Add F429 and F746 microcontrolers boards

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I think that you have made a typo in the symbol name:

Should NUCLEO144-FR429ZI instead be NUCLEO144-F**4**29ZI?

**Comment by El3ctr0nic** [comment]
Thanks :) . I don't know how it was possible ;/
I think it's ok now.
Footprints 95% done. 
Merge Pls :)

Regards,
Marcin

**Comment by SchrodingersGat** [comment]
Please see errors in the Travis log :)

**Comment by El3ctr0nic** [comment]
Done :) Rravis pass :)

 I have one more problem. When I try check footprints usin kicad-library-utils i get output from  check_kicad_mod.py ;
"Please, resave the files using KiCad to keep indentation standard."
What I do wrong??
I'm poor with python ;/

**Comment by SchrodingersGat** [comment]
It's not your fault that this is happening. Essentially when you use the `--fix` option for the scripts, it makes changes to the `.kicad_mod` files and then resaves them. Sometimes it does not completely match the indentation of the original file, which means that when you open the file in KiCad and re-save it, the file will change.

The new scripts (which were uploaded yesterday, so you should grab them) do a much better job of copying the KiCad native file format.

**Comment by SchrodingersGat** [comment]
And thankyou for the contribution

**Pull request merged**
