### PR TITLE
Added Dual TVS Device

### PR DESCRIPTION
**Pull request by shaneburrell**
Added a dual TVS device.  There are many makers of this device.  NUP2105LT1G is an example.

### CODE REVIEW

**Comment by shaneburrell** [comment]
Added LCFN series and started minicircuit lib.

**Comment by keruseykaryu** [comment]
Please fill the documentation fields for LCFN Filter.

**Comment by shaneburrell** [comment]
Added LCFN filter doc link and alias.

**Comment by keruseykaryu** [comment]
Your aliases doesn't have the doc file entries. Please clone and update it from base component.

**Comment by shaneburrell** [comment]
Added Aliases Doc Files and Detailed Description.

**Pull request closed without merging**
