### PR TITLE
Create new library called 'MODULES' with CHIP from NextThingCo

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
I have created a new library called MODULES to add CHIP board from NextThingCo.

If you prefer putting this kind of components in another library, please let me known. I have also prepared a footprint but I'm waiting for the answer to this question to submit it.

Thanks.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

I think there is no footprint available so far ... could you also add the footprint? Or did you already do in another PR?

Please also change the footprint filter to MODULE_NEXTTHINGCO_CHIP* so also variants of the CHIP are found, we can build a hirarchy of modules and the company is anmed.

Best,
JAN

**Comment by jkriege2** [comment]
PS: The footprint should be named MODULE_NEXTTHINGCO_CHIP then too ... maybe in a modules.pretty?

**Comment by myfreescalewebpage** [comment]
@jkriege2 
Footprint updated.
As explained, I was waiting your point of view about the name of the library (If 'modules' is OK or not). Then I can pull request the footprint.

**Comment by myfreescalewebpage** [comment]
New board CHIP-PRO added.

**Comment by myfreescalewebpage** [comment]
Up ?
Is the name of the library "modules" ok for you ? If yes can you create the modules.pretty repository so I can pull request the footprints?
Thanks,
Joel

**Comment by SchrodingersGat** [comment]
I like the simplicity of something like `SOC_SOM.lib` that should cover the uses for this library, no? Sorry that I have not responded sooner - have been away :)

**Comment by jkriege2** [comment]
Hhmmm ... I had to look up what you meant by SOC and SOM ... I suppose:
- SOC = System on Chip (not really what this lib would be about)
- SOM = System on Module (exactly that ... but is the abreviation well known?)

I would prefer modules.lib ... What do the others think? @diggit @pointhi ...

Best,
JAN

**Comment by SchrodingersGat** [comment]
True, SOM is not really widely used. Perhaps `modules.lib` is best after all. If no one else objects, let us go with that.

**Comment by myfreescalewebpage** [comment]
I agree, SOM is not very used. If agreed, please can you create the Modules.pretty repository so I can pull request the footprints ? Thanks.

**Comment by SchrodingersGat** [comment]
Ask and ye shall receive - https://github.com/KiCad/modules.pretty

**Comment by jkriege2** [comment]
Hi!

symbols look good. Please still fix these:
1. CHIP pin50 has unspecified electrical type
2. could you link directly to a datasheet-pdf and not their repo?
3. CHIP-PRO please move all GND-pins (also those next to the USB-pins) to the bottom
4. is VUSB a power input?

Best,
JAN

**Comment by myfreescalewebpage** [comment]
Hi @jkriege2 

Fixes:
1- corrected
2- There is no datasheet, only the schematic of the module.... I can link to it if you prefer?
3- corrected
4- yes, corrected

Joel

**Comment by myfreescalewebpage** [comment]
Footprints added : https://github.com/KiCad/Modules.pretty/pull/1

**Comment by El3ctr0nic** [comment]
Hi All,
I have Nucleo boards (144 and ) drawed as PIM modules. Do U think that i Can add them to modules.lib

**Comment by jkriege2** [comment]
@El3ctr0nic yes, why not? I also planned to maybe make (in due time) some of the Arduinos (especially nano ...)

cu
JAN

**Comment by El3ctr0nic** [comment]
Ok :) So I start clean up files mess.

Schematic symbol is clear, only STM32 pin names (PA0, PA1...) with default board func. (PD8/STLINK_TX).

Some suggestions?

nucleo_schematic
nucleo_module

**Comment by diggit** [comment]
Hi, I've tried module footprint once, but it was not usable. Every time you want to move any FP "inside" of module, KiCAD asks, if want to move that FP or module. (in fact, they are overlapping FPs) When you missed that FP at all, you automatically grab module.  Is there any way to make KiCAD ignore some placed footprints?

**Comment by El3ctr0nic** [comment]
It's a problem.  U can lock footprint but i don't think that helps too much.
Nucleo pinout is so crazy that evrything under boards is only tracks and vias to keep connection outside clean :)

**Comment by El3ctr0nic** [comment]
Pls bring this lib to "life" :)

**Comment by jkriege2** [comment]
Just make a PR and create a new lib with that name (if this PR is not yet merged) ... The merge step will then combine the two. The footprint-repo is available: https://github.com/KiCad/Modules.pretty

JAN

**Comment by jkriege2** [comment]
Hi!

you're back at this? Great!

please have a look at the Travis output ... It tells you to make datasheet and footpritn fields invisible. Also you should wildcard all `-`.`_`, ... in the FPFilter with `?`(1 character) or `*`(multiple characters or none).

Also I think we should wait with merging, until also the PR for the footprint (https://github.com/KiCad/Modules.pretty/pull/1) is mature.

OK?

Best,
JAN

**Comment by myfreescalewebpage** [comment]
@jkriege2 yes, I have some few hours free, I'm fixing my PR on Kicad project today. this one should be ok now, I'm fixing the footprint actually and will push them soon.

**Comment by jkriege2** [comment]
OK,
I'll have a look at both later today then!

JAN

**Comment by SchrodingersGat** [comment]
@myfreescalewebpage we are slowly working through the backlog here. Can you please fix the conflicts here and we can try to merge? Thanks!

**Comment by myfreescalewebpage** [comment]
@SchrodingersGat no worries :-) Conflict resolution done.

**Comment by SchrodingersGat** [comment]
Thanks, this is one of our longest running PRs! Thanks for the contributions :)

**Pull request merged**
