### PR TITLE
Create MSP432P401R.lib

### PR DESCRIPTION
**Pull request by mohamedamjad**
Add TI MSP432P401R lib

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @mohamedamjad. Please, give a look here: http://kicad-pcb.org/contribute/librarians/ to see how to contribute to KiCad Libraries. Thanks

**Comment by SchrodingersGat** [comment]
Hi @mohamedamjad please indicate if you are still interested in contributing this, otherwise the PR will be closed. Thanks.

**Comment by poeschlr** [comment]
Closed and reopened to trigger travis

**Comment by SchrodingersGat** [comment]
CLosing due to inactivity. @mohamedamjad if you are still interested, please feel free to re-open

**Pull request closed without merging**
