### PR TITLE
Added LED driver IS31LT3360 to regul library

### PR DESCRIPTION
**Pull request by joewaj**

### CODE REVIEW

**Comment by reportingsjr** [comment]
The symbol doesn't conform to rule 3.6 of the library conventions. Please fix that.

**Comment by joewaj** [comment]
Where can I find a description of "rule 3.6" or: what exactly is wrong?

**Comment by reportingsjr** [comment]
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
It is in the base directory of this repository as a text file as well.

**Comment by ricardocrudo** [comment]
Hello @joewaj. please move the symbol to powerint library. Also fix the datasheet link, it's broken. Thanks for contributing.

**Comment by keruseykaryu** [comment]
I designed the `powerint.lib` for the Power Integration's devices. Only for PI devices.

**Comment by ricardocrudo** [comment]
hmm, ok, I didn't realize power integration was the manufacturer name. So @joewaj you can keep on regul.lib for while, in the future, maybe, a new led_drivers.lib fits better.

**Comment by ricardocrudo** [comment]
Thanks @keruseykaryu

**Pull request merged**
