### PR TITLE
Add ISSI IS31FL3216

### PR DESCRIPTION
**Pull request by GyrosGeier**
This is a 16 channel LED driver

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution (and sorry for this review to take so long ;-) Please change a few things on your symbol:
1) set the footprint-field to `Housings_DFN_QFN:QFN-28-1EP-4x4mm_Pitch0.4mm`
2) FPFilter should be `QFN*4x4mm*Pitch0.4mm*`
3) add description+keywords+datasheet-link (i.e. a DCM-file)
4) the outline should be 0.01" thick and the box should be filled yellow
5) VCC should be at the top-border
6) GND-pins at the bottom border

Best,
JAN

**Comment by hackscribble** [comment]
Closing and opening to rerun Travis CI checks.

**Comment by hackscribble** [comment]
Hi @GyrosGeier 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please check your symbol against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

If you click on the `Details` link in the box below, you will see some KLC errors flagged up by the automated tests.

When you update the PR, please post an image of the footprint and a link to the datasheet.

Many thanks

**Comment by Misca1234** [comment]
This component have been repushed, see 
https://github.com/KiCad/kicad-library/pull/1652

This push can be closed and deleted

**Pull request closed without merging**
