### PR TITLE
Xpt2046

### PR DESCRIPTION
**Pull request by Misca1234**
This is push for XPT2046TS and XPT2046QF

XPT2046TS and XPT2046QF
http://www.xptek.com.cn/uploadfile/download/201707171401161883.pdf

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

FPFilter should be `TSSOP*4.4x5mm*Pitch0.65mm*` and `QFN*4x4mm*Pitch0.65mm*`

Best,
JAN

**Comment by Misca1234** [comment]
Fixed, fixed pin 17 on QFN as well

bild

bild

**Comment by Misca1234** [comment]
I guess the travis script errors could be ignored, VBAT is an input and VREF is bidirectional according to datasheet

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
