### PR TITLE
Display symbol cleanup

### PR DESCRIPTION
**Pull request by Misca1234**
This is a cleanup of the displays

It replaces old symbols that have new foot prints and 3D models

LM16255K  (replaces LM16255K)
Can not be found, only found source is
https://easyeda.com/component/LM16255K-RuC8EysK2
http://pdf.datasheetcatalog.com/datasheet/Sharp/mXvtrzw.pdf

RC1602A  (replaces RC1602A-GHW-ESX)
http://www.raystar-optronics.com/down.php?ProID=18

bild

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks :)

**Comment by Misca1234** [comment]
Thx

**Comment by evanshultz** [comment]
@Misca1234 
Your contributions to KiCad have been awesome and all of us really appreciate it, as will KiCad users. That being said, you need not reply "Thx" to every single PR that is merged. This creates an automatic email for every single librarian. If you have further comments please include them, but we all value what you do for KiCad and it's not necessary to close out each PR with a message. Thanks again for your time and work!

**Comment by Misca1234** [comment]
oh, ok

**Pull request merged**
