### PR TITLE
Add Intersil EL72x2 MOSFET Driver

### PR DESCRIPTION
**Pull request by Gasman2014**
Fixing Travis errors (hopefully)

### CODE REVIEW

**Comment by Gasman2014** [comment]
Aargh - had enough of learning how to use Git for one day! Apologies to all for my general uselessness / double posting etc.

**Comment by Gasman2014** [comment]
Realise that despite my attempts to avoid it, I have pushed one update of the Micrel 442x series and then included those same changes in this push of the Intersil EL72x2 series. Pleased to see it all passed.

Hope it won't cause too much chaos - just learning Git and it is a steep learning curve :(

**Comment by poeschlr** [comment]
> Hope it won't cause too much chaos - just learning Git and it is a steep learning curve :(

A good explanatory video of what git really is:
https://www.youtube.com/watch?v=ZDR433b0HJY

Good tutorial site:
https://www.atlassian.com/git

**Comment by Gasman2014** [comment]
Hi Rene

Thanks for being understanding and helpful! I have also downloaded Scott Chacon’s book for a bit of light bedtime reading :). I don’t really have much of an IT background - (although I manage to work most stuff out - eventually!) and have only really used SVN for versioning before- GIT requires a bit of a paradigm shift - all those bad commits seem to hang around. I am a medical doctor by training and nearing retirement so need a few new challenges to keep the mind active!

John

**Pull request closed without merging**
