### PR TITLE
Ea e dip240 xxx

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIP240B-7LW
Aliases: EA eDIP240B-7LWTP, EA eDIP240J-7LW, EA eDIP240J-7LWTP, EA eDIP240J-7LA and EA eDIP240J-7LATP

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/edip240-7e.pdf

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1504

pretty push branch is
https://github.com/KiCad/Displays.pretty/pull/31

packages3D push branch is
https://github.com/KiCad/packages3D/pull/114

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/41

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
This one have aliases and default RS-232 as well, I guess it will be updated 
https://github.com/KiCad/kicad-library/pull/1494
is sorted out

**Comment by Misca1234** [comment]
It seems that 
https://github.com/KiCad/kicad-library/pull/1494
was merged, should this be merged or shall I do different types depending on the serial interface ?
(as discussed in the https://github.com/KiCad/kicad-library/pull/1494 thread)

**Comment by Misca1234** [comment]
Resolved conflict and took the opportunity to move in the NC pins 

bild

**Comment by evanshultz** [comment]
@Misca1234 
I'll let someone else do the review, but just a quick note that I believe the pin text offset should be 20milor less. This symbol is 40mil.

**Comment by Misca1234** [comment]
Changed text to 2 mm 
bild

**Comment by poeschlr** [comment]
@Misca1234 sorry for hijacking this but we would need your input about licensing of 3d models over at the issue https://github.com/KiCad/kicad-packages3D/issues/134

**Comment by Misca1234** [comment]
Let us wait with this one until 
https://github.com/KiCad/kicad-library/pull/1495
is merged.
https://github.com/KiCad/kicad-library/pull/1495
Messes up the lib and dcm for each of my displays pushes

**Comment by Misca1234** [comment]
This push have been repalced by 
https://github.com/KiCad/kicad-library/pull/1647

**Pull request closed without merging**
