### PR TITLE
Fixes all duplicated aliases in transistors.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR fixes all the duplications in transistors.lib

Ref: https://github.com/KiCad/kicad-library/issues/1074#issuecomment-283184959

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
With this fix there are no duplicated parts in any .lib file (checked with script)

**Comment by jkriege2** [comment]
Hi!

there are a few strange things in this commit:

## BF244B, BF244C, BF240
You assigned BF244B/C to BF240, but I would leave it with 2N7000 which also has BF244A. In addition BF240 is a bit strange. There is a tilde `~` in the DEF-line and F1 != BF240. Finally BF240 is an NPN transistor, but BF244 is a N-Channel FET ...
```
#
# BF240
#
DEF ~BF240 Q 0 0 Y N 1 F N
F0 "Q" 200 75 50 H V L CNN
F1 "BF244A" 200 0 50 H V L CNN
F2 "TO_SOT_Packages_THT:TO-92_Molded_Narrow" 200 -75 50 H I L CIN
F3 "" 0 -50 50 H I L CNN
ALIAS BF244B BF244C
$FPLIST
 TO?92*
$ENDFPLIST
DRAW
C 50 0 111 0 1 10 N
P 2 0 1 0 0 0 25 0 N
P 2 0 1 0 25 25 100 100 N
P 3 0 1 0 25 -25 100 -100 100 -100 N
P 3 0 1 20 25 75 25 -75 25 -75 N
P 5 0 1 0 50 -70 70 -50 90 -90 50 -70 50 -70 F
X C 1 100 200 100 D 50 50 1 1 P
X E 2 100 -200 100 U 50 50 1 1 P
X B 3 -200 0 200 R 50 50 1 1 I
ENDDRAW
ENDDEF
```

## IRF540N
OK

## BC856 BC857 BC858
OK

## BC850 BC849
OK

**Comment by jkriege2** [comment]
Please also have a look at BF245A which also has a tilde in the DEF-statement ... I think I had that once when the symbols are marked as power-symbols ....

**Comment by SchrodingersGat** [comment]
This PR has some issues caused by https://github.com/KiCad/kicad-library/pull/1076

I'll wait for that one to be merged and then tackle this. Thanks for the comments.

**Comment by jkriege2** [comment]
OK #1076 is merged ... now for this one?

JAN

**Comment by SchrodingersGat** [comment]
Ok I think I have this one fixed, check again please :)

**Comment by jkriege2** [comment]
nice work on all those fixes !

JAN

**Pull request merged**
