### PR TITLE
ZXCT current sensors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fixed footprint association for ZXCT1009
Added footprint filter for ZXCT1009
Added ZXCT1107
Added ZXCT1109

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

The ZXCT1009 is available in two packages (according to datasheet):
- ZXCT1009F: SOT23
- ZXCT1009T8TA: SM8

So could you maybe add a second component ZXCT1009T8TA?
And if you're at it ... could you also add the ZXCT1110 which is mentioned in the ZXCT1109 datasheet (SOT23-5 package)?

Best & thanks,
JAN

**Comment by jkriege2** [comment]
```
D:\KiCAD\kicad-library-review\library>..\..\kicad-library-utils\schlib\checklib.py -vv --enable-extra sensors.lib -p ZXCT
checking component: ZXCT1009
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -100, posy 200, recommended posx 0, posy 275
    field: reference, justification L, recommended C
    field: name, posx -100, posy -200, recommended posx 0, posy 200
    field: name, justification L, recommended C
    field: footprint, posx -100, posy -300, recommended posx 0, posy -200
    field: footprint, justification L, recommended C
checking component: ZXCT1107
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -100, posy 200, recommended posx 0, posy 275
    field: reference, justification L, recommended C
    field: name, posx -100, posy -200, recommended posx 0, posy 200
    field: name, justification L, recommended C
    field: footprint, posx -100, posy -300, recommended posx 0, posy -200
    field: footprint, justification L, recommended C
checking component: ZXCT1109
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -100, posy 200, recommended posx 0, posy 275
    field: reference, justification L, recommended C
    field: name, posx -100, posy -200, recommended posx 0, posy 200
    field: name, justification L, recommended C
    field: footprint, posx -100, posy -300, recommended posx 0, posy -200
    field: footprint, justification L, recommended C
```

**Comment by SchrodingersGat** [comment]
Jan,

I also like the position of the texts as they are. I look at that EC rule as a "suggestion".

If you want to merge what I have done thus far, the extra components can be added at a later stage?

**Comment by jkriege2** [comment]
Fine with me ...

**Comment by jkriege2** [comment]
PS: Could you have a look at my device.lib workover?
https://github.com/KiCad/kicad-library/pull/742

Thanks,
JAN

**Pull request merged**
