### PR TITLE
Battery related components

### PR DESCRIPTION
**Pull request by SchrodingersGat**
I have started a new library for battery related components:
i.e. chargers, balancers, etc

Some of these components are new additions,

Some have been moved from regul.lib to batt.lib

There may be some back-and-forth required to get this one sorted!

@ricardocrudo @pointhi  @CarlPoirier  maybe you guys can weigh in here? I think these components are out of place in regul.lib, and batt.lib seems to be a glaring omission :)

LMK what you think.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@CarlPoirier  @ricardocrudo  @pointhi do any of you fine fellows have some input here? I found that many battery-related symbols were either uncategorized or poorly categorized. 

I have removed these components from my other PR (https://github.com/KiCad/kicad-library/pull/260) as required.

**Comment by SchrodingersGat** [comment]
@diggit  what do you think of the addition of a "batt" library?

**Comment by diggit** [comment]
IDK if power management lib is not enough. (future merging libs is bad) On the other hand, battery chips are quite specific. I'd prefer to see more opinions. Unfortunately it seems, that other librarians are busy. I'll set appropriate label. We'll see...

**Comment by CarlPoirier** [comment]
Hi guys,

I think it is a good idea, although I'd call it something more meaningful like battery_management.lib!

**Comment by SchrodingersGat** [comment]
I can rename to that if everyone is in agreement. I agree that
battery_management is a better name.

**Comment by SchrodingersGat** [comment]
Howdy. I have merged the most recent kicad/master branch and renamed batt to battery_management

I await instruction.

**Comment by CarlPoirier** [comment]
This is great. Thank you very much Oliver.

**Pull request merged**
