### PR TITLE
rfcom: add MOD-nRF8001 symbol

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by piotr-wiszowaty** [comment]
A schematic containing the symbol loads properly. checklib.py (commit 
f6036f) shows no rule violation.
How else can I check it?

**Comment by reportingsjr** [comment]
Sorry, I am trying to set up some automated checklib.py testing on this repo. Feel free to ignore that comment. :)

**Comment by piotr-wiszowaty** [comment]
No problem.

**Comment by SchrodingersGat** [comment]
Hi @piotr-wiszowaty sorry that this PR has been neglected.

Please check the output of the KLC scripits - https://travis-ci.org/KiCad/kicad-library/builds/239779832

**Comment by piotr-wiszowaty** [comment]
Rule violations corrected.

**Comment by jkriege2** [comment]
Hi (also @SchrodingersGat )!

looks good overall ... Will you also provide the footprint? If so, we could wait with merging until (at least) the footprint anme is clear and already put it here ...

Best,
JAN

**Comment by piotr-wiszowaty** [comment]
Footprint PR-ed (Modules.pretty).

**Comment by SchrodingersGat** [comment]
Thanks for your contribution @piotr-wiszowaty sorry it was delayed for so long

**Pull request merged**
