### PR TITLE
Added LQFP variants of SAME70

### PR DESCRIPTION
**Pull request by DerekGn**
ATSAME70Q21A-AN
ATSAME70Q20A-AN
ATSAME70Q19A-AN

image

ATSAME70N21A-AN
ATSAME70N20A-AN
ATSAME70N19A-AN

image

ATSAME70J21A-AN
ATSAME70J20A-AN
ATSAME70J19A-AN

image

### CODE REVIEW

**Comment by poeschlr** [comment]
All other Microchip MCU libs have already been moved to the new repo  in preparation for the v5 release.
Could you please re submit this over at the new repo https://github.com/KiCad/kicad-symbols

**Comment by DerekGn** [comment]
Can we not have it in both prior to v5 release?

**Comment by poeschlr** [comment]
There will not be a new release prior to v5. So we decided not to except anything to the legacy libs after we start moving libs. (otherwise we will make a lot of mistakes during the moving/reorganization process.)

**Comment by DerekGn** [comment]
Ok I will close this PR. I have submitted one to the new repo.

**Pull request closed without merging**
