### PR TITLE
Add temperature sensors (KTYxx, PT100, PT500, PT1000, MCP950x)

### PR DESCRIPTION
**Pull request by jkriege2**
I added symbols for 
* [ ] PT100, PT500, PT1000, 
* [ ] KTY81, 
* [ ] KTY82, 
* [ ] KTY83, 
* [ ] KTY84:
* [ ] MCP950x 

kty

also added MCP950x temperature switch devices:
mcp9501

- see KiCad/Diodes_ThroughHole.prettyy#13 for footprints (DO-34) and 
- see #722 for 3D models (DO-34)
- see KiCad/TO_SOT_Packages_THT.pretty#11 for the TO92-2pin footprints for PT100/500/1000

### CODE REVIEW

**Comment by jkriege2** [comment]
added: 
- PT500
- RTD_3wire
- RTD_4wire
- KTY83
- KTY84

fixed KLC violations, altered symbols a bit

**Comment by jkriege2** [comment]
Added symbols for thermocouples:

thermocouple

**Comment by jkriege2** [comment]
I added general symbols for NTC, PTC, NTC_3write, PTC_3wire, NTC_4wire, PTC_4wire
+ some minor corrections to symbols (text alignment/placing, ...)
+ all new symbols conform to KLC (except datasheets, as they are general symbols)

tempsense
thermocouple

**Comment by jkriege2** [comment]
OK; I also added some of these components (the general version!) to device.lib in this (https://github.com/KiCad/kicad-library/pull/742) PR. So we should wait until that PR is pulled, bevore pulling this. I will then alter this lib!

Best,
JAN

**Comment by diggit** [comment]
Is here anything that is not included in #742 ?

**Comment by jkriege2** [comment]
Hi yes, there are e.g. KTY-devices, some special symbols for PT100/500/1000 etz. I'll fix this up and make it ready (if anything is left ;-) when #742 is merged.

cu
JAN

**Comment by jkriege2** [comment]
This PR should be consistent with https://github.com/KiCad/kicad-library/pull/742 now!
JAN

kty

**Comment by jkriege2** [comment]
also added MCP950x temperature switch devices:
mcp9501

**Comment by jkriege2** [comment]
@diggit This PR should be cleaned-up now and won't cpollide with #742 but follows the style of #742 

Can be merged, or should we wait for #742 ?

JAN

**Comment by jkriege2** [comment]
@SchrodingersGat @CarlPoirier could you have a look at this?
Thanks,
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat @pointhi @diggit  Could you have a look at this one? Would be great if it was still in the tag!

best,
JAN

**Comment by SchrodingersGat** [comment]
Great work, merging

**Pull request merged**
