### PR TITLE
Added schematic libs for MIC5353 fixed voltage LDOs

### PR DESCRIPTION
**Pull request by swedishhat**
Added MIC5353-3.3YMT schematic lib and then aliases for the other fixed voltage LDOs in the product line. I omitted the adjustable output variant.

### CODE REVIEW

**Comment by swedishhat** [comment]
The archive.txt file says:

checking component: TEST_1P
  Violating Rule 3.6
  Violating Rule 3.8

I don't have any component called TEST_1P. Is this something to do with Jenkins CI?

**Comment by reportingsjr** [comment]
Yeah, I don't know why it is doing that. Feel free to ignore it.

Carl - any idea what happened there?

**Comment by CarlPoirier** [comment]
Yeah I wanted to email you about it. I committed this TEST_1P while it was wrong. I then batch corrected all components with this pull request: https://github.com/KiCad/kicad-library/pull/332

While we're at it, would you mind giving it a spot-check so we can merge it?

**Comment by CarlPoirier** [comment]
@swedishhat As for your pull request, can you please fill in the description and keywords in the symbol properties? It will then be good to go.

Thanks!

**Comment by swedishhat** [comment]
@CarlPoirier The keywords and description look like they're already taken care of both in the Part Library Editor on my machine and in the .dcm file that was committed. Am I going crazy and missing something obvious?

**Comment by swedishhat** [comment]
Also, while somewhat off topic, I need some guidance on which repository to add the footprint files to. They're identified as "6-Pin 1.6mm x 1.6mm Thin MLF" (some variant of DFN I think?) with a power pad underneath. SMD_Packages.pretty and Power_Packages_SMD.pretty look depreciated. Is Housings_DFN_QFN.pretty the way to go here?

**Comment by reportingsjr** [comment]
test this please

**Comment by ricardocrudo** [comment]
Hello @swedishhat. Can you please also create the documentation to aliases?

**Comment by swedishhat** [comment]
I'm not totally sure how to do that. If someone can point me in the right direction, I'll get right on it. I'm fairly new to contributing to big open source projects like this.

**Comment by ricardocrudo** [comment]
@swedishhat 

Select the alias you want to edit:



Open the properties dialog:



Copy documentation from parent and edit it according the alias you selected:

**Comment by swedishhat** [comment]
Okay, I went through and added the documentation to the aliases. Those changes have been pushed.

**Comment by CarlPoirier** [comment]
Hi @swedishhat,

Can you pull the kicad-library master and fix the conflicts please? I'd like to get this merged!

**Comment by hackscribble** [comment]
Hi @swedishhat 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
