### PR TITLE
added 3d shape for smb connector

### PR DESCRIPTION
**Pull request by dfro**
Added 3d shape for smb connector. Footprint for this connector in KiCad/Connect.pretty/pull/20
Connector: [1-1337482-0](http://www.te.com/usa-en/product-1-1337482-0.html)

### CODE REVIEW

**Comment by michal777** [comment]
I'm afraid it can't be added to open source library because it's property of TE Connectivity.

**Comment by dfro** [comment]
@michal777  I have made this model form scratch and it does not fully repeats design of TE Connectivity.
Is it still violates TE Connectivity rights?

**Comment by michal777** [comment]
If it is not the model available on their page it's ok.

**Comment by dfro** [comment]
No, it is not.

**Comment by michal777** [comment]
Could you rename it to SMB_Straight and scale the 3d model? Wayne asked to keep these 0.1inch/div units in official libraries.

**Comment by michal777** [comment]
Sorry that I didn't write clear enough about the scaling. Scale in footprint properties should be 1,1,1 (I meant that in wings3d 0.1 inch is one default unit). Now it's 10x too big.

**Comment by michal777** [comment]
Thanks. It's a bit shifted from the centre. Not a big problem, so if you won't correct this I will merge it tomorrow.

**Pull request merged**
