### PR TITLE
Connectors: Add SMA connector

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
KLC 3.8 fails because generic component.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Do you have an example footprint for this symbol, just for checking?

**Comment by pointhi** [comment]
For me it doesn't make sense to split GND into 4 pins. Is there any use case where you have to connect different lanes to different GND pins of an RF connector?

**Comment by myfreescalewebpage** [comment]
@pointhi No there isn't. The connector has 4 pins for the ground, so I have created the 4 pins on the schematic. I can make only one for the ground, but then, how to make the association with the footprint ?

**Comment by SchrodingersGat** [comment]
Give all the ground pins on the footprint the same number and they will all be associated with the GND pin on the symbol :)

**Comment by myfreescalewebpage** [comment]
Done. I have also modified my SMA footprint on Connectors_Amphenol.

**Comment by seec** [comment]
where can i find Connectors_Amphenol library?
(to add HCCPHPE24BKA90 footprint)

**Comment by pointhi** [comment]
@seec https://github.com/KiCad/Connectors_Amphenol.pretty

**Comment by myfreescalewebpage** [comment]
Up?

**Comment by myfreescalewebpage** [comment]
Merge from master to resolve conflicts done.

**Comment by jkriege2** [comment]
I made a PR for an extended coax-connector that can be used for SMA,SMB,SMC,BNC,RCS/Cinch,...

https://github.com/KiCad/kicad-library/pull/958

Would that be OK for you too?

**Comment by jkriege2** [comment]
I pasted better DIFF screenshots there ... just the two shown connectors added and BNC removed!

**Comment by myfreescalewebpage** [comment]
Closing this pull request as #958 is merged.

**Pull request closed without merging**
