### PR TITLE
Fixes for MAX777

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Added documentation
- Fixed pin types
- Improvements to schematic symbol

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@diggit  fixes for the MAX777

**Comment by diggit** [comment]
Please add step-up and boost keywords.
Violation of KLC 3.3.  Origin is placed in the middle of symbol.
Reset graphical style of SHDN as it is already indicated by overline.
I'd prefer not placing pins so close to the top edge.

Thanks that you are taking care of whole symbol and docs.

**Comment by SchrodingersGat** [comment]
Done.

**Comment by diggit** [comment]
Thanks for fixing that.
nice work you did, merging

**Pull request merged**
