### PR TITLE
Add M95256-WMN6P

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
[Datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/9d/75/f0/3e/76/00/4c/0b/CD00103810.pdf/files/CD00103810.pdf/jcr:content/translations/en.CD00103810.pdf)

imagen

imagen

imagen

imagen

Thank you very much!

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
* Please fix size of text fields (change to 50mils)
* Pins look quite long - can you reduce them by 100mils or so?

**Comment by antoniovazquezblanco** [comment]
Done. Thanks!

**Comment by antoniovazquezblanco** [comment]
Forgot power pin lenghts. Done!

**Comment by antoniovazquezblanco** [comment]
Fastest merge ever. Thank you again for your work! ;)

**Comment by SchrodingersGat** [comment]
And thanks for yours! Please keep the contributions coming :)

**Pull request merged**
