### PR TITLE
Lmc7660

### PR DESCRIPTION
**Pull request by Misca1234**
The author of push 
https://github.com/KiCad/kicad-library/pull/1334
have not responded in 2 month so this push is a replacement

http://www.ti.com/lit/ds/symlink/lmc7660.pdf

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Some of the pushes of a symbol people do include the pin type in blue as well, 
how do I switch on that in the symbol editor ?

**Comment by suzizecat** [comment]
AFAIK you need a nighty build of KiCAD and switch it using a button on the left side bar

**Comment by Misca1234** [comment]
Aha, ok, thx

**Comment by evanshultz** [comment]
You can show the Pin Table in released versions:
image

**Comment by Misca1234** [comment]
bild

bild

**Pull request merged**
