### PR TITLE
Added CP2104 USB to UART bridge

### PR DESCRIPTION
**Pull request by SchrodingersGat**
https://www.silabs.com/Support%20Documents/TechnicalDocs/cp2104.pdf

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

```
checking component: CP2104
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin NC (10): P (PASSIVE), expected: N (NOT CONNECTED)
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 300, posy 1050, recommended posx -300, posy 925
    field: reference, justification L, recommended R
    field: name, posx 300, posy 950, recommended posx -300, posy 850
    field: name, justification L, recommended R
    field: footprint, posx 300, posy 850, recommended posx 150, posy -950
```
... maybe just the EC01 is really valid?

Best,
JAN

**Comment by SchrodingersGat** [comment]
In the [datasheet](https://www.silabs.com/Support%20Documents/TechnicalDocs/cp2104.pdf) it says that the NC can be left unconnected **or connected to Vio**.

For this reason I have left it visible, as it may be connected to the other pin.

**Comment by jkriege2** [comment]
Then maybe mark it as NC and call it NC_OR_VIO ??? Currently its PASSIVE ... But my proposal is also not the best solution ;-) What do you think?

JAN

**Comment by SchrodingersGat** [comment]
Personally I'd leave it as is - it's up to the user to read the datasheet and decide what to do with the pin ;)

**Comment by jkriege2** [comment]
OK, but is the pin PASSIVE or NC? Or even POWER_INPUT, if it can be optionally tied to Vio?

**Comment by SchrodingersGat** [comment]
I will change it to power_input then :)

**Comment by jkriege2** [comment]
Cool with me ... I'll merge when done ;-)

**Comment by SchrodingersGat** [comment]
fixed :)

**Pull request merged**
