### PR TITLE
Add 3dmodels sip res arrays

### PR DESCRIPTION
**Pull request by jkriege2**
3D packages for this PR https://github.com/KiCad/Resistors_ThroughHole.pretty/pull/13

res14

### CODE REVIEW

**Comment by jkriege2** [comment]
I created a PR for the creator-script: https://github.com/pointhi/kicad-footprint-generator/pull/12

**Comment by jkriege2** [comment]
@pointhi: Can be merged? The footprints were already merged (https://github.com/KiCad/Resistors_ThroughHole.pretty/pull/13).

JAN

**Comment by jkriege2** [comment]
Should we also have the STEP-files here? As `.stp` or `.step` files?

JAN

**Comment by jkriege2** [comment]
@diggit ... Should we have STEP files here too?

JAN

**Comment by jkriege2** [comment]
@diggit : As for the TO-18 packages (see https://github.com/KiCad/kicad-library/pull/734) I also added the STEP models here ... Can be merged?

best,
JAN

**Comment by pointhi** [comment]
Thanks, look good to me

**Pull request merged**
