### PR TITLE
Template Arduino : Fix pin order SS, MOSI, MISO, SCK

### PR DESCRIPTION
**Pull request by jonathan-iap**
On board : nano , fio, mini. 
ISP (ss, mosi, miso, sck) pin were not in correct order.

### CODE REVIEW

**Comment by ashtonchase** [comment]
Checked
- [ ] Nano
- [ ] Fio
- [ ] Mini

**Comment by jonathan-iap** [comment]
Thank for your help !
I need to open a new pull request for this or i can add a commit ?

**Comment by SchrodingersGat** [comment]
@jonathan-iap just keep adding commits to this PR :)

**Comment by jonathan-iap** [comment]
Ok cool, I correct Arduino mini pin mapping.

**Comment by ashtonchase** [comment]
Hi @jonathan-iap,
It appears in your last commit, you also pushed changes that were not related to this pull request. It's an honest mistake if this is a new process to you. 

In order to get the specific changes you commited, I had to manually merge the specific files related to this pull request. That was performed here: https://github.com/KiCad/kicad-library/commit/5f329e76467f7a24995e2d6d5887d20d4994f45c

Because of this, I will close this pull request. Even though it will say that its not merged. It is. 

Hi @CarlPoirier. I wanted to tag you in this so that you are aware of what took place.

**Pull request closed without merging**
