### PR TITLE
MC34063 corrected.

### PR DESCRIPTION
**Pull request by mpkopec**

### CODE REVIEW

**Comment by diggit** [comment]
Good, I was thinking about layout and I almost agree.
Tweaks:
- put GND on bottom and Ct on GND's old position
- rename Ct to Tc as Ct is mostly called capacitor connected to this pin
- set outline thickness to 0.010
- set fill to background
- change SwC to type open collector, SwE to open emitter
- change footprint filters to SOIC*, DIP*, DFN*, * wildcard is important

**Comment by mpkopec** [comment]
Thanks for the message! I changed DC to open collector as well. The rest is as you asked.

**Comment by diggit** [comment]
Whoops, I checked ERC matrix and OC and OE connected to power output will generate error, my fault.
- change SwE, SwC and DC to passive (eg. SwE sohuld be input when connected to GND, but sometimes it drives transistor, then output is correct. -> passive)

Everything else look OK

**Comment by mpkopec** [comment]
Done ;)

**Comment by diggit** [comment]
Value field is really too close to GND pin.
You can try `./checklib.py -vv  --enable-extra  -c MC34063 --fix regul.lib` to do it for you. (latest utils needed)
I am not telling this is last thing, but I hope...

**Comment by mpkopec** [comment]
Done the auto fix thing. Hope nothing more is wrong.

**Comment by diggit** [comment]
> change footprint filters to SOIC, DIP, DFN\*, \* wildcard is important

markdown and wildcard are not friends :/
I meant SOIC\* DIP\* DFN\*

**Comment by mpkopec** [comment]
To be honest, when you wrote to put wildcard I was wondering if you meant all the filters or only the one... Apparently my hunch was correct xD

**Comment by diggit** [comment]
Yeah, I forgot to escape all \*.
Nice work you did, merging.

**Comment by mpkopec** [comment]
Thanks!

**Pull request merged**
