### PR TITLE
sensors: add ams AS726X Spectral Sensing Engine

### PR DESCRIPTION
**Pull request by ChristianHirsch**
Hi @poeschlr @SchrodingersGat,
added ams [AS7261](http://ams.com/eng/Products/Spectral-Sensing/Multi-spectral-Sensing/AS7261) [AS7262](http://ams.com/eng/Products/Spectral-Sensing/Multi-spectral-Sensing/AS7262) and [AS7263](http://ams.com/eng/Products/Spectral-Sensing/Multi-spectral-Sensing/AS7263) spectral sensing engines.
image

### CODE REVIEW

**Comment by poeschlr** [comment]
The placement of the not connected pins is not the best idea. Place them somewhere around the outline like normal pins. (If you place them somewhere else it is quite easy for a user to connect them by accident.)

**Comment by ChristianHirsch** [comment]
Can I place them inbetween the other pins, @poeschlr? Doesn't this placement destroy the grouping of the other pins so I need to increase the size of the component?
image

**Comment by jkriege2** [comment]
THat placement should be fine ... may I ask: Why are the NC-pins called NF?

Best,
JAN

**Comment by ChristianHirsch** [comment]
@jkriege2 they are called NF ("Non-Functional") in the datasheet, that's why I also called them NF.

**Comment by ChristianHirsch** [comment]
@SchrodingersGat @poeschlr Anything I need to change?

**Comment by SchrodingersGat** [comment]
Thanks for your contribution :)

**Pull request merged**
