### PR TITLE
Anger checklib.py

### PR DESCRIPTION
**Pull request by reportingsjr**
Testing out the new automated testing script.

It looks like the jenkins plugin might have a bug so we wont be able to use "test this please" quite yet.

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by SchrodingersGat** [comment]
Is there a way to automatically run the script when a PR is opened? Or do you have to say "test this please"?

**Comment by reportingsjr** [comment]
So I've apparently run across a bug in the jenkin's plugin being used for this. I'm going to continue poking around trying to get it working, but right now it is entirely broken. :(

I'll keep you updated on this as I try and fix it. Sorry if the pull requests being annoying!

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
testing

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: MCP1700T-3002E/TT
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
checking component: MPU-9250
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
checking component: MPU-6000
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
checking component: MPU-9150
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
checking component: MPU-6050
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
+ MCP1700T-3002E/TT
+ MPU-9250
+ MPU-6000
+ MPU-9150
+ MPU-6050
```

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: DS1822Z
  Violating Rule 3.6
    Field text uses a common size of 50mils.
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
# DS1822Z
```

**Pull request closed without merging**
