### PR TITLE
Added the Analog Devices ADP2302ARDZ

### PR DESCRIPTION
**Pull request by johnfwhitmore**
I've made it a bit fatter this time. One error from this component:

$ schlib/checklib.py -cADP2302ARDZ ../kicad-library/library/dc-dc.lib 
Checking symbol 'ADP2302ARDZ':
  Violating Rule 4.5 - Pin orientation

adp2302ardz

### CODE REVIEW

**Comment by jkriege2** [comment]
Could you do some final visual enhancements and move the end of the NC-pin onto the outline (then it's harder to accidentally connect to it:

2017-11-06 20_54_17-part library editor -- d__kicad_kicad-library-review_library_dc-dc lib

Thanks,
JAN

PS: You don't need to open a new PR every time you change something. Just commit to your local branch and push the cchanges into your fork. the PR will be updated then!

**Comment by johnfwhitmore** [comment]
I can't edit the component in kicad, so it has been simpler to make the changes, copy out the text into a temp file,  and delete everything. Rebase and start again just adding the text that has changed in a oner. Adding incremental lines of text would be a pain. 
If it can be fixed so that I can make changes to a single component in Kicad, and not as a result make changes to every single component in the open library, I'm all for that type of change. In the mean time making the changes and deleting everything is the work flow which seems to work.
I'll try to make those changes to this PR, just for the laugh, but ultimately I'd not be surprise if it was to be deleted as my branch gets messed up by kicad.

**Comment by johnfwhitmore** [comment]
adp2302ardz

**Comment by johnfwhitmore** [comment]
Made another commit to this branch. Well I hope my merge to my branch shows up here

**Comment by jkriege2** [comment]
Which version of KiCAD do you use? Usually if KiCAD changes several lines it has one of two reasons:
1. the lib was created with an old version of KiCAD, then some resorting of lines and sometimes removal of whitespace is done (and will be accepted)
2. the KiCAD version is too old, some older version intriduce double-whitespaces behind some params ... that won't beaccepted.

Otherwise: Nice work!

Thanks,
JAN

**Comment by johnfwhitmore** [comment]
Application: kicad
Version: (2017-11-03 revision 08a9dc0)-master, debug build
Libraries:
    wxWidgets 3.0.2
    libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Platform: Linux 4.4.0-97-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.2 (wchar_t,wx containers,compatible with 2.8) GTK+ 2.24
    Boost: 1.58.0
    Curl: 7.47.0
    Compiler: GCC 5.4.0 with C++ ABI 1009

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=OFF
    KICAD_SCRIPTING=OFF
    KICAD_SCRIPTING_MODULES=OFF
    KICAD_SCRIPTING_WXPYTHON=OFF
    KICAD_SCRIPTING_ACTION_MENU=OFF
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=OFF
    KICAD_SPICE=OFF

**Comment by johnfwhitmore** [comment]
Thanks a million for that. My kicad is a build from the weekend, checked it out of the mirror.
Hopefully the next one will be a bit smoother ;-)

**Comment by jkriege2** [comment]
Hmm .. mine resorts some of the lines that specify pins ... so that should be fine 

But if only the new part changes that's even better ;-)

JAN

**Pull request merged**
