### PR TITLE
Added 3d models for Molex SPOX 5267 2-10 pins straight connectors

### PR DESCRIPTION
**Pull request by sonelu**
The footprints are included in a separate pull request against the Connectors_Molex.pretty repository.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice models. Which program did you use to draw them? If it was e.g. FreeCAD could you also provide the source file?

Best,
JAN

**Comment by sonelu** [comment]
Jan, the models are downloaded directly from Molex (STEP) and are converted to VRML using FreeCad macro that was mentioned in the forums.
I can include the STEP files if you think they are valuable.

**Comment by jkriege2** [comment]
Do you know which license MOLEX uses for their models? Are we allowed (at all) to host them here and use them?

best,
JAN

**Comment by sonelu** [comment]
Jan,

The download [link](http://www.molex.com/molex/part/partModels.jsp?&prodLevel=part&partNo=022035035&channel=products) for one of the models states:

> I understand that the information I am about to download may not be complete or accurate, and the products depicted in drawings, models, specifications, and other types of content may not be to scale, or the most recent version. I further agree that these files will be used in accordance with the terms and conditions appearing in the web site LEGAL NOTICE including use of these files AT MY OWN RISK

The [Legal](http://www.molex.com/molex/common/staticLoader.jsp?fileName=/legal.html) page referred to states (among others):

> The entire content (images and text) of this Website is copyrighted and may not be distributed, downloaded, modified, reused, reposted or otherwise used, except as provided herein, without the express written permission of Molex. You may download content only for your personal, non-commercial use.

I guess if we really want to be sure we might have to send them a mail and ask for a formal confirmation that the use on KiCad constitutes non-commercial use.

What do you think?

Alex.

**Comment by jkriege2** [comment]
I would say the Legal-page excludes reposting the 3D models here ... `may not be distributed, downloaded, modified, reused, reposted or otherwise used`

Unless you write them and they give their OK!

Best,
JAN

**Comment by sonelu** [comment]
Jan,

I've sent them a mail, although it's quite convoluted as they don't have a contact mail address listed; instead you need to use one of those web forms and there is no confirmation sent back to your email address. I will let you know if I hear anything from them.

Alex.

**Comment by sonelu** [comment]
Changed the names of the Molex SPOX 3D files to match the names of the footprints.

Alex.

**Comment by jkriege2** [comment]
Hi @sonelu Did you hear back from MOLEX?

JAN

**Comment by sonelu** [comment]
Jan,

No, there was no reply from them. But I have noticed that component sellers also provide the STPs for the parts. For instance Digikey [here](https://www.digikey.co.uk/product-detail/en/molex-llc/22-03-5035/WM18887-ND/403302). I'll send them a mail - they might be more responsive.

Alex.

**Comment by SchrodingersGat** [comment]
@sonelu unless you receive explicit instruction from Molex that they are happy for us to relicense their model data under the CC-BY-SA 4.0 license then we will not be able to accept this PR, sorry!

I'll close this for now, please re-open this PR if you hear back. Thanks :)

**Pull request closed without merging**
