### PR TITLE
Mic5504  ym5

### PR DESCRIPTION
**Pull request by Misca1234**
This is a SOT-23 based LDO regulator
The base is the MIC5504-3.3V
http://ww1.microchip.com/downloads/en/devicedoc/mic550x.pdf
and the aliases
MIC5504-2.8V
MIC5504-2.5V
MIC5504-1.8V
MIC5504-1.2V

bild

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
As these devices only have a single compatible footprint (SOT-23-5) please add that as the default footprint.

Otherwise good to merge :)

**Comment by Misca1234** [comment]
Like this ?
(It will "miss" the hand soldering variant of the SOT23-5 footprint)


bild

**Comment by SchrodingersGat** [comment]
Exactly! Thanks :)

**Comment by Misca1234** [comment]
awsome, thx

**Pull request merged**
