### PR TITLE
Added Multiwatt-11 model

### PR DESCRIPTION
**Pull request by maqifrnswa**
EDIT (other pull requests):
KiCad/packages3D-source#7
KiCad/packages3D#45

This is my first model, let me know if anything needs to be updated.

Footprint already exists and already references this model, this model fits the existing footprint.

This is based on:
http://www.st.com/content/ccc/resource/technical/document/datasheet/1a/b1/d0/90/8b/8d/40/fe/CD00236549.pdf/files/CD00236549.pdf/jcr:content/translations/en.CD00236549.pdf

multiwatt-11_vertical_staggeredtype2
multiwatt-11_vertical_staggeredtype2-2

### CODE REVIEW

**Comment by poeschlr** [comment]
First question: Did you design this model yourself or did you download it somewhere?
(If you downloaded it somewhere what is the license of this model? In most cases it is not a good idea for this project to include files that are not produced by the person who commits the files.)

Now to the model itself:
It looks very nice (on the screenshot. I did not yet check the file itself.)
Assuming you designed it in freecad (there is a freecad file in your pull request) could you also add a step file?
But don't use freecad 0.16 to export the step file. (There is a nasty bug in v0.16 use either a current v0.17 or v0.15)
The easiest way to export a correctly scaled wrl and step file with nice colors is to use the [kicad stepup tools](https://sourceforge.net/projects/kicadstepup/).

I'm not sure if the wings file is useful anymore. The fcstd file should be uploaded to the https://github.com/KiCad/packages3D-source repo.
The step and wrl models should be uploaded to the https://github.com/KiCad/packages3D repo. (In the future this new repo will take over the role of the models directory in this library. For now the models should also be included here.)

Don't include source files in this repo though. (As written above there is a dedicated repo for that.)

**Comment by maqifrnswa** [comment]
Thanks - I did do this model myself. I'll change it up and make the appropriate pull requests.

I followed the suggested workflow in kicad/packages3d which had you use wings3d to add color. How do you add/change colors without using wings3d? (I'm a 3d asset novice!)

I read a lot of the "how to contribute" documentation, and it isn't clear what files are wanted and where (in fact this is the output of what is suggested to do on the kicad/packages3d repo). I don't mind figuring it out, but it could be helpful to have the workflow (which repos to pull request against, and how those get merged to the main repo) and the list of needed file types somewhere (the documentation just says wrl and freecad files, but in my case you can't recreate the wrl without the wings file too - mostly because the tutorial had toy use wings3d to add color)

**Comment by jkriege2** [comment]
Hi!

I think the 3D model-workflow is only currently developing properly ... THe bottom line is this:
1. Sources should go to https://github.com/KiCad/packages3D-source
2. Output (VRML/WRL+STEP-files) should go to two places: 
  1. https://github.com/KiCad/kicad-library/tree/master/modules/packages3d as that's the place where KiCAD currently searches for the 3D models
  2. https://github.com/KiCad/packages3D as that is where the models will move to in future
3. WINGS is no longer used. Currently VRML is the format of choice for KiCAD, but I think future versions will be able to read STEP. Also STEP is required for good export to mechanical 3D-CAD
4. For coloring: I simply apply the colors in FreeCAD, as follows:
2017-04-30 19_31_43-freecad
2017-04-30 19_31_57-freecad

Hope that helps,
JAN

**Comment by maqifrnswa** [comment]
Thank you! This is excellent help! It was fun learning how to make these models, I think I may have to make more models to finish off my board and contribute them to the library ;)
I've also learned some tricks to improve this model.

Is there any standard for material colors? Default freecad silver looks good for leads, but "plastic" is too dark for the body. I can just play around and get something that works, just curious what you or others use.

**Comment by Shackmeister** [comment]
If you use stepup you can add the material properties when exporting. This will also give the correct scaling for 1 1 1 in the footprint. All in all, stepup is the way, stay far away from wings :)

**Comment by Shackmeister** [comment]
Stepup has default colors (you should use black body and metal grey pins), the colors are also added to the step model, but without the materiel properties

**Comment by maqifrnswa** [comment]
Thank you so much everyone! I made the two pull requests, and also made a model for the staggered variant. I used the stepup colors, that is a really nice tool. There are a couple other things I wanted to model on my board, if I get to them I'll submit them as well.

KiCad/packages3D-source#7
KiCad/packages3D#45

multiwatt-11_vertical_staggeredtype-bothtypes

**Comment by easyw** [comment]
@maqifrnswa you may also have a look at the [new scripts for TO models](https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/TO_SOT_Packages_SMD_custom) made by @hackscribble 
with this structure it would be possible to create the Multiwatt11 by script, obtaining both STEP and WRL with the right colors and materials for KiCad
You can get a [doc for the Materials](https://cld.pt/dl/download/64e39e99-c5b6-451b-accd-9e25331ceafe/KiCad_3D-Viewer_component-materials-reference-list_MarioLuzeiro.pdf?download=true) at the section 'Preferred method to create 3D models' in the README.md of this repo; you can find a list of properties for the materials used in this repo [here](https://github.com/easyw/kicad-3d-models-in-freecad/blob/master/cadquery/FCAD_script_generator/_tools/shaderColors.py)
@Shackmeister would it be useful to remove the suggestion to use Wings3D when KiCad is installed in windows? I think now this is a wrong information to give users...

**Comment by Shackmeister** [comment]
@easyw it has already been removed :)

**Comment by easyw** [comment]
@maqifrnswa I noticed that the step model 'Multiwatt-11_Vertical_StaggeredType2' inside FC is named (Label) 'Fillet001_sp' instead of the file name
Would you mind to rename it accordingly?
@Shackmeister good to know they finally removed it 😄

**Comment by easyw** [comment]
@Shackmeister @SchrodingersGat 
it seems that Wings3D is still suggested by the windows installer:
https://github.com/KiCad/kicad-winbuilder/blob/master/nsis/install.nsi

**Comment by maqifrnswa** [comment]
@easyw thank you! I renamed the label to the file name.
Those new scripts for TO models are helpful... if I get some time I'm thinking of messing with them to auto-generate Multwatt 5, 11, and 15 packages (e.g., KiCad/kicad-library/issues/1190)

The resources you've shown me have been great, and I'd like to help new contributors, so I can give you my impression.

I know things are currently in flux, but it was a little overwhelming trying to figure out exactly what files were needed and where (especially to someone that doesn't know 3D modeling) and what tools should be used.

Here are some notes that might be helpful to a novice modeler (but technically experienced), please feel free to use/post this somewhere:

- 3D models must at least be given in VRML 2.0 (.wrl) and should be given also as STEP (.step) files. Both are ISO standard files for 3D models. .wrl files only contain info on rendering the model, .step files also include precision mechanical information. .wrl files are used to generate models in KiCAD's 3D viewer, but if you want to use your KiCAD PCB model in some other CAD program, you'll need to use the .step files. Future KiCAD viewers may render STEP files, so both should be generated.
- The suggested way to make WRL and STEP files is to use FreeCAD (version 0.17+ because of a bug in 0.16) along with an add-on to FreeCAD called "StepUp." FreeCAD makes the model and StepUp will (1) export to wrl and step with the proper settings/scale for KiCAD, (2) allow you to easily align your model to an existing footprint, and (3) add the correct materials so it renders properly.
  - Good video on how to make a model in FreeCAD: https://youtu.be/S63DLV5HOPA
  - Good video on how to use StepUp: https://youtu.be/COUdDZAhbHc https://youtu.be/h6wMU3lE_sA
  - Documentation on StepUp: https://sourceforge.net/projects/kicadstepup/files/kicadStepUp-starter-Guide.pdf/download
  - To make it easier to use StepUp to assign materials to your model, make sure you assign a unique color to each unique material in FreeCAD ("Appearance" menu in FreeCAD, ctrl+D). For example, assign the color "red" to all pins (or choose some material in FreeCAD that you can overwrite when you export in StepUp). When you export with StepUp, you can then assign the color "red" to the material "grey metal pins." More info on the materials: https://cld.pt/dl/download/64e39e99-c5b6-451b-accd-9e25331ceafe/KiCad_3D-Viewer_component-materials-reference-list_MarioLuzeiro.pdf?download=true
- Parametric modeling (i.e., generating models with scripts) can be used for components with many similar variants. For example, DIP packages with 8, 14, or 16 pins are very similar. A tool "CADQuery" can be used as a module within FreeCAD (https://github.com/jmwright/cadquery-freecad-module) to do this. See https://github.com/easyw/kicad-3d-models-in-freecad for examples
- Github pull requests are used to add your file to the library. Several different repositories are used for different purposes, but all need to be updated:
  - Sources are needed so we can edit the files in the future if needed. The FreeCAD (fcstd) files therefore go to: 
    - https://github.com/KiCad/packages3D-source
  - Output (VRML/WRL+STEP-files) should go to two places:
    - https://github.com/KiCad/kicad-library/tree/master/modules/packages3d as that's the current place KiCAD searches for the 3D models
    - https://github.com/KiCad/packages3D as that is where the models will be housed in future
  - Parametric scripts should go to:
    - https://github.com/easyw/kicad-3d-models-in-freecad


> You can get a doc for the Materials at the section 'Preferred method to create 3D models' in the README.md of this repo;

This was very helpful, but I could not find any link to it in any README.md in any repo

**Comment by Shackmeister** [comment]
"Parametric modeling (i.e., generating models with scripts)" Parametric modeling and scripting are not (necessarily) the same

**Comment by maqifrnswa** [comment]
thanks @Shackmeister, I edited it to now read

> As an alternative to manually generating models, scripts can be used to generate parametric models for components that have many similar variants.

**Comment by easyw** [comment]
Hi @maqifrnswa , nice description that could be merged in the main README.md 
> This was very helpful, but I could not find any link to it in any README.md in any repo
sorry, my bad... the repo where you can find the links is:
https://github.com/KiCad/packages3D
and there the [README.md](https://github.com/KiCad/packages3D/blob/master/README.md) file is giving you some help tips and links
Probably, because this new packages3D repo is not well known, some tips referring that kicad-library will move its 3D packages to the new repo shortly and tips to create 3D models would be useful also in the README.md of the kicad-library
I'm adding also @SchrodingersGat to this conversation...
Maurice

**Comment by poeschlr** [comment]
@SchrodingersGat you merged the models over at the packages3d repo. Is there a reason why this has not been merged?

**Comment by SchrodingersGat** [comment]
Only due to negligence. Merged.

**Pull request merged**
