### PR TITLE
Adding symbols for lem HO-NP and HO-NP/SP33 series current transducers.

### PR DESCRIPTION
**Pull request by poeschlr**
This pull request adds a library for lem current transducers.
Currently it holds only the symbols for HO-NP and HO-NP/SP33 series transducers.
These symbols are intended to be used with the footprints provided by pull request:
https://github.com/KiCad/Hall-Effect_Transducers_LEM.pretty/pull/3

Datasheets:
http://www.lem.com/docs/products/ho-np-0000_series.pdf
http://www.lem.com/docs/products/ho-np_sp33-1000_series.pdf

screenshot from 2017-03-17 23-44-31

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi Rene,

Please rename the lib to `LEM` (uppercase) - library name capitalisation should match the proper naming of the manufacturer

**Comment by SchrodingersGat** [comment]
Looks good, only one small change: Alter the outline of the box to 10mil (0.01inch).
Then OK to merge

**Comment by poeschlr** [comment]
Ignore the unit mentioned in my commit message. The outline is of course 0.01 inch.

**Comment by SchrodingersGat** [comment]
Great work :)

**Pull request merged**
