### PR TITLE
added PIC18F45K50-I/PT

### PR DESCRIPTION
**Pull request by rar61**
Data Sheet of the part:
http://ww1.microchip.com/downloads/en/DeviceDoc/30000684B.pdf

### CODE REVIEW

**Comment by rar61** [comment]
I have added one part, but git says that i've removed 637 lines. How can i fix that?

**Comment by SchrodingersGat** [comment]
You have also added 703 - I suspect that many parts have been rearranged.

What version of KiCad are you running?

**Comment by rar61** [comment]
4.0.6

**Comment by SchrodingersGat** [comment]
I believe that there are difference between the way that nightly and stable builds order the parts within the library. Your changes should not make a difference to the other parts even though they are re-ordered.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution

**Pull request merged**
