### PR TITLE
Added MCP1640 boost regulater

### PR DESCRIPTION
**Pull request by mkleinschmidt**
This pull request adds the MCP1640 bost regulator from Microchip with two different pin configurations/packages.

[MCP1640.pdf](https://github.com/KiCad/kicad-library/files/385803/MCP1640.pdf)

mcp1640-ch

mcp1640-mc

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @mkleinschmidt nice work on these they look very good. Just a couple of small notes:

* Please use the exact reference to matching footprints in the "Footprint" field (look at MCP16301 for an example of this)
* The part descriptions should provide differentiation between the part varieties. Currently a user browsing through the library won't have any easy way of telling these apart: e.g.:

options

The differences are laid out on p29 of the datasheeet http://ww1.microchip.com/downloads/en/DeviceDoc/20002234D.pdf

**Comment by SchrodingersGat** [comment]
Nice work - can you also update the part descriptions to distinguish the different versions? :)

**Comment by mkleinschmidt** [comment]
I will but right now I am fighting with git :-)

**Comment by SchrodingersGat** [comment]
Good luck! ;)

**Comment by mkleinschmidt** [comment]
The parts are finished but I will probably have to create a new pull request due to the many unrelated/wrong commits, right?

**Comment by SchrodingersGat** [comment]
You don't have to make a new PR. Just merge kicad/master back into this branch (there have been some changes in the last half hour that conflict with your changes). You'll need to merge the master branch back in to fix these conflicts.

**Comment by mkleinschmidt** [comment]
Since the diffs of the two relevant files don't really work here at github I created a new Pull Request #642.

**Pull request closed without merging**
