### PR TITLE
Move Allegro current sensors into new lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
As the Allegro hall-effect current sensors are fairly specialized, this PR moves them from sensors.lib into (new) allegro.lib.

Additionally, the following improvements are made:
- New sensors added (mostly aliases)
- Improved and standardized part descriptions
- Fixed default footprints and footprint filters

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
Doh, this one will not play well with the script in its current incarnation because it adds a new library!

**Comment by SchrodingersGat** [comment]
Bump

**Comment by SchrodingersGat** [comment]
@pointhi if you have time can you look at this one please :)

**Comment by SchrodingersGat** [comment]
@diggit @pointhi @CarlPoirier  can you guys look at this one please, there are now other PRs that will conflict with this (e.g. https://github.com/KiCad/kicad-library/pull/747)

**Comment by diggit** [comment]
**All(almost)**
- improve FP filter to match package dimensions
- unify style, some symbols have Vcc and GND on side (matching DSH), and other have them on top/bottom

**ACS706ELC-05C**
 ```
 Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 6 is missing
```
*It is NC pin*

**ACS722LLCTR-05AB-T**
- BWSel is most likely input

*I am not big fan of separating them to manufacturer specific library, but it is KLC compliant....*

**Comment by SchrodingersGat** [comment]
Fixed, and also merged kicad/master back in

**Comment by diggit** [comment]
FP filters need trailing asterisk, otherwise it does not work on other version of FP.

**Comment by SchrodingersGat** [comment]
Ok, added

**Comment by jkriege2** [comment]
still some missing trailing *:
- ACS712ELCTR-05B-T

still some missing FPFilters/PACKAGES:
- ACS756SCB-050B

Best,
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2  I have fixed the trailing * and merge conflicts.

There is currently no default footprint available for the LEADFORM versions of this IC so I cannot add a filter or default footprint.

Are you OK to merge and we can update the footprint issues when a proper footprint is added to the libraries? 

Cheers

**Comment by jkriege2** [comment]
OK for me then ...

**Pull request merged**
