### PR TITLE
Add a new dsPIC33FJ64GP306A-I/MR device to libs

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Not yet finished. Will provide images when done ;)

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
This is my component:
screenshot from 2017-09-07 11-51-56

Due to the placement of the power pins I get the following KLC violation:
```
  Violating Rule 4.5 - Pin orientation
    Wherever possible, pins should be arranged by function
    Ground and negative power pins should be placed at bottom of symbol
     - Pin VSS (9) @ (-900,-3100)
     - Pin AVSS (20) @ (-900,-2800)
     - Pin VSS (41) @ (-900,-3300)
     - Pin VSS (25) @ (-900,-3200)
    Positive power pins should be placed at top of symbol
     - Pin VDD (10) @ (-900,1750)
     - Pin VDD (26) @ (-900,1650)
     - Pin VDD (57) @ (-900,1450)
     - Pin VDD (38) @ (-900,1550)
     - Pin AVDD (19) @ (-900,1000)
```

Following that KLC directive would make the device even bigger than it currently is. Should I comply with KLC 4.5 or should I follow the example of other devices in this same lib that position the pins as in what I have done?
Other device in this lib:
screenshot from 2017-09-07 11-50-59

**Comment by antoniovazquezblanco** [comment]
I've finally decided to reorder the pins to comply with KLC 4.1. Here it is the final result:
screenshot from 2017-09-13 11-32-04
screenshot from 2017-09-13 11-32-27
screenshot from 2017-09-13 11-32-49
screenshot from 2017-09-13 11-33-10

**Comment by antoniovazquezblanco** [comment]
Forgot some other dialogs:
screenshot from 2017-09-15 08-35-41
screenshot from 2017-09-15 08-35-53
screenshot from 2017-09-15 08-36-18

**Comment by antoniovazquezblanco** [comment]
Added a hidden pin for the pin filter to work.

imagen

imagen
imagen

**Comment by antoniovazquezblanco** [comment]
Could someone please review? I am sorry to ask for this guys but I've made this pull request from my master branch and it is keeping me from performing other changes. I know there are lots of other people waiting, again sorry. Will change my workflow from now on.

@SchrodingersGat @jkriege2

**Comment by SchrodingersGat** [comment]
This looks good to me - thanks for your contribution :)

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Pull request merged**
