### PR TITLE
adding XR20M1172

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
I think this device should go to `Interface.lib` or a new `exar.lib`. The lib `device.lib` is meant for generic devices!

Best,
JAN

**Comment by jeromebeguin** [comment]
Perfect, I moved it to interface.

**Comment by jkriege2** [comment]
Please push your move ... it's still in device.lib in this PR???

**Comment by jkriege2** [comment]
Please check this ... now there is no XR20M1172 but a SPARK_GAP???

**Comment by evanshultz** [comment]
Note there is already a spark gap symbol in the library.

**Comment by jeromebeguin** [comment]
I moved the XR20M1172 to interface.lib, I don't know what is the Spark_Gap.

**Pull request closed without merging**
