### PR TITLE
added LTC1100xN8

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
image

**Comment by SchrodingersGat** [comment]
The description fields for each of the ALIASes should vary to show what the differences are between each alias. This helps users to differentiate between different symbols in the selection window.

**Comment by evanshultz** [comment]
@ilya-epifanov Thanks! I'm currently almost finished with a major overhaul of the linear library.

@SchrodingersGat Would you mind not merging this until my PR is done?

**Comment by evanshultz** [comment]
@SchrodingersGat Due to the recent conversation about libraries, I'll get out of your way and let you review and merge this. I can integrate into my updates once the dust has settled.

@ilya-epifanov When submitting a symbol, please include the datasheet as well as an image (which you did). This part's datasheet is [here](http://cds.linear.com/docs/en/datasheet/1100fc.pdf).

**Comment by evanshultz** [comment]
Quick review:
-Only `LTC1100xN8` is needed since all the 8-pin versions have the same package and the CERDIP version is obsolete. This also affects the items in the DCM.
-Since only the DIP packages is suitable, please add a default footprint; your FPFilter is good.
-Add the package name to the end of the description, such as `, DIP-8` or `SOIC-16`.

Also, you could add `LTC1100xSW` if you're so inclined.

**Comment by evanshultz** [comment]
Hi @ilya-epifanov 
I decided to add this symbol into in my PR at https://github.com/KiCad/kicad-library/pull/1081, so you can close this PR if you want to wait for mine to be merged (hopefully soon!). Your call.

Changes:
- Shrunk symbol so the left and right pins are both the same horizontal distance from the origin.
- Updated documentation to add package name, simplify keywords, and add datasheet link.
- Removed ALIAS entries and renamed symbol since there's only one valid 8-pin PN.
- Added default footprint.
- Added 16-pin version for completeness.

Here is my symbol if you're interested.
LIB:
```
# LTC1100xN8
#
DEF LTC1100xN8 U 0 10 Y Y 1 F N
F0 "U" 50 250 50 H V L CNN
F1 "LTC1100xN8" 50 150 50 H V L CNN
F2 "Housings_DIP:DIP-8_W7.62mm" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 DIP*W7.62mm*
$ENDFPLIST
DRAW
P 2 0 1 6 0 -150 0 -100 N
P 2 0 1 0 0 150 0 100 N
P 3 0 1 6 50 -75 100 -125 100 -150 N
P 4 0 1 10 -200 200 200 0 -200 -200 -200 200 f
X ~ 1 0 -300 150 U 50 50 1 1 I
X ~ 2 100 -300 150 U 50 50 1 1 I
X - 3 -300 -100 100 R 50 50 1 1 I
X V- 4 -100 -300 150 U 50 50 1 1 W
X V+ 5 -100 300 150 D 50 50 1 1 W
X + 6 -300 100 100 R 50 50 1 1 I
X ~ 7 0 300 150 D 50 50 1 1 I
X ~ 8 300 0 100 L 50 50 1 1 O
ENDDRAW
ENDDEF
#
# LTC1100xSW
#
DEF LTC1100xSW U 0 10 Y Y 1 F N
F0 "U" 150 250 50 H V L CNN
F1 "LTC1100xSW" 150 150 50 H V L CNN
F2 "Housings_SOIC:SOIC-16W_7.5x10.3mm_Pitch1.27mm" 0 0 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 SOIC*7.5x10.3mm*Pitch1.27mm*
$ENDFPLIST
DRAW
P 2 0 1 6 0 -150 0 -100 N
P 2 0 1 0 0 150 0 100 N
P 3 0 1 6 50 -75 100 -125 100 -150 N
P 3 0 1 6 50 75 100 125 100 150 N
P 3 0 1 6 115 -40 200 -125 200 -150 N
P 4 0 1 10 -200 200 200 0 -200 -200 -200 200 f
X NC 1 -100 100 100 D 50 50 1 1 N N
X ~ 2 0 -300 150 U 50 50 1 1 I
X ~ 3 100 -300 150 U 50 50 1 1 P
X ~ 4 200 -300 150 U 50 50 1 1 I
X NC 5 0 100 100 D 50 50 1 1 N N
X - 6 -300 -100 100 R 50 50 1 1 I
X V- 7 -100 -300 150 U 50 50 1 1 W
X NC 8 100 100 100 D 50 50 1 1 N N
X NC 9 -100 -100 100 U 50 50 1 1 N N
X V+ 10 -100 300 150 D 50 50 1 1 W
X + 11 -300 100 100 R 50 50 1 1 I
X NC 12 0 -100 100 U 50 50 1 1 N N
X ~ 13 0 300 150 D 50 50 1 1 I
X ~ 14 100 300 150 D 50 50 1 1 P
X ~ 15 300 0 100 L 50 50 1 1 O
X NC 16 100 -100 100 U 50 50 1 1 N N
ENDDRAW
ENDDEF
#
```

DCM:
```
$CMP LTC1100xN8
D Single Precision, Zero-Drift Instrumentation Amplifier, Gain = 100, DIP-8
K single instrumentation amp
F http://cds.linear.com/docs/en/datasheet/1100fc.pdf
$ENDCMP
#
$CMP LTC1100xSW
D Single Precision, Zero-Drift Instrumentation Amplifier, Gain = 10/100, SOIC-16W
K single instrumentation amp
F http://cds.linear.com/docs/en/datasheet/1100fc.pdf
$ENDCMP
#
```

**Comment by evanshultz** [comment]
The part in this PR has been merged as part of my PR: https://github.com/KiCad/kicad-library/pull/1437. I'm closing this PR now. The new part is available by pulling the library from GitHub, or waiting for the next official KiCad release.

**Pull request closed without merging**
