### PR TITLE
Added NCS21x series of current-shunt monitors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.onsemi.com/pub_link/Collateral/NCS210-D.PDF

### CODE REVIEW

**Comment by diggit** [comment]
Can you follow design and location of current sense amplifiers you did in #580 ? Also put info about package in description.
Also resolve branch conflicts.

**Comment by SchrodingersGat** [comment]
@diggit  I have done the following:

* Resolved the branch conflicts
* Moved the parts into linear.lib (to match the other current sense amplifiers)
* Consolidated the symbols to be drop-in-replacements for MAX408*
* Pin fixes for MAX4080 and MAX4081 (pins were not on an 0.1" grid)

Lmk if there is anything else you want done.

Cheers

**Comment by SchrodingersGat** [comment]
Extra KLC fix for NCS210

**Comment by diggit** [comment]
I noticed empty fields increasing area to show in component chooser and thus decreasing size of symbol.
Can you move datasheet field to 0,0? (BTW I was not able do it from fields overview, I had to move it manually.)
Also set FP field invisible even when left empty. When you assign FP in CvPcb FP field holds actual FP. And place it on some sane position.

**Comment by SchrodingersGat** [comment]
done

**Comment by SchrodingersGat** [comment]
@diggit anything else? :)

**Comment by SchrodingersGat** [comment]
Bump :)

**Comment by diggit** [comment]
Looks ok, please solve conflicts before merging. You can try to rebase on current master.

**Comment by SchrodingersGat** [comment]
Merged kicad/master

**Comment by diggit** [comment]
And same problem here. Pull, merge, push :)

**Comment by SchrodingersGat** [comment]
P,M,P'ed

**Comment by diggit** [comment]
There are some changes on MAX408*, It looks like there were shortened from left side. Was it on purpose?

**Comment by SchrodingersGat** [comment]
Looks like I changed it here - https://github.com/KiCad/kicad-library/pull/570/commits/8724d01f78ef36b39a94faed951ed53d04c6412c

**Comment by diggit** [comment]
Oh, I just didn't expect changes on other symbols and didn't check commit history.
Nice work you did, merging.

**Pull request merged**
