### PR TITLE
Add AS5045B

### PR DESCRIPTION
**Pull request by El3ctr0nic**
Add AS5045B to sensors.lib
If my style (key words etc) will be ok i change rest of magnetic
encoders description.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

looks good to me and checks out with KLCs. So two things remaining:
1. Could you pull the master into your brach or rebase it, so the conflicts are fixed? (Only then I can merge)
2. What about making the "magnetic" of the sensor explicit by altering the symbol slightly like this:
as5045b

Best,
JAN

PS: Go ahead with any other changes ... best in a second PullRequest, then we can already merge this one!

**Comment by El3ctr0nic** [comment]
I try fix conflicts again pls. check if I made it. I'm still week in Git. 
Regards

**Comment by El3ctr0nic** [comment]
I made it :) Wow :)
Pls check. If all OK i redraw rest of symbols

**Comment by jkriege2** [comment]
Hi!

please look at your DCM-file ... seems like you committed in some remenants from DIFF/PATCH?

cu
JAN

**Pull request closed without merging**
