### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Gasman2014**
Added EL7202CN, EL7212CN & EL7222CN MOSFET Drivers to the intersil
library.

Added Micrel MIC4426, MIC4427 and MIC4428 to the Microchip library
(Micrel now taken over by Microchip and numbering scheme retained).
SCREENSHOTS added.

(My first KiCad Library commit - hope it is OK!)

### CODE REVIEW

**Comment by poeschlr** [comment]
Please split this pull request into two pull requests. One for the Microchip stuff and one for the intersil parts.

Please don't add screenshots to the library itself. Add them to the pull request by dragging them into the text input field for the description. (or press the link "selecting them" in the bottom of the text-field.)

screenshot from 2017-03-23 23-02-00


Also make sure you fix the KLC issues found by travis. Some of your pins are not on a 100mil grid and some of the symbol fields have the wrong fontsize. (see the travis log: https://travis-ci.org/KiCad/kicad-library/builds/214437387)

To change the fontsize open the field properties dialog and look if all fields have a fontsize of 50 mil:
screenshot from 2017-03-23 23-04-50

Otherwise the symbols (in your screenshots) look great.

**Comment by poeschlr** [comment]
For future pull request maybe give them a meaningful title. (I'm convinced you didn't mean to give this request the title "master".) 

It might be a good idea to have a different branch than your master branch as source for a pull request. I fear you might need to repair your master branch now.

**How to reset the master branch to synchronize it with the original repo master**
I would make a new branch at your current master tip (give it a meaningful name). After that rewind your master to be synchronized with the master of this repository.
Here my idea of how it could work (I tested it with one of my repos where i destroyed my master branch by merging two different forks into it.)
```
git checkout -b [meaningfull branch name for old master tip]
git push --set-upstream origin [meaningfull branch name for old master tip]
```

if not already done add this repo as upstream repo to your local repo:
`git remote add upstream https://github.com/KiCad/kicad-library.git`

now the tricky part. (deleting the remote master branch does not work so we need to forcefully push to it the current upstream master.)
```
git fetch upstream
git checkout upstream/master
git branch -D master
git checkout -b master
git push --force
```
Of course this means this pull request will die because of this. Just close this PR when you are done with that. You could open a new pull request with [meaningfull branch name for old master tip] as source but it might be better to create two branches for the two libraries you changed and open two pull requests.
(Just switch to the [meaningfull branch name for old master tip] branch and copy the changed files to a location outside of your local repo.)

**So how should making a pull request be done**
Again make sure your master branch is synchronized with the upstream master before doing anything.
After that make a new branch and commit your changes to this branch. (Copy the files you copied from your old branch into this branch)
Make the pull request and push any necessary changes to the same branch. (The pull request will be updated automatically.)

If you need more details just ask.

**Comment by poeschlr** [comment]
Just as a safety precaution: i cloned your repo. This means if you deride to repair your master branch and something goes wrong, i still have your changed files. If this happens just drop me an email or contact me over at the kicad forum (via a private message.) You could also comment on this pull request.

**Comment by Gasman2014** [comment]
Sorry for all the hassle! I have an unedited copy of the repo which I keep in sync with the master version, so no harm done. I cloned an additional copy and made my edits to that one and have the new libraries saved separately anyway. I have re-edited the footprints (It was far from obvious but the empty datasheet field had the wrong font size). I will close this PR, split it into two new PRs and try to add the screenshots in the approved manner. This is my first time with git (I use SVN at home) and it is a bit confusing!

**Comment by poeschlr** [comment]
> I have an unedited copy of the repo which I keep in sync with the master version, so no harm done.

The problem is the online master branch of your fork. (fixing the local repo is very easy. there you can simply delete the current master, switch to upstream/master and create a new master branch. But the online master branch can not be deleted.)

Another option would be to keep your online master branch like it is now and always branch away from upstream/master if you make a new pull request branch.
I just really like my master branch to be in sync with the upstream master branch.

**Pull request closed without merging**
