### PR TITLE
Add LMC6482

### PR DESCRIPTION
**Pull request by Partmedia**

### CODE REVIEW

**Comment by evanshultz** [comment]
@Partmedia Hi! Thanks for contributing.

Please see the failures in the 'Details' link above. You should provide keywords in the DCM file.

The other issue isn't related to the changes you made. However, I'm working on a major update to this library so to library maintainers, please hold off on merging this PR until I finish. I hope early next week.

**Comment by Partmedia** [comment]
I amended my commit adding the keyword 'ampliop'.

For future reference, I've taken a look at `library-check.sh` and can't tell how to run these checks locally. Running *checklib.py* from *kicad-library-utils* didn't shake out the error for me.

**Comment by SchrodingersGat** [comment]
Hi @Partmedia please change `ampliop` to `opamp`, we try to keep the library english-centric.

thanks

**Comment by Partmedia** [comment]
I've amended my commit again with keyword 'opamp'.

I'd like to point out that suggested keywords aren't documented in KLC, and I found this keyword ('ampliop') by consulting other op amps that already existed.

**Comment by evanshultz** [comment]
@Partmedia Thank you. You're right, but the existing linear library was in need of many updates and I've already made this correction in a large update to be merged soon.

**Comment by Partmedia** [comment]
Just wanted to make sure folks are aware. I'm looking forward to the updates.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution

**Pull request merged**
