### PR TITLE
Ea e diptft32

### PR DESCRIPTION
**Pull request by Misca1234**
Display EA eDIPTFT32-A (and it's alias EA eDIPTFT32-ATP)

kicad-library push branch is 
https://github.com/KiCad/kicad-library/pull/1492

pretty push branch is 
https://github.com/KiCad/Displays.pretty/pull/25

packages3D push branch is 
https://github.com/KiCad/packages3D/pull/108

packages3D-source push branch is 
https://github.com/KiCad/packages3D-source/pull/35

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

**Comment by poeschlr** [comment]
I get a library load error with this branch. (display lib is corrupted.)

**Comment by poeschlr** [comment]
Merge required.

**Comment by SchrodingersGat** [comment]
Please fix conflicts here

**Comment by Misca1234** [comment]
The travis error says that pin 18, DNC, is a NC pin, which is not the case, the travis error should be ignored

**Pull request merged**
