### PR TITLE
Add BTS50055-1TMA power switch

### PR DESCRIPTION
**Pull request by hackscribble**
Added BTS50055-1TMA symbol with four aliases:
BTS50055-1TMC
BTS50080-1TMA
BTS50080-1TMC
BTS50085-1TMA

image

Datasheets:
http://www.infineon.com/dgdl/Infineon-BTS50055-1TMA-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aa9b00de935ed
http://www.infineon.com/dgdl/Infineon-BTS50055-1TMC-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aa9b0007235e9
http://www.infineon.com/dgdl/Infineon-BTS50080-1TMA-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aa435d7fe1153
http://www.infineon.com/dgdl/Infineon-BTS50080_1TMC-DS-v01_00-en.pdf?fileId=db3a3043266237920126992737c951ee
http://www.infineon.com/dgdl/Infineon-BTS50085-1TMA-DS-v01_00-EN.pdf?fileId=5546d4625a888733015aa435bccd114b

Will add a PR for the footprint.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work! Could you please fix the following things? This way the symbol looks a bit nicer and should be better usable in the schamtic (I hope).
2017-04-22 15_48_13-part library editor d__kicad_kicad-library-review_library_infineon lib

BTW: Would it make sense to have a small sketch of what the device does inside (just a suggestion, makes IMHO schematics more readable than just a box), e.g.:
2017-04-22 15_53_55-part library editor d__kicad_kicad-library-review_library_infineon lib

Finally: Please change the naming of the footprint a bit to include the SMD explicitly, as TO-220 is usually mounted as THT. Also Please add `_TabPin4` instead of simply `-4` to the footprint name, this is a bit more verbose and resembles the way something comparable is done with `TO-263-3Lead_TabPin4` in the TO-SOT-SMD-lib.

Otherwise, please link the PR for the package here, then we can merge them together!

Best,
JAN

**Comment by hackscribble** [comment]
Thanks @jkriege2 

I will make the layout changes you suggest.  I would prefer not to add the sketch inside - I think anyone using these power switches knows what they do.

About the footprint name, let me check I have understood.  The example `TO-263-3Lead_TabPin4` means a TO-263 package with 3 leads and a tab, and the tab is pin number 4?

If so, then I will use the footprint name `TO-220-7Lead_TabPin8`.  Is this sufficient or do you want me to explicitly include `SMD` in the name too?

image

Thanks.

**Comment by hackscribble** [comment]
Symbol updated.  I will submit a PR for the footprint once the name is settled.

image

**Comment by jkriege2** [comment]
Footprint looks good to me ... Naming is OK!

JAN

**Comment by hackscribble** [comment]
Footprint PR:
https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/44

**Comment by jkriege2** [comment]
Nice work!
JAN

**Pull request merged**
