### PR TITLE
added LM2776

### PR DESCRIPTION
**Pull request by ilya-epifanov**

### CODE REVIEW

**Comment by ilya-epifanov** [comment]
image

**Comment by poeschlr** [comment]
wrong description, keywords and datasheet link
C+/- should be named C1+/- to match the datasheet nomenclature
add the footprint filed (sot23-6) and footprint filter

maybe move gnd towards the bottom
The reference should be on top

(By the way, if i find one mistake in one of your pull requests and you made a similar mistake somewhere else, please fix it there as well. This will lower the workload for both of us.)

**Comment by Misca1234** [comment]
This branch is obselete and can be closed and deleted

New push is here

**Comment by poeschlr** [comment]
@Misca1234 both replacement branches have been closed. (At least the pull requests that i could find)
Could you update me on the state of this?

**Comment by SchrodingersGat** [comment]
@Misca1234 what's the deal here? :)

**Comment by Misca1234** [comment]
Jee, it looks suspicious that both branches was closed, let me check

**Comment by Misca1234** [comment]
The symbol LM2776 is already inserted in dc-dc.lib so this push can be closed

**Pull request closed without merging**
