### PR TITLE
Max712 max713

### PR DESCRIPTION
**Pull request by Misca1234**
MAX712 and MAX713

https://datasheets.maximintegrated.com/en/ds/MAX712-MAX713.pdf

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Split into two with inspiration from push 
https://github.com/KiCad/kicad-library/pull/1518

bild

bild

**Comment by jkriege2** [comment]
Hi!
nice wrok, but I spotted a few bugs:
1. could you also add the MAX712? Or is it unavailable?
2. pin-types are a bit mixed up:
  - PGM0/1 should be INPUT
  - BATT+ should be INPUT
3. Why did you choose the present pin-grouping? This does not really seem obvious to me, as on p. 1 and p.7 of the DS they propose another pin-grouping. Is your version beneficial when drawing up a schematic?
4. Finally these devices come in DIP-16/SOIC-16, but you set the footprint/FPFilters to SOIC-8/DIP-8!

Best,
JAN

**Comment by jkriege2** [comment]
Finally this should maybe live in battery_management.lib!

**Comment by Misca1234** [comment]
> could you also add the MAX712? Or is it unavailable?
From earlier pushes I have learned that the "basic" id is not used but instead the package name, in this case,
16 pin-dip MAX712CPE and MAX712EPE
16 pin-SO MAX712CSE and MAX712ESE


>     PGM0/1 should be INPUT
>     BATT+ should be INPUT
Changed


> Why did you choose the present pin-grouping? This does not really seem obvious to me, 
> as on p. 1 and p.7 of the DS they propose another pin-grouping.
It is, but on other hand p.1 does not show the four PGMx pins
p.7 does not have GND at bottom as kicad require
My guidence for the pin grouping is 
VDD ontop, GND at bottom (as kicad request) and then I group them so all "close to ground" pins are at bottom 
and all "close to VDD" is at top and the output look like the datasheet


> as on p. 1 and p.7 of the DS they propose another pin-grouping. Is your version beneficial when drawing up a schematic?
>     Finally these devices come in DIP-16/SOIC-16, but you set the footprint/FPFilters to SOIC-8/DIP-8!
Apperently I made a change while you was inspecting it, in the earlier push, I had splitted the symbol in two
with inspiration from push 
https://github.com/KiCad/kicad-library/pull/1518
I guess you had already pulled the push before i pushed it again.

I spotted another problem, the MAX713 was missing (Nickel Cadmium (NiCd))

So this push consist of
MAX712CPE, alias MAX712EPE MAX712MJE MAX713CPE MAX713EPE MAX713MJE	(16-DIP)
MAX712CSE, alias MAX712ESE MAX713CSE MAX713ESE	(16-SO)

**Comment by jkriege2** [comment]
OK, mostly fine now. But I don't really understand you comment on teh "basic version"???

Still the wrong footprints and FPFilters are set. Please fix that. footprints should be:
- `Housings_SOIC:SOIC-16_3.9x9.9mm_Pitch1.27mm` / `SOIC*3.9x9.9mm*Pitch1.27mm*`
- `Housings_DIP:DIP-16_W7.62mm` / `DIP*W7.62mm*`

Please also refrain from changing `library/maxim.dcm` in your PR, or comment on why that DCM-description should be removed ...

Best,
JAN

**Comment by Misca1234** [comment]
It is kicad that made that removal on its own, but I will manually add it

**Comment by Misca1234** [comment]
They look like this now 

bild

bild

**Comment by jkriege2** [comment]
Why did you add MAX7325AEG+?

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
