### PR TITLE
Added Allegro current sensors, a TI regulator and some transistors by On Semi

### PR DESCRIPTION
**Pull request by ReeseWang**

### CODE REVIEW

**Comment by thuSkywalker** [comment]
I just copied digital transistor symbol from original library. The original symbol didn't follow the rule 3.1

**Comment by thuSkywalker** [comment]
I just copied digital transistor symbol from original library. The original symbol didn't follow the rule 3.1

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Hi @thuSkywalker 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
