### PR TITLE
Added USB3 symbol

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added a symbol for USB3 connector to conn.lib

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

very nice work (I like the artwork). Some smaller things:
1. I still get a KLC 3.8 warning ... maybe replace `USB3` in the description by `USB 3.0`
2. The logo is for USB 1/2, please use the USB3-logo, e.g.:
2017-02-05 09_42_44-part library editor d__kicad_kicad-library-review_library_conn lib
3. Wikipedia numbers the pins differently for A- and B-connectors ... maybe we should make clear which one this is (symbol name + description): https://en.wikipedia.org/wiki/USB_3.0#Pinouts
4. I was thinking whether it would be possible to make the symbol look more like a connector
  - e.g. add small rectangles at pins (as in CONN_xxXyy symbols)
  - or add a drawing of the actual connector
2017-02-05 09_42_44-part library editor d__kicad_kicad-library-review_library_conn lib

What do you think? 

JAN

PS: When you have time, could you make the artwork of the other USB connectors in this lib similar (USB-logo and/or more like conn)?

**Comment by jkriege2** [comment]
PS: If it helps, here's my modified symbol shown above: 
```
#
# USB3
#
DEF USB3 J 0 40 Y Y 1 F N
F0 "J" -400 600 50 H V L CNN
F1 "USB3" 400 600 50 H V R CNN
F2 "" 150 100 50 H V C CNN
F3 "" 150 100 50 H V C CNN
DRAW
T 900 -30 -75 200 0 0 0 SS Italic 1 C C
S -360 340 -200 -150 0 0 20 N
S -310 290 -260 -90 0 0 20 F
S -250 0 -240 -30 0 0 20 N
S -250 70 -240 40 0 0 20 N
S -250 140 -240 110 0 0 20 N
S -250 210 -240 180 0 0 20 N
S -110 -600 -90 -560 0 0 0 N
S -10 -600 10 -560 0 0 0 N
S 400 -390 360 -410 0 0 0 N
S 400 -290 360 -310 0 0 0 N
S 400 -190 360 -210 0 0 0 N
S 400 -90 360 -110 0 0 0 N
S 400 110 360 90 0 0 0 N
S 400 210 360 190 0 0 0 N
S 400 410 360 390 0 0 0 N
C -130 275 25 0 1 10 F
S -400 550 400 -600 0 1 10 f
S 45 300 95 350 0 1 10 F
P 2 0 1 20 -30 50 -30 400 N
P 3 0 1 20 -30 100 -130 200 -130 250 N
P 3 0 1 20 -30 150 70 250 70 300 N
P 4 0 1 10 -80 400 -30 500 20 400 -80 400 F
X SHIELD 0 -200 -700 100 U 50 50 1 1 P
X VBUS 1 500 400 100 L 50 50 1 1 W
X D- 2 500 200 100 L 50 50 1 1 B
X D+ 3 500 100 100 L 50 50 1 1 B
X GND 4 0 -700 100 U 50 50 1 1 W
X SSTX- 5 500 -100 100 L 50 50 1 1 B
X SSTX+ 6 500 -200 100 L 50 50 1 1 B
X DRAIN 7 -100 -700 100 U 50 50 1 1 W
X SSRX- 8 500 -300 100 L 50 50 1 1 B
X SSRX+ 9 500 -400 100 L 50 50 1 1 B
ENDDRAW
ENDDEF
```

**Comment by SchrodingersGat** [comment]
Ah good point on the A/B differences, I've added two variants.

Have also cleaned up the other symbols. Added the USB symbol but I don't think there's room on the smaller symbols for the connector symbol, without making them needlessly large.

**Comment by jkriege2** [comment]
What do you think on this:
2017-02-05 12_54_16-part library editor d__kicad_kicad-library-review_library_conn lib
2017-02-05 12_54_54-part library editor d__kicad_kicad-library-review_library_conn lib
2017-02-05 13_00_00-part library editor d__kicad_kicad-library-review_library_conn lib

Here's a DIFF for these changes:
```
 library/conn.lib | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

diff --git a/library/conn.lib b/library/conn.lib
index bdd0c9a..bfe0d83 100644
--- a/library/conn.lib
+++ b/library/conn.lib
@@ -11483,15 +11483,17 @@ DRAW
 C -150 85 25 0 1 10 F
 C -25 135 15 0 1 10 F
 S -200 -300 200 300 0 1 10 f
+S -60 190 -170 210 0 1 0 F
+S -50 180 -180 230 0 1 0 N
 S -5 -300 5 -270 0 1 0 N
 S 10 50 -20 20 0 1 10 F
 S 200 -105 170 -95 0 1 0 N
 S 200 -5 170 5 0 1 0 N
 S 200 195 170 205 0 1 0 N
-P 2 0 1 10 -75 85 25 85 N
 P 4 0 1 10 -125 85 -100 85 -50 135 -25 135 N
 P 4 0 1 10 -100 85 -75 85 -50 35 0 35 N
 P 4 0 1 10 25 110 25 60 75 85 25 110 F
+P 2 1 1 10 -75 85 25 85 N
 X VBUS 1 300 200 100 L 50 50 1 1 W
 X D- 2 300 -100 100 L 50 50 1 1 P
 X D+ 3 300 0 100 L 50 50 1 1 P
@@ -11514,6 +11516,7 @@ DRAW
 C -150 85 25 0 1 10 F
 C -25 135 15 0 1 10 F
 S -200 -300 200 300 0 1 10 f
+S -150 220 -100 180 0 1 0 F
 S -5 -300 5 -270 0 1 0 N
 S 10 50 -20 20 0 1 10 F
 S 200 -105 170 -95 0 1 0 N
@@ -11523,6 +11526,7 @@ P 2 0 1 10 -75 85 25 85 N
 P 4 0 1 10 -125 85 -100 85 -50 135 -25 135 N
 P 4 0 1 10 -100 85 -75 85 -50 35 0 35 N
 P 4 0 1 10 25 110 25 60 75 85 25 110 F
+P 7 0 1 0 -160 170 -90 170 -90 225 -105 240 -145 240 -160 225 -160 170 N
 X VBUS 1 300 200 100 L 50 50 1 1 W
 X D- 2 300 -100 100 L 50 50 1 1 P
 X D+ 3 300 0 100 L 50 50 1 1 P
@@ -11555,6 +11559,8 @@ P 2 0 1 10 -75 85 25 85 N
 P 4 0 1 10 -125 85 -100 85 -50 135 -25 135 N
 P 4 0 1 10 -100 85 -75 85 -50 35 0 35 N
 P 4 0 1 10 25 110 25 60 75 85 25 110 F
+P 5 0 1 0 -170 220 -70 220 -80 190 -160 190 -170 220 F
+P 9 0 1 0 -185 230 -185 220 -175 190 -175 180 -65 180 -65 190 -55 220 -55 230 -185 230 N
 X VBUS 1 300 200 100 L 50 50 1 1 W
 X D- 2 300 -100 100 L 50 50 1 1 P
 X D+ 3 300 0 100 L 50 50 1 1 P
@@ -11587,6 +11593,8 @@ P 2 0 1 10 -75 85 25 85 N
 P 4 0 1 10 -125 85 -100 85 -50 135 -25 135 N
 P 4 0 1 10 -100 85 -75 85 -50 35 0 35 N
 P 4 0 1 10 25 110 25 60 75 85 25 110 F
+P 5 0 1 0 -170 220 -70 220 -80 190 -160 190 -170 220 F
+P 9 0 1 0 -185 230 -185 220 -175 190 -175 180 -65 180 -65 190 -55 220 -55 230 -185 230 N
 X Shield 0 -100 -400 100 U 50 50 1 1 P
 X VBUS 1 300 200 100 L 50 50 1 1 W
 X D- 2 300 -100 100 L 50 50 1 1 P
```

JAN

**Comment by SchrodingersGat** [comment]
Jan I am very happy with those graphics, they look fantastic! Changes have been made

**Comment by jkriege2** [comment]
for USB_B: Shouldn't VUSB/GND be POWER_OUTPUT?

JAN

**Comment by SchrodingersGat** [comment]
Very good point. Fixed.

**Comment by jkriege2** [comment]
nice work!
JAN

**Comment by SchrodingersGat** [comment]
@jjuyon thank you for pointing this out so swiftly - https://github.com/KiCad/kicad-library/pull/979

**Pull request merged**
