### PR TITLE
Lg206 l

### PR DESCRIPTION
**Pull request by Misca1234**
LG1206L
Alias LG206D

http://kodenshi.co.jp/products/pdf/sensor/photointerrupter_ic/LG205L.pdf
http://kodenshi.co.jp/products/pdf/sensor/photointerrupter_ic/LG206D.pdf

kicad-libaray push
https://github.com/KiCad/kicad-library/pull/1545

Opto-Devices.pretty
https://github.com/KiCad/Opto-Devices.pretty/pull/14

packages3D
https://github.com/KiCad/packages3D/pull/120

packages3D-source
https://github.com/KiCad/packages3D-source/pull/44

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

very nice work ... a suggestion for the symbol:
2017-08-18 19_59_14-part library editor -- d__kicad_kicad-library-review_library_opto lib

This makes the type of coupler clearer ... and is closer to the drawing in the datasheet.

Best,
JAN

**Comment by Misca1234** [comment]
It looks like this now 

bild

**Comment by Misca1234** [comment]
bild

bild

**Comment by jkriege2** [comment]
Oh, sorry forgot one thing:

please rename the footprint to match the scheme of most footprints in the Opto-Devices-lib, i.e. `PhotoInterrupter_Kodenshi_LG205L` and `PhotoInterrupter_Kodenshi_LG205D`

Thanks,
JAN

**Comment by Misca1234** [comment]
bild

bild

**Comment by jkriege2** [comment]
The symbol can keep the name LG206D ... just the footprint needed renaming!

Best,
JAN

**Comment by Misca1234** [comment]
Suffix PhotoInterrupter_Kodenshi_ removed from symbol name

bild

bild

**Comment by jkriege2** [comment]
Nice work here!

Only: Please remove `LG206X.step` and `LG206X.wrl` from this PR

Thanks,
JAN

**Comment by Misca1234** [comment]
They are removed

**Comment by jkriege2** [comment]
Hi!

FPFilters still need a bit of wditing: `PhotoInterrupter?Kodenshi?LG206L*` and `PhotoInterrupter?Kodenshi?LG206D*` would be right.

JAN

**Comment by Misca1234** [comment]
Fixed

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
