### PR TITLE
Max1898 eub4 x

### PR DESCRIPTION
**Pull request by Misca1234**
Push for 
MAX1898EUB42

Aliases
MAX1898EUB41

https://datasheets.maximintegrated.com/en/ds/MAX1898.pdf

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
PS
I have a number of pushes where travis complain of some pins that it thinks is power input, 
like push https://github.com/KiCad/kicad-library/pull/1520, 
is there a way to tell travis that the pin is actually an input and not a power input ?
DS

**Comment by poeschlr** [comment]
> I have a number of pushes where travis complain of some pins that it thinks is power input,
like push #1520,
is there a way to tell travis that the pin is actually an input and not a power input ?

Just state that information in the pull request description. (If there is a reason a rule is violated we will accept it. Especially if you state what rule is violated and why.)

**Comment by SchrodingersGat** [comment]
Please add a footprint filter to this symbol and then we should be good to merge :)

**Comment by Misca1234** [comment]
Done

bild

**Comment by Misca1234** [comment]
Kicad have changed something in MAX2606, let me fix that one as well

**Comment by Misca1234** [comment]
Replaced MAX2606 with MAX2605
Added aliases 
MAX2606
MAX2607
MAX2608
MAX2609

bild

bild

bild

bild

bild

**Pull request merged**
