### PR TITLE
reworked Oscillators.lib

### PR DESCRIPTION
**Pull request by jkriege2**
- added missing DCM
- added missing symbols/fixed wrong symbols

* [ ] CXO_DIP14
* [ ] CXO_DIP8
* [ ] IQXO/7X
* [ ] Si570
* [ ] Si571
* [ ] TCXO3
* [ ] XO32
* [ ] XO53
* [ ] XO91
* [ ] ASE-xxxMHz
* [ ] ASV-xxxMHz
* [ ] DFA-S11
* [ ] DFA-S15
* [ ] DFA-S2
* [ ] DFA-S3
* [ ] TXC-7C
* [ ] SG-8002XX

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I would suggest rearranging the NC pins on TXC03 as below:

tcx03

**Comment by jkriege2** [comment]
- updated/extended the lib
- fixed mentioned issue
- all symbols conform to KLC, except the DIP8/14, as these packages only have the pins 1,4,5,8 or 1,7,8,14, which causes (false neg.) KLC-check-results.
- updated footprint lib to macth this! See PR here: https://github.com/KiCad/Oscillators.pretty/pull/4
- list above was updated!

Best,
JAN

**Comment by jkriege2** [comment]
... and updated symbols with oscillator symbol in center, e.g.:
2017-01-06 20_50_16-part library editor d__kicad_test_addlin_ _kicad-library_library_oscillators

**Comment by SchrodingersGat** [comment]
Great work :)

**Pull request merged**
