### PR TITLE
Hdsp 48xx

### PR DESCRIPTION
**Pull request by Misca1234**
3D models for 
HDSP-48xx, HDSP-4830, HDSP-4832, HDSP-4836, HDSP-4840, HDSP-4850, HLCP-J100

https://docs.broadcom.com/docs/AV02-1798EN

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
I moved all the 3d models from Display.3dshapes to Displays.3dshapes

**Comment by poeschlr** [comment]
The models are still Display.3dshapes (It seems you copied them to Displays.3dshapes.)

**Comment by Misca1234** [comment]
I fix it now

**Comment by Misca1234** [comment]
This F git messed up my master again, I close this one and push another branch

**Pull request closed without merging**
