### PR TITLE
Add symbols: STM32F030C8,MOD-nRF8001,M25PX32,modADXL345,MCP1703AT-3302/MB

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
@piotr-wiszowaty please move the symbols to proper already existing libraries. Also check the KLC.

**Comment by piotr-wiszowaty** [comment]
Done.

**Comment by SchrodingersGat** [comment]
There are too many different commits going on here for easy merging. Can you make a separate branch for each device and submit a separate PR? That way we can break them up into manageable pieces.

Cheers

**Comment by piotr-wiszowaty** [comment]
All right.

**Pull request closed without merging**
