### PR TITLE
Fix footprint label position

### PR DESCRIPTION
**Pull request by hackscribble**
Revert change in footprint label location that happened in https://github.com/KiCad/kicad-library/pull/1309.

### CODE REVIEW

**Comment by hackscribble** [comment]
Need to fix my error in branch.

**Comment by suzizecat** [comment]
Hi, i might have messed something in #1317... I didn't touch the symbol myself (or i do believe it) but some modifications happened.
In particular, i just saw that the package label came back to 0,0...

**Comment by hackscribble** [comment]
No problem :smile:

**Comment by suzizecat** [comment]
Anyway, i don't understand where does this modification came from at all ^^'

**Comment by hackscribble** [comment]
I think what happened was ...

- We both created local feature branches to make our changes based on the same version of KiCad master.
- My PR was merged first.  This updated KiCad master. 
- Your PR from your feature branch still had the previous version of MAX31855.  So, GitHub thought you intended to change MAX31855.

I think the way to avoid this is to check the PR before submitting it.  If there are changes that were not intended, the fix would have been to do a "pull upstream" to update your master branch to the latest version, then rebase your local feature branch onto this new master.  That would have left your feature branch with just the changes to the devices you worked on.

**Comment by suzizecat** [comment]
Well well, i don't know since i updated master just before starting to work this morning, and GitKraken seems pretty straightforward about it...
image

Anyway, it's fixed so no problems 😛

**Pull request closed without merging**
