### PR TITLE
add max31856

### PR DESCRIPTION
**Pull request by ptooley**
Add footprint for the Maxim 31856 thermocouple reader, see https://datasheets.maximintegrated.com/en/ds/MAX31856.pdf following the style of the 3182x parts already in sensors.lib
max31856

### CODE REVIEW

**Comment by Misca1234** [comment]
Change description from 
Precision Thermocouple to Digital Converter with Linearization
To
Precision Thermocouple to Digital Converter with Linearization, TSOP-14

I guess the Footprint filter should be
TSSOP*4.4x5mm?Pitch0.65mm*
but I am a little uncertain

**Comment by ptooley** [comment]
okay, that is done. I assumed you meant TSSOP-14 in the description and I have retained filtering to 14 pin TSSOPs

**Comment by jkriege2** [comment]
Sorry for the long wait ... very nice work. Could you please do some final corrections:
1. DRDY and FAULT ar OUTPUTS as stated in the datasheet
2. move the end of the NC pin onto the outline, so it's less likely to erroneously connect to it
3. set the pin label offset to 20mil to improve visual appearance

Thanks,
JAN

2017-11-06 21_14_32-part library editor -- d__kicad_kicad-library-review_library_sensors lib

**Comment by ptooley** [comment]
@jkriege2 hopefully that should be everything now.

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Pull request merged**
