### PR TITLE
Ea dogs104 a

### PR DESCRIPTION
**Pull request by Misca1234**
Display:
EA DOGS104B-A

Aliases: 
EA DOGS104W-A
EA DOGS104N-A

http://www.lcd-module.com/fileadmin/eng/pdf/doma/dogs104e.pdf

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1507

pretty push branch is
https://github.com/KiCad/Displays.pretty/pull/33

packages3D push branch is
https://github.com/KiCad/packages3D/pull/116

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/43

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Is it on purpose that you did not reuse the pins you normally use for such models?
(Not a problem just curious.)

Is this symbol for the backlight version? If not should the backlight pins be NC?

If the pins are for the backlight LED they should be of type passive.

**Comment by poeschlr** [comment]
I'm not certain we should add all these aliases for different colors. I think it would be better to add one symbol with and one without backlight instead. (More functionality for the user.)

I also noticed that the other ea-dog display only has the symbol for the backlight version but has the description of the non backlight version.

**Comment by Misca1234** [comment]
> Is it on purpose that you did not reuse the pins you normally use for such models?
Naaa, was just trying something new

> Is this symbol for the backlight version? If not should the backlight pins be NC?
I change them to NC, the pins does not have any purpose for the display itself

I remove the aliases

bild

**Comment by evanshultz** [comment]
@Misca1234 I'll let @poeschlr finish this review and merge, but I have one note. Slide the NC pins a bit left so they're at the border of the symbol body. This will help avoid an accidental connection to them.

**Comment by Misca1234** [comment]
Like this 

bild

**Comment by poeschlr** [comment]
@Misca1234 it seems you did not remove the aliases. (Did you forget to push?)

**Comment by Misca1234** [comment]
I have probably forgot it on others, but for EA DOGS104 they are gone now

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
