### PR TITLE
Add VNH2SP30

### PR DESCRIPTION
**Pull request by Marsfan**
Added a high current motor driver that I created for a personal project. 

3 Travis Failures: 
1. Footprint filter (not sure what this is)
2. Pin suggestion (CS means current sense in this case, not clock select, so it should be an output)
3. Unknown text field of bad size (Cannot fix this without finding it, and it eludes me)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@Marsfan first and foremost please either merge the kicad/master branch into this one or reimplement your changes on top of the latest master branch. The only files that should show changes are the ones mentioned in this PR

**Comment by poeschlr** [comment]
To answer your original questions:
> Footprint filter (not sure what this is)

You can find it in the component properties dialog.
screenshot from 2017-05-01 11-08-20

> Unknown text field of bad size (Cannot fix this without finding it, and it eludes me)

You can use the field properties dialog for that.
footprintfields

> Pin suggestion (CS means current sense in this case, not clock select, so it should be an output)

Travis can not really know what a pin with a specific name is. (There is no standard.)
So if the pin is named CS in the datasheet this should be ok.

**Comment by poeschlr** [comment]
### How to work with git
Here detailed how to work with github. I wrote it for another user but i think it might be helpful for you as well. Especially part about synchronizing your fork to the official repo.

Short note: everything between "[" and "]" is to be filled out by the user. (The brackets are for marking it here. They are not part of the command)

Create a separate branch for each pull request.
How to do this:
first switch to your master branch and make sure it is up do date with the master branch of the repo you want to merge into.
If you did not already do this, add this repo as a second remote location to your local repo:
`git remote add upstream https://github.com/KiCad/kicad-library.git`

Now to the synchronizing and creation of the pull request branch: (Make sure that your local repo is clean before doing anything.)
```
git checkout master
git fetch upstream
git pull upstream master
git push
```
If this is done make the branch for your pull request.
```
git checkout -b [meaningfull branch name]
git push --set-upstream origin [meaningfull branch name]
```
Do your changes and commit / push them to your online repo
The save option is to add each file seperatly:
`git add [filename of changed file]`

You can also add all your changes at once. But make sure with git status that you did not change anything unintentionally.
`git add -u`

After that do another check with git status if everything looks good and commit the changes to your repo
`git commit -m "[meaningfull commit message]"`

Then the last thing to do is to push the changes:
`git push`

Open the webbrowser and go to the website of the target repo. You should see a button for create pull request. If you press that just fill out the title and description field.
screenshot from 2017-03-23 23-22-45

Make sure your pull request is ready to be merged automatically. If not do the synchronization step again and merge the changes into your pull request branch.
It can also happen that while your pull request awaits merging someone else got their pull request merged that changed the same files as your pull request would. This of course means you need to merge these changes into your branch. Otherwise merging your pull request would fail.
```
git fetch upstream
git merge upstream/master
```

Also note that after a while travis will report back if your files do pass the klc checks. fix any issue that is reported.
Do do that make sure your local repo is in the branch associated with the pull request in question.
`git checkout [name of the branch]`

Do your changes
`git add [name of the changed files]`
or
`git add -u`

```
git commit -m "[another meaningfull commit message]"
git push
```

**Comment by Marsfan** [comment]
@SchrodingersGat I'm busy right now, but I will get around to fixing this soon.

**Comment by Marsfan** [comment]
Fixed the problem with file changes. I had merged things incorrectly. Seems a pull request from master is not the same as clicking update from master on the github application. 

Can someone point me to a guide on how to properly set up footprint filters?

**Comment by poeschlr** [comment]
https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions
Section Footprint association.

**Comment by Marsfan** [comment]
I have fixed up almost everything, but it uses a special type of footprint called a multipower-SO 30. It is a ST Micro proprietary footprint. I do not have a lot of experience making footprints, so could I leave this blank for now?

**Comment by jkriege2** [comment]
Hi!

nice work overall. Some things remain to be fixed though:
1. GNDx-pins should be at the bottom border (best exchange with the NC-pins). 
2. One OUTA is PASSIVE, why? all other OUTA and all OUTB are OUTPUT ... Please fix
3. I made the package: https://github.com/KiCad/Housings_SSOP.pretty/pull/33 Please reference it (I would say we wait to merge this until the footprint is approved). 
4. Please ensure that all 33 pins of the footprint are refernced in the symbol!

Best,
JAN

**Comment by Marsfan** [comment]
@jkriege2 Sorry I did not get to this sooner, life has been busy, I should be able to work on it within the week.

**Comment by jkriege2** [comment]
OK!
I'll have a look at the symbol then ,-)

JAN

**Comment by Marsfan** [comment]
@jkriege2 when you say all 33 pins, are you including the heat slugs? I just need that and the package, and this should be ready to go.

**Comment by jkriege2** [comment]
Yes, with 33 pins I mean all pads including the three pads at the bottom.

Best,
JAN

**Comment by jkriege2** [comment]
@Marsfan the package is merged!
JAN

**Comment by Marsfan** [comment]
@jkriege2 This should get it working. Three notes:
1. Was not 100% sure what to put in footprint filter, so I used `*MultiPowerSO*` since only the multipower is used with the VNH.

2. Gitignore edit is because there is a symlink in my repo to make running the KLC check script eaiser, and I do not know how to block .gitignore without blocking that, I can change it if 100% need be.

3. Why the heck is every footprint folder a different git repo? This makes it really hard for me if I decide I will want to start adding footprints of my own, I do not want a gazillion git repos cloned onto my PC, and have to filter through them whenever I use github desktop (which I use whenever I want to easily visualize diffs).

**Comment by jkriege2** [comment]
Hi!

ad 1) The FPFilter should be `ST*MultiPowerSO*`, which matches the footprint you linked and is specific (i.e. if there were e.g. a `LT_MultiPowerSO-30` you would not want that matched to this symbol!). So please add the ST in front ;-)

ad 2) Yes please remove the .gitognore from this PR

ad 3) yes, but that's how it is at the moment ... I think there are ideas to change that, or to at least have a repo that somehow summarizes the others ... I think @SchrodingersGat  can maybe comment a bit more on this.

About the symbol itself:
- there are pins `HS1`, `HS2`, `HS3`... I think thos are the heatslugs, right? If so they should be numberes 31,32,33 (please countercheck with the footprint).
- In addition we now have rules that allow for stacking equal pins together (NOT THE NC-pins as that would connect them). Maybe this would be useful for this symbol: e.g. all OUTA-pins (also the heatslug): Make one visible and of type OUTPUT, make the others invisible and of type PASSIVE then move them all in one spot. Also please then remove the `_HEAT_SLUG` from the HS-pin, then you can also stack that one:
2017-06-15 08_22_12-part library editor d__kicad_kicad-library-review_library_motor_drivers lib
2017-06-15 08_22_48-part library editor d__kicad_kicad-library-review_library_motor_drivers lib

Best,
JAN

**Comment by jkriege2** [comment]
PS: With the same scheme you can also stack the groups of VCC, GNDA, GNDB and OUTA-pins

**Comment by SchrodingersGat** [comment]
> Why the heck is every footprint folder a different git repo?

This is due to the silly way that KiCAD "integrates" with GitHub. I won't go into too much detail other than to agree that it's ridiculous. Hopefully with continued pressure it can be changed to a sensible approach.

**Comment by Marsfan** [comment]
@jkriege2 I can make those changes. But there is an issue with the heat slugs, on the schematic the heat slugs are not labeled anything but Heat Slug 1/2/3. They are not given a number that is linked with the rest of the footprint.

**Comment by evanshultz** [comment]
The heat slug pin numbering has already been defined in the footprint as it has pins 31, 32, and 33. Check it out. Just match up the physical and logical symbol pin numbers.

As for what to call those pins, it shouldn't matter since they'll be invisible and stacked under other pins. But they could still be named VCC, OUTA, and OUTB if you want something logical. Or HS1, HS2, and HS3 if you want something physical. Or HS1/VCC, etc. if you want both names. Logical pin names seems best to me.

**Comment by Marsfan** [comment]
@evanshultz oh, use the footprint, not the part datasheet. I'm an idiot.

**Comment by jkriege2** [comment]
ABout the stacks: Note all pins in a stack have to have the same name!

JAN

**Comment by Marsfan** [comment]
@jkriege2 Kicad library check says that stacking violates rule 4.3 because one pin does not match other types. I am going over to the kicad utils to check if there is already a bug report on this.

**Comment by Marsfan** [comment]
@jkriege2 I deem (again), believe this system is ready to be merged.

**Comment by SchrodingersGat** [comment]
Hi @Marsfan looks like all the KLC issues were sorted out but unfortunately now there's a merge conflict. If you can fix this up, I'll take a final look before we can merge :)

**Comment by Marsfan** [comment]
Huh, I'll poke around when I have some time and try to fix this.

**Comment by Marsfan** [comment]
@SchrodingersGat  @jkriege2 Something got really screwy with this branch. I am going to close this PR, and open a new one on another branch. 

I believe the weirdness is related to windows lack of understanding about capitalization in file name.

**Pull request closed without merging**
