### PR TITLE
Corrected symbol for MC34063. Matches the one from the datasheet.

### PR DESCRIPTION
**Pull request by mpkopec**
Additionally corrected pin lengths and grid matching.

### CODE REVIEW

**Comment by pointhi** [comment]
ehm, why do you delete MCP73811T and co. in this PR?

**Comment by diggit** [comment]
...and TPS79318-EP?

MC34063 needs some design improvements, but I am nut sure, if this is the right way.

**Comment by mpkopec** [comment]
Thanks for the insight. I must have switched from my branch, not master,
I'll correct it later tonight. As it comes to the symbol what can you
suggest?
15 mar 2016 18:34 "Patrik Bachan" <notifications@github.com> napisał(a):

**Comment by mpkopec** [comment]
Ok, that's weird. The library editor must have done something wrong or I did and I don't know what. I'll revert these changes and redraw the symbol. If you don't like the datasheet-style, I came up with two sensible (imho) possibilities without drawing internal diagram, both should support sensible schematic drawing. Please tell me which do you prefer?

[mc34063-improvement1.pdf](https://github.com/KiCad/kicad-library/files/175522/mc34063-improvement1.pdf)
[mc34063-improvement2.pdf](https://github.com/KiCad/kicad-library/files/175521/mc34063-improvement2.pdf)

**Comment by mpkopec** [comment]
Ok, something is seriously wrong with my repo. I'll close this PR, remove branch, recreate repo and redo the MC34063 changes according to mc34063-improvement2.pdf

**Pull request closed without merging**
