### PR TITLE
`dc-dc.lib`, `dsp.lib`, `texas.lib` and `powerint.lib` adaptation to KLC

### PR DESCRIPTION
**Pull request by keruseykaryu**
`dc-dc.lib` : NID60 series. Pins wrong positions has been overlooked during merging, so its position had to be repaired now.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Kerusey,

For your touch controllers, could you put the origin right in the middle? It's offset a little bit. The pin ends will align to the 100mils grid if you shorten them to the minimum length, at least on the small symbols.

If you can create two distinct pull requests next time you add content and refactor libraries, it would be great. I would have merged the other libraries.

Thanks!

**Comment by keruseykaryu** [comment]
> For your touch controllers, could you put the origin right in the middle? It's offset a little bit. The pin ends will align to the 100mils grid if you shorten them to the minimum length, at least on the small symbols.

This way?
thisway

> If you can create two distinct pull requests next time you add content and refactor libraries, it would be great. I would have merged the other libraries.

Working with separate branches in GitHub 4 Windows is a horrible thing. Last time I've lost some data. I don't know it is my fault or application fault. But I'm now aware of making separate branches.

I've update `cypress.lib` once you look at the above example. 
Next time I will try to simply wait for merging and do not mix-up the refactoring with other things.

Thanks. I'm going because I'll be late to job. :)

**Comment by CarlPoirier** [comment]
Yes! This is great.

As for branching, I guess you could copy the library to update to another directory on your computer and open it manually from KiCad. Then, once the first pull request is merged, you would just have to copy-paste that library into the local repository. That way, you will be able to work even though the first pull request is not merged yet.

Thanks Kerusey, your contributions are very valuable.

**Comment by keruseykaryu** [comment]
> Yes! This is great.

Adjusted.

> As for branching, I guess you could copy the library to update to another directory on your computer and open it manually from KiCad.

This is one of solution, but it could create more mess than I already have in my KiCad stuff. :-) Official libraries, fork of them, my own libraries, sources, GUI translation, doc translations (ODF, HTML, ADOC), Marco Ciampa's doc building system, KiCad projects (company, private, unfinished), WinBuilder, our Win package source for INNO. Uff! A lot of this. Once I lose in that...

**Comment by keruseykaryu** [comment]
This reqest still waiting for approval.

**Comment by ricardocrudo** [comment]
I found some violations using the checklib script.

```
library: dc-dc.lib
    component: APE1707M-33-HF
    Violations of rule 3.1
        pin: VSS (5), posx -150, posy -300, length: 100
        pin: VSS (6), posx -50, posy -300, length: 100
        pin: VSS (7), posx 50, posy -300, length: 100
        pin: VSS (8), posx 150, posy -300, length: 100
    component: LMR10510YSD
    Violations of rule 3.2
        pin: SW (3), dir: L, length: 147
        pin: VIND (4), dir: R, length: 146
        pin: VINA (5), dir: R, length: 147
        pin: EN (6), dir: R, length: 147
    component: NID60
    Violations of rule 3.6
        pin: RC (11), dir: R, name_text_size: 35, num_text_size: 50
    component: ST1CC40PHR
    Violations of rule 3.1
        pin: PGND (2), posx 150, posy -400, length: 100
```
```
library: powerint.lib
	component: CAP002DG
	Violations of rule 3.1
		pin: ~ (2), posx -100, posy 250, length: 100
		pin: ~ (3), posx 100, posy 250, length: 100
		pin: ~ (6), posx -100, posy -250, length: 100
		pin: ~ (7), posx 100, posy -250, length: 100
	component: LNK457V
	Violations of rule 3.1
		pin: FB (2), posx 300, posy -350, length: 100
		pin: D (6), posx -200, posy 350, length: 100
		pin: S (7), posx -400, posy -350, length: 100
		pin: S (8), posx -300, posy -350, length: 100
		pin: S (9), posx -200, posy -350, length: 100
		pin: S (10), posx -100, posy -350, length: 100
		pin: S (11), posx 0, posy -350, length: 100
		pin: S (12), posx 100, posy -350, length: 100
```

**Comment by keruseykaryu** [comment]
Problems has been repaired.

BTW: Welcome in the team.

**Comment by CarlPoirier** [comment]
Hi Kerusey,

Thank you for the hard work. It's awesome!!

**Pull request merged**
