### PR TITLE
Update `transistors.lib`, `hc11.lib`, `opto.lib` and `transf.lib` to meet KLC rules.

### PR DESCRIPTION
**Pull request by keruseykaryu**
`transistiors.lib`: Resolve a bunch of conflicts caused by pull request #141 against my previous commit #140.

`hc11.lib`: Applying KLC rules. Parts has been renamed to match Motorola/Freescale notation.

`opto.lib`: Applying KLC rules. Some generic symbols was preserved, but I think they could be moved to `device.lib`.

`transf.lib`: Applying KLC rules for pin length, and height of fields text.

### CODE REVIEW

**Comment by keruseykaryu** [comment]
This request is ready to check by other librarian and merge if there are no issues.

**Comment by CarlPoirier** [comment]
Hi Kerusey,

The pin length and box size for LTV-817 and LTV-827 should be adjusted and match the other parts in the library. Besides that, it's awesome! I'm merging it now, and I will take care of these pins shortly. Thank you very much for your great work.

**Comment by CarlPoirier** [comment]
Oh and sorry for being a bit slow on the approval these days. I'm pretty busy.

**Comment by keruseykaryu** [comment]
> The pin length and box size for LTV-817 and LTV-827 should be adjusted and match the other parts in the library.

I fixed it: https://github.com/KiCad/kicad-library/pull/144

**Pull request merged**
