### PR TITLE
Added MSP430F2617TPMR to msp430 Library

### PR DESCRIPTION
**Pull request by swedishhat**
Hey all,

This is my first time creating a pull request so go easy please. I added the MSP430F2617 microcontroller with 92KB+256B Flash Memory and 8KB RAM. I described it as a 64-LQFP (TI calls it the 64-PM package) [The datasheet can be found here](http://www.ti.com/lit/ds/symlink/msp430f2617.pdf). Please let me know if there is anything I need to correct.

Thanks,
Pat

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @swedishhat, thanks for your interest to contribute. To add new symbols or footprints to kicad library them have be in conformance with (KLC)[https://raw.githubusercontent.com/KiCad/kicad-library/master/KiCad_Library_Convention.txt]. To help you to check KLC Rules you can use the [checklib script](https://github.com/KiCad/kicad-library-utils/tree/master/schlib).

**Comment by ricardocrudo** [comment]
Also, please, before you fix the KLC issues remove the backup files from git history. 
run:

> git reset --soft HEAD~2

remove *.bak and *.bck from stage and re-commit it.

> cd library
> git commit msp430.dcm msp430.lib -m"Added MSP430F2617TPMR symbol to msp430.lib"

After, force pushing your pull request or open a new one.

**Comment by swedishhat** [comment]
Ok, I believe I successfully removed backup files from the git history. After

**Comment by swedishhat** [comment]
Also, after attempting to address some of the KLC issues, I noticed this from the rules:

> 3.1.  Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617)

Eeschema and the part editor only have a maximum grid size of 50mil. There is an [open bug](https://bugs.launchpad.net/kicad/+bug/1416745) on launchpad to address this.

**Pull request closed without merging**
