### PR TITLE
Added ltc4001 charger

### PR DESCRIPTION
**Pull request by kajusK**
SSIA

### CODE REVIEW

**Comment by diggit** [comment]
>SSIA

It says, but screenshot can be really helpful.

Several things to fix:
- pin 10 is FAULT output, something bad happened there...
- set default FP to: `Housings_DFN_QFN:QFN-16-1EP_4x4mm_Pitch0.65mm`, set FP field invisible and size to 0.05
- set FP filter to `QFN*1EP*4x4mm*Pitch0.65mm*`
- mention in description (you can get inspiration from other charger chips...):
 - that it is for single cell, 4.2V might not me enough
 - it is programmable
 - maximal input voltage

**Comment by diggit** [comment]
@reportingsjr what is the status of automatic checks?

**Comment by kajusK** [comment]
@diggit Thank you for checking, I completely missed the Fault pin problem...

Updated all the problems you mentioned, hope it's ok now.

2016-10-30-082332_1366x768_scrot

**Comment by diggit** [comment]
@kajusK Can you please set remaining "datasheet" field to 0.05 size too? Otherwise checking script won't stop complaining.

@CarlPoirier Can you take a look on default text filed size in kicad upstream? 50mils as default would really help. Assignment is done [here](http://bazaar.launchpad.net/~kicad-product-committers/kicad/product/view/head:/eeschema/lib_field.cpp#L70). There is several levels of abstraction and original value is sourced from [here](http://bazaar.launchpad.net/~kicad-product-committers/kicad/product/view/head:/include/eda_text.h#L68), but comment says, it should be changed in individual apps and not touched there. I'm not sure where it is...

**Comment by diggit** [comment]
Nice work you did, merging.

**Comment by kajusK** [comment]
@diggit Done

@CarlPoirier Changing default text size would be really helpful, it's quite error prone and annoying to do it manually when creating a new part...

**Pull request merged**
