### PR TITLE
Adding SST39SF0x0 flash chips

### PR DESCRIPTION
**Pull request by DavidGriffith**
Adding symbols for three flash chips from SST (Microchip): SST39SF010 (128x8), SST39SF020 (256x8), and SST39SF040 (512x8)

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Proposed symbol does not meet the KiCad Library Convention rules. Please fix these issues.

**Comment by keruseykaryu** [comment]
I didn't talk about the documentation fields. Symbols have some glitches to fix.

**Comment by DavidGriffith** [comment]
Oh... can you elaborate on that?  I just stretched an existing footprint.

**Comment by keruseykaryu** [comment]
1. Open the [Kicad Library Convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention).
2. Go to the **General Rules for Symbols** chapter
3. Read it sequentially and check your symbol against given assumptions.

Do not look at existing similar symbols because they not meet this assumptions yet. We are trying to fix it but it took a time that we don't have it (a much). However, for the new symbols we require that they already meet these goals before merging.

**Comment by DavidGriffith** [comment]
Would you please be more verbose about what, specifically, I need to do?

**Comment by keruseykaryu** [comment]
Dave, please again read my previous comment.

**Comment by DavidGriffith** [comment]
Okay, I now see that the field text, pins numbers and pin descriptions were not 50mil.  Is that it?

**Comment by keruseykaryu** [comment]
Bravo! Only one issue left to find.

**Comment by DavidGriffith** [comment]
What issue is that?

**Comment by DavidGriffith** [comment]
Origin back to the center.  Was that the last one?

**Comment by keruseykaryu** [comment]
The last edit worsened things even more.

**Comment by DavidGriffith** [comment]
All I did was move the origin.  How could that possibly lengthen the pins?

**Comment by reportingsjr** [comment]
Keruseykaryu, is there a reason to be so short with contributors? I understand that being a maintainer can be frustrating, but this is the same sort of behavior that Dick would present and he alienated a LOT of developers from KiCad for no reason.

**Comment by keruseykaryu** [comment]
Being be very verbose and polite the situations where I had to repeat the same thing will continue. It is not my intention to bring somebody down, only to force someone to **act independently**. That's why I give you a hints not a solutions, and it can be perceived as rude of me.
Please do not compare me to Dick Hollenbeck. If Mr. Hollenbeck would be in my place you would have more trouble. However, obvious attempts to create turmoil and devastation I will block without question, just like him. And that situations already happens.

If anyone has doubts whether I am the right person for this place, please express it directly. I can always say goodbye.

**Comment by CarlPoirier** [comment]
Hi David,

These look great now. Thanks a bunch for your contribution.

**Pull request merged**
