### PR TITLE
Some corrections in linear.lib

### PR DESCRIPTION
**Pull request by Heiko-L**
Moved alias MCP601-xSN from MCP601-xP (wrong package) to alias for OPA333xxD (same pinout, same package)
Deleted symbol for OP179GS and readded OP179GS as alias for OPA333xxD (same pinout, same package)
Deleted symbol LMV331 and readded as alias for LMV321 (same pinout, same package)

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

hmmm ... I poked around a bit in the datasheets and:
- MCP6561U MCP6001U are only available in SOT-23-5, NOT SC-70
- MCP601-xST is in TSSOP but FPFilters also list SOIC and DIP
- MCP601-xSN + OP179GS are in SOIC, but FPFilters also list DIP and MSOP

... if you want to do this, you'll need to make a complete workover of the lib ... I think!

Best,
JAN

**Comment by Heiko-L** [comment]
Now there is a lot of overlapping with #1623, maybe we should care about #1623 first

**Comment by Heiko-L** [comment]
I close this PR, rebasing seems to be a PITA.
@jkriege2 @evanshultz Should I Pick OP179GS and LMV321/331 rework or leave it to you?

**Comment by evanshultz** [comment]
I'll do it. Thanks for your contributions.

**Comment by Heiko-L** [comment]
Ok, good luck!

**Pull request closed without merging**
