### PR TITLE
Add TXB0102DCU and TXB0102YZP in library/texas

### PR DESCRIPTION
**Pull request by jjuyon**
Hi,
Her two new components from Texas Instruments: [TXB0102DCU and TXB0102YZP](http://www.ti.com/lit/ds/symlink/txb0102.pdf)

Best,
Julien

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi! 
some small changes please:
1. make outline 0.01" thick
2. change all text size to 50mil (you can use the `check_lib`-scripts to fix 1 and 2)
3. Please add a third one TXB0102DCT and set the correct package for each of the three explicitly in footprint-field and set the FPFilter accordingly (you currently have the TXB0102DCU which is VSSOP-only)

best,
JAN

**Comment by jjuyon** [comment]
Hi,
Changes done. I add an alias for the DCT package, and that's  imply an addition a FPFilter. Maybe is better to make it as a separate component to avoid user confusion between footprints?

Best
Julien

**Comment by jkriege2** [comment]
Yes please make separate symbols, as currently an alias cannot be linked to a specific footprint ;-(

Best,
JAN

**Comment by jjuyon** [comment]
It's done.

Julien

**Comment by jkriege2** [comment]
Hi!

1. please solve conflicts (pull master)
2. FPFilter should be `VSSOP*Pitch0.5mm*` , `SSOP*Pitch0.65mm*`, `DSBGA*Pitch0.5mm*`
3. add package name to description
4. set footprint field to the actual footprint.

Best,
JAN

**Comment by jjuyon** [comment]
Hi,
It is done.

Best,
Julien

**Comment by jjuyon** [comment]
Hi,
I add footprint field for the TXB0102 and create a new component USB2414B/Bi from Microchip

Best
Julien

**Comment by jkriege2** [comment]
please fix conficts!

**Comment by jjuyon** [comment]
Hi,
Conflicts solved

**Comment by jkriege2** [comment]
Hi!

mostly OK now, only a few small changes please:
1. set text-size of datasheet field in all TXB0102... to 0.05in=50mil
2. Please set the correct footprint name (lib:fp-format) in TXB0102DCT.

Best,
JAN

**Comment by jjuyon** [comment]
Hi,
What do you mean by _lib:fp-format_? Is it Footprint field like the two other components? There is already FP filter filled and there is not only one footprint possibility.

Best,
Julien

**Comment by jkriege2** [comment]
The description says its TSSOP, so why are there different options? If there are none, please set the correct TSSOP-package in the footprint field and set the FPFilter matching.

JAN

**Comment by jjuyon** [comment]
Ho ok, I get it.
It is fixed.

Julien

**Comment by jkriege2** [comment]
PLease fix conflicts!

**Comment by jjuyon** [comment]
Conflicts solved

**Comment by jkriege2** [comment]
@jjuyon sorry more conflicts to solve :-(

**Comment by jjuyon** [comment]
Hi,
Conflicts fixed

**Comment by jkriege2** [comment]
Please mpty the datasheet-field on `USB2514B/Bi`.

then I will merge.

best,
JAN

**Comment by jjuyon** [comment]
It's done,

Best,
Julien

**Comment by jkriege2** [comment]
THANKS
JAN

**Pull request merged**
