### PR TITLE
Added Zero-Drift Op's LTC1151CSW and LTC1152

### PR DESCRIPTION
**Pull request by chrigro**
ltc1151csw

ltc1152

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. the basics look fine, but please restyle your symbols:
1. LTC1152 should look like all the other OPAMPS in this lib (triangle-shape)
2. LTC1151: please make a symbol with two units, one for each amp and a triangle shape as the other dual OPAMPs in this lib. Also: Would you be willing to also provide the symbol for the DIP-8 variant of this device? That would be great!

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

better now ... could you still tweak your triangles a bit more to match the symbol of other (dual) OPAMPS, yours is a bit too large:
2017-09-20 08_30_25-eeschema kicad_review-project2 _ d__kicad_kicad_review-project2

Thanks,
JAN

**Comment by jkriege2** [comment]
Also having the SHDN-pin between the +/--inputs is quit uncommon in this lib, please change:
2017-09-20 08_33_21-eeschema kicad_review-project2 _ d__kicad_kicad_review-project2
You can orient your symbol on the LM318N ... and maybe even add some pin-naming inside as (extra) text-element.

Best,
JAN

**Comment by evanshultz** [comment]
@chrigro 
Sorry to disrupt your post here.

@jkriege2 
Once these two PRs from @chrigro are merged, are you OK with a moratorium on linear.lib? There's been an uptick in contributions lately so I didn't feel there was a good time to separate parts physically. But based on recent events, I think we should instead make time for me to clean it up.

**Comment by jkriege2** [comment]
Nice work!
Thanks,
JAN

PS: @evanshultz fine with me ...

**Pull request merged**
