### PR TITLE
Added ADM101E (miniature RS232 transceiver)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
uSOIC-10 package
http://www.analog.com/en/products/interface-isolation/rs-232-rs-422-rs-485/interface-rs-232/adm101e.html#product-overview
http://www.analog.com/media/en/technical-documentation/data-sheets/ADM101E.pdf

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hi @SchrodingersGat. Please, when creating black-box symbol grouping pins logically, as KLC 3.4 says, instead of numerical order. Be carefully when you take a symbol as reference to create a new symbol, there are a lot of old symbols in disagreement with KLC.
Example: 
adm101e

Fix pin2 name of ADM101E, should be C1-.

**Comment by SchrodingersGat** [comment]
Hi @ricardocrudo I have made the requested changes to all the new parts I've put in interface.lib :)

**Comment by SchrodingersGat** [comment]
Any further requirements to get this up to spec, @ricardocrudo ? :)

**Comment by ricardocrudo** [comment]
Hi @SchrodingersGat 

I gave a fast look up in all symbols, please re-check some points:
* always that possible place inputs left side, output right side, vcc top, gnd bottom
* add footprint hints to footprint filter tab
* check pin electrical type
* do not place footprint label in the middle of box, the label can cover some pins names
* keywords shouldn't be a copy of description it should contain some key words :) that better describe the device (mainly in the searching time)
* only includes footprint on description if part number has only one footprint option and it's considered as "feature"

After do the changes, please re-check them using the checklib script.
Thanks

**Comment by SchrodingersGat** [comment]
As far as possible I have updated these components to match the requests by @ricardocrudo lmk if you wan't anything else adjusted. Thanks.

**Comment by SchrodingersGat** [comment]
I have now also improved some of the non-KLC symbols in this library.

**Comment by SchrodingersGat** [comment]
@ricardocrudo I have merged kicad/master back into this branch to fix all conflicts. Cheers

**Comment by SchrodingersGat** [comment]
@ricardocrudo  any update on this? A lot of changes in this pull request now - if you can let me know what I need to do to get it merged, that'd be great :) Thanks

**Comment by SchrodingersGat** [comment]
Some components have been removed from this commit, and moved to power_management.lib

See: https://github.com/KiCad/kicad-library/pull/439

**Comment by diggit** [comment]
This PR is large, it will take some time to check it. Be patient...

On the first look, some improvements are needed.

### Keywords
 Keep in mind, that keyword are space separated. So they have to make sense as individuals. Keywords like "_wide input voltage driver FET MOSFET gate driver_" will resilt in keywords:
- wide (doesn't make sense)
- input (doesn't make sense)
- voltage (doesn't make sense)
- driver (ok)
- FET (MOSFET is enough)
- MOSFET (ok)
- gate (doesn't make sense)
- driver (duplicity)

Too generic or not useful keywords you used:
wide, input, voltage, gate, line, canbus, monitor, supervisory, 232, speed, high-speed, transient, immunity
maybe some more...

high-side, driver, mosfet, uart, transciever, CAN, RS232, supervisor, microcontroller,....
are IMO ok

All LTC4440* have poor keywords.


### Description
Use comma to separate individual properties.
`High voltage high side gate driver, 80V input` -> `High voltage, high side, gate driver, 80V input`

### Footprint
When you set footprint field, create footprint filter too.

**Comment by diggit** [comment]
Btw @SchrodingersGat What version of KiCad do you use (build number) on which platform(widows/linux_distro)? Those changes in line ordering makes error checking really painful...

**Comment by diggit** [comment]
Never mind, line ordering problem comes from checklib.py script from kicad-libary-utils.

**Comment by SchrodingersGat** [comment]
@diggit - some good points. I've moved some of these components from this PR as they really should be in power-management - https://github.com/KiCad/kicad-library/pull/439

**Comment by SchrodingersGat** [comment]
@diggit I have tried to improve as many components as I can here as per your suggestions. Please let me know if there are any specific changes you want me to make. Happy to help :)

I have also moved some more components (e.g. LTC4440) out of this PR and into power-management.lib

**Comment by SchrodingersGat** [comment]
I've fixed some issues (of my own making) with the ADM232 part - I had some part aliases that were not correct.

**Comment by SchrodingersGat** [comment]
@diggit as there's a lot to take in here, I'm going to close this and re-issue as separate PRs. Especially given that with some of my more recent PRs (e.g. https://github.com/KiCad/kicad-library/pull/472) some of these changes have been superseded

**Pull request closed without merging**
