### PR TITLE
Dsbga 12 maxim wlp texas junior dsbga 12

### PR DESCRIPTION
**Pull request by Misca1234**
The 3d models for 
https://github.com/KiCad/Housings_BGA.pretty/pull/11

This push includes the 90 degree rotation included in the 
https://github.com/KiCad/Housings_BGA.pretty/pull/14

bild

bild

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @Misca1234 did you make these 3D models yourself? Have you submitted to the [3D packages repo](http://github.com/kicad/packages3d)?

**Comment by Misca1234** [comment]
I used the easyw/kicad-3d-models-in-freecad to produce them

And here is the (new) push for the package3D
https://github.com/KiCad/Housings_BGA.pretty/pull/15

**Comment by SchrodingersGat** [comment]
Thanks :)

**Comment by Misca1234** [comment]
Nice, thx

**Pull request merged**
