### PR TITLE
4543

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by piotr-wiszowaty** [comment]
Symbol updated.

**Comment by hackscribble** [comment]
See comment https://github.com/KiCad/kicad-library/pull/688#issuecomment-314207976

**Comment by piotr-wiszowaty** [comment]
Moved to a fresh feature branch.

**Pull request closed without merging**
