### PR TITLE
Add Intersil 72x2 Series MOSFET Driver ICs

### PR DESCRIPTION
**Pull request by Gasman2014**
Add Intersil 72x2 Series MOSFET Driver ICs

/Users/johnpateman/Desktop/EL72/EL7202CN.png
/Users/johnpateman/Desktop/EL72/EL7212CN.png
/Users/johnpateman/Desktop/EL72/EL7222CN.png

### CODE REVIEW

**Comment by Gasman2014** [comment]
el7202cn
el7212cn
el7222cn

**Comment by SchrodingersGat** [comment]
You seem to be missing changes to the .lib file - only the .dcm file has been included.

**Comment by Gasman2014** [comment]
Sorry - just when I thought I was getting the hang of it!

**Comment by SchrodingersGat** [comment]
Great work, thanks for the contribution :)

**Pull request merged**
