### PR TITLE
added FRT5 relays (2-switch DIL signal relays), as standard relay symbol and as symbol separated into coil+2switches

### PR DESCRIPTION
**Pull request by jkriege2**
schematic symbols conform to KLC

see https://github.com/KiCad/Relays_ThroughHole.pretty/pull/8 for the footprint

Here are screenshots of the 3D package and the schematic symbols
frt5sch
frt5

### CODE REVIEW

**Comment by jkriege2** [comment]
Here are screenshots of the 3D package and the schematic symbols
frt5
frt5sch

**Comment by jkriege2** [comment]
schematic symbols conform to KLC

**Comment by jkriege2** [comment]
see https://github.com/KiCad/Relays_ThroughHole.pretty/pull/8 for the footprint

**Comment by SchrodingersGat** [comment]
Please fix conflict

**Pull request merged**
