### PR TITLE
I have made a huge mistake

### PR DESCRIPTION
**Pull request by SchrodingersGat**
gob-bluth

So. Still getting my head around these new admin powers, and I fear that I may have used them in error. 

I accidentally pushed **my** master branch to kicad/master.

*The shame.*

This PR reverts all those changes to preserve history. I have checked to ensure that my personal repos are no longer present in this branch. I shall continue to check.

@CarlPoirier  I have emailed you about this, and spent a while working out how to revert it - I'm pretty sure I'm managed to negate all the damage I have done.

I'd love to get this fix merged ASAP as I've exposed:

* My private repos which contain mostly years-old mangled parts
* My repository of 3D shapes for which the licensing for releasing publicly is dubious.
* All my outstanding PRs have been automatically merged as they were in my main branch

Hopefully we can fix this before anyone notices...

@diggit  @pointhi  you guys are on here often enough that you should weigh in. Make sure that I haven't missed anything in this revert.

My apologies for wasting everyone's time.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
It goes without saying that I have removed my user-account for kicad/master from my git client (I didn't even know I *could* push straight from there. Sorry everyone.

**Comment by diggit** [comment]
Oh, that explains why my recent pull from master took 17s and didn't fit in my terminal buffer. If these are all, no time to waste.

**Comment by SchrodingersGat** [comment]
Thanks @diggit, much appreciated. I'll see what a diff between new kicad/master and *good* kicad/master turns up. 

Cheers

**Comment by CarlPoirier** [comment]
Hi guys, no worries for that.

As an advice, after having tested the pull request locally on my computer, I personally come back on Github and merge through the web interface instead.

Carl

**Comment by pointhi** [comment]
I can also suggest the command ```git remote -v```. I always use it, when I'm unsure where the repository is pointing.

**Comment by diggit** [comment]
I prefer using github web interface for merging too.
My local repo's remote origin is my fork and I sync them by pulling changes from upstream. No **pushurl** for upstream is defined in config, so I believe that pushing to upstream is not possible. (not tested :)

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:diggit/kicad-library.git
        fetch = +refs/heads/*:refs/remotes/origin/*
        pushurl = git@github.com:diggit/kicad-library.git
[remote "upstream"]
        url = git@github.com:KiCad/kicad-library.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Pull request merged**
