### PR TITLE
Added Micrel MIC5205-*M5 regulator family

### PR DESCRIPTION
**Pull request by jhol**

### CODE REVIEW

**Comment by jhol** [comment]
bump

**Comment by ricardocrudo** [comment]
Hello @jhol. Here in this PR there are same KLC issues as in #315

**Comment by jkriege2** [comment]
I included these into an overhaul of the whole lib: https://github.com/KiCad/kicad-library/pull/948

**Comment by SchrodingersGat** [comment]
Closing due to inactivity and @jkriege2 including them in his PR

**Pull request closed without merging**
