### PR TITLE
Add PM8834

### PR DESCRIPTION
**Pull request by raiden00pl**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. Please make these two minor changes:
1. The output pins should be outputs, not power_outputs
2. Please refer to KLC4.12.iv for example of correct footprint filters. (see https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

Best,
JAN

**Comment by raiden00pl** [comment]
Fixed

**Comment by SchrodingersGat** [comment]
Hi @raiden00pl you are going to have to make this into two separate symbols, as the MSOP variant has an exposed pad (pin-9) which needs to be connected to GND.

As per the [datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/9a/22/3e/55/d3/f8/46/d5/CD00212712.pdf/files/CD00212712.pdf/jcr:content/translations/en.CD00212712.pdf) please name the symbols as follows:

* SOIC: `PM8834`
* MSOP: `PM8834M`

In the `Description` field for each symbol, change `(SO8 or MSOP8 package)` to (e.g.) `, SO8 package`

**Comment by raiden00pl** [comment]
You're right. Fixed again :)

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Pull request merged**
