### PR TITLE
Added BD1020HVF Analog Temperature Sensor

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contrib! Could you please change some minor things?
1. please hide the NC-pin
2. please add a footprint and footprint filter
3. A suggestion: What about adding something to the symbol that indicates this is a temperature sensor? e.g. like the thermometer in the  MCP9700 symbols ...

est,
JAN

**Comment by crackerizer** [comment]
1,3 are done. I have added footprint filter to the symbol but there is still no footprint (HVSOF5) in the module library.

**Comment by jkriege2** [comment]
Do the two addition PRs to TO_SOT-lib contain the footprints? If so, I'll review them this evening ... then we can finish this PR with a complete symbol ;-)

JAN

**Comment by jkriege2** [comment]
Please have a look at my comment there: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/23 ... Otherwise this symbol looks good to me. So if you would already set the footprint field then I can merge and the footprint is available, as soon, as the issues there are resolved.

Best,
JAN

**Comment by crackerizer** [comment]
I have set the footprint to TO_SOT_Packages_SMD:HVSOF5.

**Pull request merged**
