### PR TITLE
Add LM5109 family, MPY634

### PR DESCRIPTION
**Pull request by evanshultz**
LM5109/LM5109A/LM5109B
- New part

Datasheets:
http://www.ti.com/lit/ds/snvs369/snvs369.pdf
http://www.ti.com/lit/ds/symlink/lm5109a.pdf
http://www.ti.com/lit/ds/symlink/lm5109b.pdf

MPY634: http://www.ti.com/lit/ds/symlink/mpy634.pdf
- New part
- Added simplified internal schematic for Jan!

Image:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Now that I place a diode above LM5109, it looks bad. The HB pin is too close. Maybe I should move the HB pin to the right side and push the HO pin towards the top of the symbol. Comments?
image

**Comment by poeschlr** [comment]
I played around a bit and managed to reduced the size of MPY634KP (Without reducing the information content)
[mpy634kp.lib.txt](https://github.com/KiCad/kicad-library/files/1217098/mpy634kp.lib.txt)
screenshot from 2017-08-11 08-45-07

**Comment by evanshultz** [comment]
@poeschlr Thanks!

New symbols:
image

**Comment by evanshultz** [comment]
Thanks again for the feedback. Can this be merged now?

**Comment by evanshultz** [comment]
@jkriege2 In the mood to review/merge this?

**Comment by jkriege2** [comment]
@poeschlr Will you finish this, or should I have a look?
Best,
JAN

**Comment by poeschlr** [comment]
I played around a bit more with the MPY634 symbol.
I managed to allow the output to be named. (VO)
And i moved the '+' and '-' of the inputs such that they do not collide with the triangular outlines.
This time i only exported the artwork as sym file: [MPY634.sym.txt](https://github.com/KiCad/kicad-library/files/1220360/MPY634.sym.txt) (This should make it easier for you to use it.)

screenshot from 2017-08-13 10-22-55

We could merge as is but if you find some time to update the artwork i think the symbol would look even better.

**Comment by evanshultz** [comment]
@poeschlr Updated with your artwork? Anything before this can be merged?

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
