### PR TITLE
added several missing linear ICs

### PR DESCRIPTION
**Pull request by jkriege2**
# linear.lib
## NEW/MODIFIED:
* [x] LM555N NE555 ICM7555 LMC555 TLC555 NA555 SE555 SA555
* [x] ICM7556 NA556 NE556 SA556 SE556
* [x] NE567 SE567
* [x] L272D 
* [x] L272M
* [x] LM321
* [ ] TL061 TL071 TL081
* [x] LT1492
* [x] LT1493
* [x] NE5534 SA5534 LM101 LM201 LM301
* [x] LMV321
* [x] INA128
* [x] INA129
* [x] INA326
* [ ] INA327
* [x] MAX4238ASA
* [x] MAX4238AUT
* [x] MAX4239ASA
* [x] MAX4239AUT
* [x] OPA333D OPA340D
* [x] OPA333DBV OPA340DBV
* [x] OPA2340
* [x] OPA2333D
* [x] OPA333DCK
* [x] OPA340P
* [x] OPA4340D
* [x] OPA4340DBQ
* [x] OP07 OP077 LT1363
* [x] LM4250
* [ ] MCP601P
* [ ] MCP601R
* [ ] MCP601SN
* [ ] MCP601ST
* [ ] MCP603
* [ ] MCP603P
* [ ] MCP603SN
* [ ] MCP603ST

## ALIASES:
* [ ] LF155 LF156 LF255 LF256 LF257 LF357 LF355 LF356
* [ ] MCP6004 TL084 TL064 LMV324 LMC6484 MCP604
* [ ] TL062 TL072 TL082 NE5532 LMV358 TS912 TLC272 MCP602

# mototr_drivers.lib:
## NEW:

* [ ] L293 
* [ ] L293D

# interface.lib:
## NEW:

* [x] MC1413 MC1413P SN75468 SN75469 ULN2002 ULN2002A ULN2003 ULN2003A ULN2004 ULN2004A
* [x] ULN2801A ULN2802A ULN2803A ULN2804A ULN2805A
* [ ] ICL7667

## ALIASES:
* [ ] MAX3232

# dc-dc.lib:
## NEW:
* [ ] LT1073
* [x] LM2734

## ALIASES: 
* [ ] LM2575-12BT LM2575-3.3BT LM2575-5.0BT LM2575BT-ADJ
* [ ] LM2575-12BU LM2575-3.3BU LM2575-5.0BU LM2575BU-ADJ

# audio.lib:
## NEW:
* [x] MSGEQ7

# reference.lib:
## NEW:
* [x] TL432DBV
* [x] TL432DBZ
* [x] TL432PK

## General changes to libs:
- added several missing NC pins

Here are some screenshots (not all, but the ones where I didn't simply add an alias, i.e. the new ones and the ones where the symbol was altered!
addlin

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 if you can write a list of all the parts you have added and want me to check, I'll have a look through them.

**Comment by jkriege2** [comment]
== linear.lib
=== NEW/MODIFIED:
```
LM555N NE555 ICM7555 LMC555 TLC555 NA555 SE555 SA555
ICM7556 NA556 NE556 SA556 SE556
NE567 SE567
L272D 
L272M
TL061 TL071 TL081
LT1492
LT1493
NE5534 SA5534 LM101 LM201 LM301
LMV321
INA128
INA129
INA326
INA327
MAX4238ASA
MAX4238AUT
MAX4239ASA
MAX4239AUT
OPA333D OPA340D
OPA333DBV OPA340DBV
OPA2340
OPA2333D
OPA333DCK
OPA340P
OPA4340D
OPA4340DBQ
OP07 OP077 LT1363
LM4250
MCP601P
MCP601R
MCP601SN
MCP601ST
MCP603
MCP603P
MCP603SN
MCP603ST
```
=== ALIASES:
```
LF155 LF156 LF255 LF256 LF257 LF357 LF355 LF356
MCP6004 TL084 TL064 LMV324 LMC6484 MCP604
TL062 TL072 TL082 NE5532 LMV358 TS912 TLC272 MCP602
```

== interface.lib:
=== NEW:
```
MC1413 MC1413P SN75468 SN75469 ULN2002 ULN2002A ULN2003 ULN2003A ULN2004 ULN2004A
ULN2801A ULN2802A ULN2803A ULN2804A ULN2805A
L293 L293D
ICL7667
```
=== ALIASES:
```
MAX3232
```

== dc-dc.lib:
=== NEW:
```
LT1073
LM2734
```

=== ALIASES: 
```
LM2575-12BT LM2575-3.3BT LM2575-5.0BT LM2575BT-ADJ
LM2575-12BU LM2575-3.3BU LM2575-5.0BU LM2575BU-ADJ
```

== audio.lib:
=== NEW:
```
MSGEQ7
```

== reference.lib:
=== NEW:
```
TL432DBV
TL432DBZ
TL432PK
```

**Comment by jkriege2** [comment]
@SchrodingersGat : see my last post for a complete list ... 
- in one line there are aliases. 
- under NEW/MODIFIED I listed new or modified symbols
- under ALIASES I listed new symbols that are "just" aliases to existing components

Note that there are also some general fixes to the libs: I fixed some FPFilter and added some missing NC-pins

Would be great if you have some (more?) time to look through this ... I know it's a lot, but looking more and more into the KiCAD lib, I see that there is still a lot of work to do ...

cu
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat I made a checkable list at the top ... that should make review a bit easier!

Best,
JAN

**Comment by SchrodingersGat** [comment]
Hi @jkriege2  please fix conflicts :)

**Comment by jkriege2** [comment]
Done!

Best,
JAN

**Comment by SchrodingersGat** [comment]
This is a huge contribution - but in the future please try to keep them separated at least by library. This is very tedious to check...

## Linear.lib
* TL071 - Datasheet incorrect, and part seems to be missing OFFSET pins ( as per [datasheet](http://www.ti.com/lit/ds/symlink/tl072a.pdf) )
* INA327 - Pin names are overlapping, looks messy
* MCP601 - Needs FP filters
* MCP601x - Change V+ and V- to "Power Input"
* MCP603x - As above
* MCP603x / MCP601x - Change pin text offset to "10"

## Motor_drivers.lib
* L293 - Pin 8 should be VCC2 (not GND)

## Interface.lib
* ICL7667 - increase pin text offset such that text is further from edge of rectangle

## dc-dc.lib
* LT1054 - Add DIP filter

**Comment by SchrodingersGat** [comment]
There are also a large number of parts (especially in linear.lib) for which the power/gnd pins are NOT set to POWER_INPUT

Some are POWER_OUPUT and some are INPUT. please address this (the KLC scripts should show these)

**Comment by jkriege2** [comment]
Hi @SchrodingersGat 
Thanks for the review ... I'll fix the things in the next days ,-)

cu
JAN

PS: Next time I'll split a bit more ... There are still some other larger PRs from me (transistors, ...), but they are at least in one single lib.

**Comment by jkriege2** [comment]
Hi!

should be fixed now!

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan, this is fine work :)

**Comment by jkriege2** [comment]
thanks for the detailed review ;-)

**Pull request merged**
