### PR TITLE
Ea e dip320 xxx

### PR DESCRIPTION
**Pull request by Misca1234**
Display:
EA eDIP320B-8LW

Aliases: 
EA eDIP320B-8LWTP
EA eDIP320J-8LW
EA eDIP320J-8LWTP
EA eDIP320J-8LA
EA eDIP320J-8LATP

http://www.lcd-module.com/fileadmin/eng/pdf/grafik/edip320-8e.pdf

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1506

pretty push branch is
https://github.com/KiCad/Displays.pretty/pull/32

packages3D push branch is
https://github.com/KiCad/packages3D/pull/115

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/42

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
This one have aliases and default RS-232 as well, I guess it will be updated 
https://github.com/KiCad/kicad-library/pull/1494
is sorted out

**Comment by SchrodingersGat** [comment]
Please fix conflicts

**Comment by Misca1234** [comment]
Conflict resolved

I took the opportunity to move in the NC pins as well

bild

**Comment by Misca1234** [comment]
Fixed conflicts and moved in the NC pins


bild

**Pull request merged**
