### PR TITLE
adc_dac: Added MAX5139 DAC

### PR DESCRIPTION
**Pull request by mpkopec**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@mpkopec finally got around to this one :) The symbol is mostly very good, I would only suggest a few slight changes (shown below)

* Slightly rearrange the pins to have AGND at the bottom and A/DVDD at the top
* Add the matching default footprint (shown) and ensure it is set to INVISIBLE
* Fix the footprint filters (the datasheet shows there is only one compatible footprint for this part)

fix


Thanks!

**Comment by mpkopec** [comment]
Done ;)

**Comment by SchrodingersGat** [comment]
Just remove the duplicated datasheet from the "Datasheet" field (leaving it in the "Documentation File Name" field) and we'll be god to go :)

**Comment by mpkopec** [comment]
Done :)

**Comment by SchrodingersGat** [comment]
Awesome, nice work :)

**Pull request merged**
