### PR TITLE
Added LT6106 - low cost high side current sense amplifier.

### PR DESCRIPTION
**Pull request by mpkopec**

### CODE REVIEW

**Comment by diggit** [comment]
needed changes:
- correct pin types: 
 - V+ and V- as power inputs
 - output pin as open collector
- extend description (you can get inspiration eg. from AD8212)
 - add info about open collector out, maximal voltage, bandwidth, gain,...

**Please save library with latest version of kicad. There were some changes in formatting.**
(bzr build 6331 and later)

**Comment by mpkopec** [comment]
Done :)

**Comment by diggit** [comment]
You have "amplifier" twice in keywords.

4.0.2 is probably not enough, if possible, use nightly. For windows http://downloads.kicad-pcb.org/windows/nightly/ ...

**Comment by diggit** [comment]
@SchrodingersGat what version of KiCAD you use now?

**Comment by mpkopec** [comment]
I have bzr 6690 now. Please tell me if there is any way to automate update of KiCad?

**Comment by diggit** [comment]
Output looks ok. There are no more double spaces in lib file.
Updating depends on your system. Eg. Arch Linux have kicad build package in user repositories (AUR), easy to install. (which I use)

I am quite surprised about unique pinout. (no alias possible)

Nice work you did, merging.

**Pull request merged**
