### PR TITLE
Added STM32F030F4 to STM32 Library

### PR DESCRIPTION
**Pull request by nagelkl**

### CODE REVIEW

**Comment by pointhi** [comment]
test this please

**Comment by pointhi** [comment]
Thanks for your contribution.

**Comment by yaqwsx** [comment]
Asking just from curiosity: Why is this PR merged preferably rather than #304? Is it because every symbol was manully reviewed?

**Comment by pointhi** [comment]
Thats a good question. Shortly because I'm a new maintainer and doesn't know there was already a pull for this microcontroller pending.

I will look into #304 to find PR blockers, but merging such a big PR would be done by more experienced maintainiers.

**Comment by nagelkl** [comment]
What is the benefit of auto generating the library as suggested in PR #304? In my opinion it is verry dificult to test if the parts are generated correctly

**Comment by yaqwsx** [comment]
Yes, it is difficult, however in my opinion you can get a complete library with no missing symbols almost for free and the library can be easily updated, if new MCUs are released. For me it outweights the complexity of scripting and testing. However this is just my opinion.

**Pull request merged**
