### PR TITLE
Pspice: Fix diode

### PR DESCRIPTION
**Pull request by myfreescalewebpage**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Can you add a description for what you have changed / fixed? Thanks.

**Comment by myfreescalewebpage** [comment]
Size of the diode reduced (it was larger than my ICs on the schematic !!)

**Comment by jkriege2** [comment]
I think this will superfluous, when https://github.com/KiCad/kicad-library/pull/742 is merged ...

JAN

**Comment by myfreescalewebpage** [comment]
I have not read all the issue, have you seen the simple diode ? I have seen zener, unitunnel, etc but not simple one.

**Comment by jkriege2** [comment]
I reworked the complete lib of diodes ... I forgot to put an image of the diode, but you can find one with the Thyristors (mid-bottom), see here:

https://cloud.githubusercontent.com/assets/11967523/19699537/fdc55b4c-9af3-11e6-8d83-e7928514858f.png

This OK for you?

**Comment by myfreescalewebpage** [comment]
Perfect for me !

To Kicad admin, maybe you can reject my Pull Request if you accept the one from jkriege2 ?

**Comment by myfreescalewebpage** [comment]
#742 has been merged, closing the pull request.

**Pull request closed without merging**
