### PR TITLE
added AD differential amplifiers AD8xxx

### PR DESCRIPTION
**Pull request by diggit**
Added all AD8xxx device from [current sense amplifiers category](http://www.analog.com/en/products/amplifiers/specialty-amplifiers/current-sense-amplifiers.html) except those who differ in temp. range only.
Those are differential amplifiers for current sensing in highside. High CMRR and bandwidth. 
- pin numbers were double checked
- datasheets assigned
- pin types set according to datasheets but not tested nor verified
- passing extended checklib test
- descriptions and keywords may need tweaking...

Review welcome!

```
checklib.py -v --enable-extra library/linear.lib 
library: library/linear.lib
...
checking component: AD813
  No violations found
checking component: AD8202
  No violations found
checking component: AD8203
  No violations found
checking component: AD8207
  No violations found
checking component: AD8210
  No violations found
checking component: AD8211
  No violations found
checking component: AD8212
  No violations found
checking component: AD8213
  No violations found
checking component: AD8215
  No violations found
checking component: AD8217
  No violations found
checking component: AD8218
  No violations found
checking component: AD8219
  No violations found
checking component: AD8417
  No violations found
...
```

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Patrik,

Thanks for your contribution! Your amplifiers are great.

**Comment by CarlPoirier** [comment]
Please fix the conflicts and then I'll merge the pull request.

**Comment by CarlPoirier** [comment]
As for the shape of the symbols, you could use the triangle with more pins such as the LM733CH (which needs fixing BTW).

**Comment by diggit** [comment]
Everything should be Ok now. A lot of conflicts were spacing inconsistencies. Probably some changes in KiCad's library formating.

**Pull request merged**
