### PR TITLE
Add 3d models of 6x6mm² buttons with different heights

### PR DESCRIPTION
**Pull request by jkriege2**
added 3D models for 6x6mm² tactile buttons (PHAP33xx) with different heights. They are all the same, but point to different 3D modules.
see http://nal.apem.com/pdf/phap33-series.pdf

phap1
phap13

### CODE REVIEW

**Comment by diggit** [comment]
Neat! Can you tweak material properties to make plastic look like plastic and same for metal?

**Comment by jkriege2** [comment]
btn

**Comment by jkriege2** [comment]
- button rounded now
- materials changed
- all created from one FCStd-file


btn1
btn2
btn

**Comment by jkriege2** [comment]
Can be merged?

**Comment by jkriege2** [comment]
@diggit : As for the TO-18 packages (see https://github.com/KiCad/kicad-library/pull/734) I also added the STEP models here ... Can be merged?

best,
JAN

**Comment by diggit** [comment]
I've spotted 2 problems:
- origin placement - FP(SW_PUSH_6mm) has it on top left pin, but your models have it on bottom left. (looking from top)
- Step models have correct scale, but wrl not. Did you change something between exports or is it behavior of kicad? (maybe step carries dimension units and kicad developers used it to fix mm/inch scaling problems)

**Comment by jkriege2** [comment]
The origin I can fix, but as far as I know the dimensions are a KiCAD export problem, as there are no explicit dimensions in vrml.
JAN

**Comment by diggit** [comment]
Ok then, just fix origin.

STEP models are future. I hope, that kicad nightlies are built with support turned on.

**Comment by jkriege2** [comment]
OK, Origin fixed ... + footprints modified accordingly

JAN

**Comment by diggit** [comment]
Did you set material properties? Metal parts does not look shiny. Freecad project says, default.
Can you make them look like plastic and metal? (steel)
Sorry that I didn't spot it earlier. I just saw some correctly set model next to this a realized it.

**Comment by jkriege2** [comment]
Actually ... yes, I set it to Silver, which has a shinyness of 20% in FreeCAD ... choosing Steel makes them even darker, so for me they look OK ... the plastic parts have the properties of plastic (although Freecad resets the choosen material to default every time, but keeps the properties themselves ... Bit strange, but in all they should be fine.

**Comment by jkriege2** [comment]
@SchrodingersGat @pointhi Could you have a look at this one? Would be great if it was still in the tag! It is (IMHO) complete!

If you do, please also merge: https://github.com/KiCad/Buttons_Switches_THT.pretty/pull/10

best,
JAN

**Comment by SchrodingersGat** [comment]
Mergerated

**Pull request merged**
