### PR TITLE
Max17572 max17574

### PR DESCRIPTION
**Pull request by Misca1234**
Re push of the , presumably, abandoned push
https://github.com/KiCad/kicad-library/pull/1338

Push consist of 
MAX 17572
https://datasheets.maximintegrated.com/en/ds/MAX17572.pdf

MAX 17574
https://datasheets.maximintegrated.com/en/ds/MAX17574.pdf

bild

bild

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis errors should be ok

**Comment by sandhan26** [comment]
Hey, just a newbie question. What are these blue texts alongside the pins. What is their importance, adn do i need to implement them in my designs? If yes, how?

**Comment by SchrodingersGat** [comment]
@sandhan26 they are the 'electrical type' of the pin (input / output / power / etc). These are optionally displayed in the symbol editor but are not shown in the schematic.

**Comment by sandhan26** [comment]
Hi, in my designs, i did set the electrical pin type. But i did not find any option to display it on the symbol editor.

**Comment by poeschlr** [comment]
The feature mentioned by oliver is only available in nightly builds.
For stable builds (4.x) the only way to get an overview is by looking at the pin table.

**Comment by Misca1234** [comment]
@sandhan26 
look here 
http://kicad-pcb.org/download/windows/
Under
Nightly Development Builds

Download and use one of those, then you get the blue lines, very helpful for the librarians
you might have to click on the new icon to the left

bild

**Pull request merged**
