### PR TITLE
Adding TPS2042D - dual version of existing quad component

### PR DESCRIPTION
**Pull request by scott-t-wilson**
TPS2042D is the dual version of the TPS2044D Quad power-distribution switch.

This component is a copy of the TPS2044D adjusted for package/pinout.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work, thanks! Please change two things:
1. switch footprint field to invisible
2. (suggestion): maybe move GND-pin to the bottom border of the symbol ... usually power pins are on top (VCC...) or bottom (GND...)

Best,
JAN

**Comment by scott-t-wilson** [comment]
I'm happy to move GND to the bottom, it does make sense. I copied the existing quad part TSP2044, I can move the two new parts, or all three. Let me know if you have a preference.

**Comment by SchrodingersGat** [comment]
Hi @scott-t-wilson  if you are willing to fix the quad part too (if that is what you are asking?) then that would be great :)

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
