### PR TITLE
added footprint filter to SW_E3_SA3216

### PR DESCRIPTION
**Pull request by openelectron**
@jkriege2  As requested.

thanks for your help in getting these parts merged.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

please snure to use a current nightly build of KiCAD, so it does not introduce all the whitespaces ... 

I think the filter should be `SW?PUSH?LCD?E3?SAxxxx*` so it matches different types of separating characters.

Best,
JAN

**Comment by openelectron** [comment]
@jkriege2  sorry this took so long. I missed it.
Rob

**Comment by evanshultz** [comment]
@jkriege2 Would you be available to continue reviewing this PR?

**Comment by openelectron** [comment]
@evanshultz @SchrodingersGat @jkriege2   If there is anything else I can do to get this merged please let me know. I'm about to release some open source designs using these parts so would really appreciate getting it merged.
Thanks
Rob.

**Comment by jkriege2** [comment]
Thanks,
sorry for the long wait!
JAN

**Pull request merged**
