### PR TITLE
Added  Hirose DF12 and DF13 3D files (.wings and .wrl)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Downloaded from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm (under CC)

A .pretty repository for the associated footprints is available here - https://github.com/SchrodingersGat/Connectors_Hirose.pretty

mod_conn_df12
mod_conn_df13

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Same as I commented in your others pull request. Apply KLC to footprints.

**Comment by SchrodingersGat** [comment]
DF13 series of connectors have been fixed, conform to naming convention and rules in KLC check.

DF12 series has been removed (for now) - may add in again later when conforms to KLC

**Comment by SchrodingersGat** [comment]
Refer to .kicad_mod files in https://github.com/SchrodingersGat/Connectors_Hirose.pretty

**Comment by SchrodingersGat** [comment]
I'm going to re-gen these - I'll make use of the 3D models as supplied but rescripting the footprints is easier to meet KLC

**Comment by CarlPoirier** [comment]
Hi @SchrodingersGat ,

I'd like to get this merged. The 3D models don't work as the filenames don't match the ones in the footprints. There is a missing period.

Can you please fix this?

Carl

**Comment by SchrodingersGat** [comment]
@CarlPoirier I have added the period to the filenames as requested. LMK if there's anything else you need. Cheers

**Comment by CarlPoirier** [comment]
Hi Oliver,

Most is not all of the through-hole footprints are not aligned with the 3D model because rule 6.3 is not respected. Can you fix this? I opened the issue here: https://github.com/KiCad/Connectors_Hirose.pretty/issues/9

Also, the Hirose_DF13C-13P-1.25V_13.1.25mm_Straight is missing its footprint, is it normal?

Carl

**Comment by CarlPoirier** [comment]
I'll take care of the aforementioned issue today.

**Comment by CarlPoirier** [comment]
I was mistaken. It's the 3D models that don't match. They will need rotation and offset in Wings3D.

**Pull request merged**
