### PR TITLE
TI LMX9838 Bluetooth 2.0 Module Library Rev#7 Errors Removed

### PR DESCRIPTION
**Pull request by gsgill112**
1. Shifted the lmx9838.wrl file to RF_Modules.3dshapes for consistency of the library
2. TI LMX9838 Bluetooth 2.0 Module Library Rev#7 Errors Rectified 
3. use 0.398000 in 3D Settings -> Shape Scale in X,Y,Z fields and 
    -0.380000     -> Shape offset X
    -0.450000     -> Shape Offset Y
Rest all 0's 

//Guri

### CODE REVIEW

**Comment by poeschlr** [comment]
Did you make any changes to the footprint? If so could you link the pull request here?

Normally we would make the scaling via the wrl file. (Keep the scaling factor in the footprint itself = 1,1,1)
We also create the 3d model in such a way that it is correctly aligned with the footprint. Such that all offset and rotation values can be = 0.
In other words: If you already changed something in the wrl file, it would be a good idea to do correct the legacy errors as well. (Yes this will likely mean you need to change the footprint as well but if i understand it correctly you already made some changes to it.)

Now to the symbol:
Why are your gnd pins power output instead of power input?
Why are all other pins inputs? According to the pin table in the datasheet i would use the following electrical types:

- 32K- should be an output
- TXD should be an output
- RTS# should be an output
- OP4/PG4 should be bidirectional
- PG6 and PG7 should be bidirectional (GPIO)
- XOSCEN should be an output
- SCLK and SFS should be bidirectional
- STD should be an output

**Comment by poeschlr** [comment]
@gsgill112 could you at least take another look at the symbol you added? (Or better at the problems i found with it.)

**Comment by evanshultz** [comment]
@scibi 
I'm reviewing unmerged PRs that add parts to texas.lib. Please advise if you're going to update this PR so it can be merged, or otherwise it will be closed. We'd like to have your contribution added to KiCad's official library, but we need to reduce the number of open PRs. Thank you.

**Comment by scibi** [comment]
@evanshultz I guess you should tag @gsgill112 not me ;)

**Comment by evanshultz** [comment]
Oops! Sorry about that.

@gsgill112 
Please see my message above.

**Comment by evanshultz** [comment]
@gsgill112 I'm going to consider you've abandoned this PR.

**Comment by gsgill112** [comment]
I am sorry, I was out station, and my PC got faulty .
IT will take time for me to re clone the entire library and further work on
the issues. I am yet to setup my pc after repair.  it will definitely take
time till this weekend .

For your Consideration.

Regards,
GS Gill

**Comment by evanshultz** [comment]
@gsgill112 
Thanks for replying. You will see several comments above from May 24. Please start by implementing that feedback. Thank you!

**Comment by gsgill112** [comment]
@evanshultz I have made the above mentioned changes. Pl .
//Guri

**Comment by poeschlr** [comment]
There is no new commit. Did you forget to push it?

**Comment by gsgill112** [comment]
@poeschlr 
1.       Permission to KiCad/kicad-library.git denied to gsgill112.
fatal: unable to access 'https://github.com/KiCad/kicad-library.git/': The requested URL returned error: 403
2.      kicad-library gsgill$ git push origin2
Counting objects: 5635, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1695/1695), done.
error: RPC failed; curl 56 SSLRead() return error -36s/s     
fatal: The remote end hung up unexpectedlyiB | 0 bytes/s   
Writing objects: 100% (5635/5635), 129.54 MiB | 45.00 KiB/s, done.
Total 5635 (delta 4183), reused 5374 (delta 3938)
fatal: The remote end hung up unexpectedly
Everything up-to-date
3.      and Git status shows      --   git status 
On branch master
Your branch is ahead of 'origin/master' by 12 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
 
I have 2 remote one from master origin : KiCad/kicad-library.git 
and second master origin2  : gsgill/kicad-library.git 

any help ?

**Comment by poeschlr** [comment]
You need to push to your personal fork not to the kicad repo. (you used the master branch originally so you need to use the master branch now.)

In other words push to origin not origin2

I googled your error output:
Do you have any firewall setup?
https://confluence.atlassian.com/stashkb/git-clone-fails-error-rpc-failed-result-56-http-code-200-693897332.html
There could also be a problem with buffer sizes
https://confluence.atlassian.com/bitbucketserverkb/git-push-fails-fatal-the-remote-end-hung-up-unexpectedly-779171796.html

You could try to use ssh instead of https (Google how to setup ssh git with your operating system. Here i can only help if you use linux)

**Comment by gsgill112** [comment]
@poeschlr thanks , the links worked. There was some issue with the buffer. 
//Guri

**Comment by poeschlr** [comment]
The symbol looks very nice now.

Regarding the 3d model:
How did you create it? (If it is created in a MCAD tool it would be nice to add a step model as well.)
It is scaled wrong and it is positioned wrong. (our rule is that the 3d model it self needs to be scaled and aligned to the footprint. Without using the scale and offset functions of the footprint.)

Currently our recommended tool-chain is [freecad](https://www.freecadweb.org/) to design the model and [kicad stepup](https://sourceforge.net/projects/kicadstepup/) (freecad extension) to export the model in both step and wrl. This tool-chain creates correctly scaled models with nice color properties.
Freecad can import step files if you already created your model in another MCAD tool. (import the original step and export it with freecad stepup.)

If you have MCAD files, add the source files to the packages3d-source repo and the wrl/step files to the pacakges3d repo. (Only if you can supply step models. If you designed your model in wings we can not use it in the new repo.)

**Comment by gsgill112** [comment]
Hi @poeschlr I had designed the 3D model using freecad to design the model and kicad stepup itself. but apparently after resetting the toolchain kicadStepup has somehow stopped working and is misbehaving !! I am currently re going through the docs.

**Comment by poeschlr** [comment]
@gsgill112 do you still have problems with stepup? maybe @easyw can help. (Just give a more specific problem description.)

You could also add the freecad files to the packages3d-source repo and link this pull request. I could then take a look at the 3d files and help you out.

**Comment by Shackmeister** [comment]
Hi @gsgill112 
PR's for 3D models are no longer being accepted into this repo.
If you would still like to contribute this models, please add a new PR on the new 3D repository which can be found here: https://github.com/KiCad/packages3D

**Pull request closed without merging**
