### PR TITLE
Sensors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added a number of parts to sensors.lib (and some improvements to components already there):

- Added INA28x series of current shunt monitors
- Added MMA856FCR1 accelerometer
- Added information to the INA19x series of parts
- Added the ACS722LLCTR-XXX series of hall effect current sensor ICs from Allegro microsystems

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please (running some tests on the new automatic library symbol checker)

**Comment by ricardocrudo** [comment]
Hello @SchrodingersGat. would be better if you keep the same design used to others INA symbols

**Comment by SchrodingersGat** [comment]
Done.

**Comment by SchrodingersGat** [comment]
Failing checks due to KLC errors in https://github.com/KiCad/kicad-library/pull/370

**Comment by ricardocrudo** [comment]
test this please

**Comment by ricardocrudo** [comment]
@SchrodingersGat please fix INA282 GND pin type. You can use checklib with `--enable-extra` to check this kind of issue.

**Comment by SchrodingersGat** [comment]
Done.

**Comment by ricardocrudo** [comment]
Thank you.

**Pull request merged**
