### PR TITLE
Added Template for Raspberry Pi 40 Pin Models.

### PR DESCRIPTION
**Pull request by ashtonchase**
Reference [Pi Hat Specification](https://github.com/raspberrypi/hats/blob/master/hat-board-mechanical.pdf) for dimensions.

For the mounting hole, I was surprised to not find a mounting hole/screw symbol in the repos already. Let me know if it exists and I missed it.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!
about the MOUNTING_HOLE ... we really don't have one, unless you simply use a 1x1 connector ... As I'm currently working on a huge overhaul of device.lib I proposed your symbol there: https://github.com/KiCad/kicad-library/pull/742 ... If you ask me, it would be good to have such a symbol, but I would make the symbol simpler (not a complete screw, but more a hole-like symbol, as e.g. used here: http://www.fedevel.com/welldoneblog/wp-content/uploads/2016/07/mounting-holes.jpg) ... and maybe I would put the symbol into conn.lib ... But let's wait, what the others say ...

cu
JAN

**Comment by pointhi** [comment]
@ashtonchase, @jkriege2 What about this repository:
https://github.com/KiCad/Mounting_Holes.pretty

**Comment by jkriege2** [comment]
Yes, but there is no schematic symbol (unless you use a simple 1x1 connector) ... THat's what the proposal is about ...
JAN

**Comment by jkriege2** [comment]
PS: Sometimes you want to explicitly connect a mounting hole to say GND ... then this weould be handy + it would be nice to have a symbol for mounting holes/screws that is different from connector or screw_terminal to distinguish them, as they are essentially different things on the PCB ...

**Comment by ashtonchase** [comment]
Just as a note, I am pending the merge of #742, so I can utilize the mounting hole symbols in there before proceeding with this.

**Comment by ashtonchase** [comment]
This has been updated to include the new mounting hole symbols introduced in #742 .

**Comment by CarlPoirier** [comment]
There is a typo in the brd.png. It reads "disiplay" instead of "display".

**Comment by ashtonchase** [comment]
Hi @CarlPoirier, 
I have updated the typo.  Thanks.

**Comment by ashtonchase** [comment]
Hi @jkriege2,  @SchrodingersGat ,

Would either of you mind taking a look at this? It's been sitting out there for quite and feel like the community could really benefit from it given the  great prevalence of the Raspberry Pi.

**Comment by jkriege2** [comment]
Hi1

I'm just having a look. I noted several things:
1. Please use the new socket strip footprints, which have a F.Fab-drawing
2. Shouldn't the socket strip be mounted on the bottom of the board? Pin1 should point inwards and Pin2 outwards/towards the Hat edge!
3. Please check you pinout. Your's is 
2017-02-18 09_45_49-eeschema test _ d__temp_test But if you compare e.g. with https://www.elektronik-kompendium.de/sites/raspberry-pi/1907101.htm you see that pin40 is NOT GND, but 36=GPIO16, 38=GPIO20, 40=GPIO21
4. Geometry seems OK
5. In the `.pro` and `.sch`-files there are libs linked that do not exist on my installation (and are not part of the default libs) and that cause error messages:
```
LibName21=device_BACKUP_1978
LibName22=device_BACKUP_2034
LibName23=device_BASE_1978
LibName24=device_BASE_2034
LibName25=device_LOCAL_1978
LibName26=device_LOCAL_2034
LibName27=device_REMOTE_1978
LibName28=device_REMOTE_2034
```
Please remove them!

best,
JAN

**Comment by ashtonchase** [comment]
Hi @jkriege2, 

I have finally gotten around to updating this. Please review. Thanks. 

-Ashton

**Comment by jkriege2** [comment]
Looks good to me now ... one last thing I saw: It seems your project does not include mechanical.lib, but that is required for the mounting hole symbols. Please add that lib and I can merge!

Thanks,
JAN

**Comment by ashtonchase** [comment]
Hi @jkriege2, 
It has been added. Thank you!
-Ashton

**Comment by jkriege2** [comment]
Thanks for all the work!
JAN

**Pull request merged**
