### PR TITLE
Ltc4414

### PR DESCRIPTION
**Pull request by openelectron**
created LTC4414 in linear.lib

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @openelectron. please make the symbol symmetrical, fix GND pin electrical type and add the NC pins.

**Comment by openelectron** [comment]
I'm not sure what you mean by "make the symbol symmetrical" If it is to do with the pin layout the current layout reflects the way that the IC is used.

I have made the other changes.
Please advise how to resolve the symmetry issue?
Thanks

**Comment by diggit** [comment]
What about much more minimal design? More logical pin arrangement IMO.

- fix pin types
 - Vin - power input
 - STAT - open collector
 - CTL - input
 - GATE - output
- clear datasheet field
- set NC pins invisible
- fix link in documentation
- fix FP filters to `MSOP-*` only

**Comment by openelectron** [comment]
Changes as requested.

Thanks for your help. Hopefully my next components are better.

**Comment by diggit** [comment]
Thanks for changes :)
You forgot to change **CTL** to **Input**.
Set FP field to: **Housings_SSOP:MSOP-8_3x3mm_Pitch0.65mm**
Improve FP filter to: __MSOP\*3x3mm\*Pitch0.65mm\*__
Remove \*.orig files - probably your local backup.
And we are ready to go!

**Comment by openelectron** [comment]
As requested.

**Comment by openelectron** [comment]
Is there anything I can do to help get this merged?

**Comment by diggit** [comment]
Everything is ok. Next time, you can post message, that you made some changes. It triggers email notification. You can get attention by mentioning people you are waiting for, like this: @diggit
Nice work you did!

**Pull request merged**
