### PR TITLE
Added Maxim DS75 schematic symbol 

### PR DESCRIPTION
**Pull request by frogshead**
Maxim DS75 I2C temperature sensor.
 [https://www.maximintegrated.com/en/products/analog/sensors-and-sensor-interface/DS75.html](https://www.maximintegrated.com/en/products/analog/sensors-and-sensor-interface/DS75.html)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @frogshead  can you tell me what version of KiCad you are running? Your addition of a single component has caused a lot of other changes in the library, probably because you are not running the "most recent" version of KiCad...

**Comment by frogshead** [comment]
Hi @SchrodingersGat 
I can't check it at the moment but i am pretty sure it is latest stable 4.0.2 

I wondered those line changes myself too but ignored because lines were mostly rewritten back but  other location...

Should I try to resubmit with changes done with nightly build?

**Comment by SchrodingersGat** [comment]
Yep, resubmitting with the latest nightly would be great, thanks :)

**Comment by hackscribble** [comment]
Hi @frogshead 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
