### PR TITLE
added Espressif library with esp8266EX

### PR DESCRIPTION
**Pull request by sandhan26**
Hi, i have added a new library to hold all Espressif chips. Presently i have added only the esp8266EX integrated Wifi SoC. I will add other SoCs as i explore Kicad and Espressif further.

I have tried to be KLC compliant. I ran the checklib script and fixed all the errors. 

This is my first time contributing in an open source project. Kindly, advise and suggest in case of mistakes and any enhancements.

### CODE REVIEW

**Comment by Misca1234** [comment]
It would be nice if you could provide a screen shoot of the symbol as well

alsom Pin "33", that is the pad below the chip you say it should be GND (and not NC), where does it say in the documentation that the pad under the chip is internally connected to GND ?

**Comment by sandhan26** [comment]
screenshot from 2017-10-01 23-30-34

**Comment by sandhan26** [comment]
screenshot from 2017-10-01 23-30-19

**Comment by Misca1234** [comment]
Place a '~' to the left of the 'E' in 'EXT_RSTB', then you get a line above the text, indicating it is active low

**Comment by sandhan26** [comment]
Pin 7, has CHIP_EN in pin out, whereas in the list CHIP_PU. CHIP_EN is more informative it seems. I don't know exactly what _PU means.

**Comment by sandhan26** [comment]
I think CHIP_PU means Chip pull up

**Comment by Misca1234** [comment]
It might but the common practise is to use the name for the pins given in the pin list even if another pin would be better or more informative.

Also, CHIP_PU is mentioned in the text on atleast 2 places, CHIP_EN is not mentioned anywhere.

But in the en d the librarians have the final say.

**Comment by sandhan26** [comment]
I agree. Thanks for showing me around.

**Comment by SchrodingersGat** [comment]
Hi @sandhan26 this looks great, the only think I can ask is that you capitalize the name of the symbols

e..g `ESP8266` rather than `esp8266`

**Comment by SchrodingersGat** [comment]
Great, thanks :)

**Comment by sandhan26** [comment]
I would be adding few more chips by Espressif. So, i keep the branch alive? I am really not much experienced with github workflow. Kindly advise me on this

**Comment by SchrodingersGat** [comment]
As this one has already been merged, you'll need to start a new branch :)

**Comment by poeschlr** [comment]
To add to the information given by oliver: 
Make sure your new branch starts from the current master state (of the official repo).
For that simply first checkout the master of your fork and most importantly sync itwith the master of the official repo.
Assuming you have the official repo added as upstream and your fork as origin use the following commands: (If you used different names replace them in the commands below.)
1. git checkout master
1. git pull origin/master (optional.)
1. git pull upstream/master
1. git push

**Pull request merged**
