### PR TITLE
Added ATMEL SAML21E,G,J parts

### PR DESCRIPTION
**Pull request by DerekGn**
This PR adds the SAML21 series of arm cortex m0+ microcontrollers and RFSolutions devices

http://www.atmel.com/Images/Atmel-42385-SAM-L21-Datasheet.pdf

Files changed:
 atmel.lib
 •Added MAX6100 symbol with multiple aliases

atmel.dcm
 •Added description for each SAML21 ALIAS

Files added:
RFSolutions.dcm
RFSolutions.lib

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi please fix conflicts in this PR (merge kicad/master back in)

**Comment by DerekGn** [comment]
Hi I have resolved the conflicts

**Comment by DerekGn** [comment]
fixed merge and ci issues

**Comment by SchrodingersGat** [comment]
Hi @DerekGn there are still merge issues it seems?

**Comment by DerekGn** [comment]
I have merged the changes again from master.

Now a symbol AVR-JTAG-10 is being reported as violating rule see here https://travis-ci.org/KiCad/kicad-library/builds/212088650

My previous merge 12 days ago did not have this issue https://travis-ci.org/KiCad/kicad-library/builds/207955662

As of this post there are no merge conflicts, like last time I merged.

merge

The issue with the AVR-JTAG-10 is in master branch.

At this point it feels like I am shooting at a moving target.

**Comment by SchrodingersGat** [comment]
Hi @DerekGn - some issues below:

For the RF parts, please arrange GND pins at bottom and PWR Pins at top, as so:

layour

Also, you have changed AVD-PDI-6 to AVR-PUDI-6 in atmel.lib but no changes have been made to this symbol in ateml.dcm

1. What is the reason for this change?
1. This change also needs to be reflected in the .dcm file

**Comment by DerekGn** [comment]
Hi @SchrodingersGat 

I have modified the ZETA part to move the power and ground pins.

I didnt change AVD-PDI-6 to AVR-PUDI-6, I merged the change in master back in to my changes so they can be merged WO conflict.

If you check the history of atmel.lib you will see that the change by @EvansMike, on the 13 Oct 2016, added an additional white space to the pin definition see line 10688 of this change https://github.com/KiCad/kicad-library/commit/e77022671ea3442786dbee836b4e9b6c78676500#diff-2499a520da5039337a7a1973a36b24e5

On the Mar 5, 2017 you removed the extra whitespace from the symbols mentioned, see line 10688 of change to atmel.lib here https://github.com/KiCad/kicad-library/commit/9f3648ac9c6d142cb3363bf3427e14ba283362f5#diff-2499a520da5039337a7a1973a36b24e5

**Comment by SchrodingersGat** [comment]
It appears that the .dcm file has been changed in the master branch since you branched this one off. In that case, I think this should be OK..

Thanks for the contribution :)

**Pull request merged**
