### PR TITLE
Kcsa02 kcsc02

### PR DESCRIPTION
**Pull request by Misca1234**
Update of KCSA02-XXX and KCSC02-105

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1468

Displays.pretty push branch is
https://github.com/KiCad/Displays_7-Segment.pretty/pull/12

Displays_7-Segment.3dshapes push branch is
https://github.com/KiCad/packages3D/pull/103

packages3D-source push branch is
https://github.com/KiCad/packages3D-source/pull/34

KCSC02-105 Hyper Red 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSC02-105(Ver.9A).pdf

KCSC02-106  Super Bright Orange 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSC02-106(Ver.10A).pdf

KCSC02-107 Super Bright Yellow 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSC02-107(Ver.9A).pdf

KCSC02-123 Green 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSC02-123(Ver.10A).pdf

KCSC02-136 Blue 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSC02-136(Ver.6B).pdf

KCSA02-105 Hyper Red 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSA02-105(Ver.10A).pdf

KCSA02-106 Super Bright Orange 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSA02-106(Ver.11A).pdf

KCSA02-107 Super Bright Yellow 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSA02-107(Ver.10A).pdf

KCSA02-123 Green 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSA02-123(Ver.9A).pdf

KCSA02-136 Blue 
http://www.kingbright.com/attachments/file/psearch/000/00/00/KCSA02-136(Ver.7B).pdf

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Move the symbols up by 100mil to center it along y.
Otherwise everything is ok.

**Comment by Misca1234** [comment]
Fixed

**Comment by Schlumpf** [comment]
Hi,
what's about stacking the multible CC and CA pins?

**Comment by poeschlr** [comment]
The user can rotate the symbol if they wish to.
The reason why the pins are on the left/right is for consistency with the rest of the lib.

Stacking might be a possibility but i don't think the symbols would be a lot better for that. (The clutter is not that large to begin with and with the current way it is clear to the user that there are two pins.)

**Comment by poeschlr** [comment]
Thanks for this contribution

**Pull request merged**
