### PR TITLE
Added several missing ADCs and DACs

### PR DESCRIPTION
**Pull request by jkriege2**
ADCs:
- [x] MCP3301
- [x] MCP3004
- [x] MCP3422
- [x] MCP3423
- [x] MCP3424

DACs:
**MCP48x2**
- [x] MCP4802
- [x] MCP4812
- [x] MCP4822

**MCP49x2**
- [x] MCP4902
- [x] MCP4912
- [x] MCP4922

**MCP48x1**
- [x] MCP4801
- [x] MCP4811
- [x] MCP4821

**MCP49x1**
- [x] MCP4901
- [x] MCP4911
- [x] MCP4921

**LTC**
- [x] LTC1446
- [x] LTC1446L

adcdac

### CODE REVIEW

**Comment by jkriege2** [comment]
all components conform to KLC

**Comment by jkriege2** [comment]
changed outler line thickness to the standard 0.01"

Ready to merge?

**Comment by jkriege2** [comment]
@pointhi / @SchrodingersGat / @diggit : could you have a look at this?

**Comment by diggit** [comment]
Take a look on:
- missing (omitted) NC pins
- FP filters
- wrong DSH links (they are mixed up)

**Comment by jkriege2** [comment]
should be fixed now ... could you double-check?
Thanks,
JAN

**Comment by diggit** [comment]
**DACs**
- add 1CH, 2CH, 4CH,... to keywords accordingly
- DFN 1EP is "N+1pin" FP, this is not matching symbol, remove it from filters
 (eg. MCP4921 already exists in FP specific variannts)
- I'd prefer to have same symbol for 2 and 1 channel versions, 1ch. version will be just missing second channel, but that is probably only my opinion

**MCP49x2**
- ~LDAC is input

**LTC1446**
- ~CS is ~CS~/LD, LD reminds, that data are loaded on log. H

**MCP3301**
- ~CS is ~CS~/SHDN ...^^
- no MSOP version exist

**MCP3004**
- ~CS is ~CS~/SHDN ...^^

__MCP34\*\*__
- swapped power pins!

Delta character in description and KW crippled, delta as word is enough. Nobody will search for delta by its' character...


Symbols are not matching pin names with datasheet.

| symbol | dsh |
| -------- | ---- |
| GND | Vss |
|SDI|Din|
|SDO|Dout|
|SCK|CLK|

I don't see it as problem, but more opinions needed.

**Comment by jkriege2** [comment]
Hi!

Thanks for the detailed review ... I hope I caught all errors and fixed them properly. Please have a second look!

Thanks already,
JAN

PS: For the DFN-packages, I added additional symbols that have the 9th pin.

**Comment by jkriege2** [comment]
@SchrodingersGat @pointhi Could you have a look at this one? Would be great if it was still in the tag!

best,
JAN

**Comment by jkriege2** [comment]
anything needs to be changed here?

**Comment by SchrodingersGat** [comment]
Jan can you fix conflicts so I can check? :)

**Comment by jkriege2** [comment]
can do this evening. 
JAN

**Comment by jkriege2** [comment]
fixed! Please review ;-)

**Comment by jkriege2** [comment]
@SchrodingersGat Do you have time for this one?

**Comment by SchrodingersGat** [comment]
This is some great work, thanks for the additions :)

**Pull request merged**
