### PR TITLE
Add Atmel SAMD21G18A-A and aliases

### PR DESCRIPTION
**Pull request by pointhi**
http://www.atmel.com/Images/Atmel-42181-SAM-D21_Datasheet.pdf

Based on the SAMD21G14A-A with some minor changes to the pin attributes (there were pretty minor like adding additional interfaces. Pin names didn't changed at all)

samd21g18a-a

### CODE REVIEW

**Comment by jkriege2** [comment]
looks good to me ...
JAN

**Comment by jkriege2** [comment]
... except footprint-name:
```
Violating Rule 3.9
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint field 'TQFP48' should be set to invisible.
    Footprint field 'TQFP48' should be of the format Library:Footprint
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -2050, posy 1650, recommended posx -400, posy 1725
    field: reference, justification C, recommended R
    field: name, posx 1800, posy -1650, recommended posx -400, posy 1650
    field: name, justification C, recommended R
    field: footprint, posx 0, posy -1150, recommended posx 250, posy -1650
    field: footprint, justification C, recommended L
```

**Comment by hackscribble** [comment]
Hi @pointhi 

Sorry this PR got forgotten.  If you would still like to contribute the symbol, could you please rebase, or open a new PR based on latest master.

Many thanks

**Comment by poeschlr** [comment]
It might be a good idea to shorten the pin names. Maybe only use the port names. (Similar to how the symbols in  the nxp_armcpu library look like.)

**Comment by SchrodingersGat** [comment]
As we are now close to moving all the symbols to the new kicad-symbols repository, this PR will have to be reissued at https://github.com/kicad/kicad-symbols

Thanks for your contributions, and sorry for the inconvenience

**Pull request closed without merging**
