### PR TITLE
Final stage of linear library cleanup

### PR DESCRIPTION
**Pull request by evanshultz**
As mentioned at https://github.com/KiCad/kicad-library/pull/1437, here is the resolution of the "graphical issues". A list:
- AD620/AD623/LM311/LMC555*/LT1011: Pin text overlapping body
- AD8236/8421/8422/8429: Ref pin length could be longer to match Vs- pin
- AD8610/LF15x/LF25x/LF35x/LM741/LT1363/OP07/OP77/OPA134/TL061/TL071/TL081: Shrink NC pin length
- ADA4807-2ACP/MCP603-xCH/TLC555*: Crash between text and pin
- CA3080/CA3080A/L272D/LF398_DIP8/LF398_SOIC8/LM318J/LM319/LM6171/LM6361/LT1493/LTC4414/LTC6082*/MAX4080*/MAX423xASA/MCP601-xP/MCP601-xS*/MCP603-xP/MCP603-xS*/MCP6L91RT-EMS/MCP6L91RT-ESN/MIC845*/OPA333xxD/OPA340P/OPA340UA/OPA376xxD/OPA4340EA/THS4631D/TSV911IDT: NC pins floating away from symbol body or outside symbol body
- INA19x: Text crashing inside and outside symbol body
- INA28x/LM4250: Triangle is unnecessarily bigger than others
- L272: Mismatched GND pin lengths
- LM318*: Pins point to the right instead of up/down
- LM6321*: Pins turned around and floating away from body
- OPA2691-14: Pins in a row with unmatched length

Also, I found [LMV331](http://www.ti.com/lit/ds/symlink/lmv331.pdf) in my local library which I hadn't included, so I added it here.

@SchrodingersGat You reviewed and merged the big PR for this lib. Do you mind doing this one? Certainly anyone else would be welcome to review and/or merge as well.

### CODE REVIEW

**Comment by evanshultz** [comment]
Hmmm... will need to resolve errors before merge. Sorry about that. Hang on...

**Comment by SchrodingersGat** [comment]
Thanks :) I'm away for the weekend, if this hasn't been merged by Tuesday I'll take a look.

**Comment by evanshultz** [comment]
Corrected the errors present, but LM331 and LM339 have open emitter pins named `Gnd`, which causes a KLC violation. But that's fine.

I also added the other parts in the LMV331 datasheet.

**Comment by evanshultz** [comment]
Another pile of polish:
- Changed a few part outlines to 10mil where they were 0mil
- Found a few more NC pins outside the symbol body
- Shifted text on a few symbols to avoid overlapping
- Fixed LM4250 pin 4 length
- Shrunk INA327/LTC6082*
- OPA2695xRGT: Found and fixed stacked NC pins

**Comment by evanshultz** [comment]
- Fixed LTC6362xDD pin type
- Changed pin text offset to <=20mil for most triangle opamp shapes for better readability and consistency
- Updated CA3080 symbol to use visible pin names

@SchrodingersGat (and/or anyone else) Ready for review! The remaining KLC violations are OK and discussed at #1081 if you really want to go digging.

**Comment by evanshultz** [comment]
@SchrodingersGat Now that you're back, are you able to review and merge this?

**Comment by SchrodingersGat** [comment]
> Now that you're back

I haven't actually left yet! I was hoping for a few days of peace before actually leaving on holiday, but well, here we are...

Is this due to your changes?
image

**Comment by SchrodingersGat** [comment]
The graphical improvements look very good, pending the LM?93 error above

**Comment by evanshultz** [comment]
Fixed now. I removed the high-temp versions leaving only LM393, but forgot to strike them from the DCM.

https://github.com/KiCad/kicad-library-utils/issues/133 was based on things like this. It's easy (for me, anyway) to lose track with a big change. I'm not sure where you found this because I don't see any errors with the scripts or when loading the lib into KiCad.

**Comment by SchrodingersGat** [comment]
Thanks for the fix. The linked issue certainly requires further attention.

**Pull request merged**
