### PR TITLE
Add 3D model for DIP-32_W7.62

### PR DESCRIPTION
**Pull request by patricklaf**
Package used by UM61512AK SRAM and may be others components.

### CODE REVIEW

**Comment by Shackmeister** [comment]
Hello what modeling software did you use to make this model? I would highly recommend to use the DIP model generator which can be found here: https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/DIP_packages

This will generate a 1/2.54 scaled WRL file with proper material properties and a 1:1 step file which is used for mechanical integration.
Both the wrl and step file should be added here and to the packages3d repo (https://github.com/KiCad/packages3D)
Don't hesitate to ask if you have any questions :)

**Comment by patricklaf** [comment]
Hi @Shackmeister,
I used Notepad++, starting from DIP-32_15.24mm.wrl and another file DIP-XX_7.62mm.wrl to get the correct widths. Not the best way, but it worked :-)
I use KiCad nightly and there is not the script generated wrl and step files in ${KISYS3DMOD}\modules\packages3d\Housings_DIP.3dshapes.
BTW I can do a pull request to [https://github.com/easyw/kicad-3d-models-in-freecad/blob/master/cadquery/FCAD_script_generator/DIP_packages/main_generator.py](url) to add the parameters for this DIP package, so it could be automatically generated and later appears in nightly.
What do you think about this?

**Comment by Shackmeister** [comment]
Nightly doesn't automatically update libraries.. And you should make a PR for that repo but it doesnt automatically generate it, you should do that :) 
So, add the parameters in cq_parameters. 
Generate the step and Wrl. 
Add a PR here, the generator repo and the packages3d

**Comment by patricklaf** [comment]
Thanks for your help. Almost done. Why should I need a new PR here?

**Comment by Shackmeister** [comment]
Well you should change the files in this PR :)

**Comment by patricklaf** [comment]
Hi @Shackmeister,
It's done.

**Comment by Shackmeister** [comment]
Nice, can you please provide a Screenshot of the model in the kicad 3D viewer? This way the librarians can quite quickly check if it looks fine and fits on the footprint :)

**Comment by patricklaf** [comment]
image

**Comment by Shackmeister** [comment]
Looks very nice, should be merged in no time :) 
If you havent, you should also check out all the other 3D generator scripts at the repo :)

**Comment by Shackmeister** [comment]
Merged
nice work :)

**Pull request merged**
