### PR TITLE
Create microchip_dspic33dsc.lib

### PR DESCRIPTION
**Pull request by El3ctr0nic**
Michrochip 16-bit Digital Signal Controllers

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Please create `.dcm` file with documentation.

**Comment by El3ctr0nic** [comment]
Ok.
It's my first time on github. I need to lern fiev things ;]

**Comment by El3ctr0nic** [comment]
I pushed .dcm file. Hope that no screw up nothing ;]

**Comment by keruseykaryu** [comment]
I'm merging your commit. Minor and not important issues I have fix ASAP.

**Comment by El3ctr0nic** [comment]
Thank You. I have more interresting library but im newbie on git so be patient ;].
Please let me know about all my erreors 9i fix it ASAP.
I'm glad to I can help You.
Sorry for my English its not my primary language
regards

**Comment by keruseykaryu** [comment]
> I'm glad to I can help You.

You didn't help me. You did help us.

> Sorry for my English its not my primary language

Mine too. After 10 years of self-teaching I still have serious problems. :(

**Pull request merged**
