### PR TITLE
(HELP) The modified library Maxim according to the rules KLC

### PR DESCRIPTION
**Pull request by PiotrCzCc**
Please Help - What is wrong.
I still receives non-compliance with 3.8 "Description and keywords properties contain the relevant information."

### CODE REVIEW

**Comment by pointhi** [comment]
Thats likely a bug in the CI-system. Use kicad-library-utils to check them manually against KLC

**Comment by PiotrCzCc** [comment]
I verified by the library "kicad-library-utils". Verification has been successfully and do not contain errors. How do I add them to the repository?

When this error will be corrected? Many people try to add changes and can not do. Is it not a pity to lose enthusiasm of people?

Regards

**Comment by reportingsjr** [comment]
I'll try to debug this, it may be a little noisy, sorry!

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
*thumbs up*

The issue seems to be that some of the files have \r (return carriage) and was causing the script to fail. Fixed!

**Comment by PiotrCzCc** [comment]
Jon, good job, thanks.
I will test with further changes

**Comment by PiotrCzCc** [comment]
Maxim lib is ready for evaluation.
Please enable changes.

**Comment by Fat-Zer** [comment]
You created a copy of library in root with last commit...

**Comment by PiotrCzCc** [comment]
I don't know what you mean. I'm just starting to play with github. I approve all changes on my fork.
If I do something wrong, please for a brief explanation.

**Comment by Fat-Zer** [comment]
Your last commit includes maxim.dcm in the root directory of the file structure instead of library/maxim.dcm. You are likely missaved it to a wrong directory...

**Comment by PiotrCzCc** [comment]
corrected - files is transferred.

**Comment by hackscribble** [comment]
Hi @PiotrCzCc 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
