### PR TITLE
Dc dc

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added some switching dc-dc regulators

Microchip:
MCP16311
MCP16322

Linear
LTC3630 (accidentally commented as 'LM3630' in commit messsage)

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Oliver, please just fix electrical type of Vcc pin.

**Comment by SchrodingersGat** [comment]
Which device @ricardocrudo ?

**Comment by SchrodingersGat** [comment]
Done

**Comment by SchrodingersGat** [comment]
Conflicts have been resolved

**Comment by SchrodingersGat** [comment]
@ricardocrudo any input as to anything I can change to get this merged? :) thanks

**Comment by diggit** [comment]
@SchrodingersGat You broke MAX777 in c10b26f0dc67e9b0cf980ce06894465a4a3e8234 in dc-dc.lib,
please fix it.

In case you wan to see this change...
`git diff c10b26f0dc67e9b0cf980ce06894465a4a3e8234^ c10b26f0dc67e9b0cf980ce06894465a4a3e8234 library/dc-dc.lib` and find MAX777

**Comment by SchrodingersGat** [comment]
@diggit  thanks for pointing this out. I've unbroken it and made some improvements.

**Comment by SchrodingersGat** [comment]
see https://github.com/KiCad/kicad-library/pull/441

**Pull request merged**
