### PR TITLE
Add FAN7842 mosfet driver

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by crackerizer** [comment]
Something went wrong with previous commit. It's fixed in this one.

**Comment by jkriege2** [comment]
Hi I ran our tools to check KLC issues, output is:

D:\KiCAD\kicad-library-review\library>..\..\kicad-library-utils\schlib\checklib.py -vv --enable-extra Power_Management.lib -p FAN7842
checking component: FAN7842
```
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx 0, posy 350, recommended posx 0, posy 425
    field: name, posx 0, posy -250, recommended posx 0, posy 350
    field: footprint, posx 0, posy 0, recommended posx 0, posy -250
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10
    Component background filled with TRANSPARENT color, recommended is BACKGROUND color
```

So could you do the following:
- set package to `Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm` (this device only has one package)
- set footprint filter to `SOIC*3.9x4.9mm*Pitch1.27mm*`
- change outline thickness to 0.01" and color to background
- I would suggest to reorganize the IC to match the functional diagram inFig2 of the datasheet (just a proposal ...): 
fanpm


Here's a proposal (just paste into the -lib-file):
```
#
# FAN7842
#
DEF FAN7842 U 0 40 Y Y 1 F N
F0 "U" 0 400 50 H V C CNN
F1 "FAN7842" 0 -400 50 H V C CNN
F2 "Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm" 0 -500 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 SOIC*3.9x4.9mm*Pitch1.27mm*
$ENDFPLIST
DRAW
S -200 350 200 -350 0 1 10 f
X VCC 1 300 -100 100 L 50 50 1 1 W
X HIN 2 -300 200 100 R 50 50 1 1 I
X LIN 3 -300 -200 100 R 50 50 1 1 I
X COM 4 300 -300 100 L 50 50 1 1 W
X LO 5 300 -200 100 L 50 50 1 1 O
X VS 6 300 100 100 L 50 50 1 1 O
X HO 7 300 200 100 L 50 50 1 1 O
X VB 8 300 300 100 L 50 50 1 1 W
ENDDRAW
ENDDEF
```

best,
JAN

**Comment by crackerizer** [comment]
Hi JAN, the part has changed accordingly.

**Comment by jkriege2** [comment]
Thanks,
could you please set the PDF directly as atasheet, i.e. `https://www.fairchildsemi.com/datasheets/FA/FAN7842.pdf`

JAN

**Comment by crackerizer** [comment]
Done

**Pull request merged**
