### PR TITLE
4047

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: 4047
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
checking component: 4056
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
Components Added: 2
+ 4047
+ 4056
```

**Comment by piotr-wiszowaty** [comment]
Is compliance with extra KLC rules required for accepting a pull request?

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by piotr-wiszowaty** [comment]
Symbol updated.

**Comment by hackscribble** [comment]
Hi @piotr-wiszowaty 

These comments apply to this PR and also https://github.com/KiCad/kicad-library/pull/695

I can see that you updated both symbols in line with latest KLC - thank you for that.  There are conflicts with the master branch after the merge just now of the symbol for 4056.

Maybe the quickest way to fix this would be to export both symbols from your feature branch (export button in symbol editor), create a new feature branch off latest master, import the two symbols and open a new PR that covers both of them.  That should give just the changes to add the two new symbols.

**Comment by piotr-wiszowaty** [comment]
#688 + #695 done.

**Comment by piotr-wiszowaty** [comment]
Moved to a fresh feature branch.

**Pull request closed without merging**
