### PR TITLE
adding BAT54A to diode lib

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Please make the symbol look like the generic symbol from `device.lib`:
2017-01-31 21_27_41-part library editor d__kicad_kicad-library-review_library_device lib

**Comment by jeromebeguin** [comment]
I've made the De Morgan symbol already isn't that enough ?

**Comment by jkriege2** [comment]
We usually don't use the De Morgan ... only for logic symbols and there for the DeMorgan equivalent!

Please don't use deMorgan here and Change the Symbol as requested. THanks!
JAN

**Comment by jkriege2** [comment]
OK!

one last change:
Please add the line that goes (horizontally) through the diodes' triangle (as in the image above)

JAN

**Comment by jkriege2** [comment]
thanks,
JAN

**Pull request merged**
