### PR TITLE
RF: Add MM002, TD1205, TD1208, iM880A, iM880B

### PR DESCRIPTION
**Pull request by myfreescalewebpage**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @myfreescalewebpage please fix branch conflicts and we can proceed :)

**Comment by myfreescalewebpage** [comment]
Done.

**Comment by SchrodingersGat** [comment]
iM880A
* Change "NC" pins to not-connect type and set to insivible

TD1208:
* Change name of P23 to "RF GND"
* Change name of P25 to "RF GND"

Looks good otherwise

**Comment by myfreescalewebpage** [comment]
Thanks for your review.
Done.

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
