### PR TITLE
reworked power.lib

### PR DESCRIPTION
**Pull request by jkriege2**
- fixed KLC-issues (mainly docu)
- added some missing symbols
- requires new KLC-additions from this: https://github.com/KiCad/kicad-library/issues/1287 ... and the check-scripts that go with it: https://github.com/KiCad/kicad-library-utils/pull/126
- one error remain:
```
Checking symbol 'PWR_FLAG':
  Violating Rule 4.13 - Power flag symbols
    Power-flag symbols follow some special rules/KLC-exceptions
    The pin in power-flag symbols has to be INVISIBLE
    The pin name (pwr) in power-flag symbols has to be the same as the component
 name (PWR_FLAG)
```
As I understand this is some special symbol: This is the only symbol with VISIBLE pin (PWR-OUT) ... does anybody know whether this has to stay as that? If so, we leave it. Otherwise I would be happy to change the pin visiblility ...

Best,
JAN

### CODE REVIEW

**Comment by poeschlr** [comment]
The pin of the power flag needs to be power output but i think it could be invisible as well.

**Comment by jkriege2** [comment]
Do you know what this symbol is used for?

Best,
JAN

**Comment by poeschlr** [comment]
Yes to get the nasty erc warnings to go away if you have no power output pin on a net where at least one power input pin is located.

An example would be the connector that supplies your pcb.
Or if you have a passive component in series to your dc/dc converter. (A fuse, the inductance of a lc filter, ....)
With this power flag you tell erc: i promise this net has a connection to a supply.

**Comment by evanshultz** [comment]
Doesn't the pin need to be visible?

I agree with Rene to leave it as is. Any change to this would need to be thoroughly tested since it's critical for making the ERC system work. I expect we all have loads of example circuits to test; I'm pretty sure every KiCad design I've done uses this symbol.

**Comment by SchrodingersGat** [comment]
Agreed, we definitely should not change the POWER_FLAG symbol! Even if it breaks KLC it is a very special case.

**Comment by jkriege2** [comment]
Then this PR should be ready to merge (Errors will go away, once https://github.com/KiCad/kicad-library-utils/pull/126 has been merged.

Best,
JAN

**Comment by poeschlr** [comment]
Do you want to use this as a testcase for the library utils pull request or can this be merged?

**Comment by jkriege2** [comment]
I tested it locally with the new scripts and they worked for me (all green, except PWR_FLAG) ... so IMHO it can be merged also before the PR for the utils, But @SchrodingersGat : Do you need this PR to counter-check the utils-PR?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan

**Pull request merged**
