### PR TITLE
Improvements to Power_Management library

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR improves a number of existing components in Power_Management.lib, adds a lot of new ones, and adds a Power_Management.dcm file

**Power_Management.lib**
* Fixed package referenced for LM5051
* Fixed symbol for LM5051
* Added multiple power-management parts

**Power_Management.dcm** *(new file)*
* Added .dcm file
* Added descriptions for already-existing parts
* Added descriptions for all new parts

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Fairly large number of new components and improvements here. @ashtonchase @CarlPoirier  @ricardocrudo anyone want to take a look?

**Comment by SchrodingersGat** [comment]
Bump.. @ashtonchase @diggit  want to take a look?

**Comment by diggit** [comment]
Ok, I'm on it!

- __MIC2026\*__
 - why so wide?
- __MCP141\*__
 - fix FP field
- __LTC4440\*__
 - pin 2 (GND), wrong el. type (input) -> power input
 - shift 100mil left to center the symbol 
 - __LTC4440EMS8__
   - fix FP filter, match dimensions and pitch `MSOP*1EP*3x3mm*Pitch0.65mm*`
- __LTC4365\*__
 - shift 100mil up to center the symbol
 - GND on bottom side is prefered
 - wrong el. pin types
   - Vout: power output -> input
   - ~FAULT: input -> open collector
   - ~GATE: input -> output
 - __LTC4365TS8__
   - you can set FP filter to `*SOT-23*`, it should work in future
 - __LTC4365DDB__
   - we have it's FP in libraries `Housings_DFN_QFN:DFN-8-1EP_2x3mm_Pitch0.5mm`, and that implies FP filter `DFN*1EP*2x3mm*Pitch0.5mm*`
- __LTC4364\*__
 - wrong el. pin types:
   - ENOUT: input -> open collector
   - ~FLT: input -> open collector
 - __LTC4364CMS__
   - edit FP filter to match only necessary parts: `MSOP*3x4mm*Pitch0.5mm*`
 - __LTC4364CDE__
   - edit FP filter to match only necessary parts: `DFN*3x4mm*Pitch0.5mm*`
- __LTC4359-MS8__
 - package info to description
 -  you can prefill FP filter `MSOP*3x3mm*Pitch0.65mm*`
- __LTC4357MS8__
 - you can prefill FP filter `MSOP*3x3mm*Pitch0.65mm*`
- __LTC4357DCB__
 - you can prefill FP filter `DFN*1EP*3x2mm*Pitch0.5mm*`
- __LT1641-1__
 - wrong el. pin types:
   - PWRGD: output -> open collector
 - default FP: `Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm`
 - fix FP filter to allow SOIC only (now it matches SOIJ too), `SOIC*`
- __LM5060__
 - improve FP filter to match only necessary parts `*SOP*3x3mm*Pitch0.5mm*`

I followed list of edited symbols. Documentation not much checked.
When I used asterisk in symbol name, it meant there are multiple **symbols** affected, I didn't care about aliases now.

Your turn! :D

**Comment by SchrodingersGat** [comment]
Your turn again :)

**Comment by SchrodingersGat** [comment]
@diggit any time you get a chance to look at this again :)

**Comment by SchrodingersGat** [comment]
@pointhi if you get a change, this one should be ok

**Comment by diggit** [comment]
This is gonna be race between other PRs, but can you merge master here too?

**Comment by SchrodingersGat** [comment]
Ok, merged master back in again. Thanks @diggit

**Comment by diggit** [comment]
**LM5051**
- wrong FP (-> Housings_SOIC)
- improve FP filter to match correct size FP

**LM5060**
- nPGD -> ~PGD, open collectror

**LTC1641-1**
- improve FP filter to match correct size FP

**LTC4357DCB, LTC4357MS8**
- Vdd -> Power Input

**LTC4359-DCB, LTC4359-MS8**
- OUT -> Input

**LTC4364CDE**
- duplicated pins (NC - EC05), fix them, (with great power of copying comes great responsibility :)
- pin GATE -> HGATE

**LTC440EMS8, LTC4440ES6**
- pin INP -> input

__MCP-10\*__
- there are 2 to-92 versions with different pinouts, not obvious which is this one

__MCP141[5,6][,R]__ _(4)_
- improve FP filter -> `sot-23*`

__MIC2026-\*__
- wrong dsh link -> `http://ww1.microchip.com/downloads/en/DeviceDoc/mic2026.pdf`
(did Microchip managed to buy Micrel during PR waiting period? :o )

__LTC4365\*__
- indirect dsh link -> use direct links to pdf

You can check them too ;)
checklib found some of them...

**Comment by SchrodingersGat** [comment]
I have fixed all these. LMK if there's anything else required :)

**Comment by diggit** [comment]
Please include pitch in FP filtes for SOIC packages.
I think(hope) that would be all.

**Comment by SchrodingersGat** [comment]
Alrighty, done

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
