### PR TITLE
fixed marker on TO-18 packages (3D models)

### PR DESCRIPTION
**Pull request by jkriege2**
see https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/12 for altered footprints

to182
to183

### CODE REVIEW

**Comment by diggit** [comment]
Thanks, I am confused by dimensions you set. Biggest radius 9.4/2mm ?
That does not match [reference sheet from JEDEC](https://www.jedec.org/sites/default/files/docs/archive/to/to-018.pdf).
Set correct material properties. Can should be from metal, probably steel or chrome.

BTW sou can create all wires from 1 sketch ;)
If you wan to attach FreeCAD project files, I'd prefer fully constrainted sketches or at least constrains on all ref. sheet dimensions.

**Comment by jkriege2** [comment]
Oohhh ... I picked the wrong def (was TO-5 instead of TO-18) ... and I was already wondering, why I had to alter the scaling in the footprint ... Here's the new (also nicer) version:

to183

**Comment by diggit** [comment]
What do you think @SchrodingersGat ? Ok for merge? I am not sure about current 3D models requirements.

**Comment by jkriege2** [comment]
based on the TO-18 3D sketch, I made variants with a window/lens on top for opto-devices.

If you like them, you can merge them with the basic package (https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/12 als contains appropriate footprints!).

to18var

**Comment by jkriege2** [comment]
@diggit @CarlPoirier : OK to merge?

JAN

**Comment by diggit** [comment]
Can you export STEP files too? New KiCAD can use them and even export.

**Comment by jkriege2** [comment]
Hi!

can do ... this evening ;-)

cu
JAN

**Comment by jkriege2** [comment]
OK; I committed the files ... OK like that (e.g. file extensions ...). I fo, I'll also commit STEP-files for my other 3D model commits ...

Best,
JAN

**Comment by jkriege2** [comment]
@diggit: If this is OK; I can also derive 3D models for the larger TO-packages from these ... But first I'll wait until this PR (and this connected one: https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/12) go through ...

JAN

**Pull request merged**
