### PR TITLE
Analog Devices ADP2302/ADP2303 DC/DC Converter

### PR DESCRIPTION
**Pull request by johnfwhitmore**
I have run this component through check_lib.py and am still getting an error on the footprints. I've tried everything I can think of but can't clear the error. The device uses a:
Housings_SOIC:SOIC-8-1EP_3.9x4.9mm_Pitch1.27mm
There are 8 part numbers associated with this part but I've simply called the component an ADP230x

ADP2302ARDZ         2 Amp adjustable
ADP2302ARDZ-2.5   2 Amp 2.5V Output
ADP2302ARDZ-3.3   2 Amp 3.3V Output
ADP2302ARDZ-5.0   2 Amp 5.0V Output

ADP2303ARDZ         3 Amp adjustable
ADP2303ARDZ-2.5   3 Amp 2.5V Output
ADP2303ARDZ-3.3   3 Amp 3.3V Output
ADP2303ARDZ-5.0   3 Amp 5.0V Output

All eight options use the same SOIC-8-1EP device and only differ in output characteristics. If it is felt that all eight part numbers should be in the component library let me know. I decided that I'd keep it clean and be lazy ;-)

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

I'm still on holidays, so you'll have to wait until weekend or next week for a proper review, but from a quick glance, I see the follwoing issues with your PR:
1. please post a screenshot of your new symbols as this will ease review significantly!
2. Did you use an old version of KiCAD to edit the files?? Your version introduced several additional whitepsaces that are not necessary. Please use a recent KiCAD version or a nightly build for editing this PR
3. Please add the variants you list above explicitly, i.e. rename the symbol itself to e.g. ADP2302ARDZ and add all variants (if they don't differ in symbol of course) as ALIASes. Then provide the description for each. Usually we x-out (Wildcard) temperature ranges, but not power-ratings and voltages for voltage regulators/DC-DCs
4. rename the pin for the pad to PADGND (suggestion) so it's clear that this is the PAD
5. The FPFilter should be `SOIC*EP*3.9x4.9mm*Pitch1.27mm*`
6. You changed the footprint of LT1073CN with this PR ... is there a reason for this? If it's an error, please revert that change, if not, please explain: For future PRs, please limit one PR to one device (or family of devices) as that makes review much easier. To achieve this in your GIT-fork of the repo, open a new branch from an updated master for each PR that you post here. This way the PRs are isolated and you can go on with more changes and several parallel PRs!
7. You also added an MCP1825S to dc-dc.lib, which has a wron FPFilter from what I can see. Also this device is a linear regulator which should be in regul.lib. Finally please post a separate PR for that device and remove it from this PR ...

Would be great if you could look after the issues above!

Best and I'll do a more detailed review when I'm back,
JAN

**Comment by jkriege2** [comment]
PS: The one Travis-issues that you should solve is that the GND pins of your device are not on a 100mil, but on a 50mil grid ... please also fix ;-) Thanks,
JAN

**Comment by johnfwhitmore** [comment]
Hi Jan, enjoy the holidays. I'll redo those changes over the next few days,
when I get a chance. I did add the MCP1825 but decided I was being greedy
and would only try add one component at a time.

I never touched the LT component, bit if it's changed, something must have
happened. I might have looked at it but certainly didn't mean to change it.

First attempt to contribute so thank you for you advice. I'm no sure how I
should proceed from here. Can I simply discard that pull request and
refork? I'll have a look through docs and hopefully get back to you next
week. Sort of helping friends move house at the moment so can't see me
getting to computer today or tomorrow.

Thanks again.

John

**Comment by jkriege2** [comment]
Either remove the MCP and other stuff from your trunk, wait until this is merged and  then do your next edits, or we close this, you branch from a clean trunk and add your changes and start a new PR ... its up to you ;-)

**Comment by johnfwhitmore** [comment]
Restart from clean trunk I think

**Comment by jkriege2** [comment]
OK, should we close this then?

Best,
JAN

**Comment by jkriege2** [comment]
PS: Let me know, when you push another PR for this!

**Comment by johnfwhitmore** [comment]
Sorry yes, please close that pull request. I'll get back to it tomorrow. I
have to find out how best to proceed with it, in terms of github, I just
wondered should I delete my pull request, then delete my fork and then
restart again. That's what I want to do but wondered if I could delete a
pull request, or if that would upset the work flow on your side. Similarly
if I didn't delete the pull request but deleted my fork would that leave a
pull request hanging in mid air.

I sort of hoped that I could just checkout the upstream master again and
push that to my fork and simply start again.

Whichever I'll find out best approach, redo my work and resubmit tomorrow.

John

**Comment by jkriege2** [comment]
simply delete your fork and start over. This PR is closed now ... and will be forgotten about ;-)

**Comment by johnfwhitmore** [comment]
Thank you again. Hopefully smoother next time.

**Pull request closed without merging**
