### PR TITLE
Add Digi XBee SMT module

### PR DESCRIPTION
**Pull request by svheymann**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This is great work. I have only one request:

Please change default field position like so:

capture

**Comment by svheymann** [comment]
done. Is there some style rule where to place that fields? Sometimes the partname field is below the symbol, sometimes it is on the upper side but centered and sometimes in the upper left corner like this.

**Comment by SchrodingersGat** [comment]
This is one area in which we need to standardize, there's not really a one-size-fits-all solution to this issue yet.

**Comment by SchrodingersGat** [comment]
Thanks for your contribution.

**Pull request merged**
