### PR TITLE
Added opamp - LMV601

### PR DESCRIPTION
**Pull request by mpkopec**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
HI @mpkopec  this is mostly pretty good, just a couple of small suggestions:

eg

* You can add a default footprint for this part (TO_SOT_Packages_SMD:SC-70-6) as there is only one possible footprint (as per the datasheet)
* Make sure you set the default footprint to "invisible"
* Some additional text in the description
* Center the symbol as per the image

**Comment by mpkopec** [comment]
Thanks for the tips, I'll do that this week probably. By the way, do you know any easy way to refresh a library after changing branches without closing whole KiCad?

**Comment by SchrodingersGat** [comment]
No I don't, it's a real pain! I think that it loads the library afresh when you launch KiCad. However if you find a way to do it please let me know :)

**Comment by mpkopec** [comment]
I'll let you know, ofc! We should create a ticket somewhere to the developers somewhere to put a button 'Refresh libraries' :)

**Comment by SchrodingersGat** [comment]
Thanks for the changes, but you have also added the datasheet to the "datasheet" field. This would seem like a good idea, but if anyone tries to make an ALIAS of this part then the datasheet will follow. Having the datasheet in the part documentation field is enough :) If you revert that single change it's ready to go :)

**Comment by mpkopec** [comment]
Done ;)

**Comment by SchrodingersGat** [comment]
Awesome, thanks :)

**Pull request merged**
