### PR TITLE
STM32: Updated against KiCad Library Convention

### PR DESCRIPTION
**Pull request by MateuszKrawczuk**
STM32F050C4(C6)
STM32F050K4(K6)
STM32F100C4(C6)
STM32F100C8(CB)
STM32F100R4(R6)

### CODE REVIEW

**Comment by keruseykaryu** [comment]
Would you like to make a full modification of the library to meet the KLC rules? 
If so, I can sign-up you to the status table [here](https://github.com/KiCad/kicad-library/wiki/Status-of-the-libraries). This way, no other librarian will adapt this file until you finish.

**Comment by MateuszKrawczuk** [comment]
Yes, I think can do full modification of library. I'm trying make script to do this faster.

**Comment by keruseykaryu** [comment]
You have been subscribed.
This might be interesting for You: https://github.com/ricardocrudo/kicad-utils

**Comment by keruseykaryu** [comment]
Please look here: https://github.com/KiCad/kicad-library/pull/208

**Comment by pointhi** [comment]
I think this PR is not longer useful: #304

**Pull request closed without merging**
