### PR TITLE
Add MCP3002 and MCP3008 ADCs

### PR DESCRIPTION
**Pull request by cedricboudinet**
Here is an integration of two Analog to Digital Converters with SPI from Microchip

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by ricardocrudo** [comment]
hello @cedricboudinet. Could you please make some adjustments? 

* move reference and component name outside of the symbol body
* make pins length at least 100mil shorter
* organize pins logically, instead of pin numbers

**Comment by cedricboudinet** [comment]
Hi @ricardocrudo. I've done the adjustments. Tell me if it's ok for you

**Comment by CarlPoirier** [comment]
Hi @cedricboudinet,

Your arrow shaped for the MCP3002 is not symmetrical. You can also shorten the pins another 100mils for that particular symbol since the numbers don't go over one digit.

Thanks,

Carl

**Comment by cedricboudinet** [comment]
Hi @CarlPoirier. I've done some corrections.

**Comment by CarlPoirier** [comment]
Hi @cedricboudinet,

I have one last requirement to ask. For the MCP3008, please move the reference designator and component name closer to the corners of the rectangle such as with the MCP3002.

I also have an optional change. You could remove 200mils between pin pairs 9-14 and 15-16 so that the whole component is 200mils smaller on the x axis. If you prefer to leave it that way, I will accept it nonetheless.

Thank you,

Carl

**Comment by cedricboudinet** [comment]
Hi again @CarlPoirier 
I've corrected both name placement and component width on mcp3008.

**Comment by CarlPoirier** [comment]
@cedricboudinet You forgot the reference designator. This is the "U?" at the top left corner.

**Comment by cedricboudinet** [comment]
@CarlPoirier : sorry I've been a bit too quick reading your mail. I just corrected it.

**Comment by CarlPoirier** [comment]
It is great now. Thanks for your contribution and feel free to open any new pull requests! :)

**Pull request merged**
