### PR TITLE
Added 'TEST_1P' (single-pin test-point symbol).

### PR DESCRIPTION
**Pull request by madworm**
I was missing a single-pin test point.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Thanks!

**Comment by CarlPoirier** [comment]
I'll merge it this way even though the text size is wrong. I'll work on fixing this on all symbols today.

**Comment by CarlPoirier** [comment]
We'll be able to fix the field text size library-wide with this script:

https://github.com/KiCad/kicad-library-utils/pull/10

**Comment by madworm** [comment]
I copied the test_point from the this library and just removed the 2nd pin + shifted the text around a bit. I assumed the settings were OK.

**Pull request merged**
