### PR TITLE
Dip add suffix sm

### PR DESCRIPTION
**Pull request by Misca1234**
Renamed according to 
https://github.com/KiCad/Housings_DIP.pretty/pull/15

### CODE REVIEW

**Comment by Misca1234** [comment]
I dont know wjy kicad changed in linear.lib
Just before I made the push a made a fresh clone

**Comment by jkriege2** [comment]
Please revert the changes to linear.lib, before I can merge ... these also change the pin-name-relation, as far as I can see, so we really don't want them here ...

Best,
JAN

**Comment by Misca1234** [comment]
Hmm, this pull have three 6 in its name 
d/kicad-library/pull/1666

Must have been the devil himself who was messing

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
