### PR TITLE
add bosch bmf055 9 axis motion sensor

### PR DESCRIPTION
**Pull request by ChristianHirsch**

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by ChristianHirsch** [comment]
@reportingsjr, according to the checklib.py script, I'm violating rule 3.1, but I do not see where.. Can you give me a hint? I applied some visual changes..

**Comment by ChristianHirsch** [comment]
@reportingsjr , found the problem! Fixed all violations. I'm not sure about the footprint filter. Is there a footprint for "28-pin LGA" packages?

**Comment by ChristianHirsch** [comment]
@SchrodingersGat updated footprint list to match with LGA-28 actually it's rdy :)

**Comment by SchrodingersGat** [comment]
Hi @ChristianHirsch a few notes:

**REFDES** Please change the REFDES to U? instead of IC?

**Pin Offset** Please increase the *Pin Name Position Offset* to at least 40, the pin names are too close to the edge of the symbol.

Thanks :)

**Comment by ChristianHirsch** [comment]
Hi @SchrodingersGat , changed the REFDES and the pin name offset :-)

**Comment by SchrodingersGat** [comment]
Great, nice work :)

**Pull request merged**
