### PR TITLE
STM32: Added STM32F030 family

### PR DESCRIPTION
**Pull request by Krakonos**

### CODE REVIEW

**Comment by Krakonos** [comment]
I'm sorry about the move of the S-lines, but that's what current kicad stores.

**Comment by CarlPoirier** [comment]
Hi @Krakonos,

We're looking to add a whole bunch of STM32 here: https://github.com/KiCad/kicad-library/pull/304

**Comment by yaqwsx** [comment]
@CarlPoirier: Shouldn't this PR be closed unmerged, as #304 was already merged?

**Comment by Krakonos** [comment]
It should, all the parts seem to be in #304.

**Pull request closed without merging**
