### PR TITLE
Added MAX2650 LNA

### PR DESCRIPTION
**Pull request by jhol**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @jhol. Please, check [here](http://kicad-pcb.org/contribute/librarians/) to see how to contribute to KiCad library.

**Comment by jhol** [comment]
@ricardocrudo Hi Ricardo, I studied the KLC carefully, and updated the symbol as best I could. Specifically I made the pins 0.050in long, and placed the component on a 0.1in grid. I also added more data to the component fields, and adjusted the text size to 0.05in.

If the component still has deficiencies, would you mind making a brief explanation? I would like to become a productive contributor.

**Comment by jhol** [comment]
Updated once more

**Comment by jhol** [comment]
bump

**Comment by ricardocrudo** [comment]
test this please

**Comment by ricardocrudo** [comment]
Hello @jhol. Here are some changes you can do:
* add keywords and datasheet link (clicking on ABC icon and after selecting Description tab)
* IN and OUT pins can be smaller
* symbol box can be smaller
* adjust texts size
* adjust pin position

you can use checklib script to help you: https://github.com/KiCad/kicad-library-utils/tree/master/schlib

**Comment by hackscribble** [comment]
Hi @jhol 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
