### PR TITLE
added ad9910

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This device has quite a lot of pins, I tried to layout them in a sensible way, input on the left, output on the right. However I am not quite sure if it makes sense to separate the inputs and outputs belonging to one system like I did.

This requires another footprint (TQFP-100 with 1 5x5mm exposed pad), which is not in kicad yet. I'm not sure how to add that one to the library. I have a version here, which is just a copy of the normal TQFP-100 with the pad added.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @lorem-ipsum 

I would suggest adding these components to the "motor_drivers.lib" library as this already exists, rather than creating a manufacturer-specific library for a small number of components.

Also if you have a custom TQFP that you want added, issue a PR here: https://github.com/KiCad/Housings_QFP.pretty

Cheers

**Comment by lorem-ipsum** [comment]
Hi @SchrodingersGat,

the pull request already exists: https://github.com/KiCad/Housings_QFP.pretty/pull/8

Cheers,

**Comment by SchrodingersGat** [comment]
Hi @lorem-ipsum sorry it's taken a while to get back to this. Can you please fix the branch conflicts (you'll need to merge the kicad/master branch back into the ad9910 branch) and we'll go from there.

**Comment by lorem-ipsum** [comment]
took me some time to do the rebasing, by the looks of the CI check now the standards have improved.

**Comment by lorem-ipsum** [comment]
I've adjusted the pin based on the CI checks. Changes are:
 - Use TQFP*14x14mm*Pitch0.5mm* as footprint match
 - Add NC pins to get to the correct pin count of 101
 - Set empty labels to invisible

**Comment by SchrodingersGat** [comment]
Please also set the default footprint field now that the footprint PR has been merged :)

**Comment by SchrodingersGat** [comment]
Please also set the default footprint field now that the footprint PR has been merged :)

**Comment by lorem-ipsum** [comment]
did that and moved the (invisible) text fields back to the centre as there is plenty of space.

**Comment by SchrodingersGat** [comment]
Great, nice work :)

**Pull request merged**
