### PR TITLE
added generic single and twin coaxial connector + removed old BNC

### PR DESCRIPTION
**Pull request by jkriege2**
Currently we have only a simple BNC-connector symbol, but there are more coax-connectors that could use the same symbol. Therefore I created an overworked (nicer) general symbol `CONN_COAXIAL` + a second symbol `CONN_COAXIAL_x2` which can be used for double-connectors, such as this:
http://www.reichelt.de/Cincheinbaubuchsen/CBP-2/3/index.html?&ARTICLE=30027

The symbols have descriptions that also allow to find them when searching for BNC,SMA,SMB,SMC,Cinch,RCA,...

2017-01-27 22_45_53-part library editor d__kicad_test_addlin_ _kicad-library_library_conn lib
2017-01-27 22_45_34-part library editor d__kicad_test_addlin_ _kicad-library_library_conn lib

For reference the old connector:
2017-01-27 20_42_29-part library editor d__kicad_kicad-library-review_library_conn lib

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Jan there is a lot of "noise" in this PR - but this may be due to the conn.lib file not being updated in quite some time, and it has been re-ordered.

Are the CONN_COAXIAL and CONN_COAXIAL_x2 the only changes you have made here?

**Comment by jkriege2** [comment]
Yes they are the only change ... here's a better DIFF:
2017-01-28 13_51_55-library_conn lib_ 32201c8 - tortoisegitmerge
2017-01-28 13_52_26-library_conn lib_ 32201c8 - tortoisegitmerge
2017-01-28 13_53_44-library_conn lib_ 32201c8 - tortoisegitmerge
2017-01-28 13_54_04-library_conn lib_ 32201c8 - tortoisegitmerge

**Comment by jkriege2** [comment]
and of course I removed BNC

**Comment by cvgaviao** [comment]
@jkriege2 , this "noise" seems to be related to some OS invisible characters (/n /r). Mainly caused by a Windows / Linux differences...

**Comment by SchrodingersGat** [comment]
Thanks Jan

**Pull request merged**
