### PR TITLE
Tlpxxx 2

### PR DESCRIPTION
**Pull request by Misca1234**
This push is an update of TLPXXX wich used a foot print called
Toshiba_SOP_Pins13456_4.4x3.6mm_Pitch1.27mm.kicad_mod
Toshiba_SOP_Pins1346_4.4x3.6mm_Pitch1.27mm.kicad_mod

they use now 
MFSOP6-4_4.4x3.6mm_Pitch1.27mm
MFSOP6-5_4.4x3.6mm_Pitch1.27mm

See push for the new foot print update
https://github.com/KiCad/kicad-library/pull/1553

TLP141G does not exist anymore on Toshiba's homepage, 
but I updated it according to the other TLPXXX

All lines in the symbols have been given a width different from zero

The specific foot print field have been removed

The foot print filter have been set to
MFSOP6*4.4x3.6mm*Pitch1.27mm*
MFSOP6-5_4.4x3.6mm_Pitch1.27mm

Links to datasheet have been changed to Toshiba's own home page 
(not for TLP141G wich Tosiba no longer have)

TLP184 is no longer recomended for new design, "TLP184(SE" was added as an alias
TLP185 is no longer recomended for new design, "TLP185(SE" was added as an alias

PS
analog_devices.lib have an error , AD637xQ had itself as an alias
DS

Kicad-library push
https://github.com/KiCad/kicad-library/pull/1554

Opto-Devices.pretty push
https://github.com/KiCad/Opto-Devices.pretty/pull/15

bild

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Looks good, but as all these devices have only one specific package, please set the footprint fields to that footprint!

Best,
JAN

**Comment by jkriege2** [comment]
Also some FPFilters do not seem to end with an asterics `*`. Please fix (see Travis)

**Comment by Misca1234** [comment]
The TLPXXX have specific foot print field and all OK

The travis error concern the VIN pin of the AD637xQ, which is not an error, VIN should be an input

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Comment by evanshultz** [comment]
@misca1234
I noticed the AD637 error too and I'm fixing it in a PR to come soon. Thanks for bringing this up.

**Pull request merged**
