### PR TITLE
Added Molex 90325

### PR DESCRIPTION
**Pull request by Misca1234**
Molex Picoflex PF-50 90325 series

Pins 4 to 26 in step of 2.

http://www.molex.com/pdm_docs/sd/903250004_sd.pdf

The 3D models are created by by scripts
https://github.com/easyw/kicad-3d-models-in-freecad/pull/99

The 3D models and foot prints are named in the following way 
Molex_Picoflex_90325_XXx1.27mm_Straight

Where XX is 04, 06, 08, 10, 12, 14, 16, 18, 20, 22, 24 and 26

kicad-library push branch is
https://github.com/KiCad/kicad-library/pull/1509

pretty push branch is
https://github.com/KiCad/Connectors_Molex.pretty/pull/48

packages3D push branch is
https://github.com/KiCad/packages3D/pull/117

bild

bild

### CODE REVIEW

**Comment by Shackmeister** [comment]
Hey Stefan nice to see you digging in to the cadquery scripts :) they look very nice, ill take a look tomorrow

**Comment by Misca1234** [comment]
Hi, thx yes, connectors are really well suited for the cadquery scripts

**Comment by Misca1234** [comment]
@Shackmeister 
You have not forgot this one ?
"tomorrow" was 18 days ago ;)

**Comment by Shackmeister** [comment]
@Misca1234 I started checking but found some issues with the footprints https://github.com/KiCad/Connectors_Molex.pretty/pull/49 perhaps you forgot them? ;)
Anyway I would like to resolve the footprints before the 3D models :)

**Pull request merged**
