### PR TITLE
adding R_0201 STEP and WRL parametric model

### PR DESCRIPTION
**Pull request by easyw**
models are generated by parametric scripts

https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator

discussion related at
https://forum.kicad.info/t/contributing-to-update-of-vrml-librarys-to-step/5049/

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi! and thanks for the contribution!

I'm not really sure what the advantage over the existing model is? Two come to mind:
1. smaller .wrl-file
2. STEP-file 

Does this sum up the PR correctly?
JAN

NEW:
2017-02-18 18_54_27-3d viewer


OLD:
2017-02-18 18_53_32-3d viewer

**Comment by easyw** [comment]
Hi Jan

> I'm not really sure what the advantage over the existing model is? Two come to mind:
> 
>     smaller .wrl-file
>     STEP-file

the main reason is that this model comes from a parametric model generated by a script, where dimensions are in a list compiled from manufacturer datasheet; second the model is a mechanical model (STEP) that can be used to convert your board and parts to a mechanical full model; third the WRL model is exactly the copy of the STEP model (generated by the same script) but it has all the material as Mario Luzeiro has suggested (Mario is the author of the new 3D viewer); and as you already noticed both have a really small file size, which means faster loading in KiCAD...
This PR is a first move in trying to put as much 3D models as possible in STEP format with its counterpart in WRL, so the switch to a full mechanical support in KiCAD can be done easily without any struggle for users... WRL are fine both for KiCAD 4 and next release 5 and STEP are perfect for release 5 
here the latest discussion about 3D STEP and WRL models here
https://forum.kicad.info/t/contributing-to-update-of-vrml-librarys-to-step/5049/
Hoping this can be merged
Thx
Maurice

**Comment by jkriege2** [comment]
Fine with me ... If you replace more 3D models, it would be nice to have a screenshot of them on the PCB in the respective PR ... which would make reviewing a bit easier ...

Best,
JAN

PS: In order to make future modifications/corrections easier: I think it would be a good idea to maybe host a 3D model generator somewhere here ... We're currently integrating @pointhi s footprint generator here: https://github.com/KiCad/kicad-library-utils/pull/78 ... and I've recently done some work on a large set of new footprints and 3D mdoels (script-generated ... based on Spreadsheet-parametrized FreeCAD-models), see e.g. https://github.com/KiCad/Resistors_THT.pretty/pull/18 or https://github.com/KiCad/Inductors_THT.pretty/pull/3 (and https://github.com/pointhi/kicad-footprint-generator/pull/18 for the scripts) ... and I think I could export STEP from those and also add ... so those don't have to be done again ;-)

**Comment by easyw** [comment]
Hi Jan,
because I generate all family models, I made a kicad_pcb with all models and a screenshot of the board in 3D viewer
https://github.com/easyw/kicad-3d-mcad-models/blob/master/Resistors_SMD.3dshapes/Resistor_SMD.png?raw=true
https://github.com/easyw/kicad-3d-mcad-models/raw/master/Resistors_SMD.3dshapes/Resistor_SMD_STEP.kicad_pcb
https://github.com/easyw/kicad-3d-mcad-models/raw/master/Resistors_SMD.3dshapes/Resistor_SMD.kicad_pcb
would it be fine for a PR for Resistor_SMD family?

> and I've recently done some work on a large set of new footprints and 3D mdoels (script-generated ... based on Spreadsheet-parametrized FreeCAD-models), see e.g. KiCad/Resistors_THT.pretty#18 or KiCad/Inductors_THT.pretty#3 (and pointhi/kicad-footprint-generator#18 for the scripts) ... and I think I could export STEP from those and also add ... so those don't have to be done again ;-)
that sounds perfect...
Please consider to have a look at the routines to export a wrl optimized version of your 3D model at my repo
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator
thx and keep in touch!
Maurice

**Comment by SchrodingersGat** [comment]
Thanks for the great contribution @easyw and thanks for merging Jan. Hopefully we can together develop an extensive set of good quality models.

**Pull request merged**
