### PR TITLE
added new Cadquery scripted Radial THT capacitors

### PR DESCRIPTION
**Pull request by Shackmeister**
capacitors_tht_wrl_test

### CODE REVIEW

**Comment by Shackmeister** [comment]
https://github.com/KiCad/packages3D/pull/57

**Comment by Shackmeister** [comment]
@SchrodingersGat 
Hey Oliver
I made some other models which happend to end up here because I pushed them before this was merged
switches png

**Comment by Shackmeister** [comment]
tht_cap

**Comment by poeschlr** [comment]
> I made some other models which happend to end up here because I pushed them before this was merged

You should use one branch per pull request.

Also why are there changes in a lot of libraries?
 - dc-dc (adds an alias)
 - linear (adds an amplifier)
 - nxp_armcpu (changes to the cpu recently added by @hackscribble )
 - stm8 (adds stuff)

**Comment by Shackmeister** [comment]
sorry for the mess I made, I did a reset of my fork and added the caps to replace (and reopened this PR)
Im not a very strong git user

**Comment by poeschlr** [comment]
While i look at the files in this pull request here a git how to i wrote for some other user. (It has a lot of information that you clearly already know. But i don't want to rewrite it completely.)

More detailed tutorials can be found over at the [atlassian tutorial page](https://www.atlassian.com/git/tutorials)
If you would rather watch a video, [this 1:20 hour video](https://www.youtube.com/watch?v=ZDR433b0HJY) gives a good explanation what git is and how the basics work.
### How to work with git (Command line version. Graphical interfaces do not always allow all of that easily.)
Short note: everything between "[" and "]" is to be filled out by the user. (The brackets are for marking it here. They are not part of the command)

Create a separate branch for each pull request.
How to do this:
first switch to your master branch and make sure it is up do date with the master branch of the repo you want to merge into.
If you did not already do this, add the original repo as a second remote location to your local repo: (example the kicad library repo. Make sure you use the correct repo here! Otherwise you might destroy your local repo. You can check if you already have this second remote repo by using the command `git remote -v`)
`git remote add upstream https://github.com/KiCad/kicad-library.git`

Now to the synchronizing and creation of the pull request branch: (Make sure that your local repo is clean before doing anything.)
```
git checkout master
git fetch upstream
git pull upstream master
git push
```
If this is done make the branch for your pull request.
```
git checkout -b [meaningfull branch name]
git push --set-upstream origin [meaningfull branch name]
```
Do your changes and commit / push them to your online repo
The save option is to add each file seperatly:
`git add [filename of changed file]`

You can also add all your changes at once. But make sure with git status that you did not change anything unintentionally.
`git add -u`

After that do another check with git status if everything looks good and commit the changes to your repo
`git commit -m "[meaningfull commit message]"`

Then the last thing to do is to push the changes:
`git push`

Open the webbrowser and go to the website of the target repo. You should see a button for create pull request. If you press that just fill out the title and description field.
screenshot from 2017-03-23 23-22-45

Make sure your pull request is ready to be merged automatically. If not do the synchronization step again and merge the changes into your pull request branch.
It can also happen that while your pull request awaits merging someone else got their pull request merged that changed the same files as your pull request would. This of course means you need to merge these changes into your branch. Otherwise merging your pull request would fail.
```
git fetch upstream
git checkout [your local branchname for the pull request in question]
git merge upstream/master
```

Also note that after a while travis will report back if your files do pass the klc checks. fix any issue that is reported.
Do do that make sure your local repo is in the branch associated with the pull request in question.
`git checkout [name of the branch]`

Do your changes
`git add [name of the changed files]`
or
`git add -u`

```
git commit -m "[another meaningfull commit message]"
git push
```

The safest thing to do is to switch back to the master branch after you are finished for the day. (This way it is harder to accidentally change something in your pull request. But make sure you switch back to the branch associated with your pull request before you start to work again.)

**Comment by Shackmeister** [comment]
Should I remove the angled switches from here or can you take them into consinderation too?

**Comment by poeschlr** [comment]
No i look at both the capacitors and the buttons. (Now that the button footprints are merged this should be easy.)
I just need to find out how i can get the changed files into my local repo. (My normal method of fetching origin pull/PR_Number/head does not work for some reason. I will look into this tomorrow morning. It is quite late here already.)

**Comment by Shackmeister** [comment]
Actually they are only on the packages3d repo so Ill add them here. 
Also pretty late here in Denmark so im heading to bed sleep tight :)

**Comment by poeschlr** [comment]
There is a problem with CP_Radial_D10.0mm_P3.50mm:
screenshot from 2017-06-02 10-49-38
screenshot from 2017-06-02 10-54-34

**Comment by poeschlr** [comment]
I can't find a footprint that uses SW_Tactile_SPST_Angled.wrl The footprints use SW_Tactile_SPST_Angled_[some specific information].wrl

**Comment by Shackmeister** [comment]
the cap should be fixed now and I added the 3 switches

**Comment by Shackmeister** [comment]
@poeschlr does it look good to you?

**Comment by poeschlr** [comment]
Still looks the same.

**Comment by Shackmeister** [comment]
@poeschlr can you merge this? :)

**Comment by poeschlr** [comment]
Thanks for this great contribution. (And remember: maybe use a separate branch for each pull request going forward.)

**Pull request merged**
