### PR TITLE
3D Package for VSONP-8-1EP_5x6_Pitch1.27mm

### PR DESCRIPTION
**Pull request by SG-O**
vsonp-8-1ep_5x6_pitch1 27mm_2
vsonp-8-1ep_5x6_pitch1 27mm_1

### CODE REVIEW

**Comment by Shackmeister** [comment]
Hello did you make this model yourself? :)

**Comment by SG-O** [comment]
Yes I did. I used Autodesk's Inventor. It is based on the Datasheet for TI's CSD18531Q5A http://www.ti.com/lit/ds/symlink/csd18531q5a.pdf .

**Comment by Misca1234** [comment]
Just a tip for own made capsules for IC's

First check here
https://github.com/easyw/kicad-3d-models-in-freecad

There might be a script that already make the 3D model for the capsule 
or you can take an existing one that is similar and you can modify it.

If still you have to a hand made model you need to do the following in your case.
Let us assume that your 3D model corresponds to a capsule similar to 
VSON 10 Thermal on 11 3x3mm Pitch 0.5mm that is in "Housings_SON"

You need to do the following
Make a push for both a .wrl and .step models to 
https://github.com/KiCad/kicad-library/modules/packages3d/Housings_SON.3dshapes

Make a push both a .wrl and .step models to 
https://github.com/KiCad/packages3D/Housings_SON.3dshapes

Make a push of the CAD source program to
https://github.com/KiCad/packages3D-source/Housings_SON.3dshapes
And update the CREDITS.md file with your name and what tools you use.

Note, in some cases you have to create the directory yourself, most likely in the packages3D-source repository

Finally, I recommend to use FreeCAD 0.17 and the StepUp macro to produce the step and wrl file.

See this push what it takes for a hand made footprint and 3d model.
https://github.com/KiCad/kicad-library/pull/1545
(in this push a symbol was made as well but you can see the 3D models and links and what they contain)

**Comment by evanshultz** [comment]
@Misca1234 
What do you mean by "capsule"? I believe you should use "package". Package is the physical container of the part (usually metal and epoxy), such as TO-220, SOIC-8, etc.

**Comment by Misca1234** [comment]
Comment updated

**Comment by Misca1234** [comment]
@SG-O 
Have you decided what to do ?
If you do not want to continue with this push, I suggest you close and delete this branch

**Comment by SG-O** [comment]
@Misca1234 Sorry for the delay, I was on holiday for a few days. I will get to work on this as soon as I have time.

**Comment by Misca1234** [comment]
@SG-O 
You read my comment above ?
You are ware that the 3D model already exist ?

**Comment by Shackmeister** [comment]
Hi @SG-O 
PR's for 3D models are no longer being accepted into this repo.
If you would still like to contribute this models, please add a new PR on the new 3D repository which can be found here: https://github.com/KiCad/packages3D

**Pull request closed without merging**
