### PR TITLE
Added NUP2105 ESD protection diode pair for CAN bus

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.onsemi.com/pub_link/Collateral/NUP2105L-D.PDF

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!
looks good ... would you also add the automative variant `SZNUP2105L` from the datasheet? If not I'll merge, if yes: I'll wait. Rest is OK for me ...

Best,
JAN

**Comment by SchrodingersGat** [comment]
Added

**Comment by jkriege2** [comment]
Hi! 
There are 14 changed files now ... could you single out the changes in ESD_...?

cu
JAN

**Comment by SchrodingersGat** [comment]
Ok, I have fixed it. Git went crazy on me.

**Comment by jkriege2** [comment]
:+1: 

JAN

**Pull request merged**
