### PR TITLE
Add MRA4003T3G - MRA4007T3G

### PR DESCRIPTION
**Pull request by MHolzbrecher**

### CODE REVIEW

**Comment by jkriege2** [comment]
Very nice work!

Could you also add the NRVA400-variants from the datasheet? 

Otherwise I will merge!

JAN

**Comment by MHolzbrecher** [comment]
Yes, no problem, I will add the NRVA400-variants.

**Comment by MHolzbrecher** [comment]
NRVA4003-NRVA4007 added.

**Comment by jkriege2** [comment]
nice work!
Thanks!
JAN

**Pull request merged**
