### PR TITLE
Add linear technologie libbs and LT3555 Led Driver componant

### PR DESCRIPTION
**Pull request by kro007**
Hello,
This is my first contribution to an open-source project.

I added New library for brand "linear technology", wich contain (for now...) one componant.

I have grouped some input (FB,ISP,ISN ...) pin on the right side wich is a KRC violation, to simplefy use in schematic. 

Datasheet here : http://cds.linear.com/docs/en/datasheet/37551fd.pdf
lt3755-qfn

LT3755-2 is an alias of LT3755. QFN and MSOP pinout differ.
LT3755-1 have another pinout and its also depend on package.
So there is 4 componant and 2 alias.

Gabriel.

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi Gabriel,

Thanks for contributing.

First, this part should be in the existing dc-dc library. Please move it there and remove it from this new library.

Next, please click on the Details link above. This will take you to the results of automated testing on this part. As you can see, some tests have failed and you should resolve them. Details can be found on [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) and the [FAQ](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions).

Some of the KiCad defaults, like line widths, will need to be changed for your symbol.

The pin type for the VREF pin is OK. The automated tests are generic but having this pin as an OUTPUT is fine.

 You should find many of the parts in the dc-dc library a good reference for making the corrections to this symbol. And if you have questions, please ask!

**Comment by kro007** [comment]
hi,
Thanks for you feedback.

I have some question : 

1) Why is there some library by manufacturer's name (Microchip, altera, stm8...) and others by function (linear, DC-DC...) ?  How to choose ?

2) How to define footprint filter properly ?

3) How to permanently modify default settings like font size, default grid size ext... (Grid size is not saved !)

4) How to commit correction ? should i open a new pull request ?

**Comment by SchrodingersGat** [comment]
@kro007 hi!

> Why is there some library by manufacturer's name (Microchip, altera, stm8...) and others by function (linear, DC-DC...) ? How to choose ?

This is a legacy issue which we have been dealing with for a while. We are currently in discussion as to how to move forward in a more logical manner - see discussion [here](https://github.com/KiCad/kicad-library/issues/1402)

We are moving to a sort-by-function management system, so the advice by @evanshultz above is appropriate.

**Comment by poeschlr** [comment]
To answer your questions:
> Why is there some library by manufacturer's name (Microchip, altera, stm8...) and others by function (linear, DC-DC...) ?

This has historical reasons. The kicad lib grew over a number of years with different people behind it.
We are in the process of cleaning this up, but we will not make major changes during a minor release cycle. See #1402 

> How to choose ?

In most cases it should be quite obvious where a specific symbol should go. Read all symbol lib names and think about what is best for your contribution. If you are not sure, either open an issue for a specific symbol.
Or open a pull request with the symbol added to where you think it might fit. And ask if this is the correct lib.
New libs should only be created in cooperation with the library maintainers.

> How to define footprint filter properly

Find out what footprints you want to appear in the filtered list. This should tell you what the filter should look like.
If your symbol should be connected to one symbol than simply copy the footprint name and replace the "-" and "_" characters as well as the pin count with the wildcard character "*". Finally add a "*" at the end.
Example: assume the symbol should be connected to `Housings_DIP:DIP-10_W7.62mm`
The filter would look like: `DIP*W7.62mm*`

If your symbol should match multiple footprints, add one filter for each of them via the algorithm described above.

Have a look at the [FAQ](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions) for more details.

> How to commit correction ? should i open a new pull request ?

All changes to the lib need to go through pull requests. Even people who have write access should not directly push to the repos. (All changes need to be approved by someone different then the person making the changes.)
If you already have a pull request open and you need to change parts of your contribution, simply push to the same branch as the one connected with the pull request. (For this to work properly you should make a different branch for each pull request. Don't use your master branch.)

See the documentation on pull requests: https://help.github.com/articles/about-pull-requests/

**Pull request closed without merging**
