### PR TITLE
Added the ADS1118 to adc-dac.lib

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added the quad-input 16-bit ADC with SPI interface and integrated temperature sensor and front-end MUX

http://www.ti.com/lit/ds/symlink/ads1118.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I moved this from regul.lib to adc-dac.lib as requested. No functional changes to the part.

**Comment by ricardocrudo** [comment]
@SchrodingersGat please improve the design and fix KLC issues for ADS1120-PW

**Comment by SchrodingersGat** [comment]
Yep, done.

**Comment by SchrodingersGat** [comment]
@ricardocrudo I think this one is good to go now - can you confirm? :)

**Comment by ricardocrudo** [comment]
Hello @SchrodingersGat  Is there any special reason why you've chosen a different shape for ADS1120-PW? I'm asking because all others ADS have the regular box.

**Comment by SchrodingersGat** [comment]
Not really - should I make the ADS1120 like the others?

**Comment by SchrodingersGat** [comment]
Hey @ricardocrudo I have fixed the shape of ADS1120-PW and also merged master branch back in to fix conflicts.

LMK if there is anything else standing in the way for this one.

Cheers

**Pull request merged**
