### PR TITLE
Add 3D models for basic SMD LEDs by Walter Lain

### PR DESCRIPTION
**Pull request by marv**
Add 3D models for SMD LEDs in the sizes 0402, 0603 and 0805

They are created by Walter Lain and were copied from his repository:
http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm

I renamed them following the naming scheme of other SMD components.

### CODE REVIEW

**Comment by andres53016** [comment]
I add the led-0805 in pull-request #240

**Comment by ricardocrudo** [comment]
hello @marv, some of 3d models are already present in the library, can you please remove them from your PR?

**Comment by marv** [comment]
@ricardocrudo: Sure, I'll remove the model for the 0805 LED from my PR

Models for other SMD components are named <part>_<size>, e.g. R_0805 and C_0805, but the LED model named LED-0805 - which naming should I use?

**Comment by ricardocrudo** [comment]
Hi @marv. Sorry for late reply. You can use _ underline.

**Comment by marv** [comment]
Hey @ricardocrudo,

no worries, I can see you have a lot of PRs to go through.

I cleaned up my original PR and used underscore as separator for the models I've added and renamed LED-0805 to LED_0805 for consistency.

The corresponding footprint changes are in KiCad/LEDs.pretty#10

**Comment by marv** [comment]
Polite ping. I'd appreciate if someone could take a look at this and let me know if there's anything I should do to get this merged. Thanks!

**Comment by ricardocrudo** [comment]
thank you!

**Pull request merged**
