### PR TITLE
Added AP131-xx series of LDO linear regulators

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.diodes.com/_files/datasheets/AP131.pdf

### CODE REVIEW

**Comment by diggit** [comment]
Symbol looks ok.
Keywords:
- extend *reg* to *regulator*
- add *fixed* *positive*

(I hope, you are not doing these changes one by one in kicad.)

**Comment by SchrodingersGat** [comment]
@diggit that would be tiresome! Notepad++ find/replace :)

**Comment by diggit** [comment]
Good, so..
- add *fixed* and *positive* into **keywords**
- set FP field to correct value (Library:FootPrint) and invisible
- SOT-23-5 into description
- FP filter to SOT-23\*

and we are ready to go.

**Comment by SchrodingersGat** [comment]
Done

**Comment by diggit** [comment]
Any special reason to skip
> - add *fixed* and *positive* into **keywords**

(・・?

**Comment by SchrodingersGat** [comment]
Sorry, I misunderstood and put that in the description field. It's now fixed.

**Comment by diggit** [comment]
Nice work you did, merging.

**Pull request merged**
