### PR TITLE
fix several issues in `conn.lib`

### PR DESCRIPTION
**Pull request by jkriege2**
- fix some pin-types from BIDI to PASSIVE (https://github.com/KiCad/kicad-library/issues/946)
- add diverse description texts
- fiy style/pin-positions of diverse connectors

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Jan I shall look over this one soon :) Thanks

**Comment by SchrodingersGat** [comment]
Ok some notes on these:

### JACKs
1. Change RefDes from `CON?` to `J?`

### LEMO
1. Change Refdes from `K?` to `J?`

**Comment by jkriege2** [comment]
Done1
renamed all (of all symbols) to J ...

**Comment by SchrodingersGat** [comment]
Thanks, nice work

**Pull request merged**
