### PR TITLE
Added OPA2695

### PR DESCRIPTION
**Pull request by matyro**
Added the TI OPA2695 dual ultra high bandwidth operation amplifier

http://www.ti.com/lit/ds/sbos354a/sbos354a.pdf

opa2695

### CODE REVIEW

**Comment by evanshultz** [comment]
Hi @matyro!

First, thanks for contributing. You've followed the rules for contributing a new part by adding the datasheet link and image of the symbol. And you addressed the KLC issues caught by Travis. Thank you!

However, there are a few issues. Please see [KLC ](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) for more details. I haven't checked everything, but here are a few things that I see:
- The symbol name should be `OPA2695_SOIC`, since it only covers the SOIC package.
- The DCM file should specify the package in the description and use "dual opamp" as the keywords.

Lastly, for contributors, please don't merge this. I want to finish #1081 first.

**Comment by jkriege2** [comment]
Hi!

please add `,SO-8` to the description (in the DCM-file).

Thanks,
JAN

**Comment by matyro** [comment]
Done

Should the package be in the keywords of every part or is this special because it only covers the SOIC part?

**Comment by jkriege2** [comment]
the package should not be in the keywords, but in the description, as `, SOIC-8` or `, SO-8`

Best,
JAN

**Comment by matyro** [comment]
For some reason I am not able to edit the files.
I think the cause for this issue is the fact that the repository disapeared :

> matyro wants to merge 5 commits into KiCad:master from unknown repository

**Comment by jkriege2** [comment]
Hhmmm ... seems you have deleted the branch/repo from which you created the PR ... I think the thing to do now is save the DIFF, create a new branch, apply the patch and open a new PR ... then you have (in your GitHub account) a branch that you can edit until the PR is accepted ... only then you should delete the merged branch.

Best,
JAN

**Comment by matyro** [comment]
Closed this pullrequest because of the missing branch

See #1315 for further informations [link](https://github.com/KiCad/kicad-library/pull/1315)

**Pull request closed without merging**
