### PR TITLE
Added MCP16301 / MCP16301H

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Footprint and pin fixes for MCP16311/2
Consolidated symbols

### CODE REVIEW

**Comment by diggit** [comment]
Good job.
- Don't forget on trailing asterisk in FP filter.
- *Vcc* pin of MCP16311\* is power output
- *Pad* pin is power input
- Please center all symbols at least horizontally.

**Comment by SchrodingersGat** [comment]
All these parts should be consistent now, and horizontally centered

**Comment by diggit** [comment]
Thanks.
Please improve DFN FP filter, you must match 3x3mm dimension. Current filter allows 3x2mm which is incorrect.
Use commas in MCP16311* descriptions.

**Comment by SchrodingersGat** [comment]
Fixed the DFN footprints as suggested, and improved part descriptions

**Comment by diggit** [comment]
Thanks.
Keywords *voltage* and *regulator* works separately good, do not link them with dash.

**Comment by SchrodingersGat** [comment]
Keywords have been separated

**Pull request merged**
