### PR TITLE
added irf7324

### PR DESCRIPTION
**Pull request by openelectron**

### CODE REVIEW

**Comment by ashtonchase** [comment]
Thanks for your contribution. Merging.

**Comment by diggit** [comment]
Is IRF7309IPBF somehow different? It looks like alias would be enough this time...

**Comment by openelectron** [comment]
They require different schematic symbols as IRF7309 has an N channel and a P channel mosfet in a single package. IRF7324 has a pair of P channel mosfets.

**Comment by diggit** [comment]
Yikes, sorry, I didn't compare it to your transistor but some else. Never mind...

**Pull request merged**
