### PR TITLE
Added new pretty libs to lib-table

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds the new Housings_xxx pretty libs to the lib-table templates

Also cleans up descriptions for other Housings_xxx libs

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

is SIP 
1. "Single-inline Package" 
2. or: "System In Package"

Some footprints in that lib match 1-only (classic SIP9-package) some 2 (STK672?) and some 1+2 ... and some are SIL but with zig-zag-pin-ordering (SLA704XM) ...

What should we do?

Best,
JAN

**Comment by SchrodingersGat** [comment]
In context, it probably is Single-Inline Package, you're right.

**Comment by SchrodingersGat** [comment]
I have updated to match. Thanks for pointing this out!

**Comment by SchrodingersGat** [comment]
Thanks Jan

**Pull request merged**
