### PR TITLE
Added 3D models for a range of 2mm pin headers 

### PR DESCRIPTION
**Pull request by SchrodingersGat**
(downloaded under CC license from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm)

I have added the straight 2mm pin headers 3D files, and simply batch renamed them to match the Kicad convention

The associated footprints are currently sitting as a pull request at - https://github.com/KiCad/Pin_Headers.pretty/pulls

mod_pin_strip

### CODE REVIEW

**Comment by ricardocrudo** [comment]
waiting to merge along with KiCad/Pin_Headers.pretty#10

**Comment by SchrodingersGat** [comment]
File named for the .wrl and .wings files have been updated

**Comment by SchrodingersGat** [comment]
@Caerbannog there's a lot of good stuff there, and with some judicious application of notepad++, regex, and some gentle coaxing from @ricardocrudo on KLC compliance, it's not too much effort to convert them over :)

**Comment by michal777** [comment]
@SchrodingersGat
There is also: https://github.com/michal777/KiCad_Lib_Check which has some drawbacks comparing to scripts by ricardocrudo but it can:
- correct footprints without breaking standard file structure
- move 3d models and update their names.

I wonder if it may be better to generate the pin headers and socket strips with some scripts. Everything could be consistent. I can generate the footprints and make pull request as soon as my other pull requests will be merged. There is also possible to generate 3d models with scripts made by @cbernardo

**Comment by SchrodingersGat** [comment]
I'm closing out this request, the models have been changed to match the new KLC-compliant footprints, and are available here:

https://github.com/KiCad/kicad-library/pull/401
https://github.com/KiCad/kicad-library/pull/400

**Pull request closed without merging**
