### PR TITLE
3D packages for Power_Packages_ThroughHole

### PR DESCRIPTION
**Pull request by kajusK**
These are the 3d packages for KiCad/Power_Packages_ThroughHole.pretty#1

### CODE REVIEW

**Comment by michal777** [comment]
Could you use the same names for for .pretty libraries and folders with 3d models? Assigning one folder with 3d models to every .pretty will prevent increasing mess in 3d models.
Dnia 20 stycznia 2015 18:41 Jakub Kaderka &lt;notifications@github.com&gt; napisał(a):
These are the 3d packages for KiCad/Power_Packages_ThroughHole.pretty#1
You can view, comment on, or merge this pull request online at:  https://github.com/KiCad/kicad-library/pull/107
Commit Summary
3D packages for Power_Packages_ThroughHole
File Changes
A modules/packages3d/Power_Packages/Multiwatt15_Horizontal.wings (0)
A modules/packages3d/Power_Packages/Multiwatt15_Horizontal.wrl (2273)
A modules/packages3d/Power_Packages/Multiwatt15_Vertical.wings (0)
A modules/packages3d/Power_Packages/Multiwatt15_Vertical.wrl (2595)
A modules/packages3d/Power_Packages/SLA70X4.wings (0)
A modules/packages3d/Power_Packages/SLA70X4.wrl (3855)
A modules/packages3d/Power_Packages/STK672-040-E.wings (0)
A modules/packages3d/Power_Packages/STK672-040-E.wrl (1325)
A modules/packages3d/Power_Packages/STK672-080-E.wings (0)
A modules/packages3d/Power_Packages/STK672-080-E.wrl (1361)
Patch Links:
https://github.com/KiCad/kicad-library/pull/107.patch
https://github.com/KiCad/kicad-library/pull/107.diff—

**Comment by kajusK** [comment]
Ok, here it is

**Comment by michal777** [comment]
btw.
3d models usually looks better when they have set hard edges. To do it in wings: 1. select all (ctrl+A); 2. body selection mode (B); 3. Auto-Smooth (in context menu, clicking on rectangle in line "Auto-Smooth" allows to set threshold angle for setting hard edges).

**Comment by kajusK** [comment]
Thanks, I'll take a look

**Comment by kajusK** [comment]
I just updated the 3d modules to look better.

Once again, thank you for the hint, it definitely looks many times better now.

**Comment by kajusK** [comment]
Hi,
is there anything else which prevents this pull request from being merged?

Thanks,

**Comment by michal777** [comment]
They look good. Thanks for your contribution.

**Pull request merged**
