### PR TITLE
reworked test-points

### PR DESCRIPTION
**Pull request by jkriege2**
I reworked the symbols for test points (we had one in device.lib and two in conn.lib):
- all reside in conn.lib now
- provided 3 flavours
- modernized symbols a bit
- improved documentation of symbols

2017-09-10 13_14_37-eeschema test_addlin _ d__kicad_test_addlin

Question: Do we need the 2Pole-version (see center) ... I don't really see where that can be handy?
Question2: KiCAD (the nightly version that I used) also made some reorganization of ither symbols (automatically) ... should we keep them or should I revert manually?

Please observe that the symbols themselves check out alright in KLC, the errors are due to other symbols (I tried to fix some minor KLC-violations in some symbols in this commit!)

### CODE REVIEW

**Comment by Heiko-L** [comment]
> Question: Do we need the 2Pole-version (see center) ... I don't really see where that can be handy?

Could be handy for rf testpoints(?).

**Comment by SchrodingersGat** [comment]
I'm happy to leave the 2-pole version in.

Your new symbols look good too. Any further changes you want to make or is this OK to merge?

**Comment by jkriege2** [comment]
no, I think this can be merged .. I'm working on some footprints + 3D models but will push them separately!

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan :)

**Pull request merged**
