### PR TITLE
[new] Symbols for CPC1017N and ASSR-1218 solid state relays

### PR DESCRIPTION
**Pull request by poeschlr**
Both relays share the same copy of a symbol. Differnces are the footprint field and footprint filters. (And of course the description and datasheet)
Datasheet for ASSR-1218 relay (SO-4_4.4x4.3mm) https://docs.broadcom.com/docs/AV02-0173EN
Datasheet CPC1017N relay http://www.ixysic.com/home/pdfs.nsf/www/CPC1017N.pdf/$file/CPC1017N.pdf

Pull request for the footprints: https://github.com/KiCad/Housings_SOIC.pretty/pull/22

screenshot from 2017-07-03 00-26-01

### CODE REVIEW

**Comment by poeschlr** [comment]
Oh man. Somehow my kicad version introduced a lot of space chars. I will redo this tomorrow on my other pc that has a nightly build installed.

**Comment by poeschlr** [comment]
The problem with the spaces is solved. As soon as the name of the footprint is settled, this can be merged. (If necessary, the footprint field/filter needs to be adjusted.)

**Comment by poeschlr** [comment]
Footprint for CPC 1017N has been moved into the ssop lib.
see new PR
https://github.com/KiCad/Housings_SSOP.pretty/pull/35

**Comment by SchrodingersGat** [comment]
Thanks @poeschlr this symbol looks really good.

**Pull request merged**
