### PR TITLE
adding PCA9306 & TXB0108DQSR

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

first of all: nice work ... Please fix these issues:
1. PCA9306: VREF1 and GND have the same pin-number!!! (and pin2 is missing) -> VREF1=pin2!!!
2. TXB...: FPFilter should be `USON*2x4mm*Pitch0.4mm*`
3. TXB...: Do we already have that USON-footprint? In any case it should not be part of TO_SOT-lib!

best,
JAN

**Comment by jeromebeguin** [comment]
I have made the USON package. It's ready to be push, just waiting the PR32 to be merged on TO_SOT_Packages _SMD

**Comment by jkriege2** [comment]
Did we merge your USON? If so: Which lib? Are the symbols up-to-date?

**Comment by jeromebeguin** [comment]
Still waiting the PR32 to be merged on TO_SOT_Packages _SMD

**Comment by SchrodingersGat** [comment]
Hi @jeromebeguin there is a lot of noise in this PR - can you add a description of what you have added?

**Comment by jeromebeguin** [comment]
I've just corrected some KLC error. Otherwise I'm just waiting for merging and keeping the branch up to date by merging from master.

**Comment by SchrodingersGat** [comment]
There are a few KLC errors in the Travis log that should be corrected

**Comment by jkriege2** [comment]
Please add bottom pad for thermal vias ... otherwise looks good!

Best,
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 did you mean to leave that comment here?

**Comment by jkriege2** [comment]
oops no ... will delet ... was meant for your 3 footprint PRs ...

JAN

**Comment by jeromebeguin** [comment]
Finally done. Could you merge ?

**Comment by jkriege2** [comment]
Hi!

I'm a bit confused ... this PR contains noe of the symbls you named in the title ... but some fixes and a part that is also in here: https://github.com/KiCad/kicad-library/pull/1039 ... Could you clean that up a bit?

Best,
JAN

**Pull request closed without merging**
