### PR TITLE
adding Micro_SD_Card_Det to conn lib.

### PR DESCRIPTION
**Pull request by jeromebeguin**
Micro SD card socket with detection pins.

### CODE REVIEW

**Comment by jkriege2** [comment]
nice work, minor changes please:
1. make FPFilter `microSD?Card?Receptable*`
2. change REFDES to `J`
3. empty footprint-field, this is a generic symbol and might match to other receptables too. If not you should rename the symbol to something like the footprint name, as it's not generic then.

best,
JAN

**Comment by jkriege2** [comment]
Please add documentation for 'DM3AT'
JAN

**Comment by jkriege2** [comment]
Could you also add a name-prefix to the DM3AT Symbol? e.g. `Micro_SD_Card_Det_Hirose_DM3AT`.
JAN

**Comment by jkriege2** [comment]
looks good so far. Please fix conflicts and I'll have a final look!
JAN

**Comment by jeromebeguin** [comment]
issue with conflict. I've resolved it by erasing all the directory. The new PR is 1001.

**Pull request closed without merging**
