### PR TITLE
Add ACPL-C79x optical isolation amplifier and ACPL-C87x optical isolation voltage sensors

### PR DESCRIPTION
**Pull request by El3ctr0nic**
I dont have good idea to draw nice symbol ;/ Pls help :)
Here are my propositions

### CODE REVIEW

**Comment by El3ctr0nic** [comment]
vote

**Comment by jkriege2** [comment]
I like variant C best ... although power-supply and output pins should not meet on the output side!

Best, JAN

**Comment by SchrodingersGat** [comment]
Another vote for version C. And @jkriege2  is correct, please separate the supply and output pins from (visually) connecting.

**Comment by El3ctr0nic** [comment]
vote2

Fixed C and add D version :) 

On schematic version C is a little bit too small. It is indvidual feeling I think,

No changes anymore :) 
Pls give feedback and i prepare finall version of component

**Comment by jkriege2** [comment]
:+1: OK for me ...
JAN

**Comment by El3ctr0nic** [comment]
vote3
I think that is something what i looking for :)

**Comment by jkriege2** [comment]
Hi!

not bad, but I think what I like more in former option D is that the whole thing is a complete amplifier symbol, just split by a gap. the symbol above looks like two ...

cu
JAN

**Comment by jkriege2** [comment]
Nice work!

JAN

**Pull request merged**
