### PR TITLE
Added STSPIN2x0 motor driver ICs

### PR DESCRIPTION
**Pull request by SchrodingersGat**
**Datasheets**

www.st.com/resource/en/datasheet/stspin220.pdf
www.st.com/resource/en/datasheet/stspin230.pdf
www.st.com/resource/en/datasheet/stspin240.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
www.st.com/resource/en/datasheet/stspin220.pdf
www.st.com/resource/en/datasheet/stspin230.pdf
www.st.com/resource/en/datasheet/stspin240.pdf

**Comment by SchrodingersGat** [comment]
Fixed conflicts

**Comment by SchrodingersGat** [comment]
@pointhi if you get a chance :)

**Comment by jkriege2** [comment]
Nice! ;-)
JAN

**Pull request merged**
