### PR TITLE
Added Hirose DF-13 shapes

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR re-adds 3D shapes for the DF-13 connectors (Hirose)

These were originally [added here](https://github.com/KiCad/kicad-library/pull/249)

However a subsequent commit removed them (unintentionally).

An [issue was raised](https://github.com/KiCad/kicad-library/issues/1406) by @G33KatWork noting this.

These shapes **should not be added** to the packages3D repo as they are 

a)  Not MCAD compatible
b) Not submitted by the designer

They originally were sourced [from here](http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm)

### CODE REVIEW

**Comment by poeschlr** [comment]
Ok the original source is under CC or GPL so we should be good.

**Comment by poeschlr** [comment]
There is a problem with filenames. (A period is missing)
Example:
`Hirose_DF13-02P-125DSA_02x1.25mm_Straight` (3d file name)
`Hirose_DF13-02P-1.25DSA_02x1.25mm_Straight` (footprint file name)

**Comment by SchrodingersGat** [comment]
@poeschlr thanks for spotting. OK now?

**Comment by poeschlr** [comment]
Sorry for my long absence.
The alignment between the footprints and 3d models for the tht versions seems to be wrong.
The 13 pol smd version is missing. (Is this on purpose?)
There are models in this pull request that are not from this series. They do not match any footprint name.

screenshot from 2017-07-25 22-06-26

screenshot from 2017-07-25 22-06-49

**Pull request closed without merging**
