### PR TITLE
Create bbd.lib

### PR DESCRIPTION
**Pull request by kinichiro**
- create new component library for Bucket Brigade Delay (BBD) chip
- includes MN3005, MN3007, MN3101, MN3102, MN3207, RD5106A, SAD1024 and TDA1022
- KLC compliance

Here is a image for components.
bbd2

Thanks.

### CODE REVIEW

**Comment by diggit** [comment]
Cool ICs.

Please fix these:
- KLC rule 3.8 violation

 aliases contains description too
```
checking component: RD5106A
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    documentation OK
    checking alias: RD5107A
      missing whole documentation (description, keywords, datasheet)
checking component: SAD1024
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    documentation OK
    checking alias: SAD512
      missing whole documentation (description, keywords, datasheet)
```
KiCad/kicad-library-utils [have waiting PR](https://github.com/KiCad/kicad-library-utils/pull/21) for documentation check even for aliases.
- Use direct links to datasheet pdfs if possible. [You can use google to find them](https://www.google.ca/search?as_q=mn3005&as_filetype=pdf).
- Words like "delay","bbd",... belongs to keywords field. Description should contain:
 - **description** of component like "Bucket Brigade Delay"
 - key features like: how many stages it has, bandwidth,...
- Set NC pins invisible
- *Vdd* and *VDD*, if there is no specific reason use all capitals for all pins as other symbols

Few thoughts to consider...
- You don't need to squeeze these symbols into so small rectangles. (Eg. TDA1022 has overlaping pin names)
- When you put *VDD* on top, why not to put there *VBB* and *VGG* too?
- KLC 3.5. ` Whenever possible, inputs are on the left and outputs are on the right.` so input like *Clock*, *Sync*,... are preferred to be placed on left side

I hope, you won't find this post discouraging. It is meant to simplify your fixing process, like TODO list.

**Comment by kinichiro** [comment]
Hi,
Thanks for your concrete advices.
I tried to fix issues.

- KLC rule 3.8 violation (descriptions for aliases)
  Sorry, I forgot to add descriptions for aliases. I added.
- correct datasheet links to direct pdf URL
- I use title of datasheet as description, and some title of datasheet contains the word "delay" or "bbd". (should I correct this ?)
- I set NC pins invisible
- I'm using "Vdd" in case datasheet uses "Vdd". I thought I should use the word in the datasheet AS-IS. (should use "VDD" in this case ?)

>Few thoughts to consider...

- I rearranged pins and I think overlappings are solved. (larger square is better ?)
- I moved VBB and VGG on top as VDD.
- according to KLC 3.5, I moved input pins on the left side.

Here is a image for current progress.
bbd3
Please feel free to give a comment, I don't find any discouraging, sure :-)

Thanks

**Comment by diggit** [comment]
Ok, leave pin names as they are in DSH.

SAD1024 has _GND_ text too close to _OUT_B'_. Same for TDA1022, _V13-16_ and _GND_. This significantly decreases readability.
Higher symbol will solve it.

(I noticed, that VDD and VGG have lower potential than GND, but it would look weird to have GND on top, so no changes here.)

Datasheet links to Datasheetarchive.com are pointing to page, which then starts download, but this won't work for automated scripts and similar cases. Use clickable link on that page. (eg http://pdf.datasheetarchive.com/indexerfiles/Scans-091/DSAHI00048836.pdf) or find different source if possible.

**Comment by kinichiro** [comment]
Hi,

Thanks for your comments.
I fixed issues.
- I enlarged the square of bbd components (600x600 -> 800x800) and rearragend pins.
- And I fixed document links of RD5106A and RD5107A.

>I noticed, that VDD and VGG have lower potential than GND,

Yes, these chips have such a characteristics, negative voltage chips, funny :-)

Here is a image for current progress.
bbd4
Thanks.

**Comment by kinichiro** [comment]
I updated description and keywords providing more information of components.

**Comment by diggit** [comment]
Good.
Please clean your symbols. You have 4 rectangles in them. (3 are dots, I assume, the are mistakes)

**Comment by kinichiro** [comment]
Thanks for your comment.
I didn't notice unneeded 3 dot rectangles, and they were mistake.
I fixed this issue.

**Comment by diggit** [comment]
Good, designs and dcumentation looks OK.
MN3101 and MN3102 share same symbol. Please make MN3102 alias to MN3101.

(Tip: You have to delete MN3102 and the add it as alias to MN3101. Thiss will wipe MN3102 already filled documentation. If you wan to preserve it, copy bbc.dcm somewhere else as backup Do the changes in library and then copy back bbd.dcm)

**Comment by kinichiro** [comment]
Hi,
I made MN30102 alias of MN3101.
And I noticed that unneeded "Common to all units in component" check was set in TDA1022.
I removed this check from pin9, pin13 and pin16.

I reviewed by text editor and checklib.py.

<pre>
checking component: MN3005
  No violations found
checking component: MN3007
  No violations found
checking component: MN3101
  No violations found
checking component: MN3207
  No violations found
checking component: RD5106A
  No violations found
checking component: SAD1024
  No violations found
checking component: TDA1022
  No violations found
</pre>

**Comment by diggit** [comment]
Good catch on TDA1022. Thanks for your contribution.
Nice work you did, merging.

**Comment by kinichiro** [comment]
Thanks for merging.
And many thanks to your advices and notes.

**Pull request merged**
