### PR TITLE
New parts added to libraries

### PR DESCRIPTION
**Pull request by SchrodingersGat**
I have added the following parts:
LPC11U1x NXP ARM microcontroller to nxp_armmcu.lib
8-Pin SPI EEPROM chip (generic) to memory.lib

Also I have added a 3D model of a USB-TypeB-Mini connector (.wrl) to Connect.3dshapes

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Also, I have added 3D models for a wide range of JST connectors: (in packages3d/Connectors_JST.3dshapes)
- JST_ACH (2)
- JST_EH (12)
- JST_SFH (1)
- JST_SUR (7)
- JSR_ZE (7)

And some 3D models for Harwin connectors (packages3d/Connectors_Harwin.3dshapes)
- LTek (2)
- Gecko (3)

To go along with these 3D models, I have created two new .pretty repos for JST and Harwin connectors. They are located:

https://github.com/SchrodingersGat/Connectors_Harwin.pretty
https://github.com/SchrodingersGat/Connectors_JST.pretty

These contain the footprints associated with the 3D models, and have the proper models associated into each footprint.

This is my first time contributing to the Kicad libraries so please let me know if I should be doing something differently. Hopefully the .pretty repos I have made are useful to the Kicad community - i have used them extensively myself.

**Comment by michal777** [comment]
Are the 3d models downloaded from manufacturers website? If they are they probably can't be added to open source library.
Footprints can be added to existing libraries or new libraries can be created. We should wait for @CarlPoirier with decision. I'd prefer not to add small libraries, afaik many users are unhappy with long list of libraries with few footprints.

**Comment by SchrodingersGat** [comment]
Yes the models are straight from the jst website. If that means they can't
be added to an open source project, that is unfortunate. Jst is a huge
manufacturer and as an engineer who uses these connectors all the time, I
was surprised that they are not already in KiCAD library!
Maybe we can include the footprints and I'll just keep a local copy of the
3d models - perhaps the .pretty repo can include a link to the website
where the models are?

As a source note, what is the reasoning behind keeping the 3D model files
in the repository that contains the schematic files, but having the
footprints in separate .pretty repositories? I would think it would make
more sense to have the models with the footprints themselves?

I've only recently made the switch to the new github-version of KiCAD, and
am keen to upload some of my parts library that I've developed over the
years.

Cheers,
Oliver

Are the 3d models downloaded from manufacturers website? If they are they
probably can't be added to open source library.
Footprints can be added to existing libraries or new libraries can be
created. We should wait for @CarlPoirier <https://github.com/CarlPoirier>
with decision. I'd prefer not to add small libraries, afaik many users are
unhappy with long list of libraries with few footprints.

—
Reply to this email directly or view it on GitHub
<https://github.com/KiCad/kicad-library/pull/236#issuecomment-117763273>.

**Comment by SchrodingersGat** [comment]
The Connectors_JST.pretty library is now getting quite extensive. I have also now created a repo for Hirose connectors...

https://github.com/SchrodingersGat/Connectors_JST.pretty
https://github.com/SchrodingersGat/Connectors_Hirose.pretty

**Comment by ricardocrudo** [comment]
Hi @SchrodingersGat, thanks for your interest in helping.
I'd like to make some comments:
* It's better make multiple pull requests with more specific changes. This way is easer to check.
You can organize the changes in branches and pull request them individually. One per library would be great. Create separated PR to 3d shapes is good too.
* do not commit backup files
* when creating new symbols, make sure they are [KLC](https://raw.githubusercontent.com/KiCad/kicad-library/master/KiCad_Library_Convention.txt) compliant. You can use [checklib script](https://github.com/KiCad/kicad-library-utils/tree/master/schlib) to help you.

I would recommend you to close this pull request and create new ones, hardly a librarian will adventure itself inside it. :-)

**Comment by SchrodingersGat** [comment]
Will do :)

**Pull request closed without merging**
