### PR TITLE
L200 regulator added

### PR DESCRIPTION
**Pull request by kajusK**
SSIA

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @kajusK. Please fix pin 3 electrical type, add back color and body line width = 0.010. Thanks.

**Comment by kajusK** [comment]
Hello @ricardocrudo.
I updated the regulator, is it OK now? Also, I can't see any rule regarding the body line width and back color in KiCad_Library_Convention.txt, could these rules be added to avoid this problems in the future?

Thanks!

**Comment by kajusK** [comment]
Hi,
is the pull request ok now?

Also, is this repo still alive? I can see several pull request with no update since half a month ago.

**Comment by kajusK** [comment]
Hello guys,
this pull request has been opened for quite a while, is there anything else that should be fixed on this part? Or what's blocking the merge?

**Comment by diggit** [comment]
Hi, librarians work on this repo in their free time. Most of us study or have full time job. Some PR are quite huge and take some time to verify (not this case).
Rules about BG and outline thickness are in extra checks. use checklib.py from [kicad-library-utils](https://github.com/KiCad/kicad-library-utils/) with
`--enable-extra` flag to check extra rules.

Nice work you did, merging.

@ricardocrudo EC rules should be listed somewhere as we require them, but I'm not sure if they belong to [KiCad_Library_Convention.txt](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt)

**Comment by kajusK** [comment]
Hi @diggit,
I do really appreciate the work you do on the project and completely understand it's time consuming.

I was just afraid the @ricardocrudo has left the project and this pull request was forgotten...
Thanks for the merge!

**Comment by diggit** [comment]
Don't be afraid, **ricardocrudo** is probably busy now. It is ok to ask about status when nothing happens for a longer period.
I am looking forward to see more PRs from you. :)

**Pull request merged**
