### PR TITLE
Added TPS62177

### PR DESCRIPTION
**Pull request by SchrodingersGat**
ALIAS TPS62175

Reference: http://www.ti.com/lit/ds/symlink/tps62177.pdf

### CODE REVIEW

**Comment by diggit** [comment]
- keywords are space separated, use sth. like: Step-Down DC-DC Converter
- do not use Datasheet field to store datasheet link, put it in documentation
- use direct links with pdf suffix to minimize redirections (http://www.ti.com/lit/ds/symlink/tps62177.pdf)
- change SW pin to power output
- change NC pin to passive type, it can be left floating
- use upper case letters for Vin, En, ~Sleep as in datasheet
- use same symbol for both components to make it easily replaceable

**Comment by SchrodingersGat** [comment]
@diggit  I think I got them all

**Comment by diggit** [comment]
Stay consistent, use keyword *step-down* instead of *stepdown*
Fix it and we are ready to merge.

**Comment by SchrodingersGat** [comment]
Done!

**Comment by diggit** [comment]
Umm, I should never promise immediate merge after fix.
Move "with Sleep Mode" at the end of description to share description format with others. (devices
 tps62175 and tps62177 )

**Comment by SchrodingersGat** [comment]
Doneski

**Comment by diggit** [comment]
Great, thanks! Bored huh?
Nice work you did, merging.

**Pull request merged**
