### PR TITLE
Interface klc

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Various KLC improvements to interface.lib

### CODE REVIEW

**Comment by diggit** [comment]
Before any further PRs. Please update your KiCAD to bzr build 6331 or higher. It will minimize library changes (no double spaces).

**Comment by SchrodingersGat** [comment]
@diggit I've re-saved interface.lib. OK now?

**Comment by diggit** [comment]
As you decided to polish those symbols, can you tweak them even more?
(Why touch them in multiple PRs, whne it can be done now...)

### Digi. pots.
- VDD, VLOG on top edge
- GND, VSS on bottom edge
- whole control interface on left (SDA, SCL, AD0, AD1, ~SHDN)
- rest on right (O1, O1, A ,W, B)

Grouping i fine, it just makes sense to have address setting input on same side as i2c...

### LT1080
(pretty bad symbol now)
- shrink symbol
- fix pin types
 - C* passive
 - GND, VCC power inputs,
 - +-9 power outputs
- add internal drawing, similar as you did for max13432E in #451 
 -  make rs232 and logic side easily distinguishable
- then you can rename all pins to schematic names
- power inputs on top/bottom
- even when KLC 3.5 suggests I/O separation, in this case make sense to have logic pins on one side (left) and RS232 pins on the other side (right
- add pin names for cap. pins
- C1/2 + nad - pins 300milks apart, it helps easy cap. connection 
- KLC fixes...
 - line widh 0.010"
 - 100mil pin alignment
 - 100 or 150mil pins are enough
 - fields outside of symbol
 - ...

*just like you do other symbols, piece of cake*

IMO writing this took same time as fixing it :D

**Comment by SchrodingersGat** [comment]
Done

**Comment by diggit** [comment]
- AD5282 is easily shrinkable to size of AD5280

> - C1/2 + nad - pins 300milks apart, it helps easy cap. connection
> - make rs232 and logic side easily distinguishable

like this...

**Comment by SchrodingersGat** [comment]
@diggit I have made the requested changes. I have also nuked MAX232 and MAX202, re-made them as copies of LT1080, and improved the descriptions thereof

**Comment by SchrodingersGat** [comment]
@diggit all of the RS232 chips that I originally had here - https://github.com/KiCad/kicad-library/pull/261 - have now been added here either as ALIAS or new parts as appropriate. Now all the RS232 symbols are consistent for drop-in replacement.

**Comment by diggit** [comment]
You've done pretty good job here!

- (LT1080) fix pin name ON/~OFF
- (LT1080,MAX3226) rename left side pins to match datasheet if possible ()aliases), TX/RX are not in datasheet nor other transceivers
- (MAX3226) remove pin 18 (ON/OFF) - probably forgotten during symbol duplication

- solve conflicts

**Comment by SchrodingersGat** [comment]
Dun

**Comment by diggit** [comment]
Thanks for unification.
[This might help you in future commit messages.](http://www.alexkras.com/19-git-tips-for-everyday-use/#good-commit-message)
Nice work you did, merging.

**Pull request merged**
