### PR TITLE
3d: added a model for the Resistor_Horizontal_RM7mm

### PR DESCRIPTION
**Pull request by Fat-Zer**
see also https://github.com/KiCad/kicad-library/issues/403

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @Fat-Zer can you please adjust the 3d params to match with the footprint? thanks.

**Comment by Fat-Zer** [comment]
Hi, what do you mean?
The footprint's 3d parameters are adjusted in the PR mentioned above.

**Comment by diggit** [comment]
There are 2 problems:
- Kicad expects, that 3D model dimension units are in **0.1 inches** insteal of **mm** -> you have to scale it by 1/2.54 (approx 0.394) in all axis in Footprint 3D model assignmnet. (many models are scaled this way)
- THT footprints have anchor on pin 1 ([KLC 6.3](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt#L66)), but it seems, that your 3D model has origin in center

**Default**


**Scaled and shifted**
Shifting should be fixed in 3D model itself.

**Comment by Fat-Zer** [comment]
@diggit, everything is done the neighbouring PR: https://github.com/KiCad/Resistors_ThroughHole.pretty/pull/8

>Shifting should be fixed in 3D model itself.

hm... why?

**Comment by diggit** [comment]
Because shift is specific for each device. Eg if sb. creates generator for these 3D models, nobody wants to edit each part. It is easier to rely on fact, that pin 1 is on origin.

**Comment by hackscribble** [comment]
Hi @Fat-Zer 

Sorry for the long time to get back to you about this PR.

The components in `Resistors_THT.pretty` have been renamed and matching 3D models provided.  So it looks like this contribution has been superseded and, therefore, I am closing the PR.

**Pull request closed without merging**
