### PR TITLE
Added allegro.lib with A4950 & A4953

### PR DESCRIPTION
**Pull request by feichtinger**
The A4950  and "it's little brother" the A4953 are Full-Bridge DMOS PWM Motor Driver with 3.5A and 2A, both in a SOIC-8 package with exposed (thermal) pad.

bildschirmfoto vom 2016-10-12 23-23-46

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@feichtinger I'll hold off on this PR until the outstanding allegro lib PR is merged (https://github.com/KiCad/kicad-library/pull/668)

Nice work though :)

**Comment by ADTeasdale-OWE** [comment]
@feichtinger I realise this conversation has been dormant for a while, but I came across your PR when working with a similar part. It may be worth noting that one of the parts you've added already exists in _motor_drivers.lib_ as A4950E and A4950K, added April 2016 https://github.com/KiCad/kicad-library/commit/5532142dc305b6f841d40d6f75f2c974b707a129:
image
@SchrodingersGat I have some additional Allegro motor controller parts that I'd like to contribute (A3977, A3987 & possibly others). What is current practice - should they go in the function-based _motor_drivers.lib_ or manufacturer-based _allegro.lib_? My preference is probably the latter, but then I'm new so my opinion doesn't count for much!

Incidentally our company [[https://openworksengineering.com/](https://openworksengineering.com/)] now uses KiCAD for all our PCBs and are suitably impressed - the below being the first non-trivial example. 
top
As we continue to gain experience I'm hoping to be able to contribute any of our library parts that might be useful to the community and help in other ways as time and other commitments allow.

**Comment by SchrodingersGat** [comment]
Hi @ADTeasdale-OWE for now these will probably best be suited to the MotorDrivers library!

**Comment by Misca1234** [comment]
This push can be closed and deleted.
A replacement push is here 
https://github.com/KiCad/kicad-library/pull/1677

**Pull request closed without merging**
