### PR TITLE
Complete overhaul of linear library

### PR DESCRIPTION
**Pull request by evanshultz**
The vast majority of the information is at https://github.com/KiCad/kicad-library/pull/1081, and I suggest y'all go there for details. This has been a long saga and doesn't bear repeating here.

The gist of the update is this:
- Updated the entire library, standardizing and fixing and adding parts
- Pulled in one open PR
- Moved some parts from other libraries that belong with the parts in this library

And there you go! Whew!

Notes:
1. I accidentally got this fork's branch out of sync with master for regul.lib when I added the fix at https://github.com/KiCad/kicad-library/pull/1430. I just coped master from the original KiCad lib here so it shows there is a new commit for that lib but really it's the same. There is no diff below.
2. https://github.com/KiCad/kicad-library/pull/1424 will certainly get broken due to this PR because I'm changing so much. However, I believe this is for the greater good.

There is one KLC violation and that is for LM311. It has a pin named GND which is really an open emitter. Conversation about this, and agreement to do it this way, is in the PR linked above.

### CODE REVIEW

**Comment by evanshultz** [comment]
I don't know why Travis is marking some symbols red, some yellow, and some green, but it only lists the one KLC violation that I see when running the scripts locally. So I guess that fine...

@SchrodingersGat @jkriege2 @poeschlr 
Can I get a review and merge on this? Since so much is changing and this PR can be merged now, I would like to avoid some other merge breaking this one. Getting this far was a major slog!

One more note:
1. ZXCT1110 doesn't have an existing footprint for it. It seems like a unique footprint so I called it `Zetex_SM8`. I will create this footprint. [Datasheet](https://www.diodes.com/assets/Datasheets/ZXCT1009.pdf) and [package drawing](http://datasheet.octopart.com/ZDT6758TA-Zetex-datasheet-68057.pdf).

**Comment by DavidGriffith** [comment]
Okay, I'll withdraw #1424 and redo it, if necessary, once this patch is pulled in.

**Comment by SchrodingersGat** [comment]
@evanshultz  this is a really great effort. I have had a browse through the updated library. I have not looked at each symbol in depth.

I have noticed that there are a few graphical issues but nothing that prevents me from accepting this. Certainly it is a vast improvement.

@poeschlr @jkriege2 unless you have any objections I am happy to merge this.

**Comment by poeschlr** [comment]
Sadly i currently don't have enough time to take a detailed look at it as i did for the regul lib update. I will take a quick look at it later today.

**Comment by evanshultz** [comment]
Thank you all!

@SchrodingersGat I'll take a look for any graphical issues to be done at a later date. If you could point out the issues you saw, or a general description that I can chase, that would be nice.

**Comment by evanshultz** [comment]
@SchrodingersGat 
I used the Library Browser to look at each symbol. Due to the length of time making these changes, the patchwork of gathering more and more symbols, looking a lot at text files, and just not doing a visual polish on the symbols, I found a number of this which I believe may fall into the category of "graphical issues" that you mentioned. Here is what I found:
- AD620/AD623/LM311/LMC555*/LT1011: Pin text overlapping body
- AD236/8421/8422/8429: Ref pin length could be longer to match Vs- pin
- AD8610/LF15x/LF25x/LF35x/LM741/LT1363/OP07/OP77/OPA134/TL061/TL071/TL081: Shrink NC pin length
- ADA4807-2ACP/MCP603-xCH/TLC555*: Crash between text and pin
- CA3080/CA3080A/L272D/LF398_DIP8/LF398_SOIC8/LM318J/LM319/LM6171/LM6361/LT1493/LTC4414/LTC6082*/MAX4080*/MAX423xASA/MCP601-xP/MCP601-xS*/MCP603-xP/MCP603-xS*/MCP6L91RT-EMS/MCP6L91RT-ESN/MIC845*OPA333xxD/OPA340P/OPA340UA/OPA376xxD/OPA4340EA/THS4631D/TSV911IDT: NC pins floating away from symbol body or outside symbol body
- INA19x: Text crashing inside and outside symbol body
- INA28x/LM4250: Triangle is unnecessarily bigger than others
- L272: Mismatched GND pin lengths
- LM318*: Pins point to the right instead of up/down
- LM6321*: Pins turned around and floating away from body
- OPA2691-14: Pins in a row with unmatched length

Is that what you were talking about, Oliver? Is there something else that stood out? If you like, I'll make the changes above and then this PR can be reviewed again.

Note that some, if not many or all, are an ALIAS so the number of changes would be much smaller.

**Comment by evanshultz** [comment]
Come to think of it, I might be more inclined to have then merged and then make another PR. Just to get it done and avoid any big hassle if another PR is merged into linear.lib.

**Comment by SchrodingersGat** [comment]
@evanshultz sorry I've been pretty busy and didn't respond earlier.

Those are the kind of graphical issues I was talking about. I agree that these can be fixed in a separate PR.

As no-one has raised any serious objections I'll merge this now, any other fixes can be made later. Thanks for the great amount of work you have done on this :)

**Comment by evanshultz** [comment]
@SchrodingersGat 
Thanks! I hope to submit a PR for the cleanup tasks this weekend.

@DavidGriffith 
If you want to do the capitalization thing again, please go ahead. I didn't catch the real reason behind it, so you may want to expand on that more. I haven't run into problems, or I simply am daft.

**Comment by DavidGriffith** [comment]
@evanshultz I've resubmitted my capitalization pull in #1462.

**Pull request merged**
