### PR TITLE
Addind some component to texas and transistor lib.

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. Please follow KLC (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) and please add description+keywords+datasheet in DCM-file1

Thanks,
JAN

**Comment by jeromebeguin** [comment]
Hi!

Here is the .DCM files. I'll probably needs some more modifications/review. I'm pretty new on KiCad. But it will be better and better. 

Thanks in advance for your patience. 

Best

Jérôme

**Comment by jkriege2** [comment]
Hi!

no prob ... I'll guide you through the loops ;-)

So some things you should change in your parts:
1. You should empty the datasheet fields (datasheet should be put into the properties that end up in the dcm-File)
2. Remove the fields "Manufactirer", "Mouser ref number" ... there should only be these fields in a symbol: "Reference", "Value", "Footprint" and "Datasheet"(=EMPTY)
3. In the "Documentation file name" property you should put the PDF-datasheet-link (from the Datasheet-field)
4. The FPFilter should contain as much information as required to match the footprint (or any variant thereof), but should NOT contain the number of pins as that is filtered by the pin-number filter. In your case the FPFilter should contain more geometric info, i.e. `HTSSOP*4.4x9.7mm*Pitch0.65mm*ThermalPad*` 
5. pos. POWER-Pins (VCC, ...) should be at the top of the symbol and neg/GND-pins at the bottom
6. all pins must lie on a 100mil grid (best is to set the grid accordingly in the symbol editor, when placing/moving them)
7. in LM5175PWP the pin 25 seems to appear twice (LDRV1 and PowerPAD)
8. text size should be 50mil for all texts (some properties are 60mil!)
9. the thickness of the outline should be 0.01"
10. please add a pin 29 "PAD" for the bottom/heat pad (possibly as NC-pin)
11. For the VSON-8-package, I didn't find that in the standard KiCAD-libs ... would you provide the footprint also?

Best,
JAN 

PS: We are currently discussing imrpovements to the KLCs (see https://github.com/SchrodingersGat/kicad-library/wiki/KLC and https://github.com/KiCad/kicad-library/issues/879) and see also this set of python scripts (https://github.com/KiCad/kicad-library-utils) that check symbols for meeting the KLC requirements (and can fix some problems with the option `--fix`). Also note that it is wise to run these scripts with the option ´--enable-extra`

PPS: Here's the output of our script, run on texas.lib:
```
D:\KiCAD\kicad-library-review\library>..\..\kicad-library-utils\schlib\checklib.py -vv --enable-extra texas.lib -p 5175
checking component: LM5175PWP
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: MODE (4), posx 50, posy -800
    pin: DITH (5), posx -50, posy -800
    pin: FB (11), posx 150, posy -800
    pin: BIAS (24), posx 250, posy -800
    pin: PowerPAD (25), posx -800, posy -450
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: U at posx -550 posy 650 size 60
    field: LM5175PWP at posx -450 posy -650 size 60
    field: Housings_SSOP:HTSSOP-28_4.4x9.7mm_Pitch0.65mm_ThermalPad at posx 2550 posy -650 size 60
    field: http://www.ti.com/lit/ds/symlink/lm5175.pdf at posx 2100 posy -450 size 60
    field: Texas Instruments at posx 1450 posy -350 size 60
    field: 595-LM5175PWPR at posx 1450 posy -550 size 60
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -550, posy 650, recommended posx -200, posy 725
    field: reference, justification C, recommended R
    field: name, posx -450, posy -650, recommended posx -200, posy 650
    field: name, justification C, recommended R
    field: footprint, posx 2550, posy -650, recommended posx 300, posy -650
    field: footprint, justification C, recommended L
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10
  Violating EC05 - Extra Checking
    Pin numbers should not be duplicated, and all pins should be present
    Pin 25 is duplicated
    25 - LDRV1 @ 800,200
    25 - PowerPAD @ -800,-450
checking component: LM5175RHF
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: MODE (1), posx 50, posy -800
    pin: DITH (2), posx -50, posy -800
    pin: FB (8), posx 150, posy -800
    pin: BIAS (21), posx 250, posy -800
    pin: PowerPAD (29), posx -800, posy -450
  Violating Rule 3.6
    Field text uses a common size of 50mils.
    field: U at posx -550 posy 650 size 60
    field: LM5175RHF at posx -450 posy -650 size 60
    field: Housings_DFN_QFN:QFN-28-1EP_4x5mm_Pitch0.5mm at posx 2250 posy -650 size 60
    field: http://www.ti.com/lit/ds/symlink/lm5175.pdf at posx 2100 posy -450 size 60
    field: Texas Instruments at posx 1450 posy -350 size 60
    field: 595-LM5175RHFR at posx 1450 posy -550 size 60
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
    field: reference, posx -550, posy 650, recommended posx -200, posy 725
    field: reference, justification C, recommended R
    field: name, posx -450, posy -650, recommended posx -200, posy 650
    field: name, justification C, recommended R
    field: footprint, posx 2250, posy -650, recommended posx 300, posy -650
    field: footprint, justification C, recommended L
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
    Component line thickness 0, recommended 10
```

**Comment by jeromebeguin** [comment]
Here some improvements. 
About the VSON-8 I have made the footprint, but I put it in a new library called: Housings-SON but I don't know how to share it on the KiCad Github.

**Comment by jkriege2** [comment]
Hi!

maybe add it to `TO_SOT_Packages_SMD` ... there is already a `TO_SOT_Packages_SMD:VSOF5` ... not ideal but might work for now!

Best,
JAN

PS: Please also merge master into your branch to fix the conflict of `transistors.dcm`

**Comment by jeromebeguin** [comment]
I tried to merge, but it seems I haven't done it correctly.

**Comment by jeromebeguin** [comment]
It seems I have a problem. Any one have an idea how to resolve this ? Sorry I'm not used to gitHub.

**Comment by jkriege2** [comment]
Usually I do it under TortoiseGit on the desktop by pulling into my branch a custom URL (the kicad-library-repo) and from there the master-branch. Usually I also have to art least look through the automerge-results and say OK ... and see here:
- http://stackoverflow.com/questions/16955980/git-merge-master-into-feature-branch
- https://www.ralfebert.de/git/branches-mergen/


Best,
JAN

**Comment by jkriege2** [comment]
hmmm ... somehow it went totally  pear-shaped now ... you have 704 changed files (most of them them line-endings) ... what about making a clean new branch from the kicad-lib master and copying in the changed files from this branch?

Best,
JAN

PS: Did you check you git-settings? see e.g. here: https://help.github.com/articles/dealing-with-line-endings/ and http://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings.

**Comment by jeromebeguin** [comment]
Oh, sorry. I will check this.

**Comment by jeromebeguin** [comment]
I have tried to correct the line ending problem. Don't know if it's ok now.

**Comment by jkriege2** [comment]
not really ... this seems to get a bit out of hand, so I would propose to close this PR and open a clean new one, derived from the current master-branch and submit the new stuff there by hand ... OK for you?

Best,
JAN

**Comment by jeromebeguin** [comment]
ok for me. How should I proceed. I'm deeply sorry for putting the mess around here.

**Comment by jkriege2** [comment]
no prob ... just close this PR and open a new one ... clean and from the start ... then peace by peac copy in the added symbols. Also please split this PR then at least into one for each .lib that you changed ... Let me know if there are any problems ,-)

JAN

**Comment by jeromebeguin** [comment]
Could you help me to recover the clean main branch ? I still have all the crapy files with the line ending problem.

**Pull request closed without merging**
