### PR TITLE
Add NXP 4- and 5-unit PESD* ESD protection diodes

### PR DESCRIPTION
**Pull request by evanshultz**
Datasheets:
-http://www.nxp.com/documents/data_sheet/PESDXL4UF_G_W.pdf
-http://www.nxp.com/documents/data_sheet/PESDXL5UF_V_Y.pdf

Passes all KLC tests. Common anode on all symbols.

Symbol image:
image

If this should go in a different library, like ESD_protection, please let me know. I'm happy to update.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I think I would prefer to see these ones in ESD_Protection, thanks :)

**Comment by jkriege2** [comment]
me too ...
JAN

**Comment by evanshultz** [comment]
No problem. Will move.

**Comment by evanshultz** [comment]
Created PR #841 to keep it separate. Close this PR when ready.

**Comment by evanshultz** [comment]
Since these parts were merged into another lib, closing this PR.

**Pull request closed without merging**
