### PR TITLE
Overhaul digital_audio library

### PR DESCRIPTION
**Pull request by evanshultz**
Overhaul of this library with the following changes:
All:
- Standardize description and keywords
- Add package name to description
- Update datasheet links if needed
- Correct/add default footprint if needed
- Correct/add FPfilter if needed
- Set all line thicknesses to 10mil, if not
- Shorten all pins to 100mil
- Move all pins on 100mil grid
- Move ref des and value above symbol
- Stack power and ground pins

AKM*:
- AK5392: Add datasheet link (from DigiKey)
- Update footprint to new 18.7mm tall package

CS4245:
- Move pins so in on left and out on right

CS43L21:
- Move FILT+ up 50mil to be on 100mil grid
- Change ANGD pin to type POWER INPUT
- Add missing pins (NIC and TSTO)
- Add pin 33 for QFN package

CS5361:
- Move audio pins to top for better layout
- Show RST pin as active low

CS8406:
- Add missing pins
- Change pin names for both HW and SW modes

CS8414:
- Adjust pin positions to fit symbol
- Add datasheet

CS8416:
- Consolidate into just SOIC/TSSOP and QFN symbols
- Update datasheet link
- Add pin 29 for QFN package

TLV320AIC23BRHD:
- Add pin 29 for QFN package

TLV320AIC23BxQE:
- Create symbol for datasheet package not in lib based on existing symbols ([PR for new footprint](https://github.com/KiCad/Housings_BGA.pretty/pull/17))

TPA5050:
- Fix datasheet URL
- Fix broken FPfilter
- Add pin 17 for QFN package

### CODE REVIEW

**Comment by evanshultz** [comment]
I added the pinout for the BGA package of TLV320AIC23B and update the footprint. I left out the C3 pin since it turns out that package really doesn't have this ball.

**Comment by evanshultz** [comment]
It's absolutely baffling that Cirrus can't answer my question about the CS8416 thermal pad yet...

Anyway, here are images of the symbols:
image

With the delay from Cirrus, I added some ADI audio DACs too:
AD1853 http://www.analog.com/media/en/technical-documentation/data-sheets/AD1853.pdf
AD1855 http://www.analog.com/media/en/technical-documentation/data-sheets/AD1855.pdf
AD1955 http://www.analog.com/media/en/technical-documentation/data-sheets/AD1955.pdf

Image of those:
image

Once I get the answer, I'll add the last pad and then this PR can be merged.

**Comment by evanshultz** [comment]
Cirrus was finally able to tell me that the CS8416 QFN's thermal pad is floating and should be connected to ground for thermal performance, though. So I've added a TP pin at the bottom center of the symbol.

This PR is available for review now. Thank you.

**Comment by evanshultz** [comment]
Added some TI DACs so they won't be excluded:
DSD1794A: http://www.ti.com/lit/ds/symlink/dsd1794a.pdf
PCM1792A: http://www.ti.com/lit/ds/symlink/pcm1792a.pdf
PCM1794A: http://www.ti.com/lit/ds/symlink/pcm1794a.pdf

Image:
image

@jkriege2 @poeschlr @Shackmeister @SchrodingersGat I'd like to get this into KiCad 4.0.7. Is anyone able to review?

**Comment by evanshultz** [comment]
Can I get a review, please?

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr @Shackmeister @hackscribble 
Librarians: It has been over 2 weeks since I finished this PR and got it ready for review and merge. We've already missed the v4.0.7 window. I understand this PR is a bigger request than just a single part, but how do we handle library overhauls like this?

I've already seen a PR for this library where I asked the contributor to hold off. I'd like to avoid my branch getting out of sync with master, but the longer this PR waits the greater chance there will be. For such a major change to a library it makes the most sense to me that it all be done at once so we have a bigger overview of all the parts in the library and can achieve commonalization. But perhaps I'm wrong.

I've written and read many times in PR comments how our libraries don't conform to KLC. Here is one of a few examples where I spent the time to go through a library and make it KLC compliant. It's a big effort, but without it our library will never be fully updated and meet our own requirements.

Jan has overhauled the regulator symbol library. Frank just mentioned doing the IR-DirectFET footprint library today. I've already gotten a couple overhauls merged and have a few others waiting for review and merge. While I know we have library infrastructure work and a number of tasks for v5 coming up, getting all symbols and footprints in the library seems like one of the major objectives of librarians to me. What is the best way to go about this?

**Comment by SchrodingersGat** [comment]
@evanshultz thanks for your fine work here!

> but how do we handle library overhauls like this?

Exactly as you have done :) Sorry that it has slipped through the cracks, and that we missed the 4.0.7 release. It is certainly very much appreciated in any case. It is absolutely fantastic that there has been a marked increase in contributing in the last few months, but this also means that there's a huge backlog of PRs to look at!

I will look through it now :)

**Pull request merged**
