### PR TITLE
Added various analog comparators

### PR DESCRIPTION
**Pull request by SchrodingersGat**
TS881
ADCMP35x

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

- ADCMP...: I think you swapped pins 4 and 1 ... accoridng to datasheet 1 is Vin and 4 is Vcc
- rest is OK ...

cu
JAN

**Comment by SchrodingersGat** [comment]
Ah, great catch, thanks Jan. Now fixed.

**Comment by jkriege2** [comment]
One more proposal for the ADCMP comparators:
What about showing the reference source in the symbol? That would make (IMHO) the function of the device clearer, when reading a schematic, e.g.:
comp

JAN

**Comment by diggit** [comment]
Why does output pin have inverted graphic style? It does not match datasheet.

**Comment by jkriege2** [comment]
Because the 350 is as I proposed above, but for the other two devices the REF is connected to - and the input is + ... so 350 has technically the inverted function as the others ... I think my proposed symbol would solve that problem ;-)

JAN

**Comment by diggit** [comment]
I think this is a bit confusing. I'd stay consistent with datasheet where I read about which version have which input used for ref and input.

**Comment by jkriege2** [comment]
@SchrodingersGat : How about this one? Could you fix conflicts and see whether we get it done?

best,
JAN

**Comment by SchrodingersGat** [comment]
Conflicts have been fixed

**Comment by jkriege2** [comment]
OK! nice work!

JAN

**Pull request merged**
