### PR TITLE
Added the 3D model for HY1602E

### PR DESCRIPTION
**Pull request by Misca1234**
3D model for HY1602E
See https://github.com/KiCad/Displays.pretty/pull/12

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Please move the model to Displays.3dshapes

**Comment by poeschlr** [comment]
The same with your other PR, if you remove the files from the Display.3dshape directory it is ready to be merged.

**Comment by Misca1234** [comment]
Yes, I am in the progress of doing it

**Comment by Misca1234** [comment]
It is pushed

**Comment by poeschlr** [comment]
Thanks for this contribution.

**Comment by Misca1234** [comment]
No problem, it is fun

**Pull request merged**
