### PR TITLE
Added 3D model for Crystal_SMD_5032_4Pads

### PR DESCRIPTION
**Pull request by SchrodingersGat**
5032_4pads

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
5032_2pads

Also added 3D model for the 2-pad 5032 crystal

e.g. http://media.digikey.com/pdf/Data%20Sheets/AVX%20PDFs/CX5032GB_(CX-53F)_DS.pdf

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
Sorry for the noise, I updated the build script. Fixed at least an issue with rule 3.6.

**Comment by pointhi** [comment]
thanks for this models

**Pull request merged**
