### PR TITLE
Clean up interface lib phase 2

### PR DESCRIPTION
**Pull request by Misca1234**
Here is a partial clean-up of the interface library.

This library have A LOT of issues, so to not overwhelming the librarians I have only corrected a few of the errors so it would be more manageable if it is handled in small portions.

This push will not fix all issues but a few.
(The '/' issue will be fixed in the next one)

This push consist of the following changes

75LBC176
No indication of which type it is , assuming it it is the DIP-8 variant
Renamed into SN75LBC176P
Added aliases SN75LBC176P, SNJ55LBC176JG
Filled the description
Attached foot print
redraw symbol with box
Shortened pins

AD5280
Added footprint and foot print filter
Shortened pins
Packed the symbol a bit

AD5282
Added footprint and foot print filter
Shortened pins
Packed the symbol a bit

AD9834
Added footprint and foot print filter
Shortened pins
Packed the symbol a bit

AD9951
Fixed foot print filter and deicated foot print
Added EPAD pin

ADM3053
Moved in the NC pin
Made all text upper case
Otherwise no changed, the pin arrangement corresponds to the 
function very nice so it would be odd to move the VCC pin

ADUM4160
Cleaned up the foot print filter

ADuM1200AR
Aligned the pins to the correct grid
Filled out description
Fixed footprint filter
Rearranged the pins

ADuM1201AR
Aligned the pins to the correct grid
Filled out description
Fixed footprint filter
Rearranged the pins

### CODE REVIEW

**Comment by Misca1234** [comment]
Travis complain on
AD9834
- Pin VIN (17) @ (600,-400) is of type INPUT

It is not a power pin


ADM3053
Wherever possible, pins should be arranged by function
Positive power pins should be placed at top of symbol
  - Pin VCC (8) @ (-500,600)

I decided to keep it on the left side due to the nature of the device

**Comment by jkriege2** [comment]
Hi!

I'm taking a look at this now ...
0. generall a pin-text-offset of 20mil looks better in many cases, especially because the text is better separated in small symbols
1. Could you add the SOIC-variants of SN75LBC176D and its ALIASes ... maybe also a small internal drawing could be nice, e.g.
2017-09-24 21_55_00-part library editor -- d__kicad_kicad-library-review_library_interface lib
2. AD9951: This symbol could be improved by stacking the power-pins
3. ADM3053: This symbol could be improved by stacking the power-pins
4. ADUM4160: This symbol could be improved by stacking the power-pins
5. ADuM1200AR: This could be imrpved with directionality indicators (small triangles):
2017-09-24 21_59_14-part library editor -- d__kicad_kicad-library-review_library_interface lib
6. ADuM1200AR: This could be imrpved with directionality indicators (small triangles):
2017-09-24 22_00_33-part library editor -- d__kicad_kicad-library-review_library_interface lib

Pin-placement is fine for me ... the rest of this PR looks good!

Great work!

JAN

**Comment by Misca1234** [comment]
I was thinking of adding more of  SN75LBC176D but I thought it would be to mich but np, I will add them.
I add the triangles as well

**Comment by Misca1234** [comment]
I could not add the PLCC variant of XXLBC176, the exisitng PLCC-20 is 1 mm to large in X and Y directions

I changed the offset to 20 
I added the SOIC variants 
I added the direction triangles

bild

bild

bild

bild

bild

**Comment by jkriege2** [comment]
Hi!

I just scanned through the new version ... Some remarks:
1. Please elongate the lines on the resistor in AD5293, AD5290
2017-09-26 20_16_03-part library editor -- d__kicad_kicad-library-review_library_interface lib
2. In ADuM1201AR the lower triangle is the wrong way round

The rest looks good to me ... should I merge this way, or will you do more fixes?

Best,
JAN

**Comment by Misca1234** [comment]
You can merge it, I can make part 3 tomorrow

**Comment by jkriege2** [comment]
please fix at least item 2, which is an actual bug, above ... item1 can be in the next PR ...

**Comment by Misca1234** [comment]
All three issues fixed

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
