### PR TITLE
Add 74HC240 part

### PR DESCRIPTION
**Pull request by cydanil**
Add the 74HC240 Octal buffer/line driver; 3-state; inverting device symbol, as described in the [ attached datasheet](https://github.com/KiCad/kicad-library/files/706025/74HC_HCT240.pdf), to the 74xx library.

### CODE REVIEW

**Comment by cydanil** [comment]
I got a better hang at making parts, and found that this drawing violates the rules 3.1, 3.6, and 3.8.
I will make the necessary amends first.

**Comment by jkriege2** [comment]
Hi1

thanks for the contribution. First of all: We have a set of rules (KLC) for symbols for this lib (see here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention and note we're discussing an improved version here: https://github.com/SchrodingersGat/kicad-library/wiki/KLC and here: https://github.com/KiCad/kicad-library/issues/879

Also there exist Python-scripts to check (and in some cases fix) these rules: https://github.com/KiCad/kicad-library-utils

Now for your PR:
1. please split this pr for the 74xx.lib and the 6N137 parts ... then it's easier to review!
2. On the 74xx.lib, please note that there are severaldiscussion ongoing ... as these libs are not even near our KLCs ;-):
     - https://github.com/KiCad/kicad-library/issues/605
     - https://github.com/KiCad/kicad-library/issues/892
3. Concerning your 74HC240 version: Please make outline 0.01 thick and "fill with background" (yellow), make pins 0.2" long, VCC should be on top-edge, GND on bottom-edge and please add description to 74HCT240 (it#s not automatically copied in ALIASes), footprint field should be hidden be empty, as this is available (with the same pinput) in different packages. the FPFilters should contain filters that match all these packages: e.g. `DIP*W7.62mm*`, `TSSOP*4.4x6.5mm*Pitch0.65mm*`, `SSOP*5.3x7.2mm*Pitch0.65mm*`, `SOIC*7.5x12.8mm*Pitch1.27mm*` ... based on your datasheet
4 Concerning the 6N135-devices: Please also add description... to the ALIASes, we now uses LED-symbols as defined by IEC, i.e. non-filled triangle, see e.g. `VO615A`: 2017-01-15 18_37_49-part library editor d__kicad_kicad-library-review_library_opto lib, also please clear the footprint field (observe the different versions in the datasheet!) and use filters based on thise in `VO615A` that also are available in comparable packages, also: Why do you use a different symbol style for VO2630/VO2631?

Best,
JAN

**Comment by cydanil** [comment]
Hi Jan,
Thank you for taking the time to get back to me, and pointing me on the right track.
I'll do the amend to the pull request, as you've suggested, and I'm currently working on the issues you've highlighted.

However, I've made the pins a bit longer (increased the length by 1.27mm) as suggested in rule 3.2, as the numbering on pin 1 and 19 was messy (overlapping the inverted graphic sign). 

It now looks so:
pin_numbering_issue

Should I make them even longer, or is that acceptable?

Regarding the optos, I draw them in different ways as I wasn't sure which is acceptable, likewise for the led component within. I'll amend these.

Thanks again,
Cyril

**Comment by jkriege2** [comment]
I would leave the pin lenght as is ... this isn't really nice, but is done often ... and IMHO the too-long-pins look a bit ugly ;-)

Best,
JAN

**Comment by cydanil** [comment]
Okay, I believe it should now be good!
I added the footprints to the filters, and fixed the drawings, and will do a separate pull request for the optocouplers.

Thanks,
Cyril

**Comment by jkriege2** [comment]
Hi!

somehow you lost the background and line-width of outline (Please make outline 0.01 thick and "fill with background" (yellow)).

Also the FPFilters should not list the exact footprint, but should be:
- `DIP*W7.62mm*`
- `SOIC*7.5x12.8mm*Pitch1.27mm*`
- `TSSOP*4.4x6.5mm*Pitch0.65mm*`
- `SSOP*4.4x6.5mm*Pitch0.65mm*`

Best,
JAN

**Comment by cydanil** [comment]
Thank you for your patience.
 I've amended the filters and outlines.

Cyril

**Comment by jkriege2** [comment]
Nce work1
THANKS,
JAN

**Pull request merged**
