### PR TITLE
Fixes for ADP1108 (and added all aliases)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR fixes the ADP1108 symbol, adds a proper description and also adds all aliased parts

### CODE REVIEW

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
Sorry @SchrodingersGat, trying to get the check script up and running again with some improvements. Probably going to be to a lot of garbage here by the time I'm done. :P

**Comment by SchrodingersGat** [comment]
No problem. It'll be great to have it working once more.

**Comment by reportingsjr** [comment]
Yeah, sorry about that. I had to move and it ended up being kind of awful so my server is currently down.

On the plus side, I improved the script so it now comments the errors on to the pull request. I can't get it working on this repo though.

Any chance you have admin access to this repo?

**Comment by SchrodingersGat** [comment]
Nope sorry, only collaborator rights.

**Comment by CarlPoirier** [comment]
Hi Oliver,

I think you can make it smaller and use 100mils pins. Besides that, it's great.

image

DEF ADP1108 U 0 30 Y Y 1 F N
F0 "U" -300 350 50 H V L CNN
F1 "ADP1108" 150 350 50 H V L CNN
F2 "" 200 0 50 H V C CNN
F3 "" 200 0 50 H V C CNN
ALIAS LT1108 ADP1108-3.3 ADP1108-5 ADP1108-12
$FPLIST
 SOIC*
 DIP*
$ENDFPLIST
DRAW
S -300 -300 300 300 0 1 10 f
X ILIM 1 -100 400 100 D 50 50 1 1 I
X VIN 2 100 400 100 D 50 50 1 1 W
X SW1 3 400 -100 100 L 50 50 1 1 P
X SW2 4 400 100 100 L 50 50 1 1 P
X GND 5 0 -400 100 U 50 50 1 1 w
X AO 6 -400 -100 100 R 50 50 1 1 C
X SET 7 -400 100 100 R 50 50 1 1 I
X FB/SENSE 8 400 0 100 L 50 50 1 1 I
ENDDRAW
ENDDEF

**Comment by reportingsjr** [comment]
test this please

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: ADP1108
  Violating EC01 - Extra Checking
    Check pins names against pin types.
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
# ADP1108
```

**Comment by SchrodingersGat** [comment]
@CarlPoirier fixed!

**Comment by reportingsjr** [comment]
```
Please fix these issues:
checking component: ADP1108
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
Components Updated: 1
# ADP1108
```

**Comment by reportingsjr** [comment]
```
Please fix these issues:
Components Updated: 1
# ADP1108
```

**Comment by SchrodingersGat** [comment]
@reportingsjr I think that your script needs some tweaking - I've fixed all KLC issues and now it's failing on a blank error :p

**Comment by SchrodingersGat** [comment]
Fixed conflicts

**Pull request merged**
