### PR TITLE
Ca56

### PR DESCRIPTION
**Pull request by Misca1234**
Added 
CA56-12CGKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12CGKWA(Ver.9A).pdf

CA56-12EWA
http://www.kingbrightusa.com/images/catalog/SPEC/CA56-12EWA.pdf

CA56-12SEKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SEKWA(Ver.7A).pdf

CA56-12SURKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SURKWA(Ver.8A).pdf

CA56-12SYKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CA56-12SYKWA(Ver.6A).pdf

CC56-12SYKWA 
http://www.kingbright.com/attachments/file/psearch/000/00/00/CC56-12SYKWA(Ver.6A).pdf

CC56-12YWA
http://www.kingbrightusa.com/images/catalog/SPEC/CC56-12YWA.pdf

CC56-12SEKWA 
http://www.kingbright.com/attachments/file/psearch/000/00/00/CC56-12SEKWA(Ver.7A).pdf

CC56-12CGKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CC56-12CGKWA(Ver.8A).pdf

CC56-12GWA 
http://www.kingbrightusa.com/images/catalog/SPEC/CC56-12GWA.pdf

CC56-12SURKWA
http://www.kingbright.com/attachments/file/psearch/000/00/00/CC56-12SURKWA(Ver.7A).pdf

CC56-12SRWA
http://www.kingbrightusa.com/images/catalog/SPEC/CC56-12SRWA.pdf

CC56-12EWA
http://www.kingbrightusa.com/images/catalog/SPEC/CC56-12EWA.pdf

to
modules/packages3d/Displays.3dshapes

Both the CC (common cathode) and CA (common anode) variant is using CA's footprint

The existing Cx56-12 was a CA56-12EWA 

Removed
libraries/display/CA56-12
libraries/display/CC56-12
modules/packages3d/Displays_7-Segment.3dshapes/Cx56-12.fcstd
modules/packages3d/Displays_7-Segment.3dshapes/Cx56-12.wrl
See also 
https://github.com/KiCad/Displays_7-Segment.pretty/pull/5

kicad-libray
https://github.com/KiCad/kicad-library/pull/1413

Displays.pretty
https://github.com/KiCad/Displays.pretty/pull/22

packages3D
https://github.com/KiCad/packages3D/pull/85

packages3D-source
https://github.com/KiCad/packages3D-source/pull/22

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
Either make two symbols (com anode, cathode) without aliases but with a footprint filter that allows selecting the available colors for each symbol.

Or make one symbol for each available display with the footprint field selected.

**Comment by Misca1234** [comment]
Then I have to add the colour name in the foot print name

**Comment by Misca1234** [comment]
Removed aliases

**Comment by Misca1234** [comment]
Moved 7 segment CA56 displays from Displays.3dshapes to Displays_7-Segment.3dshapes according to comment in 
https://github.com/KiCad/Displays_7-Segment.pretty/pull/5

**Comment by poeschlr** [comment]
For the stable releases it is not a good idea to create a new lib. (the pretty lib is different, it already existed. Creating the new 3dshapes lib is ok.)
Also you only pushed the dcm file.

Splitting the display.lib will be done with the release of kicad 5 (sorry for the confusion.)

**Comment by Misca1234** [comment]
Ok, i move them back then

**Comment by poeschlr** [comment]
Looks good

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
