### PR TITLE
add texas instruments TPS2513/4 usb charge controllers

### PR DESCRIPTION
**Pull request by Telemin**
This commit adds the TPS2513(A) and TPS2514(A) charge controllers from TI. 

[http://www.ti.com/lit/ds/symlink/tps2513.pdf](url)

tps2513
tps2514

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @Telemin , great symbols. May I request that you change the footprint filters for each from *SOT-23-6* to *SOT-23-\** - this will allow the footprint filtering tool to match other versions of the footprint e.g. *SOT-23-6_HandSoldering*.

Cheers,

**Comment by Telemin** [comment]
done.

**Comment by SchrodingersGat** [comment]
Further inspection reveals a few other issues that need to be addressed:

* Part fails KLC "extra checking" - Run *python checklib.py texas.lib -c=TPS2513 --enable-extra* gives:

```
checking component: TPS2513
  Violating EC01 - Extra Checking
    Check pins names against pin types.
  Violating EC03 - Extra Checking
    Check part reference, name and footprint position and alignment
  Violating EC04 - Extra Checking
    Check line width and background for box outlines parts.
```

EC01 - Pin-type of pin GND should be set to Power Input
EC01 - Pin-type of pin IN should be set to Power Input

EC04 - Set symbol outline to 0.01" (currently set to 0.00")

* Fix GND pin numbering - GND should be pin 2 but you have it set to pin 1 (duplicate of DP1)

* Capitalize pin names to match datasheet (should be "GND" not "Gnd" and "IN" not "In")

* Commonize the pin positions - the symbol layout for TPS2513 is good, I'd like to see TPS2514 have the same shape / pin locations, except that pins 3/4 are "NC" and invisible. Having a common symbol aesthetic allows users to swap similar component symbols with minimal schematic changes, if that makes sense.

Cheers :)

**Comment by Telemin** [comment]
Okay fixes added for EC01 and EC04 failures.

I'm not sure exactly what the EC03 failure means, is the KLC going to get updated at some point to explain all these things?

**Comment by SchrodingersGat** [comment]
Thanks, I'll merge this, these look good.

Regarding EC03, it is still very confusing - we hope to update the KLC rules to be clearer in the future.

**Comment by diggit** [comment]
@Telemin @SchrodingersGat EC03 is about text fields positions and alignments. These are only suggestion and not KLC rule.
If you wand to know more about what EC03 (or any other rule) doesn't like on your symbol, use `-vv` argument fot `checklib.py` script.

**Pull request merged**
