### PR TITLE
Add new component (LM4810) to audio.lib and move LM4811 from digital-audio.lib to audio.lib.

### PR DESCRIPTION
**Pull request by mifi2909**
The LM4810_TSSOP did not exist in the libraries and is a new addition.
The LM4810 is in the same family as the LM4811. Both are dual headphone amplifiers and are linear devices for audio use. The LM4811 has push button volume control, the LM4810 does not. The LM4811 existed in digital-audio.lib, but I think the audio.lib library is better.

From the datasheet:
"The LM4810 is a dual audio power amplifier capable of delivering 105mW per channel of continuous average power into a 16Ω load with 0.1% (THD+N) from a 5V power supply. Boomer audio power amplifiers were designed specifically to provide high quality output power with a minimal amount of external components. Since the LM4810 does not require bootstrap capacitors or snubber networks, it is optimally suited for low-power portable systems. The unity-gain stable LM4810 can be configured by external gain-setting resistors. The LM4810 features an externally controlled, active- high, micropower consumption shutdown mode, as well as an internal thermal shutdown protection mechanism."

### CODE REVIEW

**Comment by jkriege2** [comment]
Please move pins on 100mil grid:
```
Checking symbol 'LM4810_TSSOP':

  Violating Rule 4.1 - Pin placement

    Pins must be placed on regular grid, and be of correct length

    Pins not located on 100mil grid:

     - Pin VOUT1 (1), @ (400, 250)

     - Pin VIN1 (2), @ (-400, 250)

     - Pin BYPASS (3), @ (150, -600)

     - Pin SHDN (5), @ (-400, -250)
```

**Comment by mifi2909** [comment]
It seems deleting a component from digital-audio.lib forces a host of checks on the rest of the library, listing lots of problems for components that were untouched by this change.
Is there something I can do to prevent the failing checks (other than fixing all other components in digital-audio.lib, which will take a serious amoutn of time)?

**Comment by jkriege2** [comment]
No, But I will ignore them ;-)

cu
JAN

**Comment by jkriege2** [comment]
PS: Thanks for the work you put in!

**Comment by mifi2909** [comment]
Thank you for the corrections. 
We will meet again at a next component!   ;-)

**Comment by jkriege2** [comment]
A final remark for your next PR: A screenshot +datasheet link in the PR-comment usually makes review much easier (especially for footprints!)

**Comment by jkriege2** [comment]
... and see you on your next PR ;-) ... looking forward to it!

**Comment by mifi2909** [comment]
I will try to remember that @jkriege2 . I am working on another one.
Your remarks about the screenshot and a link to the datasheet are good points.
Would it be an idea to add those to this page: [wiki/How-To-Contribute](https://github.com/KiCad/kicad-library/wiki/How-To-Contribute) ?
m

**Comment by evanshultz** [comment]
It's in the [FAQ ](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions) with the other related info.

**Pull request merged**
