### PR TITLE
Adding silabs si3210

### PR DESCRIPTION
**Pull request by fid0did0**
adding proslic silabs si3210, a complete analog telephone interface
datasheet: [si3210-38974.pdf](http://www.mouser.com/ds/2/368/si3210-38974.pdf)
si3210_kicad

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @fid0did0 is there a particular reason you have placed all the GND pins at the top?

As per the [KLC 4.5](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) we try to keep ground pins at the bottom of symbols

**Comment by fid0did0** [comment]
Hi @SchrodingersGat, and thanks for your feedback.
I simply replicate the pin position as shown at pg. 16 of the datasheet.
But if you have a good argument I can change it as you requested.
Is it ok to exchange the top side with the bottom or there are others rule for the vcc?

Or if you have better advice, please tell me and I will change the pins accordingly.

Bye.

**Comment by SchrodingersGat** [comment]
The requirements are laid on in the KLC linked in my previous comment.

Generally:

* Inputs on left
* Outputs on right
* Positive power pins on top
* Negative power pins on bottom

If that cannot be achieved for a particular symbol for a good reason, that's fine. Your symbol should be able to be adjusted without much work :)

**Comment by fid0did0** [comment]
Hi @SchrodingersGat,
I updated the symbol to have 
* Positive power pins on top
* Negative power pins on bottom
I prefer to have the other pins grouped per functions, but in this way, input and output are mixed left and right.
I also keep the DC/DC converter pins on the bottom like in the datasheet. IMHO this will help to keep separate the different circuit belonging to the different chip function.

si3210

Please let me know your opinion. No problem from my side to change again for good reason.

Bye.

**Comment by SchrodingersGat** [comment]
That looks great, thanks for your contribution :)

**Comment by fid0did0** [comment]
Hi @SchrodingersGat,
you was too fast!
I not yet updated in git.

**Comment by fid0did0** [comment]
@SchrodingersGat, how to proceed now?

**Comment by SchrodingersGat** [comment]
Whoops. I have reverted this, lmk when you have pushed the changes

**Comment by fid0did0** [comment]
@SchrodingersGat, 
I see something strange in github.
I see two branches in my fork, one pointing to the latest update and one to the old.
I guess we have two option:
1) I close this PR and open a new one.
2) instead of revert, you should rebase to delete the reference to the old branch.

What you prefer?

**Comment by SchrodingersGat** [comment]
Option 1 (new PR) is probably the easiest. Sorry for the inconvenience.

**Comment by fid0did0** [comment]
New PR issued and checked by Travis CI.

Bye.

Von: Oliver [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. Juni 2017 08:52
An: KiCad/kicad-library <kicad-library@noreply.github.com>
Cc: Giuseppe Lippolis <giu.lippolis@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [KiCad/kicad-library] Adding silabs si3210 (#1273)

Option 1 (new PR) is probably the easiest. Sorry for the inconvenience.

**Pull request merged**
