### PR TITLE
Add symbols for Parallax Propeller microcontroller.

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet](https://www.parallax.com/sites/default/files/downloads/P8X32A-Propeller-Datasheet-v1.4.0_0.pdf).

The DIP and LQFP footprints already exist, and I have [an open PR for the QFN footprint](https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/72).

p8x32a-d40

p8x32a-m44

p8x32a-q44

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please match the new library naming scheme and place these in `MCU_Parallax.lib` 

Microcontrollers.lib will be deprecated for v5

**Comment by ppelleti** [comment]
I've created a new `MCU_Parallax.lib`.

Is there a list of deprecated libraries somewhere?

**Comment by ppelleti** [comment]
Oops, don't merge this yet.  I realized I left off a couple of pins.

**Comment by ppelleti** [comment]
OK, should be ready to merge now.  I had left out one of the VDD pins and one of the VSS pins on the DIP version of the Propeller.

**Pull request merged**
