### PR TITLE
Add IRM-03-XS Symbols

### PR DESCRIPTION
**Pull request by svheymann**
The rest of the changes happend as i simply saved the file in kicad.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work, the only thing missing are all the NC-pins that are in the footprint, but not in the symbol. Please add them as hidden NC-pins 5,10,11,12,13,15,17,22,24,26

Best,
JAN

**Comment by svheymann** [comment]
Is it ok to put all NC pins in one place or should i better make the symbol larger?

**Comment by jkriege2** [comment]
I think its better to make them a larger symbol otherwise they might automatically get connected (which we don't really want)

JAN

**Comment by svheymann** [comment]
done.

**Comment by jkriege2** [comment]
Hmmm I would order the pins as follows:
2017-02-12 12_11_21-part library editor d__kicad_kicad-library-review_library_ac-dc lib

Otherwise it looks a bit strange in the schematic, when the NC-pins are invisible:
2017-02-12 12_13_01-eeschema kicad-library-review _ d__kicad_kicad-library-review-project
2017-02-12 12_14_07-eeschema kicad-library-review _ d__kicad_kicad-library-review-project

**Comment by svheymann** [comment]
I tried some variants before but yours is definitly the best.

**Comment by jkriege2** [comment]
nice work!
JAN

**Pull request merged**
