### PR TITLE
Added LTC2208 to linear.lib (16-Bit, 130Msps ADC)

### PR DESCRIPTION
**Pull request by yo3iti**
Checked with Travis script:

Component: LTC2208
  No violations found

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@yo3iti we are currently working on the scripts to improve the output of Travis and to fix a couple of bugs. Should be finished soon :)

**Comment by yo3iti** [comment]
Thx, Oliver, for letting me know.

Regards,

Miron

**Comment by Marsfan** [comment]
@SchrodingersGat it is the earlier commits, they added some AD series parts, and travis has picked up on those. Probably needs a couple of minor fixes. Not too sure what, I'm a bit busy and just happened to come across this.

**Comment by jkriege2** [comment]
Hi!

could you please split this PR:
1. The parts in linear.lib
2. The parts in analog_devices.lib

... and do we really need the changes to the .gitignore-file? That's just for MacOS, right? Wouldn't it be enough to simply not add these files to the repo?

Best,
JAN

**Comment by yo3iti** [comment]
Hi, Jan,

I'd gladly do the split but I don't know how.
BR
Miron

**Comment by poeschlr** [comment]
> I'd gladly do the split but I don't know how.
The easiest (least error prone) way i know of is to do the following:
While on the current branch copy the changed files somewhere else (makes everything a bit faster)
after that make sure you have your master in sync with the master of this repo.
git remote add upstream [path to this repo]
git checkout master
git fetch upstream
git pull upstream master
git push

make two new branches. (Do the following for each branch)
git checkout master (always branch away from master!!)
git checkout -b meaningful-branch-name
git push --set-upstream origin meaningful-branch-name
copy the changes for this branch (example linear.lib and linear.dcm) into the appropriate directory
git add -u
git commit -m "meaningful commit message"
git push

When all the branches are pushed to the github server simply open a pull request for both branches.
After that you can close this branch.

good git tutorials if you are interested:
https://www.atlassian.com/git
A good video that explains what git is and how it works:
https://www.youtube.com/watch?v=ZDR433b0HJY

**Comment by yo3iti** [comment]
Danke, Rene.

Let me try. Something new to learn - git. ;)

M

**Comment by yo3iti** [comment]
Hi, Rene,

Once again, thank you for your help.
Anyway, a bit too complicated for me. I gave up. :)

I closed all my PRs. Will use the libraries for my own, this entire process it is too tedious for me.

Regards and thank you all.

Miron

**Pull request closed without merging**
