### PR TITLE
applying KLC to ESD Protection library

### PR DESCRIPTION
**Pull request by ghost**
Changing pins at USB6B1  Pin 5 -> 8 ; Pin6 ->7 ; Pin 7->6 Pin8 -> 5
see Datasheet http://www.st.com/content/ccc/resource/technical/document/datasheet/3e/ec/b2/54/b2/76/47/90/CD00001361.pdf/files/CD00001361.pdf/jcr:content/translations/en.CD00001361.pdf

# USB6B1
#
DEF USB6B1 U 0 40 Y Y 1 F N
F0 "U" -250 200 50 H V C CNN
F1 "USB6B1" 175 200 50 H V C CNN
F2 "Housings_SOIC:SOIC-8_3.9x4.9mm_Pitch1.27mm" -25 -300 50 H I C CNN
F3 "" 0 0 50 H I C CNN
$FPLIST
 SO*
 SOIC*
$ENDFPLIST
DRAW
S -300 -250 300 150 0 1 10 f
X Vcc 1 -400 100 100 R 50 50 1 1 W
X I/O1 2 -400 0 100 R 50 50 1 1 B
X I/O2 3 -400 -100 100 R 50 50 1 1 B
X GND 4 -400 -200 100 R 50 50 1 1 W
X GND 5 400 -200 100 L 50 50 1 1 W
X I/O2 6 400 -100 100 L 50 50 1 1 B
X I/O1 7 400 0 100 L 50 50 1 1 B
X Vcc 8 400 100 100 L 50 50 1 1 W
ENDDRAW
ENDDEF
#

### CODE REVIEW

**Comment by jkriege2** [comment]
Please fix merge conflicts!

**Comment by LNnetAVR** [comment]
[ESD_Protection.zip](https://github.com/KiCad/kicad-library/files/962177/ESD_Protection.zip)
I hope merge conflicts are fixed with files in ESD_Protection.zip.
Following image shows the changed cpmponent
changed_usb6b1

**Comment by jkriege2** [comment]
Hi!

please fix the merge conflicts in this PR, i.e. pull/merge the current master of kicad-library into your branch of your fork of this repo. Then the conflicts should also be solved here. 

From the symbol image I can already give some hints on what needs to be changed (please also review https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention and https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions):
1. Move the Vcc pins to the top of the symbol and the GND-pins to the bottom.
2. You can stack the two Vccs and the two GNDs respectively (one of them then has to be hidden)
3. maybe add a sketch of the internal structure of this (rather simple) IC, e.g. as done here:
2017-04-27 21_08_10-part library editor d__kicad_kicad-library-review_library_esd_protection lib

Best,
JAN

**Comment by LNnetAVR** [comment]
Hi JAN,
the changes , which have to done are very simple: The pin numbers on the right side of the sysmbol must be mirrored:
The image from current library "library/ESD_Protection.lib" (date 17.03.2017)
current_usb6b1

has to be change in

changed_usb6b1

I hope that the short circuit, that the symbol generates in the real world, is thus removed.

Best regards
Eberhard

**Comment by jkriege2** [comment]
I'm a bit confused: As you already opened this PR, please make sure this PR exactly contains the intended fix ... that's what a PR is for ... or are you seeking for someone who does the bugfix in the lib (e.g. because you don't know Git/GitHub very well) ... in the latter case a bug-ISSUE would have been the right thing to do ... 

JAN

**Pull request closed without merging**
