### PR TITLE
Adding Zilog Z32F06423AKE and Z32F06423AEE Microcontroller

### PR DESCRIPTION
**Pull request by lightlace**
Hi,

here is my first commit for the KiCAD Library:
i finished a symbol for the Z32F06423AKE MCU by Zilog.
I hope, it's useful.

z32f06423ake

### CODE REVIEW

**Comment by lightlace** [comment]
My pull request has changed Z80CPU and Z8530 somehow, so i had to fix that first, but now it should look okay, as Travis has passed it.

**Comment by lightlace** [comment]
I've also added the Z32F06423AEE MCU now. It's the LQFP-48 version.

**Comment by poeschlr** [comment]
Did we take to long to look at your pull request or did something go wrong?

**Comment by lightlace** [comment]
Hi,

it was my fault - i messed something up with my libraries.
I will try again.

Thanks in advance,
Fabian

**Pull request closed without merging**
