### PR TITLE
Added LT5560

### PR DESCRIPTION
**Pull request by flaminggoat**
Added LT5560
0.01MHz to 4GHz Low Power Active Mixer.

image

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution ... could you please do some more minor changes to your symbol?
1. change the outline of the box to 0.01"
2. could you make all pins equally long (power pins!)
3. could you set the footprint field to `Housings_DFN_QFN:DFN-8-1EP_3x3mm_Pitch0.5mm` (+ hide it) and the footprint filter to `DFN*3x3mm*Pitch0.5mm*`


Thanks,
JAN

**Comment by jkriege2** [comment]
... and could you please fix the conflicts ... otherwise we can't merge!

**Comment by diggit** [comment]
@flaminggoat 
in addition to @jkriege2 , please update your kicad. Your version is outdated. (note space additions in diff) New stable was released. If you want to be sure, I suggest using some recent nightly build. (no necessarily).

I don't know your OS to be more specific, so here is [quick link to download page](http://kicad-pcb.org/download/).

**Comment by flaminggoat** [comment]
OK, I think I have sorted the issues.

**Comment by jkriege2** [comment]
Hi!

there are also conflicts ... could you please resolve them (e.g. by pulling the GitHUB master)?

Best,
JAN

**Comment by jkriege2** [comment]
Could you please also remove the changes from .gitignore?

Thanks,
JAN

**Comment by jkriege2** [comment]
Hi!

one final remark:
could you move the REFDES+Name as shown here:


Then I'll merge.
Thanks for all the work,
JAN

**Comment by jkriege2** [comment]
Thanks for the contribution!

**Pull request merged**
