### PR TITLE
Fix name field

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR fixes all violations of KLC 3.7 (value field must match symbol name)

These errors were causing issues with nightly builds - https://lists.launchpad.net/kicad-developers/msg28290.html

### CODE REVIEW

**Comment by jkriege2** [comment]
What are all these tildes `~`in the names? Wasn't there something that parts with tilde are marked as power-supply symbol?
JAN

**Comment by SchrodingersGat** [comment]
Weird, I didn't see those parts. Fixed.

**Comment by jkriege2** [comment]
When removing the tilde: Did you do it in KiCAD or with a texteditor? In the latter case: Could you please open the lib in libEdit and save it there? I think when I ran into that the last time, the ~ was generated by KiCAD ...

cu
JAN

**Comment by SchrodingersGat** [comment]
Ah, right. It occurs when the name field is set to invisible! 

I will add a check for this to KLC.

**Comment by SchrodingersGat** [comment]
It's great when Travis works well :)

**Comment by SchrodingersGat** [comment]
@jkriege2 can you merge this so we can tackle https://github.com/KiCad/kicad-library/pull/1078 ? :)

**Pull request merged**
