### PR TITLE
ams: add CCS811 indoor air qualtiy sensor

### PR DESCRIPTION
**Pull request by ChristianHirsch**
@SchrodingersGat added CCS811 indoor air quality sensor. I don't know why the rule 4.6 is violated, any hints?
More ams sensors are coming..

### CODE REVIEW

**Comment by suzizecat** [comment]
@ChristianHirsch It seems that you used the type `INPUT` for an `SDA` pin (i believe it's an I2C data pin). If this is the case (which Travis assume) you should use the pin type `BIDIRECTIONAL` since you got data in both input and output.

BTW, you should link the datasheet and add a picture of your symbol to help a quick review 😉

**Comment by ChristianHirsch** [comment]
Thanks @suzizecat for your quick reply! I fixed the pin type, no errors here. And thanks for the hints on the reviews, I'll add an pic and the datasheet the next time :)

**Comment by suzizecat** [comment]
You're welcome !
You should add the pic and the DS anyway, since the librarian may want to check if the pins length is right, the position between pins seems good and so on. They may also check your symbol against the actual manufacturer specifications. 
Since it's pretty easy to add, i would strongly recommend you to do so 😉 
(You can add a pic by copy-pasting it into github and the same for the link, just paste the URL and it'll do the job)

**Comment by ChristianHirsch** [comment]
Hi @suzizecat,
here is the image:
image
Here is the link to the datasheet: [http://ams.com/eng/content/download/951091/2269479/471718](http://ams.com/eng/content/download/951091/2269479/471718)
Hope that helps :)

**Comment by suzizecat** [comment]
Thanks =)

It looks fine, but since you should group pins by function ([KLC 4.4.ii](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention#4-general-rules-for-symbols)), IMO it would be better to : 
- put `INT` with I2C pins,
- put `ADDR` near I2C pins,
- put `AUX` near `SENSOR`, with a space,
-  add a space between `RESET` and I2C pins,

And maybe reduce a little the width of the component. 

Good job !
julien

**Comment by ChristianHirsch** [comment]
Thanks @suzizecat, I applied your suggestions:
image
Is this better?

**Comment by suzizecat** [comment]
After looking at it, i find it a little bit squashed in... I often try to make my symbols as narrow as possible but i don't quite like the look... 

Anyway, for me, it look fine, let's wait for an actual librarian to check it out ! 😉

**Comment by ChristianHirsch** [comment]
Hi @SchrodingersGat, is there anything I need to change?

**Comment by poeschlr** [comment]
I think this symbol might be better suited in the sensors library.

This part is supplied in only one package.
Please set the footprint field to `Housings_LGA:AMS_LGA-10-1EP_2.7x4mm_Pitch0.6mm`
and the footprint filter to `AMS?LGA*EP*2.7x4mm*Pitch0.6mm*` (Exclude pin count, include size specification)

Otherwise nice symbol.

**Comment by SchrodingersGat** [comment]
@poeschlr I'm fine with this either staying in AMS library or moving to sensors.lib, given that it's all [going to be rearranged anyway](https://github.com/KiCad/kicad-library/issues/1402).

@ChristianHirsch if you make the changes suggested above, and want to leave it in this library, I'm happy to merge.

**Comment by ChristianHirsch** [comment]
@poeschlr @SchrodingersGat I'll add two more sensors from ams: [AS7276](http://ams.com/eng/Products/Spectral-Sensing/Multi-spectral-Sensing/AS7262) and [ENS210](http://ams.com/eng/Products/Environmental-Sensors/Relative-Humidity-and-Temperature-Sensors/ENS210), and propably some more in the future. I don't mind putting them in the sensors lib, you guys need to tell me :)

**Comment by poeschlr** [comment]
In future we will go away from a manufacturer based library system towards a function based system.
So please put them into sensors.lib

More details about the future see issue https://github.com/KiCad/kicad-library/issues/1402 (The new libs will be created in a new repo. This library will be the legacy lib that will support kicad 4, the new system will be used in kicad 5.)

**Comment by ChristianHirsch** [comment]
@poeschlr @SchrodingersGat fixed the footprint field/filter and moved it in the sensors lib.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution @ChristianHirsch

**Pull request merged**
