### PR TITLE
Added TCA9535PWR and change description of TCA9555PWR (w/ pull-ups)

### PR DESCRIPTION
**Pull request by jaessy77**

### CODE REVIEW

**Comment by jaessy77** [comment]
http://www.ti.com/lit/ds/scps201d/scps201d.pdf

**Comment by jaessy77** [comment]
http://www.ti.com/lit/ds/scps201d/scps201d.pdf

**Comment by Misca1234** [comment]
@jaessy77 
Can you provide screen shots of the symbols?
A lot can be told by an image.

**Comment by jaessy77** [comment]
hi stefan,

the symbols are the same than on the original, i just added the similar
device and changed the Text . I my applications I was strongly recommended
not to have the interal pullups ...

Am 27.08.2017 09:09 schrieb "Stefan" <notifications@github.com>:

**Comment by jaessy77** [comment]
corrected description of Crystal_GND24_Small:
grafik
corrected description of Crystal_GND23_Small:
grafik
corrected description of Crystal_GND2_Small:
grafik
corrected description of Crystal_GND3_Small:
grafik

**Comment by jkriege2** [comment]
please fix the conflicts!

Best,
JAN

**Comment by jaessy77** [comment]
ups .. what happened there ??
Try to resolve this evening .. sorry ..

**Comment by jkriege2** [comment]
... also if possible, please don't combine two independent topics into one PR ... it would be better to post a separate PR for the quartz-stuff ...

**Comment by jaessy77** [comment]
Hi .. should now be resolved. Synced my GIT and tried the texas parts .. looks good.
The twice pull request were occoured with the silly TortoiseGIT installed on my laptop .. it hooked up and then the "miracle" of having twice stuff as an PR happend .. Sorry ..

**Comment by jkriege2** [comment]
Hi!
I just reopened ... hope that's fine with you, or was there a reason why you closed this PR?

Basically everything looks fine. I only want to ask you for one change:
TCA9555xyz and TCA9535xyz share the same symbol, so it is enough to have one symbol for each package, e.g. TCA9555DBR + TCA9555PWR + TCA9555RGER and the have the TAC9535 variants as ALIASes of these ... Could you do that? This makes lib management in the future much easier ...

I will merge as soon as this is done.

Best,
JAN

PS: I'll be away for a few days, so could be I will only be able to merge on tuesday or wednesday ... so please be patient if that happens ... I will come back to this PR next week ... unsless someone else merges, when the changes are done ( @SchrodingersGat @evanshultz @poeschlr )

**Comment by jaessy77** [comment]
Sounds reasonable, I will do it.

Am 28.09.2017 21:35 schrieb "Jan W. Krieger" <notifications@github.com>:

Hi!
I just reopened ... hope that's fine with you, or was there a reason why
you closed this PR?

Basically everything looks fine. I only want to ask you for one change:
TCA9555xyz and TCA9535xyz share the same symbol, so it is enough to have
one symbol for each package, e.g. TCA9555DBR + TCA9555PWR + TCA9555RGER and
the have the TAC9535 variants as ALIASes of these ... Could you do that?
This makes lib management in the future much easier ...

I will merge as soon as this is done.

Best,
JAN

PS: I'll be away for a few days, so could be I will only be able to merge
on tuesday or wednesday ... so please be patient if that happens ... I will
come back to this PR next week ... unsless someone else merges, when the
changes are done ( @SchrodingersGat <https://github.com/schrodingersgat>
@evanshultz <https://github.com/evanshultz> @poeschlr
<https://github.com/poeschlr> )

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/KiCad/kicad-library/pull/1563#issuecomment-332941463>,
or mute the thread

**Comment by jaessy77** [comment]
Pushed the changed library into my Fork. Now we have the ALIASE feature used for the TCA9555xyz and TCA9353xyz like suggested.

**Comment by jkriege2** [comment]
Nice work!

Thanks,
JAN

**Pull request merged**
