### PR TITLE
Add MCP42x2 Family

### PR DESCRIPTION
**Pull request by suzizecat**
Hi all !

I just created the microchip dual digital rheostat symbols
These are MCP4232 4242 4252 and 4262.

Here is the DS : http://ww1.microchip.com/downloads/en/DeviceDoc/22060b.pdf

And the pics : 

image

image

image

Thanks for the reviews !

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution. I spotted two small problems, could you please fix them?
1. The rheostats in DFN-package have an exposed pad, which is missing in the symbol (the MSOP don't), therefore please split the symbol into `MCP42x2UN` for the MSOP-version and a new symbol `MCP42x2MF` for the 10-pin DFN-version. To the latter, please add a pin 11 PAD (PASSIVE should be OK, as this should either be elft floating or tied tio Vss), situated at the bottom of the symbol.
2. Please add the package at the end of the descriptions

Best,
JAN

**Comment by jkriege2** [comment]
Hi! @suzizecat Are you still interested in this?

Best,
JAN

**Comment by SchrodingersGat** [comment]
@suzizecat please fix conflicts so I can merge :)

**Comment by suzizecat** [comment]
Sorry, missed that...
I'll check it next week

**Comment by poeschlr** [comment]
@suzizecat the microchip lib has already been transferred over to the new repo. Please re submit your symbols to the new repo into the correct lib (Potentiometer_Digital).

**Comment by SchrodingersGat** [comment]
As we are now close to moving all the symbols to the new kicad-symbols repository, this PR will have to be reissued at https://github.com/kicad/kicad-symbols

Thanks for your contributions, and sorry for the inconvenience

**Pull request closed without merging**
