### PR TITLE
Schematic ag12864 e

### PR DESCRIPTION
**Pull request by Misca1234**
Updated the symbol for AG12864E

https://www.digchip.com/datasheets/parts/datasheet/1121/AG-12864E-pdf.php

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
The symbol looks good. But the footprint has the mounting holes as pin number 0. (The mounting holes should not have a pin number.) Would you care to fix this or should i do it?

**Comment by Misca1234** [comment]
Np, i fix it

Here is the branch 

https://github.com/KiCad/Displays.pretty/pull/16

**Comment by poeschlr** [comment]
Thanks

**Comment by Misca1234** [comment]
Thanks

**Pull request merged**
