### PR TITLE
Add spark gap

### PR DESCRIPTION
**Pull request by evanshultz**
Spark gap created in accordance with the IEEE 315-1975 standard using two unfilled triangles and an "E" ref des prefix. Passes all KLC tests.

Symbol image:
image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Nice work @evanshultz - I would suggest that this should go in the ESD_protection.lib library rather than generic devices.

**Comment by jkriege2** [comment]
Hhmmm ... I think this is generic enough for device.lib ... in ESD_protection.lib we have mainly specific devices (with part number and all) ...

cu
JAN

**Comment by evanshultz** [comment]
Thank you @SchrodingersGat and @jkriege2.

I'll move it to ESD_protection if that's the consensus, but it is generic which is why I went with device.lib for the PR. Please bring in the folks that should consider this topic so we can discuss.

**Comment by SchrodingersGat** [comment]
device.lib should be fine :) @evanshultz  can you please add some extra tags to assist with searching e.g. "esd electrostatic" etc

**Comment by evanshultz** [comment]
Done! Anything else?

**Comment by SchrodingersGat** [comment]
Looks great :)

**Pull request merged**
