### PR TITLE
add library sch lora-rfm 96

### PR DESCRIPTION
**Pull request by nghiant92**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution. 

Before we will have a closer review of your symbol, please move it to `rfcom.lib`, which is the correct library for this symbol and add the necessary information: description, keywords and datasheet link.

Best,
JAN

**Comment by jkriege2** [comment]
PLease also fix the errors reported by Travis (click on "Details" next to "continuous-integration/travis-ci/pr — The Travis CI build failed" on this page)!

These scripts check against the rules that we have set for this repo. They are available here:
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

Also we are working on an overhaul of these rules that should go live soon. The current (new) version is available here: https://github.com/SchrodingersGat/kicad-library/wiki/KLC PLease stick to that version. 

You can also run the scripts locally. They arae available here: https://github.com/KiCad/kicad-library-utils

Best,
JAN

PS: Let me know if you need any help or further explanations ;-)

**Comment by nghiant92** [comment]
Hi, I know, thank a lot!

**Comment by jkriege2** [comment]
@nghiant92 Are you still on this?

**Comment by jkriege2** [comment]
While looking at the discussion on the package name, I came back to this ... could you rename this device to `RFM95W-xxxS2` and then add aliases for `RFM96W-xxxS2`, `RFM97W-xxxS2` and `RFM98W-xxxS2`. This way the device follows our usual naming conventions.

Thanks,
JAN

**Comment by Misca1234** [comment]
This push can be closed and deleted

It have been re pushed here 
https://github.com/KiCad/kicad-library/pull/1703

**Pull request closed without merging**
