### PR TITLE
sorting footprints

### PR DESCRIPTION
**Pull request by michal777**
Moved and renamed 3d models to match other pull requests:

### CODE REVIEW

**Comment by michal777** [comment]
KiCad/Resistors_ThroughHole.pretty#4
KiCad/Oscillators.pretty#2
KiCad/Measurement_Points.pretty#1
KiCad/Divers.pretty#2
KiCad/Display.pretty#6
KiCad/Discret.pretty#9
KiCad/Connect.pretty#28
KiCad/Choke_Toroid_ThroughHole.pretty#5
KiCad/Buzzers_Beepers.pretty#3
KiCad/Buttons_Switches_ThroughHole.pretty#4

KiCad/kicad-library#277

**Comment by CarlPoirier** [comment]
Thank you for your contribution!

**Comment by michal777** [comment]
It's not only the PR for oscillators models. I've listed above all PRs that are connected with this one. They may help to finish Divers and Discret libraries (mainly capacitors, resistors and transformers left).

**Comment by CarlPoirier** [comment]
Are they only footprint moves?

I was asking for the courtyard, but if these are all existent stuff, I'll merge them as is.

**Comment by michal777** [comment]
Mainly moving to more appropriate libraries but with some changes:

Two tht resistors arrays - renamed
Two test points - renamed, the one with two '1' pads has 3d model, the one with '1' and '2' - no 3d.
Buzzer - removed dead link to 3d
KSA (Tactile SPST) - renamed and Push_E-Switch_KS01Q01.kicad_mod - fixed 3d position
SELF26 and TRANSF-MICRO toroids - renamed (names with dimensions)

**Comment by CarlPoirier** [comment]
Thanks for the details. I made sens of all these commits much more quickly. They are merged now.

**Pull request merged**
