### PR TITLE
updating all script generated Resistors_SMD adding STEP and WRL parametric model 

### PR DESCRIPTION
**Pull request by easyw**

### CODE REVIEW

**Comment by jkriege2** [comment]
can you post your screenshot, as discussed elsewhere and provide some info on this PR, especially how these were created (for documentation) 
Thanks,
JAN

**Comment by jkriege2** [comment]
can you post your screenshot, as discussed elsewhere and provide some info on this PR, especially how these were created (for documentation) 
Thanks,
JAN

**Comment by jkriege2** [comment]
Oh and please don't post the doocumenting kicad_pcb and PNG into the repo! We only want the 3D models here!

**Comment by jkriege2** [comment]
Otherwise: looks good to me!
JAN

**Comment by easyw** [comment]
ok, I'm going to close it and open a new one :)

**Pull request closed without merging**
