### PR TITLE
Add triac lib, add Z01 series triac

### PR DESCRIPTION
**Pull request by svheymann**
I am not sure if i should name the components starting with Triac_ or not?
The SOT-223 package has 4 pins, but the triac has the same signal on pin 2 and 4. How do i build the symbol for this? My guess is that the way i did it is not correct because it looks very strange ;)

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

please rename your new lib to `triac_thyristor.lib` ... as I have already a PR running that adds such a lib: https://github.com/KiCad/kicad-library/pull/780

About the naming: no prefix required!

I'll have a closer look this evening,
JAN

**Comment by svheymann** [comment]
done.

**Comment by jkriege2** [comment]
I think for the 2-pin problem there are two solutions:

1. have one pin invisible and overlay the two. Then connecting to one will connect to both
2017-01-24 20_44_00-part library editor d__kicad_kicad-library-review_library_triac_thyristor lib

2. Try something like that (looks better than your solution, IMHO):
2017-01-24 20_45_56-part library editor d__kicad_kicad-library-review_library_triac_thyristor lib

Otherwise: Looks very good ;-) Onely one thing to change:
Please remove the device name from the description and rather add some basic properties of the device, e.g. `1A RMS, 600V Off-State Voltage, Triac, SOT-223`

Best,
JAN

**Comment by svheymann** [comment]
done.

**Comment by jkriege2** [comment]
Looks good. Some final changes:
1. Please add commas to the description, e.g. `4Q Triac, 1A RMS, 600V VDRM, 3mA Igt, 7mA Ih, SOT-223`
2. remove type ID from keywords ... that's matched by the symbol name already ;-)

I'll merge when that's changed!

Best,
JAN

**Comment by svheymann** [comment]
done.

**Comment by jkriege2** [comment]
Please also remove the Z01 from the keywords!
JAN

**Comment by svheymann** [comment]
done.

**Comment by jkriege2** [comment]
Thanks for the work!

JAN

**Pull request merged**
