### PR TITLE
Added support for PIC18F2xK50 family

### PR DESCRIPTION
**Pull request by carlo-bramini**

### CODE REVIEW

**Comment by carlo-bramini** [comment]
Hello, excuse me, this is my first contribution to kicad-library. I think I corrected all pin placement to 100 mil multiple and I added the missing descriptions, but I do not know how to fix this error:

Violating Rule 4.9 - Default fields
    Default fields contain the correct information
    Symbol name 'PIC18F24K50-I/ML' contains invalid characters as per KLC 1.7

If I understood correctly, it complains that a '/' character is inside the symbol name, but actually this is the name of the component, like the other MCUs inside microchip_pic18mcu.lib or .dcm
How can be this defect fixed?

**Comment by carlo-bramini** [comment]
immagine

**Comment by carlo-bramini** [comment]
I followed the instructions from this commit:

https://github.com/KiCad/kicad-library/pull/1436/commits/76168473213886a0b1e98d547d69f7c6106206cc

"1. Prohibited characters - please do not use ( ) / \ characters in part names (as per the KLC).
Note: Yes, this goes against a lot of the Microchip MCU parts, but we are working to improve them
So, I would rename as thus:
PIC16F18325-ISL"

So, I did the same thing. Thank you.

**Comment by poeschlr** [comment]
I think the naming convention is in preparation for the new file format where there will be one file per symbol. (A '/' in a filename is a bad idea.)

The symbol would look even better if the pin names are shorter.
Choose a name that identifies the pin and use that. (Example: Rxy; x = A, B, ..; y=0, 1, 2, ...)

Yes the current symbols in this lib show the alternative functions in the pin name. 
In other libs we already removed them. (Results in a symbol that is a bit easier to read.) 

We hope the new lib format will allow for alternative pin names. Until we have this new format we can not really do better than to use shorter names.

For inspiration have a look at the nxp_armcpu lib.

**Comment by carlo-bramini** [comment]
I followed your suggestion and I stripped functions from pins and I made more compact components.
Thank you for your time.

immagine

**Comment by poeschlr** [comment]
What is the difference between -EML and -IML? Either highlight this difference in the description or have only one symbol (replace E/I with a wildcard. Example instead of having PIC18F24K50-IML and PIC18F24K50-EML only use PIC18F24K50-xML)

The same is true for other packages (-I[package code] and -E[package code])

What is the difference between PIC18F24K50 and PIC18**L**F24K50? (Highlight it in the description.)

Package versions MV (uqfn), P (pdip) and PT (TQFP) are missing. (Did you forget them or are they not available. Or is it too much work to include them.)

I will review the symbols them selves after lunch. (pin types and pin numbering, footprint field and filter)

**Comment by carlo-bramini** [comment]
Hello, according to the datasheet:
immagine

I did the fixes that you requested into the descriptions. Thank you.

**Comment by carlo-bramini** [comment]
For the difference between 'I' and 'E':
immagine

**Comment by poeschlr** [comment]
Normally we do not include different symbols for different temperature ranges.
So i would go with using a wild card instead and reduce the number of symbols by a factor of two.

Including the voltage range is ok. (As long as it is mentioned in the description.)

**Comment by carlo-bramini** [comment]
I see, I removed the temperature range and I used a wildcard instead as you suggested. Thank you.

**Comment by poeschlr** [comment]
Looks good. Maybe the qfn footprint is not quite right. (Exposed pad too large.)
If you are motivated you could add a separate qfn package with the correct exposed pad size.

Sadly the naming for such a package is not yet fixed.
https://github.com/KiCad/kicad-library/issues/1447

**Comment by carlo-bramini** [comment]
Actually these mcu identical footprint to the PIC18F2450 series, so I just did a copy paste from these components since the already existed in library. Are they wrong too?

**Comment by poeschlr** [comment]
I had another look. The footprint might be ok. In it the pad for the exposed pad is 4.25x4.25mm.
The package pad is nominal 3.7mm. But the maximum is 4.2. (Would mean 4.25 is ok for the maximum size.)

Sorry for the confusion. (I have not noticed that the thermal pad has such large tolerances when i first looked at it.)

Now only one thing to say: Thanks for your contribution.

**Pull request merged**
