### PR TITLE
Add Cypress USB-Serial bridge IC symbols

### PR DESCRIPTION
**Pull request by cyrozap**
These patches add the symbols for Cypress Semi's line of USB-Serial bridges.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@cyrozap if you're still interested in getting this merged, please fix the conflicts by merging kicad/master into your branch and I'll take a look :)

**Comment by SchrodingersGat** [comment]
@cyrozap  still interested in getting this one merged? :)

**Comment by hackscribble** [comment]
Closing re-opening to trigger Travis checks.

**Comment by Misca1234** [comment]
This thread can be closed and deleted,
Replacement push is here
https://github.com/KiCad/kicad-library/pull/1612

**Pull request closed without merging**
