### PR TITLE
Add DRV8848 to texas library

### PR DESCRIPTION
**Pull request by michielbrink**
http://www.ti.com/lit/ds/symlink/drv8848.pdf

### CODE REVIEW

**Comment by evanshultz** [comment]
@michielbrink 
Thanks for making a contribution to KiCad!

Can you please post an image of the symbol? That will help us review this symbol most quickly.

In addition, you will see a number of ways in which your symbol does not conform to the KiCad library requirements if you click on the Details link above. You can find KLC, the library part requirements, at https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention. The check scripts will point out violations of KLC.

For example, many of your pins are not on a 100mil grid. Also text sizes are at the default instead of the KLC requirement. The symbol outline is not the right thickness. No footprint filters are defined to allow easy selection of a footprint in CvPcb.

Use other symbols as examples and please ask if you have questions. These issues are all easily fixable once you're familiar with KLC, and I'm looking forward to merging your symbol once it meets all the requirements. Thanks again for wanting to improve KiCad's libraries!

**Comment by evanshultz** [comment]
Hi @michielbrink! Are you having any issues updating your symbol? Any questions?

**Comment by evanshultz** [comment]
@michielbrink Will you be able to fix up this PR?

**Comment by Misca1234** [comment]
This device have been re pushed here
https://github.com/KiCad/kicad-library/pull/1657

**Pull request closed without merging**
