### PR TITLE
cmos4000: add 4056 symbol

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Hi @piotr-wiszowaty 

Sorry it has taken so long for your contribution to be reviewed.

There have been changes to the KiCad Library Convention since you opened the PR.  You can see the latest version here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

If you would still like us to review this PR, please check out the KLC and look at the errors being flagged in the Travis CI checks above: https://travis-ci.org/KiCad/kicad-library/builds/249622679?utm_source=github_status&utm_medium=notification

Many thanks

**Comment by hackscribble** [comment]
Posting image of symbol for reference.

image

**Comment by piotr-wiszowaty** [comment]
Symbol updated.

**Comment by hackscribble** [comment]
Thanks @piotr-wiszowaty 

The Travis CI errors are coming from the other existing symbols in the library, so we can ignore those.  I will review the 4056 and get back to you.

**Comment by hackscribble** [comment]
Review comments on the 4056:

1. Resize and move the symbol outline so that the centre of the outline is at (0,0).

2. Pin positions do not have to match the physical pinout when this conflicts with the best logical ordering of the pins. So ...

3. Change the input pins so they run from `2^0` at the top to `2^3` at the bottom.  Also change the output pins so they run from `a` at the top to `g` at the bottom.  

4. Keep `STROBE` and `FREQ.IN` on the left hand side, but change their position vertically if it helps with point (1) above.

5. Change `STROBE` pin type to `Input`.

6. In the symbol properties, change the description to `BCD to 7-Segment Decoder/Driver, Strobed-Latch Function` and change the keywords to `CMOS LCD 7-segment decoder driver`. 
 
7. Change the footprint filters so they show the package width as well as the type: `DIP*W7.62mm*` `SOIC*3.9x9.9mm*Pitch1.27mm*` `TSSOP*4.4x5mm*Pitch0.65mm*`.

**Comment by piotr-wiszowaty** [comment]
Done.

**Comment by hackscribble** [comment]
Note to self: comparing `checklib.py` results for current `master` branch and the feature branch for this PR shows no change to the KLC errors for the existing devices, with one exception: errors about missing footprint and datasheet fields have been replaced with errors about text size for these fields (which were added to the symbols by later KiCad version). So no regression apparent in other symbols.

**Comment by hackscribble** [comment]
Thanks for the update @piotr-wiszowaty 

I will review your changes.

**Comment by hackscribble** [comment]
Thank you for the contribution. I know you have two other PRs on this library - I will look at those next.

**Pull request merged**
