### PR TITLE
Added three-row high-density DB15 symbols

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added symbol for triple-row DB15 connector

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi! ... as a small service: the check-utility-results:

```
checking component: DB15_HighDensity
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing datasheet, please provide a datasheet link if it isn't a generic component
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin 1 does not have a name
    pin 2 does not have a name
    pin 3 does not have a name
    pin 4 does not have a name
    pin 5 does not have a name
    pin 6 does not have a name
    pin 7 does not have a name
    pin 8 does not have a name
    pin 9 does not have a name
    pin 10 does not have a name
    pin 11 does not have a name
    pin 12 does not have a name
    pin 13 does not have a name
    pin 14 does not have a name
    pin 15 does not have a name
checking component: DB15_HighDensity_MountingHoles
  Violating Rule 3.1
    Using a 100mils grid, pin ends and origin must lie on grid nodes (IEC-60617).
    pin: ~ (0), posx 0, posy -750
  Violating Rule 3.8
    Description and keywords properties contains information about the component.
    missing datasheet, please provide a datasheet link if it isn't a generic component
  Violating EC01 - Extra Checking
    Check pins names against pin types.
    pin 0 does not have a name
    pin 1 does not have a name
    pin 2 does not have a name
    pin 3 does not have a name
    pin 4 does not have a name
    pin 5 does not have a name
    pin 6 does not have a name
    pin 7 does not have a name
    pin 8 does not have a name
    pin 9 does not have a name
    pin 10 does not have a name
    pin 11 does not have a name
    pin 12 does not have a name
    pin 13 does not have a name
    pin 14 does not have a name
    pin 15 does not have a name
```

Could you please fix the errors? ... And maybe if you're at it also fix the other DBxx (optional ;-) ?

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

I think the pin-name issues, you can ignore ... that's a bug in the scripts not recognizing `~` pin names.

cu
JAN

**Comment by SchrodingersGat** [comment]
I have fixed the issue relating to the pin location being off-grid. The others are "non issues" I believe.

**Comment by jkriege2** [comment]
looks good to me :-)

Best,
JAN

**Pull request merged**
