### PR TITLE
Add H11L1 optocoupler

### PR DESCRIPTION
**Pull request by evanshultz**
Image:
image

The FPFilter is a bit hard here since it comes in multiple widths and both THT and SMT. I hope what I did will work, since it's quite generic.

Datasheets:
https://www.fairchildsemi.com/datasheets/H1/H11L1M.pdf
http://www.everlight.com/file/productfile/h11l1.pdf

### CODE REVIEW

**Comment by jkriege2** [comment]
VCC+GND should not be hidden, ... please compare with other opto-couplers from this lib ...

**Comment by evanshultz** [comment]
OK. I did find one with a logic output in this lib.

**Comment by jkriege2** [comment]
Hi!

Please solve the FPFilter problem as e.g. in this OC from opto.lib:
2017-02-24 19_21_44-part library editor d__kicad_kicad-library-review_library_opto lib

Also pin3 is better positioned like that (IMHO) ... at least it's done that way in most other libs:
2017-02-24 19_23_03-part library editor d__kicad_kicad-library-review_library_opto lib

JAN

**Comment by evanshultz** [comment]
Thank you, Jan. Done. Note that I added the 3 DIP SMD footprint shown on those datasheets.

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
